### ISSUE TITLE
Testing with Keycloak Server

### ISSUE THREAD

**Issue by kukuandroid** [FormidableLabs/react-native-app-auth#10]
Hello, can you provide an example on how to do this with keycloak ?

**Comment by philpl** [comment]
Hiya, this is ultimately an AppAuth integration for react-native and not a question board. Terribly sorry to point this out first :wink:

I'm not familiar with Keycloak myself, but there seems to be some OAuth2/OpenID support that's being provided:

https://stackoverflow.com/questions/28658735/what-are-keycloaks-oauth2-openid-connect-endpoints

So as long as you can find the typical OAuth endpoints you should be fine. Those are:

- The issuer URL
- A client ID that you created / the platform provides
- A redirect URL

If you need more specific help, I'd suggest you to go to Stackoverflow as well and try your luck by asking another question there. The keyword here would probably be OAuth 2 + Keycloak.

Hope that helps you well enough for now :smile:

**Comment by ChenWes** [comment]
@kukuandroid hi , did you have resole the issue , if yes , can you share me how you keycloack config  ??
