### ISSUE TITLE
Authorization not working for iOS 10

### ISSUE THREAD

**Issue by rlpayneibm** [FormidableLabs/react-native-app-auth#100]
Hi, we're having an issue where iOS 11 and Android devices are able to login, but when we test iOS 10 devices, we're getting this screen in the safari web view: 

![simulator screen shot - iphone 6 - 2018-03-08 at 11 34 35](https://user-images.githubusercontent.com/29464786/39067678-8f7655c4-44a7-11e8-8a97-f95ef30c5982.png)

We are using a single config setup for all of the device types/versions.

During the Auth process, we are noticing in Charles Proxy is that there are GET calls to some '/apple-app-site-association' that is returning some HTML and we were wondering if that's all coming from the backend or if there's something going on in the framework that is making those calls to check for some redirect.

**Comment by kadikraman** [comment]
Hi @rlpayneibm - strange, I've never seen that error before. Have you tried it on multiple devices (or emulators on different computers)?

**Comment by rlpayneibm** [comment]
@kadikraman Yes, and I had a device that was on iOS 10 that showed this screen, then after updating it, the problem went away.

**Comment by kadikraman** [comment]
I ran the example app on iPhone 6S on iOS10 and I can't seem to reproduce your error. Can you reproduce it on an emulator?

<img width="378" alt="screen shot 2018-04-24 at 21 26 38" src="https://user-images.githubusercontent.com/6534400/39212300-3b41ef88-4806-11e8-9582-615c66fa8ec0.png">

**Comment by rlpayneibm** [comment]
@kadikraman there was an issue with the url in the plist. I changed it and now it works as expected.
