### ISSUE TITLE
Microsoft Login didn't give any respond(token) to iOS devices

### ISSUE THREAD

**Issue by yenadh** [FormidableLabs/react-native-app-auth#1003]
I use react native to create my mobile app and I use Microsoft login. In android device login is success and respond the accessToken but in ios device login is success but does not respond any accessToken or any error message what will be the issue.

I try by giving separate redirect uri for ios but it did't work

I use `react-native-app-auth` package 

This is my Login funtion

 ```
const microsoftSignIn = async () => {
        try {
          console.log("Login Starts")
          const {accessToken} = await authorize(config);
          console.log(accessToken)
        } catch (error) {
          console.log(error)
        } 
    };
```

and this is my config file

   
```
 issuer: 'https://login.microsoftonline.com/*****',
      clientId: '******',
      redirectUrl: 'msauth.org.reactjs.native.example.mobileapp://auth',
      scopes: ['User.Read', 'User.ReadBasic.All'],to scopes
      serviceConfiguration: {
        authorizationEndpoint:
          'https://login.microsoftonline.com/******/oauth2/v2.0/authorize',
        tokenEndpoint: 'https://login.microsoftonline.com/******/oauth2/v2.0/token',
        revocationEndpoint:
          'https://login.microsoftonline.com/******/oauth2/v2.0/logout',
      },
      useNonce: true,
      usePKCE: true,
      additionalParameters: {
        prompt: 'consent',
      },
    };
```

This is a single tenant application 

I did all the configuration that are need do before use `react-native-app-auth` package but it didn't works in iOS devices.

**Comment by LMakshow** [comment]
@yenadh 
You can try to add the trailing slash to the redirectUrl:
`redirectUrl: 'msauth.org.reactjs.native.example.mobileapp://auth/'`
It worked for me.

**Comment by yenadh** [comment]
Thanks @LMakshow that also works for thanks for your help I am new to this iOS development

**Comment by zibs** [comment]
Thanks @LMakshow -- maybe I'll add something to the readme about this.

**Comment by nhan7tuoi** [comment]
Can you show me the configuration for iOS? I followed the instructions but when I click the button it immediately closes the app, but it works fine on Android.
<key>CFBundleURLTypes</key>
	<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>AzureAuth</string>
        <key>CFBundleURLSchemes</key>
            <string>com.library</string>
    </dict>
	</array> tôi chỉ mới thêm nó vào infi.plist

**Comment by nhan7tuoi** [comment]
Can you show me the configuration for iOS? I followed the instructions but when I click the button it immediately closes the app, but it works fine on Android. 
<key>CFBundleURLTypes</key>
	<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>AzureAuth</string>
        <key>CFBundleURLSchemes</key>
            <string>com.library</string>
    </dict>
	</array>
