### ISSUE TITLE
Interacting with In App Browser in Detox

### ISSUE THREAD

**Issue by skriptly** [FormidableLabs/react-native-app-auth#1025]
## Issue

I am trying to write end-to-end tests using Detox for my React Native app, which incorporates an in-app browser through the react-native-app-auth for handling OAuth login flows. However, I am having difficulty interacting with this in-app browser, particularly for filling out login forms and clicking buttons

I attempted to locate elements within the in-app browser using Detox’s standard by.id, by.text, and other element selectors, but Detox does not seem to recognize elements. 

## Questions

Is there a known way to interact with in-app browsers in Detox?
Does Detox currently support interacting with in app browsers in this context?

---

## Environment
* **Platform that you're experiencing the issue on**: `both`
* **Your `react-native` Version**: `0.75.2`
* **Your `react-native-app-auth` Version**: `7.1.0`
* **Are you using Expo?**: `yes`

**Comment by robwalkerco** [comment]
Hi @skriptly 

This is not something that we can offer much help with, I'm afraid.
This library does not provide any specific helpers for testing in-app modals using Detox.

I would suggest you ask this question on the [Detox Discord](https://discord.com/invite/CkD5QKheF5) or the [Detox Repo](https://github.com/wix/Detox).
