### ISSUE TITLE
library not found for -lAppAuth

### ISSUE THREAD

**Issue by Solitaryo** [FormidableLabs/react-native-app-auth#106]
For some reason, if i run react-native run-ios works perfectly fine, but if I try to build the app for production, I got this error, every single time:
`
ld: warning: directory not found for option '-L/Users/User/Library/Developer/Xcode/DerivedData/Quimbee-ezgqfvnmwvkmzqamiicqkwzzennb/Build/Intermediates.noindex/ArchiveIntermediates/Production/BuildProductsPath/Production-iphoneos/AppAuth'
ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Any idea how to fix this?, this thing is driving me crazy, I unlinked, uninstall and reinstall and link everything again, nothing works.

**Comment by kadikraman** [comment]
Hi, sounds like your issue is similar to this one: https://github.com/FormidableLabs/react-native-app-auth/issues/16 - try comparing your app to the example one and make sure the linked dependencies are the same.

**Comment by tiffanym19** [comment]
Im also having this issue using react-native 0.62

**Comment by AtharZaib** [comment]
Anyone got its solution ?

**Comment by rakefetWorkiz** [comment]
same 
started happening to me after upgrading react-native to 0.63 & updating xcode to 12.0.1
anybody got the solution for that?

**Comment by joeljerushan** [comment]
We need solution for this running react-native 0.63 can anyone help ?

**Comment by joeljerushan** [comment]
This maybe Stupid but do as i say. 

01 - Create a Swift File inside your Project. (Check Screenshot)
![Screenshot 2020-10-15 at 8 58 52 AM](https://user-images.githubusercontent.com/10111309/96074915-80f8c580-0ec7-11eb-9f3b-ed3647c768ba.png)

02 - Click Don't Create when you asked on next popup once you click create button. 

03 - Pod Install then Clean Project Folder (if you can remove node_modules and reinstall it then pod install that will be great)

04 - Run Project That Worked for me.

**Comment by rakefetWorkiz** [comment]
So after I upgraded to react native 63, this issue kept happening to me no matter what I did.
Eventually, I just cloned my project to a new directory and run yarn install & pod install from scratch, 
and walla - that worked 😅 
so - I would guess it was probably some leftover from the previous version that had to be cleaned..

**Comment by alenseferovic1** [comment]
I have the same issue here. I started with new project a few days ago and installed this package. Android is working perfect but iOS has this issue.

**Comment by smamahasn** [comment]
i am facing same issue , any one can help me?
