### ISSUE TITLE
refresh does not resolve promise

### ISSUE THREAD

**Issue by schneck** [FormidableLabs/react-native-app-auth#116]
Hi,

I'm trying to refresh a token with something like this:

```
const dorefresh = async () => {
  console.log('refresh');
  const result = await refresh(config, {refreshToken});
  console.log({ result });
};
```

The result is never logged, however. I tried to obtain a new token in a redux middleware, and within a  component, without success. Authorization works fine. The refresh token is valid, I tested it on jwt.io.
As an auth backend, I'm using keycloak.

Any idea?

**Comment by kadikraman** [comment]
Very strange, don't think I've encountered this before. Does it happen on both Android and iOS?

**Comment by schneck** [comment]
I found that this happens from time to time (not predictable when, but it always happens) when running the app in debug mode. I'm running it on Android. 
The only way to make it work again is to disable the debugger and restart the app.
Any information I can provide to help finding the issue?

**Comment by ChenWes** [comment]
@samwhale hi , can you share me how do you config keycloak ? i have use https://github.com/FormidableLabs/react-native-app-auth#keycloak , but android have error , can you help me , please ??

**Comment by samwhale** [comment]
Hi @ChenWes, I'm sorry but I don't know React Native yet. I'm learning, but good luck!

**Comment by kadikraman** [comment]
@ChenWes what's your error?

**Comment by tarun29061990** [comment]
Any updates on this?? Refresh is not resolving promise

**Comment by systemidx** [comment]
For me, it doesn't ever actually make the HTTP request. Generating the original token is fine.

**Comment by timorss** [comment]
Same here

**Comment by Jay-A-McBee** [comment]
Closing this out since we can't recreate it, and there was no response to Kadi's request for a specific/problematic IDP.
