### ISSUE TITLE
Possible to use library without scope parameter

### ISSUE THREAD

**Issue by zzorba** [FormidableLabs/react-native-app-auth#117]
The 3rd party server I am trying to connect to does not need or accept a `scope` parameter when requesting authorization (you always get full access).  Unfortunately, I haven't found a way to use this library without 'scope', I just get validation exceptions.

Is there any known workaround for this issue?

**Comment by zzorba** [comment]
Thanks for the quick update, I'll try this branch out later today and report back.

**Comment by zzorba** [comment]
Looks great, thanks so much!  I left the scopes param off altogether, which seemed to work just fine with my API.

**Comment by kadikraman** [comment]
Thanks for validating. Released as [v2.5.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.5.0) 🎉
