### ISSUE TITLE
RNAppAuthModule.java is missing TimeZone import

### ISSUE THREAD

**Issue by Landcross** [FormidableLabs/react-native-app-auth#120]
With the newest 2.5 version, I get a build error 'Cannot find symbol TimeZone' in RNAppAuthModule.java. And indeed, the import java.util.TimeZone is missing.

If I add the import, everything works perfectly fine.

**Comment by freemanUA** [comment]
Same problem. Where to add the import?

**Comment by kadikraman** [comment]
Thanks so much for pointing this out. Fixed in [v2.6.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.6.0) 🎉
