### ISSUE TITLE
OAuth token successfully received, but await authorize(config) promise is never returned in ReactNative app

### ISSUE THREAD

**Issue by makraade** [FormidableLabs/react-native-app-auth#125]
Heya,

we have downloaded and built the provided test app, which works fine with the provided Okta sample.

We then simply changed the config to point to the mercedes.me Oauth provider, as shown below:

`const config = {
    clientId: ‚REMOVED‘,
    clientSecret: ‚REMOVED‘,
    redirectUrl: 'mercedesLogbook://redirect.url',
    scopes: ['mb:vehicle:status:general', 'mb:user:pool:reader'],
    additionalParameters: {responseType: 'code'},
    serviceConfiguration: {
        authorizationEndpoint: 'https://api.secure.mercedes-benz.com/oidc10/auth/oauth/v2/authorize',
        tokenEndpoint: 'https://api.secure.mercedes-benz.com/oidc10/auth/oauth/v2/token',
        revocationEndpoint: 'https://api.secure.mercedes-benz.com/oidc10/auth/oauth/v2/revoke'
    }
};`

Using this provider, the app reaches the mercedes.me login page, credentials are correctly handled, but the Auth token is never returned.

Digging into the issue, we found by logging 

`OIDAuthorizationUICoordinatorIOS.m
if (callbackURL) {
NSLog(@"%@", callbackURL);       
[self->_session resumeAuthorizationFlowWithURL:callbackURL];
}`

that the callbackURL is received OK with the token on the native side of the app:

`2018-06-20 13:56:48.675083+0200 OktaRN[22018:1239496] mercedeslogbook://redirect.url?code=d6955680-98bf-41a5-8789-1a8720954c9a&state=xQyD9gRe23TUOz-fezEh-PjcwGoAYw_I6D2hlWPON3E`

but on the ReactNative side, the promise never arrives:

`authorize = async () => {
const authState = await authorize(config);
console.log("SUCCESS");`

The console.log never fires; execution seems to hang/die on the await authorize(config);

Any and all pointers are welcome!

**Comment by makraade** [comment]
Got the solution:
The Problem was that the shouldHandleURL function returned false for my redirect url scheme.
The Mercedes Me API Console only allows redirect urls in this format aa://domain.bb/... 
I adjusted the function and now anything works!

**Comment by edcs** [comment]
I thought I'd add to this for future searchers having a similar issue - your URL must be all lowercase for this to package work. I'd set my scheme to `cognitoDemo://...` and it was being standardised to `cognitodemo://...` by `shouldHandleURL` causing it to fail the comparison tests it performs.
