### ISSUE TITLE
Is there any way to manually control the behaviour of the OAuth window?

### ISSUE THREAD

**Issue by shishiranshuman** [FormidableLabs/react-native-app-auth#126]
Hi all,

I just wanted to know if it's possible to close the OAuth window after a successful login or on an event. 
The window remains open even on successful authentication on the iOS 11.4 

react-native: 0.51.0
react-native-app-auth: 2.6.0

**Comment by kadikraman** [comment]
The window should close automatically 😕

This is what the correct behaviour looks like. This is taken from our Example app runing RN 0.50.3 and react-native-app-auth: 2.6.0.

![appauthdemosmall](https://user-images.githubusercontent.com/6534400/41734011-a4afcf54-757d-11e8-8791-fd478cdce1b6.gif)

**Comment by shishiranshuman** [comment]
This is not happening in my case. The auth window remains open with a blank page. I cannot downgrade/upgrade the react-native version because there are more plugins in my app that might break.

If I there is an API or a workaround to close the window, I'll be okay with this for now.

**Comment by shishiranshuman** [comment]
Okay, I got it. My redirect URI was incorrect. Now the auth window is getting closed, but an error page is displayed.

```
JSON value '{
  code = "RNAppAuth Error";
  column = 24;
  domain = "org.openid.appauth.oauth_authorization";
  framesToPop = 1;
  line = 2808
  .
  .
  .
```

![sibyai5cyq](https://user-images.githubusercontent.com/20037600/41777712-efea3eba-7649-11e8-9631-c2d8f2e74eed.gif)

**Comment by kadikraman** [comment]
Oh, interesting. I created a dummy FitBit app so I could test RNAppAuth on it. Could you try if you can auth with this config (this works for me on the example app):

```
  clientId: '22CMVB',
  clientSecret: '6ab7f24f24060376385bc22842996c1c',
  redirectUrl: 'com.my.test.fitbit.app://oauthredirect',
  additionalParameters: {},
  scopes: ['activity', 'sleep'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.fitbit.com/oauth2/authorize',
    tokenEndpoint: 'https://api.fitbit.com/oauth2/token'
  }
```

**Comment by shishiranshuman** [comment]
Yes, my app is working with your configuration. I compared this with mine and the only difference was the `additionalParameters`. 

```
additionalParameters: {
  response_type: 'code'
}
```

If I remove the value of `additionalConfigurations` from my config, it works perfectly. Could you please try passing some `additionalConfigurations` and see if the OAuth works?

**Comment by kadikraman** [comment]
Sorry, but what are you trying to achieve by setting the response type? We already set it to `code` [in the library](https://github.com/FormidableLabs/react-native-app-auth/blob/f2c20113d7e93516f6566144f5cb0ac3f14b64e1/ios/RNAppAuth.m#L143).

**Comment by kadikraman** [comment]
State is also handled internally. The idea of this library is that all you need to do is pass in the auth endpoints and your app details and it will handle the OAuth (including [PKCE](https://tools.ietf.org/html/rfc7636) if the auth server supports it).

**Comment by shishiranshuman** [comment]
Ah! That's nice. Is this information added to the readme? I think I missed it. Also apologies for the trouble. Obviously, this was a dumb mistake. Closing this issue now.

Thanks a lot for the help. ☮️

**Comment by kadikraman** [comment]
No worries at all, glad you got it sorted 🙏
