### ISSUE TITLE
Crash in android native bridge when 'scopes' are omitted

### ISSUE THREAD

**Issue by zzorba** [FormidableLabs/react-native-app-auth#132]
A couple weeks back I filed https://github.com/FormidableLabs/react-native-app-auth/issues/117 and it was fixed very quickly.  At the time I was only running my project with iOS, when I dusted it off on android today I noticed that I'm getting a crash if I omit the 'scopes' parameter from my configuration on Android.

Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference.

Sorry for not having tested this when I filed issue 117.

**Comment by zzorba** [comment]
Indeed, right once test everywhere.

As for the patch, confirmed that its working great.  Thanks so much for the quick turn around.

**Comment by kadikraman** [comment]
Published in [v2.6.1](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.6.1) 🎉
