### ISSUE TITLE
RNAppAuth Object is undefined. 

### ISSUE THREAD

**Issue by mafelix** [FormidableLabs/react-native-app-auth#141]
I think something is broken with your library.

OS: Android
Functionality: authorize

```
Where RNAppAuth is defined: 
- index.js@L4 ( const { RNAppAuth } = NativeModules) 
```

React Native Version: 0.38
React-Native-App-Auth: "^2.6.1"

Whenever I try to call the authorize function with the proper credentials, it returns a: 
```
"Calling an undefined property authorize" error. 
```
Logging out the RNAuthApp object, I discovered that indeed the RNAuthApp object is undefined!
This means there's either NativeModules being included is incorrect.

Solutions I've tried:
- react-native linked the library already. 
- I've restarted my running server to purge any "cached?" elements. 

Does anyone else have this problem? Should I be diving deeper into why NativeModules is undefined?

**Comment by kadikraman** [comment]
Hi @mafelix - sorry you happened to try the library at the awkward time when the docs were out of date with the latest release.

I've just published `v3.0.0`. Could you please try again with the latest version 🙏

**Comment by mafelix** [comment]
Thank you so much @kadikraman! I'll try the updated version soon.

**Comment by kadikraman** [comment]
@mafelix I just read your issue again and `v3` affects iOS, not really Android. If it's still not working for you, could you try cloning this repo and running the Example project to see if you get the same error?

**Comment by mafelix** [comment]
@kadikraman I believe it is related to my react-native version (0.38).

I unlinked, and uninstalled the package and reinstalled the new react-native-app-auth(3.0+) version and relinked and I got the same error. 

`Undefined property authorize`

Now I will run your example project with react-native version (0.50.1)

If this is the problem, can you include RN dependencies in the docs?

**Comment by mafelix** [comment]
@kadikraman so after some weird issues with node_modules and making sure npm packages are have all their peer dependencies met, the example works. 

But what I am doing is sending to a request to a custom oAuth2.0, it's not any of the big oAuth services(Twitter, Instagram, Facebook, etc).

This is possible with this library correct? What are the dependency requirements for thsi library?

**Comment by kadikraman** [comment]
Yes, it should work with any OAuth client, given they have implemented the OAuth spec correctly. RN 38 is quite old, it’s possible that the bridging API would have changed and is not backwards compatible. 50 is the oldest version I’ve tested with 😕

It’s a very good point though, I should definitely find out the lowest version this works with. At the moment I’m only confident that it’s 50+

**Comment by SuhanKoh** [comment]
I think this may be related to #113, this is the error I am getting on iOS with react-native 0.55.4

**Comment by kadikraman** [comment]
That error just means that your app can't find the RNAppAuth module, so something's gone wrong either in the configuration, e.g. forgetting to run `react-native link`.

**Comment by mfranceschini** [comment]
Same here on Android. Already linked the library and cleared the cache. Is there any update on this?

**Comment by kadikraman** [comment]
It should work, I'm not sure why you're having this issue. Would you be able to create an example RN project where you get this error so I could look into it?

**Comment by SuhanKoh** [comment]
It worked on 56.0, but not 55.4

**Comment by mafelix** [comment]
Hmm. Is there any way to expose the error messages from the request? Trying to debug why I am not receiving a token for the authorize method but all I get is a generic Failed to authenticate error.

**Comment by kadikraman** [comment]
Closing this as I don't think it's an issue in the latest versions of the library. Please reopen if it's still a problem.

**Comment by mjniday** [comment]
@kadikraman I believe this should be reopened. I was unable to get this working at all unfortunately.

I just did the following steps and received the same error:
* `react-native init`
* `yarn add react-native-app-auth` (v4.0.0)
* `react-native link react-native-app-auth`
* ensured that the correct configurations were set from the setup guide in the README

This still results in an error that it cannot read property `authorize` on RNAppAuth.

**Comment by kadikraman** [comment]
@mjniday please check out our [Examples](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example) directory. There are examples there for iOS (both using Pods and Carthage) and Android.

Might also be worth noting that you're need to rebuild the native app after adding the library (`react-native run-ios` or `react-native run-android`)

**Comment by frostless** [comment]
Weird if I launch the app by using .xcworkspace I got no problem, but if I launch with RN cli react-native run-ios I keep getting this error, and I definitely run react-native link react-native-app-auth
