### ISSUE TITLE
RN-Windows support

### ISSUE THREAD

**Issue by creambyemute** [FormidableLabs/react-native-app-auth#143]
Hey there,

I'm evaluating different possibilities of adding OAuth2/OIDC to our React-Native project which supports iOS/Android as well as UWP.

Until now there is not really any rn-library that supports UWP.

My questions now are: 
You're probably not working on it yet I guess? 
Would you be interested in a PR that adds `AppAuth-UWP` (like AppAuth-Android and AppAuth-iOS) and the `/windows` UWP support/integration folder to this library?

Cheers!

**Comment by kadikraman** [comment]
It might be worth reaching out to the OpenID team about this if possible, as they've been the ones that created both AppAuth-Android and AppAuth-iOS and we've relied on their due diligence to follow the OAuth2 spec in their implementation.

I've never had the chance to try RN-Windows, but I see it's a separate library outside of RN. Would AppAuth-UWP be able to be used alone (like AppAuth-Android is used in native Android projects etc) or would it be built just to be used here?

In theory, I don't object to adding RN-Windows support if it doesn't affect the current Android/iOS implementation.

**Comment by creambyemute** [comment]
Ah good point!

It would be able to be used like AppAuth-Android in native projects, at least that'd be my goal and then be bundled in here in the /windows folder just like you did with with the ios and android implementation

**Comment by kadikraman** [comment]
Well they're a non-profit foundation. Best idea would be perhaps to [tweet at them](https://twitter.com/openid/). Would be great to get some support. But you can obviously start working on your idea under your own GitHub account and see how it goes.

**Comment by creambyemute** [comment]
Sure, I'll just check the Android Impl and start working on it.

I jave no twitter or any other social media :/

**Comment by kadikraman** [comment]
Closing as no plans to add a RN-Windows support in the near future
