### ISSUE TITLE
How to check that token is expired or not ?

### ISSUE THREAD

**Issue by nainishmodi** [FormidableLabs/react-native-app-auth#146]
is there any mechanism for token checking whether it is valid or expired ? so after checking token if it is expired then i can make request for refresh token..any help would be greatly appreciated..

**Comment by kadikraman** [comment]
The `authorize` function returns a `accessTokenExpirationDate` which tells you when the token is due to be expired.

**Comment by kadikraman** [comment]
Closing to due inactivity

**Comment by tarun29061990** [comment]
Any update on this??

**Comment by kadikraman** [comment]
As said above, the authorize function returns an `accessTokenExpirationDate` which tells you when the token is due to be expired.

You can also decode your jwt (try it [here](https://jwt.io/)). There's usually an `exp` which is the expiry date of the JWT.
