### ISSUE TITLE
Deep linking cause the authorization..

### ISSUE THREAD

**Issue by nainishmodi** [FormidableLabs/react-native-app-auth#148]
I have done deep linking for my native app..my code snippet as below
```
<intent-filter android:label="@string/app_name">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="http"
                  android:host="m.myAppName.com"
                  android:pathPrefix=""
                />
        </intent-filter>
```
my configurations is like
```
const config = {
    issuer: 'myIssuer',
    clientId: 'myClientId',
    clientSecret: 'myClientSecret',
    redirectUrl: 'm.myAppName.com:/oauthredirect',
    serviceConfiguration: {
        authorizationEndpoint: 'myIssuer',+ '/oauth/authorize',
        tokenEndpoint: 'myIssuer',+ '/oauth/token'
    },
    scopes: ['openid', 'offline_access']
};
```

when i tried to authorize with our oAuth2.0 ..it is not authorizing me first time..but second time when i tried to authorize then it is authorizing me and giving me token also..this happens vice versa..when i remove above code snippet then it is working fine..no issue with it..what to do ? any help would be greatly appreciated.

**Comment by nainishmodi** [comment]
@kadikraman Please look at on this..

**Comment by kadikraman** [comment]
I'm not 100% sure, but you could try being more explicit and [adding your redirect url to the manifest as well.](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect)

**Comment by nainishmodi** [comment]
@kadikraman  Not working above solution..

**Comment by Petemir** [comment]
How are you handling the deeplinking? In my root component, I had to use both Linking.getInitialURL() (works when the app is closed and is opened via a deeplink, as componentDidMount() is only called once in the root component) and Linking.addEventListener("url", [...]) for when the app was already open (and, thus, registered the handler already when the component mounted).

**Comment by Jay-A-McBee** [comment]
👋 hey @nainishmodi - this issue has been sitting around for a while so we're going to close it out. Feel free to open a new issue if this is still a problem.
