### ISSUE TITLE
Support id_token in response type?

### ISSUE THREAD

**Issue by zyofeng** [FormidableLabs/react-native-app-auth#15]
I can see at the moment only code is supported in response type with no way of overriding it. However, to correctly log out in IdentityServer 4 we would need to send the correct id_token to the end point
http://docs.identityserver.io/en/release/endpoints/endsession.html

and get redirected back to the app after successful logout.

Are there any plans to support this?

**Comment by kadikraman** [comment]
Hi @zyofeng This library bridges the native [iOS](https://github.com/openid/AppAuth-iOS) and [Android](https://github.com/openid/AppAuth-Android) libraries which presently do not seem to support ending a session, which is why this has not been planned so far. Here's one of the issues I could find on the matter: https://github.com/openid/AppAuth-iOS/issues/47

I think it would be a very useful enhancement, but requires some effort, as the logout flow would be similar to the sign in flow in which a user it redirected out of the app and back in. On the bright side, it would not be too hard to implement, even form scratch, as ending a session involves fewer security risks than starting one.

Presently, there are no concrete plans to support this, but we welcome anyone to open a PR that adds this functionality :)

**Comment by zyofeng** [comment]
Thanks. Unfortunately I only have a .Net background and only recently got into react native after getting frustrated with xamarin.

As a work around I am redirecting user to the end session endpoint using linking. Without id token identity server can't redirect back to the app but I can live with that in the mean time.

**Comment by philpl** [comment]
@zyofeng you might be able to drop the token and use fetch to delete the cookie on a server’s endpoint. That might work but I’m not sure whether the cookie will be sent using RN’s fetch.

On the other hand, it’s usually not a good practice to log a user out completely. If you take a look at other apps, few actually offer this. Considering that you probably thought this through, I’d suggest you try my suggestion first.

I’m afraid of that doesn’t work your options are limited :/

**Comment by zyofeng** [comment]
@philpl The cookie resides in the browser I don't see how using fetch would clear it out? Additionally IdentityServer actually presents you with a screen to confirm whether the user would like to log out which requires interaction.

The problem is if I dont log the user out completely (in the browser as well as in app) then there might as well not be a logout facility in the app at all as the user will just be automatically logged in as the last person when the app redirect to the login page, representing a significant security flaw.

**Comment by philpl** [comment]
@zyofeng it all depends on where RN is getting the cookie jar for `fetch` for. I honestly cannot rule out that it works, or confirm it for sure 😆

> IdentityServer actually presents you with a screen to confirm whether the user would like to log out which requires interaction

Then that won't work if it's not in the standard and in AppAuth (as per the linked issue). I guess the next issue to jump on then would be this one: https://github.com/openid/AppAuth-iOS/issues/132

But all I can tell you is unfortunately that as long as AppAuth doesn't support it, this library cannot support it as it's just wrapping it

**Comment by kadikraman** [comment]
^^ As @kitten said, I think we should restrict ourselves mostly to what the parent libraries support.

**Comment by TheTimeWalker** [comment]
Hello! I would like to discuss this issue again. After a few months there was actually a move that the hybrid flow should now also be accepted in AppAuth. This has actually been merged in AppAuth-iOS now which was referenced in this issue: https://github.com/openid/AppAuth-iOS/issues/292

The pull request to this is here: https://github.com/openid/AppAuth-iOS/pull/298

Seeing as the iOS version accepts `code id_token` now (and therefore Android version could follow suit), I would propose that the React Native library should also be enhanced with this flow and would accept a config setting where you could override the default `code` to `code id_token`
