### ISSUE TITLE
Wrong import in example app?

### ISSUE THREAD

**Issue by joh-klein** [FormidableLabs/react-native-app-auth#157]
Is this correct? https://github.com/FormidableLabs/react-native-app-auth/blob/master/Example/ios/AppAuthExample/AppDelegate.m#L14

When I copied it into my project, it gave me build errors, and in the readme the import is also different …

**Comment by kadikraman** [comment]
You are correct, there were some issues with the instructions, but the example app and instructions should definitely be working in `3.1.0`. Please reopen this issue if it's still a problem :)
