### ISSUE TITLE
Usage with Invitations?

### ISSUE THREAD

**Issue by waynebloss** [FormidableLabs/react-native-app-auth#158]
Has anyone implemented Oauth signups with invitations? If so, can you share some information about how the flow works?

For instance - user `A` invites user `B` to use the app. User `B` receives an email with a link to install the app. Presumably, the link opens the iOS/Android app store and lets the user install the app... However, I'm not sure where to go from there.

Do I use "deferred deep-linking" to forward an invitation token to the app for its initial startup?

Alternatively, do I just let any user perform a "sign up" action on the app and then once I have their email address as provided by the OAuth provider, match that up to an `invitation` record in my server database to complete the signup?

**Comment by kadikraman** [comment]
I think the deferred deep linking would be the way to go. I'm not sure how your referral scheme is implemented, but you could always exchange any referral tokens in the background immediately after the user has signed in.

Closing this as although interesting, the question is not related to this library 😊

**Comment by waynebloss** [comment]
No problem! Thanks for your help.
