### ISSUE TITLE
Release Build error ld: directory not found for option '-L/Users/xxxx/Release-iphonesimulator/AppAuth'

### ISSUE THREAD

**Issue by zyofeng** [FormidableLabs/react-native-app-auth#16]
Hi, 

I am trying to do a release build of the Example code in Visual Studio Code for iOS and got the following error.
Not quite sure how to resolve it, it happened to my own project as well (Debug works and I also followed the instruction and installed AppAuth through Cocoapods)

ld: library not found for -lAppAuth

Any help?

**Comment by zyofeng** [comment]
Same issue in xcode.

**Comment by kadikraman** [comment]
Hi @zyofeng - the Linked Libraries and Frameworks were not quite right in the example app. I've opened [this PR](https://github.com/FormidableLabs/react-native-app-auth/pull/20) to fix it. It is an issue with the example app, not the library itself.

That PR does the following:
1. In XCode Project Settings -> General -> Linked Frameworks and Libraries
2. Remove and re-add `libAppAuth.a`
3. Remove `libPods-AppAuthExample.a`
4. Add `libRNAppAuth.a`

Hopefully that will give you an idea of how to fix your release build as well. Hope this helps!

**Comment by UmairRehmat** [comment]
> Hi @zyofeng - the Linked Libraries and Frameworks were not quite right in the example app. I've opened [this PR](https://github.com/FormidableLabs/react-native-app-auth/pull/20) to fix it. It is an issue with the example app, not the library itself.
> 
> That PR does the following:
> 
> 1. In XCode Project Settings -> General -> Linked Frameworks and Libraries
> 2. Remove and re-add `libAppAuth.a`
> 3. Remove `libPods-AppAuthExample.a`
> 4. Add `libRNAppAuth.a`
> 
> Hopefully that will give you an idea of how to fix your release build as well. Hope this helps!

lipPods-AppAuthExample.a not found and not even libRNAppAuth.a
