### ISSUE TITLE
Accessing the granted scopes provided to the redirect URI

### ISSUE THREAD

**Issue by adcuz** [FormidableLabs/react-native-app-auth#160]
I am currently testing this out with Fitbit, but I have found that the response does not contain the scopes that the authenticating user allowed. Is there a way to get the raw data sent to the redirect URI, so I can use my own code to extract the enabled scopes?

I had thought that Fitbit may have an API method to get the enabled scopes, but they only ever give them to you via the parameters sent to the redirect URI.

Great project BTW!

**Comment by kadikraman** [comment]
Hi @adcuz - I don't quite understand the issue. Surely you know what scopes you requested from the client?

**Comment by adcuz** [comment]
@kadikraman The fitbit example above: The user can tick which scopes they want to allow from those that were requested. If the user un-ticks some, the only way to know what was actually allowed by the user is to get the allowed scopes from the redirect URI.

**Comment by pragmaticivan** [comment]
Any solution for that? I'm integrating that with Okta and it supposed to be returning more data for my extra scope, tested it with nodejs and it's working with that.

**Comment by pragmaticivan** [comment]
Nvm, I found out that okta has different types of token size, and was a workaround I'm making a request to get userProfiile data with the extra scope requested.
