### ISSUE TITLE
Still keep cookies after signout

### ISSUE THREAD

**Issue by lequangnguyenqn** [FormidableLabs/react-native-app-auth#163]
Hi!

I'm using my Identity Server 4. But it's not work correctly, i'm still authenticated from Identity Server after logout.
But it's working with your configure: https://github.com/FormidableLabs/react-native-app-auth#identity-server-4
After i changed to your configure "https://demo.identityserver.io" then it work with my code.

So i'm wonder why it's working in your setup? do we have special config in you Identity Server 4 or Reac native app.  Do you clear cookies after signout? i see the code just call to /connect/revocation. Or do you login which is open new webview in incognito mode?

**Comment by kadikraman** [comment]
I'm not 100% sure what could be different. We use their `native.code` config with PKCE, the code for the config is public [here](https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Config.cs#L67).

The revoke function doesn't have any native bindings, we simply call the revocation endpoint defined in the [discovery endpoint](https://demo.identityserver.io/.well-known/openid-configuration)

Only thing I can think of is Identity Server required client id being sent to the revocation endpoint.
Did you add `sendClientId: true` in revoke?

```js
await revoke(config, {
  tokenToRevoke: refreshedState.refreshToken,
  sendClientId: true
});
```

**Comment by lequangnguyenqn** [comment]
Hi again,

Yes, i set sendClientId to true. It's call the revocation endpoint successfully. And i also tried to use Postman to manual call to that endpoint.
But after i click on login button again, it went to Identity Server, that site remember that i did signin already and redirect back to my app.

am i missing the configure in my React Native app? something like open the webview with disable cookie, or clear cookie after call to revocation endpoint. But i do not find that code.

Can you show me how the example delete the cookies? when it clear the cookies in webview?

Thanks so much.

**Comment by kadikraman** [comment]
Glad you got it working and thanks a lot for also posting your solution 🙏

**Comment by rekha-emids** [comment]
Hi,
Revoke method is not clearing session in mobile.
