### ISSUE TITLE
Library does not handle response after provider's 'Back Button' press.

### ISSUE THREAD

**Issue by sambilov** [FormidableLabs/react-native-app-auth#167]
Hello.
First of all, thank you for your library. It is very useful.

I met the next bug:
When I am trying to login on Azure and then press back button, RNAppAuth does not handle the response. So, my authorization promise will be never resolved.
![image](https://user-images.githubusercontent.com/8501143/44731595-369c0b00-aaec-11e8-9f6c-fdc6157cfe18.png)

Have anybody met such problem?

**Comment by kadikraman** [comment]
Hi @sambilov - to be clear, can you not log in at all or only if you pressed the back button while filling in the form?

**Comment by sambilov** [comment]
Hello, @kadikraman! All works perfectly excepting described situation. So, I can not log in only if I press this 'Back' button. In other words, in all other cases (press 'Cancel' or continue login flow) it is OK.

**Comment by kadikraman** [comment]
After some consideration, I don't think this is something we can fix. It seems to be an issue within the login form. I'm not sure what the back button is meant to do. Maybe close the modal? But it's unlikely we can fix it from our end 😞
