### ISSUE TITLE
sign out

### ISSUE THREAD

**Issue by djleonskennedy** [FormidableLabs/react-native-app-auth#171]
Hello

is it posible to sign out with using this module?

I've seen this issue https://github.com/FormidableLabs/react-native-app-auth/issues/68

It is not "enhancement" or "nice to have" its a **bug** for library

we can see here how it should looks https://github.com/react-native-community/react-native-google-signin#signout

for example OIDC client https://github.com/IdentityModel/oidc-client-js  for JS have this functionality too

How we can SignOut with react-native-app-auth ?

**Comment by kadikraman** [comment]
@djleonskennedy we have a [revoke](https://github.com/FormidableLabs/react-native-app-auth#revoke) method which calls the token revocation endpoint.

**Comment by djleonskennedy** [comment]
@kadikraman Thank you for answer, is it possible that problem course **IS4** configuration on BE ?

**Comment by kadikraman** [comment]
What is BE?

The IS4 implementation requires you to [send the `clientId`](https://github.com/FormidableLabs/react-native-app-auth#identity-server-3) in the revocation request so the config for it is:

```
await revoke(config, {
  tokenToRevoke: refreshedState.refreshToken,
  sendClientId: true
});
```

This is a network request only. It doesn't open a webview. The issue you linked to was a suggestion that it should. That's on in the OAuth spec though, hence nice to have.

**Comment by djleonskennedy** [comment]
@kadikraman BE (Back End) 

as i can see now re-woke is working fine, it's resolves with status 200, however then during sign in **webview** login with previous credentials, looks like it use **cookies** or some thing like that, is it possible to reset **webview** data to avoid auto login? (solutions like 'react-native-cookies' doesn't affect)

**Comment by kadikraman** [comment]
Yeah there's quite a few people [fighting the issue](https://forums.developer.apple.com/message/286374#286374). Radio silence from Apple though.

As a workaround, if you add

```
additionalParameters: {
  prompt: 'login'
}
```

to your config, it will always prompt the user to log in.

`SFAuthenticationSession` does not persist the cookies past the current session btw, if you close the app completely and reopen it, they'll be gone, so this is only an issue if in the _same_ session you've already logged in once so hopefully the above workaround is sufficient.

**Comment by djleonskennedy** [comment]
@kadikraman that helps, thanks a lot

**Comment by spsaucier** [comment]
@kadikraman is there a way to clear the in-app-browser's cookies on Android?

**Comment by kadikraman** [comment]
Hi @spsaucier - I've been looking through the issues in AppAuth Android for this, and they also say to just use the `prompt=login` in the auth request, referring to the [openid docs](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1)

**Comment by spsaucier** [comment]
Thanks @kadikraman, we're already doing that, but for this Okta setup, it still shows only the password field.

**Comment by snicro** [comment]
@spsaucier I'm experiencing a similar issue. Any luck finding a solution?

**Comment by spsaucier** [comment]
Unfortunately, no, I haven't found one.

**Comment by itsVinodh** [comment]
> @djleonskennedy we have a [revoke](https://github.com/FormidableLabs/react-native-app-auth#revoke) method which calls the token revocation endpoint.

If we don't have the revocation endpoint, how can we sign out?

**Comment by EuriskoEDeek** [comment]
Upon logging out i am replacing authorizationEndpoint with the logout endpoint. The user manage the sign out but the authorize method is throwing an error 

how to get rid of this error ? 
is there another way to implement the sign out using this library ?
Tried revoking but the cookies in the browser are not being cleared. 


```
Error: State mismatch, expecting 5VjRYQM6SsRvcMSJNXXncPDQFxH1s3V3VucYvf_rSMM but got (null) in authorization response <OIDAuthorizationResponse: 0x600000dc5680, authorizationCode: (null), state: "(null)", accessToken: "(null)", accessTokenExpirationDate: (null), tokenType: (null), idToken: "(null)", scope: "(null)", additionalParameters: {
}, request: <OIDAuthorizationRequest: 0x60000057bf70, request: https://uat-ssid.sta.gov.sa/ssid/oauth/logout?nonce=BWWVxAplbKw9HCHlTUf0fnAGo7IRtcM6TKaJjIVIm9k&response_type=code&logout_url=sa.sauditourism.iPhone.acc://visitsaudi-acc.sauditourism.auth0.com/ios/sa.sauditourism.iPhone.acc/callback&scope=profile&code_challenge=tc9I0D4QI0JnIQWwDR6Ib0vFhytxfCKE794p0uG7c5c&code_challenge_method=S256&redirect_uri=sa.sauditourism.iPhone.acc://visitsaudi-acc.sauditourism.auth0.com/ios/sa.sauditourism.iPhone.acc/callback&client_id=82326efda338e139e1c6308082161af75e4f6381b05ea0bd577f0d02ad3f51a3&state=5VjRYQM6SsRvcMSJNXXncPDQFxH1s3V3VucYvf_rSMM>>
    at Object.promiseMethodWrapper [as authorize] (NativeModules.js:104)
    at authorize (index.js:214)
    at _callee2$ (user.js:126)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:155)
    at runtime.js:190
    at new Promise (es.promise.js:244)
```

**Comment by aureosouza** [comment]
@kadikraman thanks `additionalParameters` helped, but we noticed typescript is breaking, as it doesn't expect this param, could be good to update the `.d.ts` files

**Comment by Bekaxp** [comment]
Hi guys... just my 2 cents... as I was running into the same issue for the past few days. My workflow and issue:
- logged in
- logged out, clear all secure storage data on the app and reload the app...
- the app tried to login again (but used the same session, which was still somehow active in the auth browser popup screen) => more or less the issue described above by you guys...

What I did to make it work:
- I am using `"react-native-app-auth": "^7.0.0-rc2"`
- On the `authorize` method I've added this properties: `
  {
    {...the_rest}
    additionalParameters: {
      prompt: 'login',
    },
    iosPrefersEphemeralSession: true,
  }`
 - To `logout` I am calling a `revoke` method on the `refresh token`
 
 Hope it helps to someone 👍

**Comment by adambeer** [comment]
Has anyone run a cross a solution or workaround to this lately? All suggestions above dont seem to work for me. Im revoking a refresh token but it seems that the cookies stay in safari and force an instant login when authorize is called again.

I tried to call /logout (AWS Cognito) through authorize() and got a crash so that didn't work either. @Bekaxp and @kadikraman  solution don't seem to do anything either.
