### ISSUE TITLE
KEYCLOAK : redirectUrl: '<YOUR_REDIRECT_SCHEME>:/callback'

### ISSUE THREAD

**Issue by titoff002** [FormidableLabs/react-native-app-auth#175]
Hello,

For the part related to the keycloak configuration, what should you put in place of "YOUR_REDIRECT_SCHEME"?

redirectUrl: '<YOUR_REDIRECT_SCHEME>: / callback'

Plus, I get the following error message when I click on the "authorize" button (check the screenshot)

![image](https://user-images.githubusercontent.com/24948237/45620588-b713b300-ba7d-11e8-8ba2-c040cba16a93.png)

Thank you and have a good day.

**Comment by kadikraman** [comment]
Your error means that the native library has not installed correctly.
Have you run `react-native link`?
Have you installed the AppAuth Pod?
Have you re-run the native application (not just the packager) since you have new native changes now?

As for the redirect scheme, it's usually something like `com.yourappname`

**Comment by kadikraman** [comment]
`react-native log-android` will give you the logs. You can also run your app through Android Studio.

I don't really know why it's closing your application, it can be a lot of things. Have a look at the logs. May be a configuration issue.

Using `io.identityserver.demo` is probable fine, though usually you'd use your own app name, but you can't have a space in the string

🚫 `io.identityserver.demo: / callback`
✅ `io.identityserver.demo:/callback`

**Comment by spipatpunlop** [comment]
@kadikraman I've got the same problem for my redirectUrl and I want use my own app name instead of using `io.identityserver.demo:/callback` But I don't know how to find my pown app url from. For example, my app name "AwesomeApp" then my app url will be `com.AweSomeApp:/callback`?
