### ISSUE TITLE
application crashes for unknow reason

### ISSUE THREAD

**Issue by titoff002** [FormidableLabs/react-native-app-auth#176]
Hello,

I just created a project react-native:

npm install react-native-app-auth --save
react-native link react-native-app-auth

I added in the file "android / app / build.gradle":

    manifestPlaceholders = [
      appAuthRedirectScheme: 'io.identityserver.demo'
    ]

My configuration for keycloak:

const config = {
  issuer: 'http: // keycloakserver: 9080 / auth / realms / test',
  clientId: 'web_app',
  redirectUrl: 'io.identityserver.demo: / callback'
  scopes: ['openid', 'profile']
};

// Log in to get an authentication token
const authState = await authorize (config);

// Refresh token
const refreshedState = await refresh (config, {
  refreshToken: authState.refreshToken,
});

When I run my application, it crashes the function call: "const authState = await authorize (config)"

Do you have an idea ?
Would I have forgotten something in the configuration?
I can not find log logs (if you know how to find them, I'm interested).

PS: I use the latest version of android studio and like AVD:
![image](https://user-images.githubusercontent.com/24948237/45744053-cfaad700-bbfd-11e8-9e69-681b6a781612.png)

STEPS : 

1 - this application this start correctly
![image](https://user-images.githubusercontent.com/24948237/45744142-139ddc00-bbfe-11e8-8fc9-12ba3f856f75.png)

2 - when click on the button "Authorize coucou", i call function "const authState = await authorize (config)"  and this application crashes and i have this messages : 

![image](https://user-images.githubusercontent.com/24948237/45744214-4b0c8880-bbfe-11e8-88a1-8df57c3c0b24.png)

3- i click to "open app again" and re-click on the button "authorize coucou", and new message appear : 

![image](https://user-images.githubusercontent.com/24948237/45744286-7e4f1780-bbfe-11e8-9066-870ea71a84fa.png)

Thank you.

**Comment by titoff002** [comment]
PS : for information, when I click on the button "authorize coucou": I am not redirected on the web page login / identification keycloak.

**Comment by titoff002** [comment]
PS: Moreover, when I want to test with the example of the repository git => it does not work either.

**Comment by titoff002** [comment]
In the config, when I add:

  serviceConfiguration: {
    authorizationEndpoint: 'http: // keycloakserver / auth / realms / r / protocol / openid-connect / auth? client_id = app-web & redirect_uri = <redirecturi>',
    tokenEndpoint: 'http: // keycloakserver / auth / realms / r / protocol / openid-connect / token? client_id = app-web'
  }

I access the authentication keycloak page, and when I connect I go back to the android app but it crashes.

Is it compatible with the latest version of keycloak (keycloak-4.3.0.Final/) ??

thank you

Regards,
Christophe

**Comment by kadikraman** [comment]
@titoff002 btw in GitHub you can add single backticks around inline code blocks  `like so` and triple backticks (```) around multiline codeblocks
```
like so
```

Please use this for formatting your issue so it would be easier to read, thanks 😊

RE: your issue. It would be helpful if you could provide the actual error. To do this, either run your app through Android Strudio or run `react-native log-android`

**Comment by titoff002** [comment]
Solution (for dev environnment) :

`dangerouslyAllowInsecureHttpRequests: true`

**Comment by AliTalebi** [comment]
@titoff002 Thank you

**Comment by attachi20** [comment]
hi bro ,i have some problem that you have any idea how to fix it?
