### ISSUE TITLE
iOS 12 - WiFi Specific Issue

### ISSUE THREAD

**Issue by gsinchan** [FormidableLabs/react-native-app-auth#181]
Hi Guys,

We are using this package for authenticating with OKTA and facing an error scenario on iOS 12 only. Any thoughts on this ?

**Scenario**: On iPhone running iOS 12 while connected in WiFi
During the authentication, it's not displaying the system popup (" ABCD App " Wants to Use " abcd.com" to Sign In),  just the spinner keep on spinning and finally timeout popup comes up.

Note: The same issue is not experienced in any of iOS 11 versions also when connected to Mobile Network (LTE) in iOS 12.

**Comment by kadikraman** [comment]
@gsinchan that is very singular. Are you sure the issue is with iOS 12 and not the phone itself? Can you reproduce it on two different iOS 12 devices?

**Comment by janpieterz** [comment]
I was unable to replicate this on an iOS 12 device (iPhone 8 plus) on a wifi connection.

**Comment by gsinchan** [comment]
Thanks guys for your response. 

Actually, it was an intermittent issue and on few devices only. Could not identify the pattern though (i.e which scenario) but this is fixed now. I have just added the following in **AppDelegate.m** 

@synthesize authorizationFlowManagerDelegate;

Haven't faced that issue after that in any of the devices.
