### ISSUE TITLE
Package name confict

### ISSUE THREAD

**Issue by bulats** [FormidableLabs/react-native-app-auth#183]
Package name com.reactlibrary conflicts with other libraries that use this package name, for example, https://github.com/rumax/react-native-PDFView and https://github.com/MostWantIT/react-native-video-editor . This results in build errors. 

The package name need to be changed to something more specific.

**Comment by kadikraman** [comment]
Released in [v4.0.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.0.0) 🎉
