### ISSUE TITLE
Connecting to Azure does not redirect back to the app

### ISSUE THREAD

**Issue by mjniday** [FormidableLabs/react-native-app-auth#203]
**Is this a bug, feature request or a request for information?**
Not sure if this is me just missing info/documentation or a bug. 

**Describe your issue and include steps to reproduce if possible.**
I've set up my config as described in the documentation. I've tried a number of combinations, but primarily tested this with the following: 

```
const config = {
      issuer: 'https://login.microsoftonline.com/common',
      clientId: '<client_id>',
      redirectUrl: 'urn:ietf:wg:oauth:2.0:oob'
    }
```

I've seen a few places reference the fact that the redirectUrl here and the `appAuthRedirectScheme` need to match, so I tried setting that also to `urn:ietf:wg:oauth:2.0:oob`, so I've set it to
```
appAuthRedirectScheme: "urn:ietf:wg:oauth:2.0:oob"
```

The behavior with this config is as follows:
This opens a window where I can authenticate.
After typing in username/password, I just see a blank screen. If I inspect the url of that screen, it appears that everything in that url is correctly formatted, but I would expect at this point that the browser window would close and send me back to my application.

As a sanity check I was able to get the token back from google auth, so I don't think my entire setup is off track. Another thing that was not clear to me on that front though was that for Google I had to set the `appAuthRedirectScheme` to com.googleusercontent.apps.GOOGLE_ID". I don't see via this configuration how I could support having both google auth and azure auth in my same application.

Thanks for any info you can provide.

**Comment by mjniday** [comment]
This ended up working for me after I went against the documentation and set the `redirectUrl` to `com.myappname.app` and setting up an appropriate redirect url within azure.

Going to close this for now since it seems to be working out alright.

**Comment by VitaliiK91** [comment]
@mjniday Could you please explain how you configured Azure redirect URL. I am experiencing similar issue. here is some configuration:
```
redirectUrl: com.my.app,
 manifestPlaceholders = [
            appAuthRedirectScheme: 'com.my.app'
        ]
```
but what redirect URL should I specify in Azure console?
Thanks!

**Comment by kadikraman** [comment]
`com.my.app/oauth`

**Comment by VitaliiK91** [comment]
@kadikraman Thank you, that worked. As I side note I had to change `redirectUrl` to `com.my.app/oauth`

**Comment by liatnetach** [comment]
@mjniday hey, sorry for bothering you after all this time, but i need to add the custom scheme in my Azure portal, where exactly should I put it?
I have also Web Platform but there is isn't a possibility to add redirectUrl with custom scheme..
