### ISSUE TITLE
Azure fails to open auth page on iOS

### ISSUE THREAD

**Issue by mjniday** [FormidableLabs/react-native-app-auth#204]
**Is this a bug, feature request or a request for information?**
Bug

**Describe your issue and include steps to reproduce if possible.**
I'm using the latest version of this library and trying to implement a login flow with Azure. My config is working fine for Android (Google and Azure), and iOS (just Google). Calling the authorize method results in this error:
![image](https://user-images.githubusercontent.com/7980741/47870913-053c0600-dde1-11e8-812c-cc652f49dace.png)

I initially thought this could be related to https://github.com/FormidableLabs/react-native-app-auth/issues/194, but I tried modifying the source files with no luck. Unfortunately that error message doesn't give me much to go off of. 

Note that as soon as the `authorize` method is called, this JSON error is presented. This happens before the user would even see the screen to log into a Microsoft account

**Comment by mjniday** [comment]
Dug around a little more and found this issue, which seems to be the cause of this problem. I'm not sure if this library can do something to work around that issue: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/10069080-common-openid-connect-discovery-endpoint-should-no

**Comment by kadikraman** [comment]
Hi @mjniday - we use the openID endpoint to fetch the service configuration, but you can override it by [passing it in manually](https://github.com/FormidableLabs/react-native-app-auth#config) as `serviceConfiguration` - that should help.

**Comment by kadikraman** [comment]
This seems to be resolved, so closing 👋
