### ISSUE TITLE
In webview

### ISSUE THREAD

**Issue by titoff002** [FormidableLabs/react-native-app-auth#205]
Hello,

With keycloak: is it possible to include the authentication screens in a webview instead of being redirected to a browser?

Thank you.

**Comment by titoff002** [comment]
if it is possible: how? (Do you have a piece of code to send me?)

**Comment by kadikraman** [comment]
No, for security reasons, that won't be possible.

**Comment by tarun29061990** [comment]
Hey any updates on this??
I am using this library for login and logout both. But the logout doesn't clear browser cookies, so If I try to login again then its not showing the login screen and it directly redirecting me to dashboard. Can I open the login and logout in webview??

**Comment by kadikraman** [comment]
Add
```js
{
  additionalParameters: {
    prompt: 'login'
  }
}
```
to your config to always direct the user to the login screen.
