### ISSUE TITLE
Is this possible to be used for ReactXP project?

### ISSUE THREAD

**Issue by hmheng** [FormidableLabs/react-native-app-auth#207]
**Is this a bug, feature request or a request for information?**
Request for info

Is this possible to be used for ReactXP project since it is a cross-platform project? 
It will be good if made available to all platforms, iOS, Android, Windows, Web.

**Comment by anilpai** [comment]
Yes.. I am looking for a Web version to test a simple Okta Oauth2 integration for my app.

The Okta team is too lazy, they just used this project and created a okta example of this https://github.com/oktadeveloper/okta-react-native-app-auth-example

**Comment by kadikraman** [comment]
This library works in React Native (so iOS and Android), but not on Windows or web.

We are open to proposals or PRs to extend the library, but no concrete plans of such kind at the present.
 
@anilpai I think that repo was created as a supplement in a learning material to use Okta with this library in particular, so it's only fair they copied it. Not sure if they have a web example, but I'll ask.

**Comment by mraible** [comment]
Hello @anilpai! I’m the lazy developer you’re referring to. It’s good to be a lazy developer, right? There’s no reason to build something from scratch if it already exists! ;)

That being said, what sort of example are you looking for? What’s missing from the current example?

**Comment by kadikraman** [comment]
Hi @rndm-com - for my part, it's worth a discussion. I've heard of React XP, but never worked with it, so I'm not sure on the implications of adding additional environments to the library. However, I'd be happy to look into it.

Email me at kadi.kraman@formidable.com and we can discuss this further.
