### ISSUE TITLE
Profile details not returning 

### ISSUE THREAD

**Issue by Buwaneka1993** [FormidableLabs/react-native-app-auth#215]
I have configured custom identification server as give example for [Identity Server 4](https://github.com/FormidableLabs/react-native-app-auth#identity-server-4)

here is configurations

```
  await authorize({
        issuer: "https://www.ident-preprod1.nets.eu/oidc",
        clientId:'{MY-CLIENT-ID}',
        redirectUrl:'{REDIRECTURL}',
        scopes:['openid','profile','ssn','cert'],
        serviceConfiguration: {
          authorizationEndpoint: 'https://www.ident-preprod1.nets.eu/its/index.html',
          tokenEndpoint: 'https://www.ident-preprod1.nets.eu/oidc/token',
          revocationEndpoint: 'https://www.ident-preprod1.nets.eu/oidc/.well-known/jwk'
        },
        dangerouslyAllowInsecureHttpRequests :true,
      });
```

It will return details, but only accessToken,additionalParameters,idToken, refreshToken,tokenType 
I want to get profile info also. but how? I put 'profile' in the  scopes as well.

here is what I trying to implement 
https://www.nets.eu/developer/e-ident/overview/Pages/oidc.aspx#mandatory

**Comment by kadikraman** [comment]
On Identity Server 4, you can query the logged in user's info from https://demo.identityserver.io/connect/userinfo (it's the `userinfo_endpoint` in the discovery document). Just add the `Authorization: Bearer <JWT>` header to the request.

**Comment by Buwaneka1993** [comment]
In discovery url there is no userinfo_endpoint mensioned :-/
{"response_types_supported":["code"],"request_parameter_supported":true,"request_uri_parameter_supported":false,"claims_parameter_supported":false,"grant_types_supported":["authorization_code"],"ui_locales_supported":["nb_NO","en_GB","da_DK","fi_FI","sv_SE","sv_FI"],"scopes_supported":["openid","profile","ssn","cert"],"issuer":"https://www.ident-preprod1.nets.eu/oidc","authorization_endpoint":"https://www.ident-preprod1.nets.eu/its/index.html","claims_supported":["amr","certpolicyoid","cn","dn","birthdate","certificate","given_name","family_name","notbefore","notafter","c","no_ssn","se_ssn","dk_ssn","no_bid_pid","dk_dan_pid","se_bid_securitylevel","fi_tupas_bank","aud","sub","iss","exp","iat","nonce","auth_time","dk_dan_rid","birthdate","phone_number","fi_ssn","name","fi_tupas_pid","fi_trx_code","fi_verification_code","userid","email","bankIdVerified"],"require_request_uri_registration":false,"jwks_uri":"https://www.ident-preprod1.nets.eu/oidc/.well-known/jwk","subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":"RS256","claim_types_supported":["normal","aggregated","distributed"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"token_endpoint":"https://www.ident-preprod1.nets.eu/oidc/token"}

**Comment by kadikraman** [comment]
If there's no userinfo endpoint, perhaps they return the profile [in the ID token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)? Try decoding your JWT. https://jwt.io/

**Comment by Buwaneka1993** [comment]
Worked :) thanks

**Comment by Buwaneka1993** [comment]
> If there's no userinfo endpoint, perhaps they return the profile [in the ID token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)? Try decoding your JWT. https://jwt.io/

Worked ! :) Thanks
