### ISSUE TITLE
Strava - unhelpful error `Failed to Authenticate`

### ISSUE THREAD

**Issue by donatoaz** [FormidableLabs/react-native-app-auth#216]
**Is this a bug, feature request or a request for information?**

This is a request for information

**Describe your issue and include steps to reproduce if possible.**

I am trying to authenticate against the Strava API Oauth2 scheme. There seems to be a particularity that they [need some specific query string parameters](https://developers.strava.com/docs/authentication/) on the authorize endpoint, and as such I have the following config object.

I also noted that they seem to do some sort of checking on whatever it is I pass as the `redirect_uri` such that whatever follows the scheme needs to match what was set up as the "Authorization Callback Domain" (see image below).

That said, when I do it manually, on the browser, using the following url:
`https://www.strava.com/oauth/authorize?client_id=***&redirect_uri=com.mysampleapp://com.mysampleapp&response_type=code&scope=activity:read_all`

After I hit authorize, my application opens up -- so I know that the scheme was properly registered (the excerpt from my AndroidManifest.xml is also below).

However, all in all, when I try and `authorize(config)` I get a very unhelpful error `Failed to Authenticate`.

```
Error: Failed to authenticate
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at t (RNDebuggerWorker.js:1)
```

Screenshot of Strava's config

![image](https://user-images.githubusercontent.com/127527/49895848-bdc18480-fe38-11e8-8a81-23b0c97bdc01.png)

```javascript
const config = {
  clientId: '***',
  clientSecret: '***',
  redirectUrl: 'com.mysampleapp://com.mysampleapp',
  scopes: ['activity:read_all'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
    tokenEndpoint: 'https://www.strava.com/oauth/token',
    revocationEndpoint: 'https://www.strava.com/oauth/deauthorize'
  },
  additionalParameters: {
    redirect_uri: 'com.mysampleapp://com.mysampleapp',
    response_type: 'code',
    client_id: '***',
    approval_prompt: 'force'
  }
}
```

```xml
    <activity
      android:name="net.openid.appauth.RedirectUriReceiverActivity" >
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.mysampleapp" />
      </intent-filter>
    </activity>
```

**Comment by kadikraman** [comment]
Can you run your app in debug mode? If so, can you put a breakpoint [here](https://github.com/FormidableLabs/react-native-app-auth/blob/9f41f7ff2b3f64653ef458228ed0d06aed77af4e/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L213) to see if there's anything in the environment (maybe the resultCode?) to help you get more details on the error.

You're right though, it's not a very helpful error message. Perhaps we could pass more details through. Let me know if there are any details in the environment that could help.

**Comment by bhaskardabhi-oviyum** [comment]
I am getting invalid client_id when the library tries to fetch token after authentication.

```
config = {
    clientId: '{clientid}',
    clientSecret: '{client secret}',
    redirectUrl: 'myapp://org.reactjs.native.example.myapp',
    serviceConfiguration: {
      authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
      tokenEndpoint: 'https://www.strava.com/oauth/token',
      revocationEndpoint: 'https://www.strava.com/oauth/deauthorize'
    },
    additionalParameters: {
      response_type: 'code',
      client_id: '{client_id}',
      approval_prompt: 'force'
    },
    scopes: ['activity:read_all']
};
```
[img]https://i.imgur.com/nD3XLJj.png[/img]

though the same config opened up authentication page.

**Comment by kadikraman** [comment]
I apologise for not getting back to this sooner. I finally got around to trying this out on Strava myself. This config worked for me:

```js
config = {
  clientId: '<client_id>',
  clientSecret: '<client_secret>',
  redirectUrl: 'myapp://oauthredirect',
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
    tokenEndpoint: 'https://www.strava.com/oauth/token?client_id=<client_id>&client_secret=<client_secret>',
  },
  scopes: ['activity:read_all'],
};
```

There are a couple of quirks here:
- I had to register the callback domain as `oauthredirect`. From trial and error, it looks it can be anything as long as it is used in the redirect like so: `myapp://<callack_domain>`
- they require the client secret and id being passed in the token endpoint. This is not in the spec and thus is not supported. But we can get around it by adding them to the tokenEndpoint as url params.

Token revocation also won't work for strava, because they use the param `access_token` instead of `token`, but you can easily implement it yourself using `fetch` 

```js
const res = await fetch(`https://www.strava.com/oauth/deauthorize?access_token=${authState.accessToken}`, {
  method: 'POST',
});
```

I'll add this to the docs as well.
