### ISSUE TITLE
When we set additionalParameters the app crashes

### ISSUE THREAD

**Issue by THPubs** [FormidableLabs/react-native-app-auth#217]
I just set the `additionalParameters` like this:

    additionalParameters: {
      prompt: "select_account",
      state: "authentication_to"
    }

As soon as I set it, the app crashes. There are no errors in react native console, debugger console and not even when we run the app from the android studio (In debug mode). I simply get the following error:

<img width="384" alt="screen shot 2018-12-13 at 9 16 33 pm" src="https://user-images.githubusercontent.com/1212023/49949784-7ca2a080-ff1c-11e8-8a98-d86db0a738ac.png">

But I noticed one thing. In the sample code, I have two parameters. If I remove the last one the app works. If I remove the first and keep the last one again the app crash. Looks like the error comes only for some errors?

**Comment by kadikraman** [comment]
Additional parameters just get added to the request as they are. You can't use `state`, because it's a reserved parameter in oauth.

**Comment by THPubs** [comment]
Ah. @kadikraman What about `response_type`?

**Comment by kadikraman** [comment]
Same with `response_type` (and `client_id` and `client_secret` and `scope` and `redirect_uri` etc) - the whole idea is that the library handles all the auth stuff for you.

**Comment by THPubs** [comment]
What's the default `response_type`? How can I set it to `code`?

**Comment by THPubs** [comment]
Sorry looks like I have to set it to `code id_token`

**Comment by kadikraman** [comment]
The `response_type` is `code` at the moment. We currently are not supporting other response types.

**Comment by kadikraman** [comment]
We are planning to support the Hybrid flow in the future. You can track the progress in https://github.com/FormidableLabs/react-native-app-auth/issues/218

**Comment by tarun29061990** [comment]
Any updates on how to pas responseType ?? 
Or can I use any other flow besides "code"??
