### ISSUE TITLE
iOS/Android errors with Nibe provider

### ISSUE THREAD

**Issue by Shamplol** [FormidableLabs/react-native-app-auth#220]
Hey,

First thing, the library works perfectly fine when trying to authenticate with Somfy API.

My issues come with a specific provider ( Nibe: https://api.nibeuplink.com/ ) on both iOS and Android.

On Android, everything worked fine when I was using the version 3.0.2, but when I upgraded to 4.0.0 I started facing "Failed exchange token" while using the same configuration.

After trying some Java debugging I found the following exception in "onActivityResult" : 

`
AuthorizationException: {"type":2,"code":2001,"error":"invalid_client","errorDescription":"The client secret was incorrect.","errorUri":""}
` 

On iOS, it never worked. No matter what version I was using I always got "Invalid request".

Here's my configuration : 

```
{
    'serviceConfiguration' : {
        'authorizationEndpoint' : 'https://api.nibeuplink.com/oauth/authorize',
        'tokenEndpoint' : 'https://api.nibeuplink.com/oauth/token',
    },
    'clientId' : '****',
    'clientSecret' : '****',
    'redirectUrl' : 'net.solidom.viebrockhaus:/callback',
    'scopes' : ['READSYSTEM', 'WRITESYSTEM'],
}
```
(clientSecret contains "+" & "=" characters)

I've tried to create different apps on the Nibe API (with different clientId/clientSecret).
I have no problem authenticating with Postman.

Thanks~

**Comment by kadikraman** [comment]
Hi 👋 - sorry for the late reply. I don't really know why it would not accept the client secret, looks like a provider-specific bug. Closing this issue due to age, but I'll reopen if anyone can confirm this as a bug.
