### ISSUE TITLE
[QUESTION] Google Offline Access / Server Side Flow

### ISSUE THREAD

**Issue by kasterlod** [FormidableLabs/react-native-app-auth#221]
Hello!

I would like to know how we can get it working with server side flow for Google and receive offline code?
(https://developers.google.com/identity/sign-in/web/server-side-flow)

Is it even possible with that library?

thanks in advance for more info!

**Comment by kadikraman** [comment]
Hi @kasterlod - we support the Authorization Code Flow in OAuth2 (with PKCE). At a glance, don't think it would work with this library. It seems to be a different flow, although similar, and we're not really open for modifications outside of the OAuth spec.
