### ISSUE TITLE
Crash on IOS

### ISSUE THREAD

**Issue by ColtraneNadler** [FormidableLabs/react-native-app-auth#222]
2018-12-23 14:19:25.369302-0500 fondue[11083:4079933] *** Terminating app due to uncaught exception 'RNAppAuth Missing protocol conformance', reason: '<AppDelegate: 0x6000002212a0> does not conform to RNAppAuthAuthorizationFlowManager'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ca0c1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010b2f8031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ca81975 +[NSException raise:format:] + 197
	3   fondue                              0x000000010a4ed773 -[RNAppAuth authorizeWithConfiguration:redirectUrl:clientId:clientSecret:scopes:additionalParameters:resolve:reject:] + 755
	4   fondue                              0x000000010a4ec660 __118-[RNAppAuth issuer:redirectUrl:clientId:clientSecret:scopes:additionalParameters:serviceConfiguration:resolve:reject:]_block_invoke + 304
	5   AppAuth                             0x000000010abe39a0 __82+[OIDAuthorizationService discoverServiceConfigurationForDiscoveryURL:completion:]_block_invoke.174 + 48
	6   libdispatch.dylib                   0x000000011380f7ab _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x00000001138107ec _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000011381b8cf _dispatch_main_queue_callback_4CF + 628
	9   CoreFoundation                      0x000000010c9cec99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x000000010c992ea6 __CFRunLoopRun + 2342
	11  CoreFoundation                      0x000000010c99230b CFRunLoopRunSpecific + 635
	12  GraphicsServices                    0x0000000115955a73 GSEventRunModal + 62
	13  UIKit                               0x000000010f1d7057 UIApplicationMain + 159
	14  fondue                              0x000000010a20535f main + 111
	15  libdyld.dylib                       0x000000011388d955 start + 1
	16  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ColtraneNadler** [comment]
Restarted XCode a few times, just started working.

**Comment by JaEdmuva** [comment]
@ColtraneNadler did you do anything specific to get rid of this issue? I'm running into it as well

**Comment by dkwl93** [comment]
I'm getting this as well.
package.json `react-native-app-auth`: 4.4.0
podfile `AppAuth`: 0.95.0

**Comment by JaEdmuva** [comment]
For anyone running into this, please make sure you followed the setup part of documentation entirely. I did not completed the setup for iOS at first and run into it.

**Comment by SeedyROM** [comment]
@JaEdmuva This is 100% the issue, the docs do describe that it needs to be setup via an ios package manager but they don't really make it 100% obvious this is what's needed for it to work. I would have a note that warns users they **HAVE** to do this to get it working.

I did this as a starting point to get the cocoapods building the deps, then added the changes from the [docs](https://commerce.nearform.com/open-source/react-native-app-auth/docs/#for-react-native--068)
