### ISSUE TITLE
Okta: Revoke token does not clear / revoke user session

### ISSUE THREAD

**Issue by johncrisostomo** [FormidableLabs/react-native-app-auth#223]
Hello everyone,

I just wanted to ask if this is the correct behaviour of this library. Currently I am trying to log out of the app by revoking the token and then clearing all the related information in AsyncStorage (similar to what is being done here: https://developer.okta.com/blog/2018/03/16/build-react-native-authentication-oauth-2). Based on my understanding and based on what I saw on the source code, this library does not handle clearing or revoking the user session that Okta maintains for refreshing the token or getting another one.

The issue I am currently having is that trying to login after revoking the token will no longer redirect me to the Okta login page, it will just implicitly get the token (because of the valid user session). I currently have 
```
additionalParameters: {
  prompt: 'login'
}
```
as suggested in this issue: https://github.com/FormidableLabs/react-native-app-auth/issues/70#issuecomment-427090496  .

Should we handle this via a separate call to Okta, using the appropriate API call?

Thank you.

**Comment by BharathJLL** [comment]
https://github.com/FormidableLabs/react-native-app-auth/issues/98

**Comment by johncrisostomo** [comment]
Thanks @BharathJLL ! Closing this as this question seems to be answered in an open issue https://github.com/FormidableLabs/react-native-app-auth/issues/68

**Comment by asherzog** [comment]
@johncrisostomo were you able to get the solution in #68 to work with clearing Okta sessions?

**Comment by kadikraman** [comment]
@buskerone is this using Okta or some other IDP?

**Comment by spsaucier** [comment]
Yes, @buskerone is using Okta.
