### ISSUE TITLE
Unable to link library in ios.

### ISSUE THREAD

**Issue by nainishmodi** [FormidableLabs/react-native-app-auth#225]
I tried both way manual way and using **link** command as well. after removing package builds becoming successful. it is working fine in android. 

<img width="1080" alt="1" src="https://user-images.githubusercontent.com/17999172/50570794-e1844480-0dbe-11e9-8336-2297a328b9a1.png">

Please suggest any solution

**Comment by kadikraman** [comment]
Are you opening the `.xcworkspace` on Xcode (instead of `xcodeproj`)?

**Comment by nainishmodi** [comment]
Nup. i m not opening .xcworkspace in xcode. i have opened xcodeproj. I have tried using **link** command as well as below steps.

In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
Go to node_modules ➜ react-native-app-auth and add RNAppAuth.xcodeproj
In XCode, in the project navigator, select your project. Add libRNAppAuth.a to your project's Build Phases ➜ Link Binary With Libraries
Run your project (Cmd+R)

My android app is working like a charm using this package but i am new in mac and xcode.

**Comment by nainishmodi** [comment]
Package.json looks like
 
"dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    **"react-native-app-auth": "^4.0.0"**
  },

**X code version is 10.1 (10B61)**

**Comment by kadikraman** [comment]
If you're using pods (which we are), you have to open the `. xcworkspace` - pods don't load in `.xcodeproj`

**Comment by nainishmodi** [comment]
I am not using pods. i don't know how to use it? using pods the issue will be resolve?

**Comment by nainishmodi** [comment]
Ok I will back to you after Implement as instructed..let see what happens..Thank you so much!

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 2, 2019 at 8:58 PM, Kadi Kraman<notifications@github.com> wrote:   
Well you have to install the AppAuth dependency.

https://github.com/FormidableLabs/react-native-app-auth#ios-setup

You can do it either with Pods, Carthage or as a static library. Pods is the easiest.
   
   - cd into your /ios directory and run pod init this will create a Podfile for you
   - open the Podfile and add the AppAuth dependency
   - on the terminal, run pod install

You can use the Podfile in the example app as a guide.

**Comment by nainishmodi** [comment]
The issue has been resolved. It is working fine in IOS as well. Thanks you so much once again!! and closing the issue.
