### ISSUE TITLE
Error: invalid_request at createErrorFromErrorData

### ISSUE THREAD

**Issue by ColtraneNadler** [FormidableLabs/react-native-app-auth#226]
"react-native": "^0.55.2",
"react-native-app-auth": "^4.0.0",

Getting an error when trying to authorize with Spotify.
```
 async auth() {
    const config = {
      clientId: 'ff482262***d2fa36830957',
      redirectUrl: 'com.fondue.oauth:/redirect',
      scopes: ['user-read-email', 'playlist-modify-public', 'user-read-private'],
      serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.spotify.com/authorize',
        tokenEndpoint: 'https://accounts.spotify.com/api/token'
      }
    };

    try {

      const result = await authorize(config);

      console.log('RESULT',result);
    } catch(e) {
      console.log('Error',e);
    }
  }
```

The url opens fine, and when I click agree on this page- 
![image](https://gyazo.com/43bc4e350b3c02674a80632752c02f39.png)
, the browser window closes properly but then errors... I'm assuming there's a problem with getting the token? 

Any ideas on what could be going on? I'm pretty certain I configured everything properly.

The error after browser window closes on redirect:
```
Error Error: invalid_request
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```

**Comment by ColtraneNadler** [comment]
Seems like there is a problem when RNAppAuth tries to build the body of the post request to exchange the activation code for the access token/refresh token- https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow.

**Comment by kadikraman** [comment]
After some trial and error, I got this to work on iOS by configuring a redirect uri with one `/` instead of two `//`

So
`com.myapp:/oauth` works
`com.myapp://oauth` does not work

I'm not quite sure why, since it _should_ have two `//` to be a valid redirect scheme 😕

**Comment by kadikraman** [comment]
Looking at the original issue - looks like your problem was different. You have to include the client secret in the config.

**Comment by CallmeKingsley** [comment]
I went to https://appleid.apple.com/account/manage and scrolled down to where it shows my Devices that are signed in with this ID. I clicked on "Simulator" and chose "Remove from Account". try again
