### ISSUE TITLE
'OIDAuthState.h+IOS.h' file not found 

### ISSUE THREAD

**Issue by frostless** [FormidableLabs/react-native-app-auth#227]
**Is this a bug, feature request or a request for information?**
Bug

**Describe your issue and include steps to reproduce if possible.**
What I did in steps:
1: Download the package and do automatic link by npm install `react-native-app-auth --save`
and `react-native link react-native-app-auth`
2:Using Pod for the setup. I did not have Pod before so I `Pod init `and then add this `pod 'AppAuth', '>= 0.94'` and do `Pod install`.
3: I then follow through the rest of the iOS Setup guides.
4: I open the xcodeproject file and build and I got this `"OIDAuthState.h+IOS.h' file not found"` error.
5. If I just run `react-native run-ios` without building the xCode project, I would get this `"TypeError: Cannot read property 'authorize' of undefined" error.`

I suspect the something is wrong with the setup.

I follow this https://github.com/openid/AppAuth-iOS/issues/254 but still not working

I have this search path $(SRCROOT)/../node_modules/react-native-app-auth/ios and I manually drop the OIDAuthState.h+IOS.h file to it and it still not works.

I am using react-native: 0.57.8 and "react-native-app-auth": "^4.0.0".

**Comment by frostless** [comment]
Downloaded the example and have a good at it then follow the instruction do setup all over again. All good now..

**Comment by kadikraman** [comment]
Hi @frostless glad you got it sorted. I think I saw your comments on some other issues and looks like you found the solution in that you had to eject from expo. This is because `react-native-app-auth` has native dependencies and includes native iOS and Android code. This is not allowed unless you eject.
