### ISSUE TITLE
clientSecret parameter is not supported in identity server 4?

### ISSUE THREAD

**Issue by frostless** [FormidableLabs/react-native-app-auth#228]
The example code just omit the clientSecret part for identity server 4.(it is compulsory for identity server 3.
```
const config = {
  issuer: 'https://demo.identityserver.io',
  clientId: 'native.code',
  redirectUrl: 'io.identityserver.demo:/oauthredirect',
  scopes: ['openid', 'profile', 'offline_access']
};
```
And  I just tested by adding the parameter in but got and error "invalid client".
I understand it is not a good practice to include a static secret in app client code, but it should still work as long as it is not forbidden?

**Comment by kadikraman** [comment]
Hi. What's the identity server configuration? Can you reproduce your error exactly with one of the IS4 demo apps? https://demo.identityserver.io/

**Comment by frostless** [comment]
`const config = {
  issuer: 'https://demo.identityserver.io',
  clientId: 'server.code',
  clientSecret: 'secret',
  redirectUrl: 'io.identityserver.demo:/oauthredirect',
  additionalParameters: {},
  scopes: ['openid', 'profile', 'email', 'offline_access']

  // serviceConfiguration: {
  //   authorizationEndpoint: 'https://demo.identityserver.io/connect/authorize',
  //   tokenEndpoint: 'https://demo.identityserver.io/connect/token',
  //   revocationEndpoint: 'https://demo.identityserver.io/connect/revoke'
  // }
};`

configuration:https://demo.identityserver.io/ - > `client id: server.code 
client secret: secret 
grant type: authorization code 
allowed scopes: openid profile email api offline_access`

**Comment by kadikraman** [comment]
I can't reproduce the error with the configuration you've specified 😕- is it a full screen error for you?

**Comment by frostless** [comment]
You are right.. I just did a little test, and it is fine with their demo config.
I must have made a mistake with my own setting.
I will close this issue.
