### ISSUE TITLE
Ability to configure timeout for network request

### ISSUE THREAD

**Issue by kristerkari** [FormidableLabs/react-native-app-auth#236]
Hi there,

I was trying to search the docs and the issues for any kind of configuration or values for the network request timeouts, but could not find anything.

My use case is that when there is a ongoing refresh, I would like to block any additional refresh requests before I can be sure the timeout duration has ran out.

Please let me know if there is already a way of achieve this with the current library version.

**Comment by kadikraman** [comment]
Are you using redux? You could set a boolean flag in your redux state, e.g. `isRefreshing: true/false` and check it before calling `refersh()`?

Alternatively, you could use the lodash `throttle` or `debounce` functions, although I think a boolean flag would be more failsafe.

**Comment by kadikraman** [comment]
Alright, what about wrapping the `refetch()` call in a [throttle](https://lodash.com/docs/4.17.11#throttle) then?

**Comment by kristerkari** [comment]
> what about wrapping the `refetch()` call in a [throttle](https://lodash.com/docs/4.17.11#throttle) then?

That's what I'm already doing.

Let me explain a bit better what I want to do:

Currently the ajax calls in my app are defined to have a 30 seconds timeout duration. I would like for consistency to use the same 30 seconds timeout for the calls that `react-native-app-auth` does. That way I can specify the throttle duration to be the same value as the timeout, so that I can be sure that the previous refresh call is done before accepting a new one.

I know that I can use a boolean flag in Redux to block the calls while a refresh is in progress and un-block it when the refresh is done our times out, but that means that the refresh call to the backend is using the default timeout (which is 60 seconds, I guess?) instead of something that I have defined.

**Comment by kadikraman** [comment]
Oh, I see. I think on Android, the timeout is [15 seconds](https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/library/java/net/openid/appauth/connectivity/DefaultConnectionBuilder.java) and on iOS it's [60 seconds](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1414063-timeoutinterval) - so you'd like to be able to set them both to 30 seconds. Did I get it right this time? 😅

**Comment by kristerkari** [comment]
> I think on Android, the timeout is [15 seconds](https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/library/java/net/openid/appauth/connectivity/DefaultConnectionBuilder.java) and on iOS it's [60 seconds](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1414063-timeoutinterval) - so you'd like to be able to set them both to 30 seconds. Did I get it right this time?

Yes, exactly that! :)

**Comment by ayush-shta** [comment]
Any progress on this issue? I need to set a custom timeout for network request using this package. 

Currently, I'm seeing 60 seconds timeout for iOS which is too long for our use-case.

**Comment by hapablap21** [comment]
I'm encountering a need for this too.  We have a lot of users in areas with bad cell reception, and I need to be able to extend the timeout in certain cases.  It would also be nice if the exception generated from a timeout was something more specific than "token_refresh_failed".

**Comment by MFrat** [comment]
I think the only way to do this right now is to request token manually. As as here:

> skipCodeExchange - (boolean) (default: false) just return the authorization response, instead of automatically exchanging the authorization code. This is useful if this exchange needs to be done manually (not client-side).
