### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tienw** [FormidableLabs/react-native-app-auth#24]
After I run it after installation. I got the following error

> Task :app:compileDebugJavaWithJavac
C:\Kaizen.App\android\app\src\main\java\com\kaizenapp\MainApplication.java:6: error: package com.reactlibrary does not exist
import com.reactlibrary.RNAppAuthPackage;
                       ^
C:\Kaizen.App\android\app\src\main\java\com\kaizenapp\MainApplication.java:30: error: cannot find symbol
            new RNAppAuthPackage(),
                ^
  symbol: class RNAppAuthPackage

I also upgrade the build tool and gradle version but still not working. any suggestion?

**Comment by kadikraman** [comment]
Hi @tienw - looks like a configurations problem. Did you run `react-native link`? Make sure that the linking command worked and you have [these values set](https://github.com/FormidableLabs/react-native-app-auth#android).

If that wasn't the issue, make sure the [example project](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example) works for you and compare it to yours.

**Comment by tienw** [comment]
Yeah, I did run the linking command and also make sure all the files are fine.

I will try to run the example project to see what are the difference. tks
