### ISSUE TITLE
FitBit redirect_uri is always wrong

### ISSUE THREAD

**Issue by shyamkris** [FormidableLabs/react-native-app-auth#244]
## Issue

I've given a callBack url in FitBit as "abc://def" . What should I be configuring in the example project provided. I use the example provided under "Latest" folder.  Currently it says the following.
redirectUrl: 'com.whatever.url.you.configured.in.uber.oauth://redirect', //note: path is required
does it mean 'com.abc://def//redirect'. Please let me know what is to be done there.

## Environment

- **Your Identity Provider**: `Fitbit`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi, I'm not sure I understand your question.
You configure whatever redirect url you set up on fitbit.

E.g. in my example app that I used to test fitbit, I used `com.my.test.fitbit.app://oauthredirect`

<img width="531" alt="screenshot 2019-02-18 at 16 14 57" src="https://user-images.githubusercontent.com/6534400/52963683-5d9b1180-3398-11e9-81fd-809946384c00.png">

**Comment by shyamkris** [comment]
Thank you for the response. Did you had to change the appAuthRedirectScheme present in the build.gradle file? 
I'm trying to just change the configuration to suit fitbit oauth2, in the project named "Latest" under their git repo. Kindly help.

**Comment by kadikraman** [comment]
Yes, use the _same_ value in `appAuthRedirectScheme`

**Comment by shyamkris** [comment]
Thank you @kadikraman . That helped.
What i was setting as callbackurl in fitbit page was like "<somestring>://<somestring>.
But after your reply i understood that it had to be "<appid>://<somestring>
The same <appid> is also configured now for the appAuthRedirectScheme. Thanks again.

**Comment by kadikraman** [comment]
Great, I'm glad it's sorted 🙌
