### ISSUE TITLE
iOS build failed: RNAppAuth authorizeWithConfiguration:redirectUrl:clientId:clientSecret:scopes:additionalParameters:resolve:reject

### ISSUE THREAD

**Issue by risingworld777** [FormidableLabs/react-native-app-auth#252]
## Build failed with following error

```
[RNAppAuth authorizeWithConfiguration:redirectUrl:clientId:clientSecret:scopes:additionalParameters:resolve:reject:] in libRNAppAuth.a(RNAppAuth.o)
ld: symbol(s) not found for architecture x86_64
```

## Environment
- **React Native version**: 0.57.2
- **Library version**: 4.0.0
- **Xcode version**: 10.1
- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Have you added the AppAuth dependency in your Podfile?

**Comment by risingworld777** [comment]
Yes I did

`pod 'AppAuth', '>= 0.94'`

**Comment by kadikraman** [comment]
Do you still get this error when running [the Latest example](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example/Latest)?
```sh
git clone git@github.com:FormidableLabs/react-native-app-auth.git
cd react-native-app-auth/Example/Latest
yarn
react-native run-ios
```

**Comment by risingworld777** [comment]
I tried sample project and it's working.
But it gives me above error when integrate lib in my project.
I updated RN version to 0.57.2 like sample project.

**Comment by risingworld777** [comment]
Any update on this?

**Comment by kadikraman** [comment]
Hi @risingworld777 - if the example project works for you, then it must be a configuration issue in your project. You could try to compare the XCode configuration of the example project and yours. All I can suggest it to google the error.

If you can find a way to create a minimal example project that I could run on my machine, I could try to debug it. Until then though, since I can't reproduce the error, there's not a lot I can do.

**Comment by risingworld777** [comment]
@kadikraman I solved the problem.
I had to add `libAppAuth.a` in the third step of iOS manual installation.
