### ISSUE TITLE
Question on Coinbase Meta parameter send_limit_amount

### ISSUE THREAD

**Issue by oaramirez89** [FormidableLabs/react-native-app-auth#254]
## Documentation Feedback

I am using this library successfully to authenticate with Coinbase to get account data and to create addresses. When I add the scope to send coins Coinbase requires an additional parameter: meta[send_limit_amount]. According to their documentation the parameter should be appended to the authorizationEndpoint. I have tried this as well as adding it as an additional parameter but to no avail.

[Coinbase Documentation](https://developers.coinbase.com/docs/wallet/coinbase-connect/permissions)

Any guidance on this matter would be greatly appreciated. I could not find any examples in your documentation that dealt with a parameter similar to 'meta[send_limit_amount]'. Searching the web yielded nothing useful.

Adding it to the additional parameters yields an exception in the app as shown in my first attachment. 
```
const config = {
  clientId: '<my client id>',
  clientSecret: '<my client secret>,
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.coinbase.com/oauth/authorize',
    tokenEndpoint: 'https://www.coinbase.com/oauth/token',
    revocationEndpoint: 'https://www.coinbase.com/oauth/revoke',
  },
  redirectUrl: 'uri://com.chaching.wallet',
  scopes: ['wallet:accounts:read', 'wallet:addresses:create', 'wallet:transactions:send'],
  additionalParameters: { account: 'all', meta: { send_limit_amount: 1, send_limit_currency: 'USD', send_limit_period: 'day' } },
}
```

![screen shot 2019-02-21 at 7 32 28 am](https://user-images.githubusercontent.com/16826443/53169326-ebe6e180-35aa-11e9-99ef-cf6c4d52c709.png)

Appending the parameters to the end of the authorizationEndpoint, and removing it from the additional parameters yields a Coinbase error as shown in my second attachment (only including.

```
const config = {
  clientId: '<my client id>',
  clientSecret: '<my client secret>',
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.coinbase.com/oauth/authorize?meta[send_limit_amount]=50&meta[send_limit_currency]=USD&meta[send_limit_period]=day',
    tokenEndpoint: 'https://www.coinbase.com/oauth/token',
    revocationEndpoint: 'https://www.coinbase.com/oauth/revoke',
  },
  redirectUrl: 'uri://com.chaching.wallet',
  scopes: ['wallet:accounts:read', 'wallet:addresses:create', 'wallet:transactions:send'],
  additionalParameters: { account: 'all' },
}
```

![screen shot 2019-02-21 at 7 37 25 am](https://user-images.githubusercontent.com/16826443/53169540-90692380-35ab-11e9-8d7a-7186908aa6ac.png)

**Comment by kadikraman** [comment]
Hi @oaramirez89 - additional parameters get added to the auth request as key value pairs. Due to never having seen this use case before, we currently only support string values. So to make this work, you'll have to stringify your meta object.

Try

```js
additionalParameters: {
  account: 'all',
  meta: JSON.stringify({
    send_limit_amount: 1,
    send_limit_currency: 'USD',
    send_limit_period: 'day'
  })
}
```

**Comment by oaramirez89** [comment]
Thank you for your prompt answer @kadikraman. Your suggestion did not work but it got me thinking out of the box. Posting what worked for me here in case other people encounter this issue.

```javascript
additionalParameters: {
    account: 'all',  
    'meta[send_limit_amount]': '1',  
    'meta[send_limit_currency]': 'USD',  
    'meta[send_limit_period]': 'day',  
  }
```

**Comment by kadikraman** [comment]
Good to know, thanks @oaramirez89 !

We've actually got a folder for config examples for various IDPs [here in the repo](https://github.com/FormidableLabs/react-native-app-auth/tree/master/docs/config-examples). There's often some gotchas like this. I would _love_ to have a Coinbase example if you have a couple of minutes to put one together 😍
