### ISSUE TITLE
authorizationEndpoint and tokenEndpoint cannot be applinks. 

### ISSUE THREAD

**Issue by aungmoehein** [FormidableLabs/react-native-app-auth#258]
## The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported. was thrown while invoking authorize on target RNAppAuth with params(

---

## config

- **clientId**: `11111`
- **redirectUrl**: `com.myapp.io`
- **serviceConfiguration**: {
      **authorizationEndpoint**: `applinks://oauth2/authorize` ,
      **tokenEndpoint**: `applinks://oauth2/token` 
}
- **scopes**: `['email', 'profile']`

**Comment by kadikraman** [comment]
The purpose if this library is to enable login via oauth on the web. App links are definitely not in the scope - the IDP needs to be web hosted.
