### ISSUE TITLE
Keycloak (and Auth0) Null Pointer crash

### ISSUE THREAD

**Issue by tucamsam** [FormidableLabs/react-native-app-auth#260]
## Issue

When using the default JHipster Keycloak docker image, and using the example keycloak configuration for the Example/Latest react-native app, the app crashes on a NullPointerException.
When I tracked down the line that was causing problems, I ended up on TokenResponseFactory:createScopeArray on the `if(!scope.isEmpty())` line. In running the debugger, I found that scope was coming in as null on the authResponse argument to the TokenResponseFactory:tokenResponseToMap method. In my curiosity, I saw that my scope (as well as what appeared to be a fully authenticated response from the server) were on the response argument to that same method.

Getting to the part of my issue that's more of a question: is there any issue with simply sourcing the scope from the response rather than the authResponse? When I made that change locally, the app no longer crashes (though, interestingly, it trimmed 'email' from my scopes).

I haven't yet been able to go through the code to see exactly what the full flow is and why we might be using one argument over another - would I be able to get some guidance?

---

## Environment

- KeyCloak and Auth0
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi @tucamsam - this looks like the same issue as solved earlier today in https://github.com/FormidableLabs/react-native-app-auth/pull/259
I've released a patch with the fix - could you try installing [v4.1.1](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.1.1)?

**Comment by tucamsam** [comment]
Seems to have fixed it - thanks.
