### ISSUE TITLE
AppAuth.h file not found

### ISSUE THREAD

**Issue by erichulser** [FormidableLabs/react-native-app-auth#268]
## Issue

The AppAuth.h file not found error occurs specifically when running the Carthage setup (works fine with Pods)
---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

## Proposed Fix

For me, when this build error occurs it is not in my project but the RNAppAuth project.  I can fix this by going and adding `$(SRCROOT)/../../../ios/Carthage/Build/iOS/AppAuth.framework` as a recursive header search path to the project.

If you modify the line found here: https://github.com/FormidableLabs/react-native-app-auth/blob/master/ios/RNAppAuth.xcodeproj/project.pbxproj#L211 to include this, then it works for me (albeit with a bug in the AppAuth-iOS, but that is a separate issue)
```
HEADER_SEARCH_PATHS = (
					"$(inherited)",
					/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
					"$(SRCROOT)/../../../React/**",
					"$(SRCROOT)/../../react-native/React/**",
					"$(SRCROOT)/../../../ios/Pods/AppAuth/**",
					"$(SRCROOT)/../../../ios/Pods/Headers/**",
					"$(SRCROOT)/../../../ios/Carthage/Build/iOS/AppAuth.framework/**"
				);
```

**Comment by uncledent** [comment]
Thank you for the workaround, waiting for fix

**Comment by uncledent** [comment]
For the info, this bug is not reproducible on 4.0.0, even though it has not that line mentioned above

**Comment by moddatherrashed** [comment]
hey there, i am struggling with this issue ! @erichulser did you solve it ?

**Comment by powersjcb** [comment]
I'm able to reproduce this bug on `4.4.0`.

**Comment by tangnv** [comment]
Hi @powersjcb, what did you miss? I'm getting this problem too

**Comment by robwalkerco** [comment]
We are doing a clean-up of old issues, and as this issue was opened multiple versions ago, it's likely it's already resolved.
However, if the original problem **is** still an issue, then please feel free to re-open it, or open a new issue with replication details etc.
