### ISSUE TITLE
sha265 Typo

### ISSUE THREAD

**Issue by erichulser** [FormidableLabs/react-native-app-auth#269]
## Issue

`sha265` in the RNAppAuth.m module should be `sha256`

```
+ (nullable NSString *)codeChallengeS256ForVerifier:(NSString *)codeVerifier {
  if (!codeVerifier) {
    return nil;
  }
  // generates the code_challenge per spec https://tools.ietf.org/html/rfc7636#section-4.2
  // code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))
  // NB. the ASCII conversion on the code_verifier entropy was done at time of generation.
    NSData *sha265Verifier = [OIDTokenUtilities sha265:codeVerifier];
  return [OIDTokenUtilities encodeBase64urlNoPadding:sha265Verifier];
}
```

**Comment by kadikraman** [comment]
Hi @erichulser - this was a [naming change](https://github.com/openid/AppAuth-iOS/commit/87b0823ced25ecfbed07a36adddd508281bfe546) that AppAuth-iOS introduced in `AppAuth-iOS/1.0.0.beta1`. As this would be a breaking change for us, I don't want to add it until they've released a non-beta version.

Until, please use `AppAuth-iOS v0.95.0` and not the v1 beta.

**Comment by erichulser** [comment]
I see, thank you for the feedback @kadikraman.  Originally I was using master vs the beta line and it still was happening.  I will give it a try with that specific version.  Thanks!

**Comment by erichulser** [comment]
Unfortunately looks like rolling back to `"0.95.0"` doesn't build right with XCode 10.1, I am getting `Task failed with exit code 65:`

If I use `"master"` it builds, however still has the typo bug.

**Comment by kadikraman** [comment]
Hmm, that's unfortunate. You could use [patch-package](https://github.com/ds300/patch-package) to fix that particular rename in this library. It's pretty simple - essentially adding a postinstall that gets run immediately after `npm install` that edits the "broken" library. You can remove it once we can merge and publish in the rename.

**Comment by stefanvesca** [comment]
Hi @kadikraman  - I ran into the same problem with `react-native-app-auth` 4.4.0 and AppAuth-iOS 1.3.0. Are you planning to fix this in v5?

I can't use AppAuth-iOS < 1.0 because I need iOS 13 support.

**Comment by stefanvesca** [comment]
@kadikraman I can submit a PR maybe?

**Comment by kadikraman** [comment]
Hi @stefanvesca - yes this fix is already in the latest release candidate `react-native-app-auth@5.0.0-rc4` and will be included in `v5`.
