### ISSUE TITLE
iOS Redirect without AccessToken

### ISSUE THREAD

**Issue by FrK492** [FormidableLabs/react-native-app-auth#276]
## Issue

Hello,

I am trying to authenticate with Azure AD Application. On Android, Azure AD v1 and v2 works perfect but on iOS when I enter my credentials to WebView its redirecting me to my app as I expected but I can not receive any accessToken.

Here is my authorization config object:

```
{
    serviceConfiguration: {
        authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      },
      clientId: 'my-client-id',
      redirectUrl: 'com.'custom-scheme'://redirect',
      scopes: [
        'openid',
        'profile',
        'offline_access',
        'files.read'
      ]
 };
```
---

## Environment

- **Your Identity Provider**: Azure AD
- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi - what iOS version are you running? For iOS 10 and older you have to also [register the url scheme](https://github.com/FormidableLabs/react-native-app-auth#register-redirect-url-scheme).

Alternatively, (and this may be a long shot) - on the [Azure docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code), they recommend using `urn:ietf:wg:oauth:2.0:oob` as the redirect uri for mobile - perhaps you could try that?

**Comment by FrK492** [comment]
I was testing it with iOS 12.1.

I tried to change the redirect uri depending on Platform and fixed the issue.

I am using urn:ietf:wg:oauth:2.0:oob form iOS and custom scheme for android.

Its working like this.

Thank you for help.
