### ISSUE TITLE
Add support for React-Native for Windows UWP

### ISSUE THREAD

**Issue by hmheng** [FormidableLabs/react-native-app-auth#280]
https://github.com/Microsoft/react-native-windows

**Comment by kadikraman** [comment]
We have no plans to add this at the moment, but we're always happy to consider community contributions.

**Comment by hmheng** [comment]
May I know how can I help to add a Windows support into the package?

**Comment by kadikraman** [comment]
Ideally, produce some sort of MVP to use as a starting point. No need for feature pairity with iOS and Android, just be able to authenticate using [IS4](https://github.com/FormidableLabs/react-native-app-auth/blob/master/docs/config-examples/identity-server-4.md)'s discovery endpoint.

For iOS and Anroid are bridging native auth libraries that handle authentication from the native side. I don't know if there is something equivalent available for react native windows or it would have to be implemented form scratch.
