### ISSUE TITLE
x-access-token in additionalParameters

### ISSUE THREAD

**Issue by MQuach17** [FormidableLabs/react-native-app-auth#282]
## Issue

I'm trying to send an x-access-token in the additionalParameters object like so 
```
additionalParameters:{
   'x-access-token' : '{token}'
}
```

However, it sends the key (x-access-token) as a string. Removing the quotes results in a javascript error, Unexpected token.

Is there a way around this or am I not using it right?

---

## Environment

- **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
I don't quite understand the issue. Are you expecting `x-access-token` to be a header?
Additional parameters simply get added as url parameters in the auth/token request. E.g

**Comment by MQuach17** [comment]
Yes I want to pass x-access-token as a header, it should not be in the url paramerters

**Comment by kadikraman** [comment]
Ah, I see! For Android, we have a [`customHeaders`](https://github.com/FormidableLabs/react-native-app-auth#config) parameter that you can use to add custom headers to your token and auth requests. This has not yet been implemented on iOS.

**Comment by MQuach17** [comment]
thanks for the info!
