### ISSUE TITLE
Authorization with dynamic clientId

### ISSUE THREAD

**Issue by bumpah** [FormidableLabs/react-native-app-auth#288]
## Issue

We are using dynamic clientId's on our Gluu-server but have been unable to get it work under `react-native-app-auth`. This works well though on [AppAuth-Android](https://github.com/openid/AppAuth-Android) -native package itself, since you can enter empty string as clientId and it acquires dynamic clientId on it's own.

Is this currently feature not supported by `react-native-app-auth` -package or am i missing something?

---

## Environment

- **Your Identity Provider**: `Gluu`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi @bumpah - I've never come across this requirement before. What happens when you pass in an empty string?

**Comment by bumpah** [comment]
When giving an empty string as an clientId, we get a missing parameter/malformed request, error-response back from our server. 

![Simulator Screen Shot - iPhone X - 2019-04-15 at 17 04 34](https://user-images.githubusercontent.com/17970806/56116597-33815c80-5fa1-11e9-9d97-4f73394f55a3.png)

Otherwise config is exactly the same that we used for testing this on `AppAuth-Android` package, and everything where working as expected.

**Comment by kadikraman** [comment]
I'm not completely sure why it's not working. The easiest way to debug this would be to run your app through Android Studio in debug mode, put a breakpoint to where the authorize call is made in the native code, and step through it. From what I can see, we don't have any checks for `clientId` and it should just be passed through to the request.

**Comment by Jay-A-McBee** [comment]
:wave: hey @bumpah - closing this out due to lack of response - please open a new issue if this is still a problem.
