### ISSUE TITLE
Revocation requires a basic auth header in identity server 4

### ISSUE THREAD

**Issue by iamkoch** [FormidableLabs/react-native-app-auth#291]
## Issue

Revocation in identity server 4 requires a basic auth header, which this library seems to omit.

An example request taken from http://docs.identityserver.io/en/latest/endpoints/revocation.html is 

```
POST /connect/revocation HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token
```

The library would optionally be configured to pass the client id (and optional secret) into the basic auth header.

---

## Environment

- Identity Server 4
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
You're correct. An Authorization header should be added for [non-public clients](https://tools.ietf.org/html/rfc6749#section-2.3).

**Comment by iamkoch** [comment]
The request looks like https://tools.ietf.org/html/rfc7009#page-5. This works for public clients as well where secret can be left blank in the Authorization header. I have tested this against identity server 4 for a public PKCE-enabled client with no secret.
