### ISSUE TITLE
refresh token is always null

### ISSUE THREAD

**Issue by McDoyen** [FormidableLabs/react-native-app-auth#293]
## refresh token is always null

const authState = await authorize(config);
authState.refreshToken is always null.

---

## Environment

- **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by whittlem** [comment]
I'm having the same issue.

**Comment by kadikraman** [comment]
@McDoyen you haven't specified your IDP. I can guarantee it is not "always null" for IdentityServer, Okta or Azure. In most cases, you'll need to add the `offline_access` scope in order for your IDP to return the refresh token.
