### ISSUE TITLE
Error: Non-200 HTTP response (404) fetching discovery document

### ISSUE THREAD

**Issue by whittlem** [FormidableLabs/react-native-app-auth#294]
## Issue

I am trying to connect to the Coinbase API using OAuth.

My code looks like this:

    import { authorize } from 'react-native-app-auth';

    componentDidMount() {
        authorize(config)
            .then(response => {
                console.log(response);
            })
            .catch(error => {
                console.log(error);
            });
    }

And I am getting this...

Error: Non-200 HTTP response (404) fetching discovery document 'https://www.coinbase.com/oauth/authorize/.well-known/openid-configuration'.
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:72

I think the Coinbase API should be using a standard setup for OAuth so not sure why ".well-known/openid-configuration" is missing unless there is something I need to do from my side?

My config looks like this:

const config = {
  issuer: 'https://www.coinbase.com/oauth/authorize',
  clientId: '<removed>',
  redirectUrl: 'urn:ietf:wg:oauth:2.0:oob',
  scopes: ['wallet:accounts:read'],
};

Apparently the redirectUrl will be 'urn:ietf:wg:oauth:2.0:oob' for mobile.

I see in your docs that there is an option for "serviceConfiguration". Should I be using that instead and if so what should the config look like?

I see in the Latest example on your repo you have this commented out...

  // serviceConfiguration: {
  //   authorizationEndpoint: 'https://demo.identityserver.io/connect/authorize',
  //   tokenEndpoint: 'https://demo.identityserver.io/connect/token',
  //   revocationEndpoint: 'https://demo.identityserver.io/connect/revoke'
  // }

Should my setup look more like this? This is my first time trying out OAuth so still trying to figure out how it will all work in practice in a React Native mobile application.

---

## Environment

- **Your Identity Provider**: Coinbase
https://developers.coinbase.com/docs/wallet/coinbase-connect/reference

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by whittlem** [comment]
So I tried this...

const config = {
  issuer: 'https://www.coinbase.com/oauth/authorize',
  clientId: '<removed>',
  redirectUrl: 'urn:ietf:wg:oauth:2.0:oob',
  scopes: ['wallet:accounts:read'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.coinbase.com/oauth/authorize',
    tokenEndpoint: 'https://api.coinbase.com/oauth/token',
    revocationEndpoint: 'https://api.coinbase.com/oauth/revoke'
  }
};

Which resulted in this:

Exception '<AppDelegate: 0x60000072ae80> does not conform to RNAppAuthAuthorizationFlowManager' was thrown while invoking authorize on target RNAppAuth with params (
    "https://www.coinbase.com/oauth/authorize",
    "urn:ietf:wg:oauth:2.0:oob",
    <removed>,
    "<null>",
        (
        "wallet:accounts:read"
    ),
    "<null>",
        {
        authorizationEndpoint = "https://www.coinbase.com/oauth/authorize";
        revocationEndpoint = "https://api.coinbase.com/oauth/revoke";
        tokenEndpoint = "https://api.coinbase.com/oauth/token";
    },
    1,
    1,
    158,
    159
)
callstack: (
	0   CoreFoundation                      0x00000001069466fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001050b9ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106946555 +[NSException raise:format:] + 197
	3   CoinbaseAnalysis                    0x0000000102feeaa7 -[RNAppAuth authorizeWithConfiguration:redirectUrl:clientId:clientSecret:scopes:useNonce:usePKCE:additionalParameters:resolve:reject:] + 1559
	4   CoinbaseAnalysis                    0x0000000102fed00a -[RNAppAuth issuer:redirectUrl:clientId:clientSecret:scopes:additionalParameters:serviceConfiguration:useNonce:usePKCE:resolve:reject:] + 554
	5   CoreFoundation                      0x000000010694d4cc __invoking___ + 140
	6   CoreFoundation                      0x000000010694aa45 -[NSInvocation invoke] + 325
	7   CoreFoundation                      0x000000010694ae96 -[NSInvocation invokeWithTarget:] + 54
	8   CoinbaseAnalysis                    0x0000000102d828ca -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
	9   CoinbaseAnalysis                    0x0000000102e35016 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
	10  CoinbaseAnalysis                    0x0000000102e34b23 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
	11  CoinbaseAnalysis                    0x0000000102e34a99 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	12  libdispatch.dylib                   0x000000010981dccf _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010981ed02 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010982aa50 _dispatch_main_queue_callback_4CF + 1276
	15  CoreFoundation                      0x00000001068ad8a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00000001068a7f56 __CFRunLoopRun + 2310
	17  CoreFoundation                      0x00000001068a7302 CFRunLoopRunSpecific + 626
	18  GraphicsServices                    0x0000000109e4e2fe GSEventRunModal + 65
	19  UIKitCore                           0x000000011492bba2 UIApplicationMain + 140
	20  CoinbaseAnalysis                    0x0000000102b48010 main + 112
	21  libdyld.dylib                       0x000000010988c541 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by whittlem** [comment]
I got it working... I was missing this in AppDelegate.h:

#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : UIResponder <UIApplicationDelegate, RNAppAuthAuthorizationFlowManager>

@property (nonatomic, strong) UIWindow *window;
@property (nonatomic, weak) id <RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end

**Comment by bhaskardabhi-oviyum** [comment]
I am still getting the issue. I have defined `serviceConfiguration` but seems like it's not working

```
import AppAuth from 'react-native-app-auth';

auth = new AppAuth({
    issuer: 'https://www.strava.com/oauth/mobile/authorize',
    clientId: '{clientId}',
    clientSecret: '{clientSecret}',
    redirectUrl: 'com.myapp:/callback',
    serviceConfiguration: {
      authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
      tokenEndpoint: 'https://www.strava.com/oauth/token',
      revocationEndpoint: 'https://www.strava.com/oauth/deauthorize'
    },
    additionalParameters: {
      response_type: 'code'
    }
  });

const authState = await auth.authorize(scopes);
```
I don't know what I am doing wrong. Following is my `AppDelegate.h`

```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

@protocol OIDAuthorizationFlowSession;

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
@property(nonatomic, strong, nullable) id<OIDAuthorizationFlowSession> currentAuthorizationFlow;
@property (nonatomic, strong) UIWindow *window;
@end

```
My dependencies are as follow:

```
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-app-auth": "^1.0.1",

```

Looks like it's not even picking up `serviceConfiguration`
