### ISSUE TITLE
After authorization has complete it doesn't return back to React Native app

### ISSUE THREAD

**Issue by whittlem** [FormidableLabs/react-native-app-auth#295]
## Issue

I've got OAuth working to the Coinbase API. When I initiate authorize I get redirected to Coinabase to log in which works fine. Once I click Authorize I get redirected to a bank screen with the only option to cancel and return back to the app. 

I've read in Coinbase and other docs the redirect URI should be urn:ietf:wg:oauth:2.0:oob to allow a mobile app to catch the redirect. I've got this set in the Coinbase application settings and also in the config that is sent with "authorize" but I can't seem to return back to the app. Is there something I need to set in Xcode to make this work? 

---

## Environment

- **Your Identity Provider**: Coinbase
- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by whittlem** [comment]
I solved this here..
https://stackoverflow.com/questions/55749091/handling-coinbase-api-react-native-redirect-with-oauth-authorization-using-react/55765803#55765803

**Comment by spsaucier** [comment]
This may also have to do with an incorrect or inconsistent callback URI configuration.
