### ISSUE TITLE
Allow SSL pinning

### ISSUE THREAD

**Issue by sattaman** [FormidableLabs/react-native-app-auth#298]
I've been looking into adding SSL pinning for our app. I've found that I should be able to pin fetch requests fairly easily using https://github.com/localz/react-native-pinch . 

To lock down the auth would you consider adding a similar config to app auth?

**Comment by sattaman** [comment]
This functionality exists in the app-auth ios library https://github.com/openid/AppAuth-iOS/issues/324 , and looks like it should be easy to lock down all requests in Android.

**Comment by Jay-A-McBee** [comment]
Hmm... this enhancement request hasn't gotten a response or bumps from other commenters. It would add another argument to our function signatures that would probably see very limited use. Closing this out for now.
