### ISSUE TITLE
No webview?

### ISSUE THREAD

**Issue by mahyali** [FormidableLabs/react-native-app-auth#299]
In openid-client (a node.js only package) it allows sending the username and password directly. Is there anyway the 'config' object can be extended to have username and password optional fields? So instead of opening a webview I could use my own 'login' screen.

**Comment by kadikraman** [comment]
I'm sure there's a case to be made for this feature, but in my opinion, this would deviate a bit too far from what this library is intended for. The whole idea of OAuth is that the user can securely authenticate with via a third party and you (the application developer) will delegate anything auth related away from your app.
