### ISSUE TITLE
Is there a reason for the react-native@^0.50.3 dependancy?

### ISSUE THREAD

**Issue by edcs** [FormidableLabs/react-native-app-auth#300]
## Issue

This package has a dependency on `react-native@^0.50.3` which is pretty old now, I've been using it on `react-native@^0.57` and now `react-native@^0.59` without any issues. I'm getting the following error all the time:

```
react-native-app-auth@4.3.1" has incorrect peer dependency "react-native@^0.50.3".
```

Would changing the dependency to React Native to something like this be a good idea?

```
{
  "peerDependencies": {
    "react-native": ">=0.50.3"
  }
}
```

I'm happy to open a PR and do the work for this one.

---

## Environment

- **Your Identity Provider**: `AWS Cognito`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
There's no reason, other than that when this library was created, 50.3 was the latest RN version out, and we've not gotten around to updating it.

Your suggestion looks good to me, and if you make a PR for it, I'd be happy to merge it, thanks so much!

**Comment by edcs** [comment]
Cool thanks for letting me know - I've patched `package.json` in https://github.com/FormidableLabs/react-native-app-auth/pull/301 - glad to help as this is a super useful package 👍
