### ISSUE TITLE
Error: invalid_client: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

### ISSUE THREAD

**Issue by whittlem** [FormidableLabs/react-native-app-auth#303]
## Issue

It looks like authorize() may be working now but I'm getting the following message while authorizing:

    Error: invalid_client: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

I'm using the Xcode emulator for development. What client information would be passed if an emulator is used and is it possible to set the client information in the request?

---

## Environment

- **Your Identity Provider**: Coinbase
- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
As resolved in the other issue you raised, Coinbase requires a client secret to be passed in.

I added a [config example](https://github.com/FormidableLabs/react-native-app-auth/blob/master/docs/config-examples/coinbase.md) for Coinbase for future reference.
