### ISSUE TITLE
Problem with redirect url.

### ISSUE THREAD

**Issue by spipatpunlop** [FormidableLabs/react-native-app-auth#304]
## Issue

I can login successfully but I don't know what should my return url would be.
After I sign in I got this message from the server

> There is an error determining which application you are signing into. Return to your application and try again.

I set:
```
manifestPlaceholders = [
            appAuthRedirectScheme: 'com.trylogin:/callback'
]
```

From terminal:
```
BUILD SUCCESSFUL in 7s
43 actionable tasks: 4 executed, 39 up-to-date
info Running C:\Users\<User_name>\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
info Starting the app on emulator-5554 (C:\Users\<User_name>\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 shell am start -n com.trylogin/com.trylogin.MainActivity)...
Starting: Intent { cmp=com.trylogin/.MainActivity }
```

My config:
```
const config = {
  issuer: '<url_issuer>',
  clientId: '<client_id>',
  clientSecret: '<client_secret>',
  redirectUrl: 'com.trylogin:/callback', // is this redirectUrl correct?
  scopes: ['openid', 'member'],
};
```

I use `com.trylogin:/callback` as redirect url. Is that correct?
If not, what will the redirect url woudl be?

---

## Environment

- **Your Identity Provider**: `IdentityServer 3`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by sattaman** [comment]
Try updating the manifestPlaceholders to 
```
manifestPlaceholders = [
            appAuthRedirectScheme: 'com.trylogin'
]

**Comment by spipatpunlop** [comment]
It's redirect to my app after I logged in but then this error appeared.
![try_login_3](https://user-images.githubusercontent.com/45443468/57513206-ac799700-7348-11e9-9023-bd7aa1ed7c15.gif)
Error message:
```
Error not specified.
```

**Comment by spipatpunlop** [comment]
Here are my AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.trylogin">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by cavator** [comment]
@spipatpunlop man u solve this problem???

**Comment by spipatpunlop** [comment]
@cavator Nooooo! I hold the project for now.

**Comment by icaru88** [comment]
@cavator @spipatpunlop any insights to resolve this issue?

it's causing prob on API 30, but no prob with 28, 29.

refer here
https://github.com/FormidableLabs/react-native-app-auth/issues/561

**Comment by icaru88** [comment]
Hi all, just an quick update, after I change my android project targetSDKVersion to 29 as per official RN documentation. I am able to run my app and login in emulator running API 30/ android 11 version.

**Comment by ganeshpatil3** [comment]
Hi All, 
      I am using the updated version 6.2.0, on targetSDKVersion to 29, it is working fine. But after changing the targetSDKVersion to 30 it is not working. When calling authorize function, it raises an exception which returns an error: Error not specified.
 Now google said to update the application we must have targetSDKVersion to 30.
 Is anyone find the solution?
