### ISSUE TITLE
library not found for -lMSGraphSDK

### ISSUE THREAD

**Issue by vymallesh** [FormidableLabs/react-native-app-auth#307]
Hey,

I was facing an issue with Microsoft Outlook login SDK integration.I was using Cocoapods to install the libraries.I am getting below error,

ld: library not found for -lMSGraphSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

FYI : Podfile is   : pod 'MSGraphSDK'
 pod 'MSGraphSDK-NXOAuth2Adapter'  and XCode version is 10.2.1

Any help would be appreciated !!
Thanks.

**Comment by kadikraman** [comment]
Hi - I don't think MSGraphSDK is a dependency of ours - I'd try running `pod update && pod install` again.
