### ISSUE TITLE
Add in prefetching of the config along with warming the chrome custom tab

### ISSUE THREAD

**Issue by michaelrhughes** [FormidableLabs/react-native-app-auth#308]
Prefetching the config, warming the chrome custom tab, and prefetching the page in chrome adds a pretty significant improvement on first launch of the sign in page.

This feature should be good to go, just needs some love and attention https://github.com/FormidableLabs/react-native-app-auth/pull/289 😃

**Comment by kadikraman** [comment]
Published in [v4.4.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.4.0) - thanks for the reminder. I have far too many GH notifications and missed the ones from you addressing the review comments 🤦‍♀️- thanks for your patience and persistence!
