### ISSUE TITLE
TypeError: Cannot read property 'authorize' of undefined in test environment

### ISSUE THREAD

**Issue by nilsbacke-ef** [FormidableLabs/react-native-app-auth#317]
## TypeError: Cannot read property 'authorize' of undefined in test environment

The authorize works perfectly when I run the app, however, when I attempt to run tests using jest, I always get this: TypeError: Cannot read property 'authorize' of undefined. I am not using expo. Is there any setup that doesn't get triggered when running jest tests as opposed to running the app with react-native run-ios? Thanks.

I have tried mocking the call as a whole using 
```
jest.mock('react-native', () => ({
        NativeModules: {
            RNAppAuth: {
                authorize: jest.fn()
            }
        },
        Platform: {
            OS: 'ios'
        }
    }))
```

as present in the example tests in this repo, but I get the same error.

**Comment by kadikraman** [comment]
If you're testing your project, you'll need to mock the import for this library, not `react-native`:

```js
const authorizeSpy = jest.fn();

jest.mock('react-native-app-auth', () => ({
  authorize: authorizeSpy
}));
```

**Comment by nilsbacke-ef** [comment]
It works! Thanks so much.

Note: It only works if you put the mock call in your setupTests.js file, it didn't work for me if I left the mock call in the current test I was running.
