### ISSUE TITLE
How do i pass username in url keyclock

### ISSUE THREAD

**Issue by krishan1kamal** [FormidableLabs/react-native-app-auth#320]
## Documentation Feedback
How to pass email taken from user pass to url as pridefine email keyclock

**Comment by kadikraman** [comment]
Add it to [additionalParameters](https://github.com/FormidableLabs/react-native-app-auth#config).
```js
{
  foo: "bar",
  baz: "taz"
}
```
will result in `<url>?foo=bar&baz=taz`
