### ISSUE TITLE
[Android] Request canceled on opening 3rd party app

### ISSUE THREAD

**Issue by johnyyhign** [FormidableLabs/react-native-app-auth#322]
## Issue

Hi guys. We're using identity server as a way to reach our auth provider. This provider uses authentication based on 3rd party app, so the flow is:
1. Tap login in our app
2. App auth browser opens up
3. Website starts the 3rd party app
4. Auth in 3rd party app, then it redirects to our app
5. Website collects the result
6. App auth browser is closed and result returned

That's the correct flow and works perfectly on iOS!
On Android tho, it's fine to point 4. But when come back to our app then the browser is already closed and app auth return `user canceled` result. There is no log about any success/fail in the backend, just started authentication. (based on android animations) it seems like the browser is being closed right in the moment when the 3rd party app is being opened.
So we're unable to use this on Android! I've tested this also with your example app (with our config to `authorize`) and also with native Android App-Auth example. Same result everywhere, browser just closes on openning 3rd party app from the app-auth browser.

Any ideas what can we do?

## Environment

* **Your Identity Provider**: `IdentityServer`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** NO

**Comment by Jay-A-McBee** [comment]
:wave: hey @johnyyhign - closing this out as it appears to be a third-party issue (AppAuth-Android) - https://github.com/openid/AppAuth-Android/issues/473
