### ISSUE TITLE
Android redirect url 

### ISSUE THREAD

**Issue by krishan1kamal** [FormidableLabs/react-native-app-auth#324]
## Issue

---

## Environment

* **Your Identity Provider**: `
![f14f2fe0-ff1a-4d6b-b810-ca27cb7924bb](https://user-images.githubusercontent.com/19946070/59677976-d72cfa00-91e8-11e9-98bf-04458066870a.jpg)
Azure`
* **Platform that you're experiencing the issue on**: `Android`(Ios is working fine)
* **Are you using Expo? No

**Comment by kadikraman** [comment]
Hello  👋 

Are you using `urn:ietf:wg:oauth:2.0:oob` as your redirect uri? Can you register a different scheme with your IDP as the error suggests?

**Comment by krishan1kamal** [comment]
On different scheme it's not redirecting back to app

**Comment by kadikraman** [comment]
Have you [registered the the url scheme](https://github.com/FormidableLabs/react-native-app-auth#register-redirect-url-scheme) for Android? E.g. if your redirect uri is `com.myapp/oauth`, the url scheme should be `com.myapp`.

**Comment by krishan1kamal** [comment]
Ios is working fine problem in android

**Comment by krishan1kamal** [comment]
msauth://com.heycaro.mobile/oauth  this as a url scheme

**Comment by krishan1kamal** [comment]
This is my androidManifest.xml file

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp" xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="true"
      android:theme="@style/AppTheme"
      >

>       ****<activity
>             android:name="net.openid.appauth.RedirectUriReceiverActivity"
>             tools:node="replace">
>         <intent-filter>
>             <action android:name="android.intent.action.VIEW"/>
>             <category android:name="android.intent.category.DEFAULT"/>
>             <category android:name="android.intent.category.BROWSABLE"/>
>             <data android:scheme="com.myapp.mobile"/>
>         </intent-filter>
>       </activity>****

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="stateVisible|adjustResize">        
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity  
          android:name=".SingleTopActivity"
          android:label="singleTop launchMode"
          android:launchMode="singleTop" 
      />
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
      <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
  </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

    </application>

</manifest>


This is my build.gradle file

apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.heycaro"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 5
        versionName "5.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

>      **manifestPlaceholders = [
>         appAuthRedirectScheme: 'com.heycaro.mobile'
>       ]**

    }
    configurations.all {
   resolutionStrategy.force 'com.android.support:support-v4:26.1.0' // old dependencies version;       
   }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
      }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release

        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-exit-app')
    compile project(':react-native-gesture-handler')
    compile project(':react-native-app-auth')
    compile project(':react-native-touch-id')
    implementation project(':react-native-touch-id')
    implementation project(':react-native-webview')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-fs')
    implementation project(':react-native-firebase')
    implementation project(':react-native-doc-viewer')
    implementation project(':react-native-device-info')
    compile project(':react-native-device-info')
    compile project(':react-native-firebase')
    compile project(':react-native-webview')
    compile project(':react-native-vector-icons')
    compile project(':react-native-splash-screen')
    compile project(':react-native-fs')
    compile project(':react-native-doc-viewer')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation "com.google.firebase:firebase-messaging:17.3.4"

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'

Please guide me where I made a mistake

**Comment by krishan1kamal** [comment]
Thanks @ubready it working
