### ISSUE TITLE
Android and iOS redirect from AAD

### ISSUE THREAD

**Issue by ubreddy** [FormidableLabs/react-native-app-auth#327]
## Issue

Microsoft AAD has published [platform registrations for applications](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-android).

The current Azure example config does not work anymore for Andorid. Even ios procedure is changed. 

When the instructions in the above links are followed AAD successfully logs in but the RNAppAuth library is getting stuck at authorize function.

Both for Andoroid and ios... 
---

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
It looks like that article is aimed at the users of the Microsoft Authentication Library.

The OAuth 2 stuff should work as before. You can create your Active Directory as described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app), but use something like `com.myapp/oauth` as the redirect uri.

The confusion with the redirect uri comes com the the [Azure docs](https://docs.microsoft.com/en-gb/azure/active-directory/develop/v1-protocols-oauth-code#request-an-authorization-code) actually recommending `'urn:ietf:wg:oauth:2.0:oob'` as the `redirectUrl` for v1. This however is not supported by [AppAuth Android](https://github.com/openid/AppAuth-Android) - the library that we are wrapping.

I will update the documentation to reflect this.

**Comment by ubreddy** [comment]
com.myapp/oauth is not a valid redirect uri format anymore in Azure AD.

**Comment by ubreddy** [comment]
Any observation on the above? The apps are still getting stuck!

**Comment by kadikraman** [comment]
We’d appreciate a PR - this is how open source works 🙌
