### ISSUE TITLE
Support customHeaders in iOS

### ISSUE THREAD

**Issue by kassemdarwish** [FormidableLabs/react-native-app-auth#333]
According to the documentation, the customHeaders config object is only supported for Android. I was wondering whether it's possible to support it in iOS or there is some technical reason which prevents that from happening.

The reason why we really need this is because we are adding multi-tenancy support to our custom IdentityServer4 implementation. To do so, we expect an Origin header on the server which is used to resolve the tenant. We have tested it on Android and it worked perfectly fine, but it failed on iOS (as expected).

**Comment by kassemdarwish** [comment]
Any updates on this?

**Comment by kadikraman** [comment]
Hi @kassemdarwish 👋  - that is because [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) does not support custom headers. I don't think they're opposed to adding that functionality, but it is not currently on their roadmap.

**Comment by jordoh** [comment]
Note that AppAuth-iOS does let you [specify the NSURLSession to use](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDURLSessionProvider.h), so you can do something like this prior to calling authorize:
```
NSURLSessionConfiguration* urlSessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
urlSessionConfiguration.HTTPAdditionalHeaders = @{ @"X-Some-Header" : @"some value" };
NSURLSession* session = [NSURLSession sessionWithConfiguration:urlSessionConfiguration];

[OIDURLSessionProvider setSession:session];
```

There are some headers that [shouldn't be set this way](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411532-httpadditionalheaders?language=objc) but it does provide the basic functionality.

**Comment by kadikraman** [comment]
Interesting - thanks for pointing that out @jordoh 
In this case, I'm open to PRs if anyone would like to have a go at implementing this.
