### ISSUE TITLE
Support for ASWebAuthenticationSession

### ISSUE THREAD

**Issue by davidbani** [FormidableLabs/react-native-app-auth#334]
Since [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) is deprecated. Any support for [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) in the future?

**Comment by sattaman** [comment]
This is already used by default by the latest AppAuth which support is already in master for

**Comment by davidbani** [comment]
@sattaman oh ok, no worries. Thanks for feedback.
