### ISSUE TITLE
Update to use AppAuth 1.0.0

### ISSUE THREAD

**Issue by sattaman** [FormidableLabs/react-native-app-auth#337]
It looks like AppAuth 1.0.0 came out of beta a couple of weeks ago
https://github.com/openid/AppAuth-iOS/releases

**Comment by idhindsight** [comment]
I too would like to see this happen. From what I can tell tracking the code progress there, that team has gotten logout to work. Simple token revocation, as we have in rn-app-auth is not true signout.

**Comment by kadikraman** [comment]
Thanks for the info! I'll get it updated.

**Comment by sattaman** [comment]
What's the plan regarding publishing this? Our CI here doesn't allow us to link directly to github so I can't use master.

**Comment by kadikraman** [comment]
@sattaman I've just published a release for `5.0.0-rc1` - you can install it with `yarn add react-native-app-auth@next` - please let me know if you find any issues!
