### ISSUE TITLE
Breaking changes from 4.0 to 4.1

### ISSUE THREAD

**Issue by Oyvindkg** [FormidableLabs/react-native-app-auth#340]
## Issue

`refresh()`'s typed signature is changed between 4.0 and 4.1 causing a breaking change.
Please try to keep breaking changes to major versions in the future if you're aiming for semantic versioning.

Please include or link to docs describing your versioning scheme. 

**4.1**
```ts
export function refresh(
  config: AuthConfiguration,
  refreshConfig: RefreshConfiguration
): Promise<RefreshResult>;
```

**4.0**
```ts
export function refresh(
  config: AuthConfiguration,
  refreshConfig: RefreshConfiguration
): Promise<AuthorizeResult>;
```

**Comment by kadikraman** [comment]
Hi @Oyvindkg - apologies, that was certainly not intentional. We do follow semver.

I've added a comment to the [release docs](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.1.0), thank you for pointing this out.

**Comment by Oyvindkg** [comment]
No problem. Thanks for the great library. Saves us a bunch of time
