### ISSUE TITLE
Callbacks do not work in iOS 10 and below following instructions in readme

### ISSUE THREAD

**Issue by sattaman** [FormidableLabs/react-native-app-auth#342]
## Issue

After testing I noticed the callbacks were not being handled correctly on ios10 and below, looking at the example project provided it looks like the instructions are incomplete. I've added the snippet in the linked PR and this seems to fix. 

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?**

**Comment by matt-way** [comment]
This undoes the information from: https://github.com/FormidableLabs/react-native-app-auth/issues/314

How do you combine the code in this PR with the react-native deep linking code requirements?

**Comment by sattaman** [comment]
I've got

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
options:(NSDictionary<NSString *, id> *)options {
  if ([self.authorizationFlowManagerDelegate
resumeExternalUserAgentFlowWithURL:url]) {
    return YES;
  }
  return [RCTLinkingManager application:app openURL:url options:options];
}

**Comment by matt-way** [comment]
Thank you.
