### ISSUE TITLE
Login screen opens in new browser after androidx migration

### ISSUE THREAD

**Issue by getavinashm** [FormidableLabs/react-native-app-auth#349]
## Issue

We recently had to migrate to androidx after some breaking changes. The app has been integrated with Hydra as login provider.
The web page for authentication was always opening within the app webview earlier. However after the migration, the login screen opens in a browser independent of the app. This is a concern and we want to avoid this behaviour. Has anyone else faced the same issue ? Any help is much appreciated !!
---

## Environment
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-app-auth": "^4.3.1",

* **Your Identity Provider**: Custom Hydra setup
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** : No

**Comment by kadikraman** [comment]
Hi @getavinashm - it looks like this is an issue with AppAuth-Android - https://github.com/openid/AppAuth-Android/issues/417

**Comment by sabariprasad** [comment]
any update on this ??

**Comment by pm0** [comment]
Also requesting an update on this - the AppAuth-Android dependency may need updating

**Comment by Jay-A-McBee** [comment]
Closing this out as it shouldn't be an issue anymore according to this [comment](https://github.com/openid/AppAuth-Android/issues/417#issuecomment-815988005). We bumped up to `0.8.1` with this [PR](https://github.com/FormidableLabs/react-native-app-auth/pull/630).
