### ISSUE TITLE
RNAppAuth.Authorize 

### ISSUE THREAD

**Issue by Dean-Mills** [FormidableLabs/react-native-app-auth#350]
## Issue

Hi, I'm having an issue just running the example project. Once I've run the app and pressed the authorize button (from the main page) I get the following error. 
"RNAppAuth.Authorize got 10 arguments, expected 13"
---

**Comment by kadikraman** [comment]
Hi @Dean-Mills 👋 - which example app are you running?

**Comment by Dean-Mills** [comment]
I'm so sorry I should have specified what I was doing since you guys provide multiple examples. I was attempting to run "Latest" and I get an identical error on both emulator and real device (android)

**Comment by kadikraman** [comment]
I'm actually thinking of getting rid of the `Latest` example, as it's hard to keep so many example apps in sync. The idea for the `Latest` example was that it builds with the version of the app installed from `master`, but that isn't always the latest published version. Please could you try the pods example for iOS, or the Android example for Android while I decide what to do.

**Comment by thisisbinod** [comment]
Please delete `Latest` . I wasted half a day trying to make it work without any success. The word "latest" tricked me to use it instead of the other Android example.

**Comment by kadikraman** [comment]
Sorry for the confusion. I've [removed](https://github.com/FormidableLabs/react-native-app-auth/pull/432) the additional examples and refreshed the remaining one.

**Comment by bittu1028** [comment]
@kadikraman  i am getting this same error message when i upgraded to 0.5.2 on my project how do i solve this ?

**Comment by hotaryuzaki** [comment]
i got error after update to 6.0.1 from 5.1.2
googe login error rnappauth.authorize got 13 arguments expected 14 #583

**Comment by hugo-chq** [comment]
@hotaryuzaki for me this happened when updating without installing pods again for iOS

**Comment by nguyen-tam** [comment]
I got this error when upgrade from 5.x to 6.x too
