### ISSUE TITLE
Google OAuth not working out the box as documented: client_secret is missing

### ISSUE THREAD

**Issue by johnpc** [FormidableLabs/react-native-app-auth#355]
## Issue

This code is from the [google oauth example](https://github.com/FormidableLabs/react-native-app-auth/blob/master/docs/config-examples/google.md).

```
const config = {
  issuer: 'https://accounts.google.com',
  clientId: 'GOOGLE_OAUTH_APP_GUID.apps.googleusercontent.com',
  redirectUrl: 'com.googleusercontent.apps.GOOGLE_OAUTH_APP_GUID:/oauth2redirect/google',
  scopes: ['openid', 'profile']
};

// Log in to get an authentication token
const authState = await authorize(config);
```

However, after signing in and being redirected to the app, I get an error: 

```client_secret is missing```

<img width="374" alt="Screen Shot 2019-07-13 at 11 05 34 AM" src="https://user-images.githubusercontent.com/4824042/61173203-2b17ce00-a55e-11e9-8ce2-3df0c4bd6848.png">

Adding `clientSecret` to the config fixes the problem on iOS. However, on android, adding `clientSecret` does not allow me to log in with google and instead loads this error page saying that `client_secret` is not allowed.

<img width="372" alt="Screen Shot 2019-07-13 at 11 07 00 AM" src="https://user-images.githubusercontent.com/4824042/61173220-6b774c00-a55e-11e9-817f-2cf546e67b34.png">

So it's a little bit of a catch-22. If I provide the clientSecret, I get an invalid request error from google and can't authenticate. If I don't provide it, I get "client_secret is missing" error after authenticating. It _should_ work on both platforms without the client_secret - that's what makes sense to me and that's what's documented.

---

## Environment

* **Your Identity Provider**: **Google**
* **Platform that you're experiencing the issue on**: iOS / Android / **both**
* **Are you using Expo?** No

**Comment by Luke-Rogerson** [comment]
I think you're facing the same issue as me. I guess Google probably requires the `client_secret` to be sent in the body of the token exchange request, but it's not being included.

**Comment by sajidit** [comment]
I was facing the same issue, It turned out the problem was because i configured OAuth client with other scoped, after creating OAuth client with Android it started to work https://developers.google.com/identity/sign-in/web/sign-in

This is my configuration 
export const googleConfig = {
  issuer: 'https://accounts.google.com',
  clientId: 'GOOGLE_OAUTH_APP_GUID.apps.googleusercontent.com',
  redirectUrl: 'com.googleusercontent.apps.GOOGLE_OAUTH_APP_GUID:/oauth2redirect',
  scopes: ['openid', 'profile']
};

manifestPlaceholders = [
     appAuthRedirectScheme: 'com.googleusercontent.apps.GOOGLE_OAUTH_APP_GUID'
]

**Comment by kadikraman** [comment]
Thank you @sajidit - you're correct!

When creating an OAuth application on the Google Developer console, be sure to choose a _mobile_ client (iOS or Android). Web clients will ask for a client secret, and you don't get PKCE support!

**Comment by imthath-m** [comment]
For anyone landing here via online searches, check your client type in the Google Console. You will not get this error, if the client type is iOS or Android.

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/46041492/216039018-ce141358-9a89-4d68-82c4-a75951b06b63.png">

**Comment by Markoslc** [comment]
Thank you so much, I've been looking for a solution for hours and finally found this. This is such a stupid solution. You would expect Google to support something basic like PKCE extension for OAuth that has been around for almost 10 years now
