### ISSUE TITLE
Failed to Login , Null is not an object( evaluating RNappAuth.Authorize)

### ISSUE THREAD

**Issue by timeinvestgroup** [FormidableLabs/react-native-app-auth#358]
## Issue

1) Downloaded both Latest and Android Example from the Formidable Git hub page
2) Creating a fresh App using React-native (both Cli and Expo)
3)Followed all instruction for Android Installation and Setup (few times)
4) Tried different phones and versions
5) Tried Linking and unlinking numerous times.
6) Finally got the App running but as soon as clicking on Authorize red button I get "Failed to Login , Null is not an object( evaluating RNappAuth.Authorize)".
7) I carried all suggestions on similar post mostly on IOS but nothing worked
8) All React and React native versions as well as AppAuth and android studio all are latest versions

Any help would really be appreciated

![phone](https://user-images.githubusercontent.com/52930570/61235558-c8f8cd80-a703-11e9-87ca-e64135b092fd.png)

**Comment by kadikraman** [comment]
Hi @timeinvestgroup 👋 - I've just updated out Android example to RN v0.63, so I'm confident that will work. If you just clone this project, and run the app from `/Examples/AndroidExample`.

If you're starting a new RN project, all you need to do is
```
react-native init MyProject
cd MyProject
yarn add react-native-app-auth@next
```
Then add the [redirect scheme placeholder](https://github.com/FormidableLabs/react-native-app-auth#android-setup), and finally run the app:
```
react-native run-android
```

The latest version of this library doesn't work with RN0.63 yet, but the @next version should!

**Comment by timeinvestgroup** [comment]
Thanks very much https://github.com/kadikraman for getting back to me so quick. Really appreciate it.
I did what you suggested few times but now As soon as I click on Authorize button I get: Unfortunately AndroidExample Stop working. I tried  wiping the data, Clear the cache and Cold boot the phone but getting the same message. Thanks for further help
![mobile](https://user-images.githubusercontent.com/52930570/61321573-cbc5f200-a7d9-11e9-8d48-04d0b145928d.png)

**Comment by OliDow** [comment]
@timeinvestgroup Hey did you ever  get to the bottom of this? I am getting the same issue as you were experiencing initially.. "not an object( evaluating RNappAuth.Authorize)"

React - 16.11.0
RN - 0.61.3
App-Auth .   Same issue in 4.4.0 and 5.0.0-rc3
Emualator - IOS

**Comment by sinsedrix** [comment]
Same error message: 
> null is not an object (evaluating 'RNAppAuth.authorize')

With this config:

- React - 16.9.0
- React Native - 0.61.5
- React Native App Auth - 4.4.0
- Expo - 36.0.2  tunnel with BlackBerry Priv Android 6.0.1

Any idea of what is going wrong or how to get more trace/debug infos?

**Comment by mjtpena** [comment]
I'm experiencing the same issue. Anyone got it resolved?

**Comment by sinsedrix** [comment]
> 
> 
> I'm experiencing the same issue. Anyone got it resolved?

No answer, no better experience since last release.
@kadikraman Any help welcome...

**Comment by mjtpena** [comment]
I have solved it. It turns out, the native linking was not properly set.
In Android's MainApplication.java, make sure that RNAppAuthPackage is added to the React Packages.

`    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNAppAuthPackage()
      );
    }
`

**Comment by Texicitys** [comment]
Hello ! 

I have the same issue and I find no solution to solve it since 2 days, so I'm posting here because I find no solution. I hope you can help me.

I always got this message : 
` [TypeError: null is not an object (evaluating 'RNAppAuth.authorize')] `

My versions are : 

- "react-native": "^0.62.0", 
- "react-native-app-auth": "^5.0.0-rc4" (idem with the official one)
- "react": "16.9.0",
- Emulator Android 
- I made init and the begining (I'm not user expo)

Thank you very much...

**Comment by RaquelCasadoCRC** [comment]
Has anyone fixed this on an expo app? I'll have to eject in order to fix the wrong lining, I really didn't want to do it right now.

**Comment by kkkasio** [comment]
> RNAppAuthPackage

I have the same question, using expo and getting the error. maybe some configuration is missing outside the expo.

**Comment by srodrigues37** [comment]
Hi, same issue with expo and without expo.
Someone have found any solution?

**Comment by srodrigues37** [comment]
I try to make the sample running i clone the project change example/package.json to install last react ,react-native and react-native-app-auth and after a while it works.
I remove all stuff outside example folder, and it failed.
I restore only android folder of main folder and it works.
It seems that the react-native-app-auth is not added into android generated code.
