### ISSUE TITLE
v5.0.0-rc1 does not autolink

### ISSUE THREAD

**Issue by sibelius** [FormidableLabs/react-native-app-auth#363]
## Issue

Using this commit works well with autolinking
"react-native-app-auth": "git+https://git@github.com/FormidableLabs/react-native-app-auth.git#f16014431f5c7470a8404b9f1e26bfd08ea6e72c"

But using 

 "react-native-app-auth": "v5.0.0-rc1",

does not

![image](https://user-images.githubusercontent.com/2005841/62243304-69611a00-b3b3-11e9-86f7-83beec21d632.png)

there is no `react-native-app-auth.podspec` in our node_modules, see image above

---

## Environment

* **Your Identity Provider**: v5.0.0-rc1
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?** No

**Comment by AlgirdasVZ** [comment]
I can confirm this as well. Looks like podspec file was filtered out during package publishing. Is this maybe intended as it's still rc?

**Comment by hazone** [comment]
I guess the react-native-app-auth.podspec need to be added to the files section in package.json. https://github.com/FormidableLabs/react-native-app-auth/blob/v5.0.0-rc1/package.json

**Comment by danfri86** [comment]
@hazone That's correct.
I used the package "[Patch package](https://www.npmjs.com/package/patch-package)" that I already had installed for some other package fixes.
I downloaded the .podspec file and added to the root of react-native-app-auth in my node_modules folder. I also added react-native-app-auth.podspec to the files section in package.json and ran the patch package.
After this I did pod install from the ios folder and it worked.

**Comment by AlgirdasVZ** [comment]
@danfri86 the downside of your approach is that it doesn't fit in  in the build automatisation process. The easiest way to solve this issue would be publishing new npm package (next rc), with podscpec file put in place, as after testing rc-1 it looks like it works quite well otherwise.

**Comment by kadikraman** [comment]
Released in [v5.0.0-rc2](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.0.0-rc2) 🌟
