### ISSUE TITLE
disallowed_useragent for Google on Android 9

### ISSUE THREAD

**Issue by perry-mitchell** [FormidableLabs/react-native-app-auth#364]
## Issue

I've gotten everything working on iOS - Google OAuth2 authentication - but I'm getting Google's `disallowed_useragent` error on Android:

![image](https://user-images.githubusercontent.com/3869469/62327514-841db680-b4b9-11e9-87df-5cf680a9ee3c.png)

I'm using Android 9.0 in an emulator to test - If I test the same code on Android 8 the browser loads and I can authenticate, but the redirection is never captured or acknowledged.

It seems like the browser that is being launched is somehow broken/incorrect on Android 9?

---

## Environment

* **Your Identity Provider**: Google
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** No

**Comment by perry-mitchell** [comment]
I'm wondering if this has something to do with the base OS? For Android 8 I'm using the "Google APIs" emulator, and 9 I'm not.. the UI looks much more simplistic on 9 (I'm not usually an android user), so I'm wondering if it would work differently if a different browser was installed?

**Comment by juanriglos** [comment]
any solution?

**Comment by perry-mitchell** [comment]
@juanriglos I used `react-native-google-signin` instead, which seems to work for me. I think the general requirement is also that the OS has Google Play software installed.

**Comment by juanriglos** [comment]
Thank you perry so you ejected from expo. There is any other solution?

**Comment by kadikraman** [comment]
Hi 👋 - sorry for the late reply. I'm glad you managed to solve your issue.

As for Expo - in order to use this library, you'll have to eject, it includes native code.
