### ISSUE TITLE
AppAuth: sharedApplication is unavailable (extensions)

### ISSUE THREAD

**Issue by perry-mitchell** [FormidableLabs/react-native-app-auth#365]
## Issue

I've gotten react-native-app-auth to work perfectly in the simulator on both iOS and Android. When trying to build & archive for release, however, I get the following error:

![image](https://user-images.githubusercontent.com/3869469/62554245-767d7d80-b879-11e9-9236-25907cc1fc22.png)

I'm building a mobile app with an extension, and I guess this is why AppAuth is dying. Would anyone know of a workaround for this?

My Podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BCAutoFillExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCAutoFillExtension
  pod 'AppAuth', '0.95.0'

end

target 'Buttercup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buttercup
  pod 'AppAuth', '0.95.0'

end
```

Versions:

```
{
	"react-native": "^0.57.1",
    "react-native-app-auth": "^4.4.0"
}
```

---

## Environment

* **Your Identity Provider**: Google
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?** No

**Comment by perry-mitchell** [comment]
Not sure how to get around this. There's an issue on AppAuth referencing AppAuth and AppAuth/Core to separate concerns for extensions (https://github.com/openid/AppAuth-iOS/issues/198) - is this handled by this library at all?

**Comment by Jay-A-McBee** [comment]
:wave: hey @perry-mitchell - I'm assuming that you found a solution to your problem, but I checked out the [AppAuth-ios extension example](https://github.com/openid/AppAuth-iOS/blob/master/Examples/Example-iOS_ObjC/Podfile#L12), and it looks like your Podfile declaration is off for the extension.
