### ISSUE TITLE
Autolinking in RN >= 0.6+ for ios needs it node_modules path updated.

### ISSUE THREAD

**Issue by martinfa** [FormidableLabs/react-native-app-auth#367]
## Issue

Currently the autolinker for ios cannot find the `RNAppAuth` pod. 
To reproduce do the following: 
```
$ npm install react-native-app-auth --save
$ react-native link react-native-app-auth
$ cd ./ios && pod install
```

Results in: 
```
Detected React Native module pod for react-native-geolocation
Analyzing dependencies
Fetching podspec for `RNAppAuth` from `../node_modules/react-native-app-auth`
[!] No podspec found for `RNAppAuth` in `../node_modules/react-native-app-auth`
```

---

## Environment

* react-native-cli: 2.0.1
* react-native: 0.60.5 
* ios
* react-native-app-auth@4.4.0

--

A simple fix is just to point straight to the ios directory in the node_modules but I figured I'd let you know that autolinking doesn't work out of the box, thank you guys!

**Comment by kadikraman** [comment]
4.4.0 is not compatible with `RN0.60+`, but our latest release candidate does support autolinking. 

You can install this with: `yarn add react-native-app-auth@next`
