### ISSUE TITLE
Open web view after successfully login ?

### ISSUE THREAD

**Issue by harimtejada** [FormidableLabs/react-native-app-auth#369]
I am developing a React Native App, that connects to a remote web api and also needs to show a secure web view.

Connecting to the remote api is working perfectly I can get and refresh the token.

My problem is that I want to use the same Identity to open/show a web view within the app.

What's the best approach to accomplish this ?

**Comment by Daavidaviid** [comment]
Hi,
I was about to create an issue almost identical to yours.

What you're saying is that you'd like to be able to log in the app using let's say Azure AD SSO with react-native-app-auth and then be able to launch a webview containing a sharepoint site needing to be logged in accordingly with the right tenant and user ?

On my side, I don't know yet how to do it properly.
I was digging the possibility to inject cookies in the WebView but I don't think it'll workout as I'd like it to.

I'd like to get some news about it too.

I found some issue that might be related, event if it's not react-native :
https://stackoverflow.com/questions/43495825/force-adal-to-save-persistent-cookies/43576346

**Comment by harimtejada** [comment]
@Daavidaviid correct, I just want to be able to use the same session to connect with the API and the web view using the same Token/Cookie/Identity.

**Comment by kadikraman** [comment]
Hi @harimtejada 👋- I think the cookies should work on Android. In the case of iOS - `SafariViewController` does not share cookies with anything (it was purposefully designed like this by Apple). I think the only way to make it work would be to make a change in the native bridge code and expose an `openWebView` method that uses a custom `OIDExternalUserAgentIOS` - the same one that would also be used for visiting the authorization endpoint 🤔

**Comment by Daavidaviid** [comment]
Good to know ! So that’s not an easy task and also uncertain. But still a
good start

Le dim. 8 sept. 2019 à 17:41, Kadi Kraman <notifications@github.com> a
écrit :

**Comment by chintantatva** [comment]
Hey any updates on this ?

**Comment by abdulrehmanfas** [comment]
Any update on this?
