### ISSUE TITLE
Issue with the google sign-in via keycloak

### ISSUE THREAD

**Issue by vovailchenko** [FormidableLabs/react-native-app-auth#370]
## Issue with the google sign-in via keycloak
Thank you for the great lib.

I've been playing around with an RN app (using react-native-app-auth) and a dedicated Keycloak server, which i've set up for myself.
Everything works ok as of now. 
I'm now trying to add other identity providers to Keycloak - e.g. Google and Facebook. This allows me to let the users sign with Google or Facebook etc. 
I've been successful with setting this up for the Keycloak<->Other IDP side (the web apps and postman are working ok), but on an Android phone - i'm facing the weird issue. Here is an animcation:
![ezgif com-optimize](https://user-images.githubusercontent.com/8845925/63421818-eb23f080-c411-11e9-8be3-30acf63c7b3d.gif)

So, after approving the sign in to the account - the google sign-in just loads forever. 

If i use Facebook login - everything works as it should.

I've been trying things out for the last 2 days, so this is a list of findings:
1. Facebook login works correctly
2. Google login doesn't (endless loading)
3. One time in 50 (literally) Google login works ok. after that - again endless loading. (i'm wiping out the phone before each try)
4. my redirect URL in rn-app-auth is currently set to `tk.app:/discover`
if i change it to something like `http://blabla` - there is no endless loading but smth like "unreachable error". This gives me a clue that this may be a bug related to the custom schemas ?

Any ideas are welcome.
Thank you.
---

## Environment
* **Library version**: 4.4.0 and 5.0.0-rc1
* **Your Identity Provider**: Keycloak 6.0.1 with Google and Facebook Brokers
* **Platform that you're experiencing the issue on**:
  
  * [ ]  iOS
  * [ ]  Android
  * [ ]  **iOS** but have not tested behavior on Android
  * [x]  **Android** but have not tested behavior on iOS
  * [ ]  Both
* **Are you using Expo, e.g. `ExpoKit`?**
  
  * [x]  No
  * [ ]  Yes, I've _not_ ejected
  * [ ]  Yes, but I **have** ejected to `ExpoKit`
  * [ ]  Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi 👋 - sorry for the late reply. I hope you managed to resolve your issue. Please let me know if you're still having problems on the latest version.
