### ISSUE TITLE
Build failing on CI: Execution failed for task ':react-native-app-auth:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by dale-french** [FormidableLabs/react-native-app-auth#371]
## Issue

Android build is succeeding locally but failing on CI with the following message
`Execution failed for task ':react-native-app-auth:compileReleaseJavaWithJavac'.`

## Environment

* **React Native Version:**: 0.60.4
* **Your Identity Provider**: IdentityServer
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** No

## Logs:

> Task :react-native-app-auth:generateReleaseBuildConfig
> Task :react-native-app-auth:prepareLintJar
> Task :react-native-app-auth:generateReleaseRFile
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.
> Task :react-native-app-auth:generateReleaseSources
> Task :react-native-app-auth:javaPreCompileRelease
> Task :react-native-app-auth:compileReleaseJavaWithJavac
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:10: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:11: error: cannot find symbol
import android.support.customtabs.CustomTabsCallback;
                                 ^
  symbol:   class CustomTabsCallback
  location: package android.support.customtabs
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:12: error: cannot find symbol
import android.support.customtabs.CustomTabsClient;
                                 ^
  symbol:   class CustomTabsClient
  location: package android.support.customtabs
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:13: error: cannot find symbol
import android.support.customtabs.CustomTabsServiceConnection;
                                 ^
  symbol:   class CustomTabsServiceConnection
  location: package android.support.customtabs
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/CustomConnectionBuilder.java:19: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/UnsafeConnectionBuilder.java:20: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/UnsafeConnectionBuilder.java:21: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/MapUtil.java:3: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/CustomConnectionBuilder.java:48: error: cannot find symbol
    public HttpURLConnection openConnection(@NonNull Uri uri) throws IOException {
                                             ^
  symbol:   class NonNull
  location: class CustomConnectionBuilder
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/CustomConnectionBuilder.java:46: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class CustomConnectionBuilder
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/UnsafeConnectionBuilder.java:80: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class UnsafeConnectionBuilder
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/UnsafeConnectionBuilder.java:111: error: cannot find symbol
    public HttpURLConnection openConnection(@NonNull Uri uri) throws IOException {
                                             ^
  symbol:   class NonNull
  location: class UnsafeConnectionBuilder
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/UnsafeConnectionBuilder.java:109: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class UnsafeConnectionBuilder
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/utils/MapUtil.java:12: error: cannot find symbol
    public static HashMap<String, String> readableMapToHashMap(@Nullable ReadableMap readableMap) {
                                                                ^
  symbol:   class Nullable
  location: class MapUtil
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:108: error: cannot find symbol
                                    @Nullable AuthorizationServiceConfiguration fetchedConfiguration,
                                     ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:109: error: cannot find symbol
                                    @Nullable AuthorizationException ex) {
                                     ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:187: error: cannot find symbol
                                @Nullable AuthorizationServiceConfiguration fetchedConfiguration,
                                 ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:188: error: cannot find symbol
                                @Nullable AuthorizationException ex) {
                                 ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:269: error: cannot find symbol
                                @Nullable AuthorizationServiceConfiguration fetchedConfiguration,
                                 ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:270: error: cannot find symbol
                                @Nullable AuthorizationException ex) {
                                 ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:462: error: cannot find symbol
            public void onTokenRequestCompleted(@Nullable TokenResponse response, @Nullable AuthorizationException ex) {
                                                 ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:462: error: cannot find symbol
            public void onTokenRequestCompleted(@Nullable TokenResponse response, @Nullable AuthorizationException ex) {
                                                                                   ^
  symbol: class Nullable
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:581: error: cannot find symbol
        CustomTabsServiceConnection connection = new CustomTabsServiceConnection() {
        ^
  symbol:   class CustomTabsServiceConnection
  location: class RNAppAuthModule
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:581: error: cannot find symbol
        CustomTabsServiceConnection connection = new CustomTabsServiceConnection() {
                                                     ^
  symbol:   class CustomTabsServiceConnection
  location: class RNAppAuthModule
/bitrise/src/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:593: error: cannot find symbol
        CustomTabsClient.bindCustomTabsService(context, CUSTOM_TAB_PACKAGE_NAME, connection);
        ^
  symbol:   variable CustomTabsClient
  location: class RNAppAuthModule
25 errors
> Task :react-native-app-auth:compileReleaseJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-app-auth:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5m 18s

**Comment by kadikraman** [comment]
Hi - this looks like an androidX support issue. Which version of this library are you using? `RN0.60.4` uses AndroidX, and our AndroidX support is available as a release candidate. You can install it with `yarn add react-native-app-auth@next`

**Comment by njbuchheit** [comment]
@kadikraman Any idea when the AndroidX support fix will surpass the release candidate phase?

**Comment by kadikraman** [comment]
@njbuchheit - I'm releasing v5 later today :)
