### ISSUE TITLE
After installing on Android, the app crashes on authorize call

### ISSUE THREAD

**Issue by cat4git** [FormidableLabs/react-native-app-auth#372]
## Issue

I install the pack 
by run : 
`npm install react-native-app-auth --save`
`react-native link react-native-app-auth`

i add: 
```
 manifestPlaceholders = [
      appAuthRedirectScheme: 'io.identityserver.demo'
    ]
```
to the `android/app/build.gradle` file

when I try to call `authorize` function the app crush.

the config is: 
```
config = {
    issuer: 'https://demo.identityserver.io',
    clientId: 'native.code',
    redirectUrl: 'io.identityserver.demo:/oauthredirect',
    additionalParameters: {
        prompt: 'login'
    },
    scopes: ['openid', 'profile', 'email', 'offline_access']
    };
```

"react": "^16.8.3"
"react-native": "^0.59.10"
"react-native-app-auth": "^5.0.0-rc1"

---

## Environment
Identity Provider:  Form the demo
Tested on android only 
no Expo

**Comment by javi10823** [comment]
Same Issue here.

**Comment by kadikraman** [comment]
Hi @cat4git 👋 Please use `v4.4.0` of this library for React Native `^0.59.10`.

The release candidate is for `RN0.60` and above only, as it supports AndroidX, which was added in `RN0.60` and is not backwards compatible.
