### ISSUE TITLE
Refresh token error codes are not unified across platforms and providers

### ISSUE THREAD

**Issue by henninghall** [FormidableLabs/react-native-app-auth#377]
## Issue
When the refresh token expires (could be due to changing password, not being used for a while etc) the error message sent from the library is different depending on platform and provider. It would be very nice if this could be unified. 

### Example
Responses for Google and Azure, havn't tried the others in the table below. 

```
catch(e) {
    e.code // ErrorCode in example below
    e.message // ErrorMessage in example below
}
```

<table>
<tr><td></td><td>Android</td><td>iOS</td></tr>
<tr><td>Azure</td><td>
<b>ErrorCode:</b> Failed to refresh token
 <br>
<b>ErrorMessage:</b> AADSTS50173: The provided grant has expired due to it being revoked ....
</td><td>
<b>ErrorCode:</b> RNAppAuth Error
<br>
<b>ErrorMessage:</b> invalid_grant: AADSTS50173: The provided grant has expired due to it being revoked
</td></tr>
<tr><td>Google</td><td>
<b>ErrorCode:</b> Failed to refresh token
<b>ErrorMessage:</b> Token has been expired or revoked.
</td><td>
<b>ErrorCode:</b> RNAppAuth Error
<b>ErrorMessage:</b> invalid_grant: Token has been expired or revoked.

</td></tr>
</table>

## Suggested fix
The same error should return the same error code defined by the library. The error messages could be kept as they are.

**Comment by kadikraman** [comment]
That is an excellent point, thanks for bringing this up! This is what happens when bridging independently maintained libraries in two different languages 😅

I think the Error Codes could be updated to be the same, but the Error Message is thrown by the underlying native library, so I'd like to keep it as is. What do you think?

**Comment by henninghall** [comment]
Yes, I totally agree 👍

**Comment by kadikraman** [comment]
Hey @henninghall - does this look good to you? https://github.com/FormidableLabs/react-native-app-auth/pull/378

**Comment by henninghall** [comment]
Made I comment, check it out, otherwise, it looks good to me. Should probably be noted very clearly in the release notes since people might be relying on these old error codes.

**Comment by kadikraman** [comment]
Yes, good point. Thanks for your help! 🙌
