### ISSUE TITLE
Example for password reset in Azure

### ISSUE THREAD

**Issue by Highspeed7** [FormidableLabs/react-native-app-auth#379]
Is there any documentation on how to handle redirects such as AD B2C's reset password exception using this package? Must I just change the issuer to the authorize call?

**Comment by kadikraman** [comment]
Hi @Highspeed7 👋 - password reset should "just work" as its all done in the webview and handled by the IDP, so it doesn't require any special configuration on the app side.

If you're still having issues, please reply with steps to reproduce the issue.
