### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/react-native-app-auth#38]
Every open source library needs a logo. Well, that's not true. But it would be cool to have one anyway.

**Comment by jevakallio** [comment]
My humble proposal:
![react-native-app-auth](https://user-images.githubusercontent.com/1203949/36029377-dc2aa9cc-0d9a-11e8-8eaf-4a11d0fddbec.png)

Rationale:
![screen shot 2018-02-09 at 13 06 15](https://user-images.githubusercontent.com/1203949/36029392-e7d96722-0d9a-11e8-9b6b-b92e20586906.png)

**Comment by jevakallio** [comment]
Now with more boost and less... shapely.

![react-native-app-auth-rocketship](https://user-images.githubusercontent.com/1203949/36029695-279f4f56-0d9c-11e8-90b1-bec53ddeaa7c.png)

**Comment by kadikraman** [comment]
Love it. The rocketship shape is a winner 🚀
