### ISSUE TITLE
error: package android.support.annotation does not exist when building assembleDebug

### ISSUE THREAD

**Issue by martintjandra** [FormidableLabs/react-native-app-auth#383]
## Issue

I'm trying to build my react native project, which already use react native 0.60+, IDE visual studio code, and also already migrate to AndroidX. When I run ./gradlew assembleDebug, I encountered error below:

```
> Task :react-native-app-auth:compileDebugJavaWithJavac FAILED
/Users/martintjandra/Projects/coach-opal/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:10: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/martintjandra/Projects/coach-opal/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:11: error: cannot find symbol
import android.support.customtabs.CustomTabsCallback;
                                 ^
  symbol:   class CustomTabsCallback
  location: package android.support.customtabs
/Users/martintjandra/Projects/coach-opal/node_modules/react-native-app-auth/android/src/main/java/com/rnappauth/RNAppAuthModule.java:12: error: cannot find symbol
import android.support.customtabs.CustomTabsClient;
                                 ^
  symbol:   class CustomTabsClient
  location: package android.support.customtabs
  ...
  ...
```

After looking around, I see that this error is caused by the project already migrated to AndroidX but the plugins in node module still don't. Some people suggest that ```android.support.annotation.Nullable``` is the way of Android plugins, not AndroidX. The AndroidX calls will be ```androidx.annotation.Nullable```. I also read that jetifier should take care about things like this, and I also make sure that ```android.useAndroidX=true``` and 
```android.enableJetifier=true``` is present in the gradle.properties. I see in another thread #326 that the merging was on hold until RN 0.60 is released. Has it been merging yet? I see in #328 that it probably is? I already using the latest version of react-native-app-auth ^4.4.0.

How can I resolve this issue?

**Comment by dulmandakh** [comment]
run **npx jetify** every time you install/update/delete NPM package. It's just work around.

**Comment by kadikraman** [comment]
Thank you! Looks like this is resolved so closing.
