### ISSUE TITLE
Calls to .authorize or .refresh cause application crash when (and not only) no browser is detected

### ISSUE THREAD

**Issue by skippone** [FormidableLabs/react-native-app-auth#385]
## Issue
Currently native calls to `.authorize()` and `.refresh()` methods on **Android** platform can cause RN application to crash with native exception. Such native exceptions are by definition not catchable in RN app, unless one uses global [native exception handler](https://github.com/master-atul/react-native-exception-handler) and even than the user experience (not mentioning developer's) is rather dreadfull.

For example when underlaying AppAuth library is unable to find suitable browser it throws `ActivityNotFoundException` during `performAuthorizationRequest()` call. Such is the case with certain Android devices with [Opera browser installed ](https://github.com/openid/AppAuth-Android/issues/452) or when browser is [unavailable/disabled](https://github.com/openid/AppAuth-Android/issues/459).

Example of a stack trace for such an application crash when invoking `.authorize()` method in RN application with Opera installed (see issues above):
```
android.content.ActivityNotFoundException:
  at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent (AuthorizationService.java:372)
  at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent (AuthorizationService.java:267)
  at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent (AuthorizationService.java:296)
  at com.rnappauth.RNAppAuthModule.authorizeWithConfiguration (RNAppAuthModule.java:326)
  at com.rnappauth.RNAppAuthModule.access$000 (RNAppAuthModule.java:43)
  at com.rnappauth.RNAppAuthModule$1.onFetchConfigurationCompleted (RNAppAuthModule.java:119)
  at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute (AuthorizationServiceConfiguration.java:364)
  at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute (AuthorizationServiceConfiguration.java:305)
  at android.os.AsyncTask.finish (AsyncTask.java:695)
  at android.os.AsyncTask.-wrap1 (Unknown Source)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:7000)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:441)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)
```

I've looked through current [RNAppAuthModule.java](https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/src/main/java/com/rnappauth/RNAppAuthModule.java) implementation and apparently some calls to AppAuth service are not encapsulated in `try-catch `blocks and therefore not forwarded back to RN bridge Promise object. This seems to be rather an omission than an intent, since `.authorize()` and `.refresh()` methods already contains parts of code that actually handles exceptions when invoking AppAuth service methods.

For example (simplified stub only) this is a source of `.refresh()` method:

```
public void refresh(...) {
        ...
        if (serviceConfiguration != null || mServiceConfiguration.get() != null) {
            try { // TRY CATCH HERE
                ...
                refreshWithConfiguration(
                        ...
                );
            } catch (Exception e) {
                promise.reject("Failed to refresh token", e.getMessage());
            }
        } else {
            final Uri issuerUri = Uri.parse(issuer);
            AuthorizationServiceConfiguration.fetchFromUrl(
                    buildConfigurationUriFromIssuer(issuerUri),
                    new AuthorizationServiceConfiguration.RetrieveConfigurationCallback() {
                        public void onFetchConfigurationCompleted(
                                @Nullable AuthorizationServiceConfiguration fetchedConfiguration,
                                @Nullable AuthorizationException ex) {
                            if (ex != null) {
                                promise.reject("Failed to fetch configuration", getErrorMessage(ex));
                                return;
                            }

                            mServiceConfiguration.set(fetchedConfiguration);

                            // MISSING TRY CATCH HERE
                            refreshWithConfiguration(
                                    ...
                            );
                        }
                    },
                    builder);
        }
    }
```
The above code apparently [misses exception handling](https://github.com/FormidableLabs/react-native-app-auth/blob/1a69037cb787263f42215ff613daf4b58cd1d3be/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L195) for `else` statement.

The aforementioned error handling issue is also present in other publicly exposed methods of `RNAppAuthModule.java` such as `authorize()` and `prefetchConfiguration()`.

At least for `.authorize()` and `.refresh()` method a possible (and rather crude) solution would be to catch at least `ActivityNotFoundException` and generic `Exception` like this:

```
public void authorize(...) {
        ...
        if (serviceConfiguration != null || mServiceConfiguration.get() != null) {
            try {
                final AuthorizationServiceConfiguration serviceConfig = mServiceConfiguration.get() != null ? mServiceConfiguration.get() : createAuthorizationServiceConfiguration(serviceConfiguration);
                authorizeWithConfiguration(...);
            } catch (Exception e) {
                promise.reject("Failed to authenticate", e.getMessage());
            }
        } else {
            final Uri issuerUri = Uri.parse(issuer);
            AuthorizationServiceConfiguration.fetchFromUrl(
                    buildConfigurationUriFromIssuer(issuerUri),
                    new AuthorizationServiceConfiguration.RetrieveConfigurationCallback() {
                        public void onFetchConfigurationCompleted(
                                @Nullable AuthorizationServiceConfiguration fetchedConfiguration,
                                @Nullable AuthorizationException ex) {
                            if (ex != null) {
                                promise.reject("Failed to fetch configuration", getErrorMessage(ex));
                                return;
                            }

                            mServiceConfiguration.set(fetchedConfiguration);

                            try { // NEW TRY-CATCH...
                                authorizeWithConfiguration(...);
                            } catch (ActivityNotFoundException e) {
                                promise.reject("RNAppAuth Error", "Suitable browser could not be found", e);
                            } catch (Exception e) {
                                promise.reject("RNAppAuth Error", "Failed to authenticate", e);
                            }
                        }
                    },
                    builder
            );
        }
    }
```

However the solution above is rather a hotfix and would bloat existings methods with duplicate error handling. I think exception handling of underlaying errors raised by AppAuth is at the moment very elemental (for example Android and iOS exceptions thrown during token refresh contain different exception objects, with iOS providing detailed codes as oposed to Android which provides text messages only) and would probably require more work (and perhaps more specific exceptions to be handled separately). Either way even a simple exception handling preventing RN apps from crashing would really help...

Best regards

---

## Environment

* **Your Identity Provider**: `custom`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?**: No
* **Version**: 5.0.0-rc2

**Comment by skippone** [comment]
In case someone needs a temporary fix you may try the following patch. If you are using [patch-package](https://github.com/ds300/patch-package#readme) just put this file to your `./patches` folder, otherwise apply this update directly to your RN AppAuth package.

This patch handles exceptions thrown in `.refresh()` and `.authenticate()` methods as follows:
* when browser is not detected, methods throw JS error object:

```
{
    code: "BrowserUnavailable",
    message "Suitable browser could not be found"
}
```
* otherwise a generic JS error object is thrown.

Patch: [react-native-app-auth+5.0.0-rc2.patch.zip](https://github.com/FormidableLabs/react-native-app-auth/files/3631106/react-native-app-auth%2B5.0.0-rc2.patch.zip)

**Comment by aTastyT0ast** [comment]
+1

**Comment by kadikraman** [comment]
Hi @skippone  - thank you for the issue and the patch file. I'll use your solution 👍
