### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AppAuth"

### ISSUE THREAD

**Issue by ozasadnyy** [FormidableLabs/react-native-app-auth#387]
## Issue

We are using **Expo 35** which depends on **React Native 0.59.8**.
**ExpoKit/Core** depends on **AppAuth (~> 1.2)** while **react-native-app-auth 4.4.0** depends on **AppAuth (= 0.94.0)**

Can't update to **react-native-app-auth 5** as it depends on **React Native 0.60** which is not supported by the latest Expo version.

Any ideas how to overcome this issue? 

```
[!] CocoaPods could not find compatible versions for pod "AppAuth":
  In Podfile:
    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.13.0`) was resolved to 35.0.0, which depends on
      AppAuth (~> 1.2)

    RNAppAuth (from `../node_modules/react-native-app-auth/ios/`) was resolved to 1.0.0, which depends on
      AppAuth (= 0.94.0)

Specs satisfying the `AppAuth (~> 1.2), AppAuth (= 0.94.0)` dependency were found, but they required a higher minimum deployment target.
```

---

## Environment
```
"expo": "^35.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"react-native-app-auth": "^4.4.0",
```

**Comment by raghuureddy** [comment]
same error for me

**Comment by kadikraman** [comment]
I can't 100% vouch for Expo compatibility, but you could try using [patch-package](https://github.com/ds300/patch-package/) to change the version of AppAuth in the Podfile in your `node_modules`. I think you'd also need to make [this change](https://github.com/FormidableLabs/react-native-app-auth/pull/338/files#diff-9d58d422456571f1c785f3ec104e859dL162) - it was a typo they fixed that caused a breaking change in `v1.0`.

**Comment by oviedo97fer** [comment]
same error. Any?

**Comment by kadikraman** [comment]
Closing as `0.60+` support has been added in [expo sdk 36](https://blog.expo.io/expo-sdk-36-is-now-available-b91897b437fe)

**Comment by carlosfranz** [comment]
Hi, i have the similar error but i don´t use Expo
`"react-native":"0.62.2"`
`"react-native-app-auth":"^6.0.2"`
Error:

> [!] CocoaPods could not find compatible versions for pod "react-native-app-auth":
  In Podfile:
    react-native-app-auth (from `../node_modules/react-native-app-auth`) 

> Specs satisfying the `react-native-app-auth (from `../node_modules/react-native-app-auth`)` dependency were found, but they required a higher minimum deployment target.

just install the library and when doing pod install the error appears :(

**Comment by kadikraman** [comment]
Sounds like you would need to use a higher deployment target.

> Specs satisfying the react-native-app-auth (from ../node_modules/react-native-app-auth) dependency were found, but they required a higher minimum deployment target.

In `/ios/Podfile` this should be on 10 or higher based on our [minimum](https://github.com/FormidableLabs/react-native-app-auth/blob/main/react-native-app-auth.podspec#L12).

```
platform :ios, '10.0'
```

**Comment by carlosfranz** [comment]
> Sounds like you would need to use a higher deployment target.
> 
> > Specs satisfying the react-native-app-auth (from ../node_modules/react-native-app-auth) dependency were found, but they required a higher minimum deployment target.
> 
> In `/ios/Podfile` this should be on 10 or higher based on our [minimum](https://github.com/FormidableLabs/react-native-app-auth/blob/main/react-native-app-auth.podspec#L12).
> 
> ```
> platform :ios, '10.0'
> ```

Now it works! thank you very very much!

**Comment by michaelmurr** [comment]
> Update version with `yarn add react-native-app-auth@next` Worked for me

i ran this with npm but it still fixed it for me, so thanks a lot!
