### ISSUE TITLE
Error authorize using IOS 13.x 

### ISSUE THREAD

**Issue by ATranDev** [FormidableLabs/react-native-app-auth#388]
## Issue

Hey everyone, I have error while using ios 13 ; react-native-app-auth@5.0.0-rc2

Error: The operation couldn’t be completed. (org.openid.appauth.general error -3.)
    at createErrorFromErrorData (NativeModules.js:152)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:442)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:343)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80

Please support me =((
---

## Environment

* ** Provider**: ` 
    "react": "16.8.6", 
    "react-native": "0.60.5",
    "react-native-app-auth": "^5.0.0-rc2" `
* **Platform **: `iOS `

**Comment by longvl0208** [comment]
I stuck with the same issue like this .

**Comment by jeffreyffs** [comment]
PR is up to fix it here... just need it to be merged: https://github.com/FormidableLabs/react-native-app-auth/pull/386

**Comment by mustafawm** [comment]
Hi @jeffreyffs .. not sure if this error is related, but I did the following
1. `yarn add react-native-app-auth@next` got 5.0.0-rc2
2. manually updated the dependency in node_modules... `s.dependency 'AppAuth', '1.2.0'`
3. `cd ios/` then `pod update AppAuth` then `pod install`
4. run the app
It's **still** crashing once I try to google authenticate (screenshot).
```
<AppDelegate: 0x60000053d100> does not conform to RNAppAuthAuthorizationFlowManager
(
    "4   libc++abi.dylib                     0x00007fff4f23be97 _ZSt11__terminatePFvvE + 8",
    "5   libc++abi.dylib                     0x00007fff4f23be39 _ZSt9terminatev + 41",
    "6   libdispatch.dylib                   0x00007fff511fc80d _dispatch_client_callout + 28",
    "7   libdispatch.dylib                   0x00007fff51208d22 _dispatch_main_queue_callback_4CF + 1212",
    "8   CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9"
)
```

**Comment by ATranDev** [comment]
> Hi @jeffreyffs .. not sure if this error is related, but I did the following
> 
> 1. `yarn add react-native-app-auth@next` got 5.0.0-rc2
> 2. manually updated the dependency in node_modules... `s.dependency 'AppAuth', '1.2.0'`
> 3. `cd ios/` then `pod update AppAuth` then `pod install`
> 4. run the app
>    It's **still** crashing once I try to google authenticate (screenshot).
> 
> ```
> <AppDelegate: 0x60000053d100> does not conform to RNAppAuthAuthorizationFlowManager
> (
>     "4   libc++abi.dylib                     0x00007fff4f23be97 _ZSt11__terminatePFvvE + 8",
>     "5   libc++abi.dylib                     0x00007fff4f23be39 _ZSt9terminatev + 41",
>     "6   libdispatch.dylib                   0x00007fff511fc80d _dispatch_client_callout + 28",
>     "7   libdispatch.dylib                   0x00007fff51208d22 _dispatch_main_queue_callback_4CF + 1212",
>     "8   CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9"
> )
> ```

You can use my fork to fix it. It works.
https://github.com/ATranDev/react-native-app-auth

**Comment by jeffreyffs** [comment]
@mustafawm That is a different error (and a crash). It sounds like you didn't properly hook up your native iOS code to receive AppAuth callbacks.

**Comment by mustafawm** [comment]
Thanks @ATranDev  & @jeffreyffs 🙏

**Comment by kadikraman** [comment]
[v5.0.0-rc3](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.0.0-rc3) includes the new version of AppAuth iOS, which should resolve this issue - closing!

**Comment by djleonskennedy** [comment]
@kadikraman Hello 
have same issue with `"react-native-app-auth": "^5.1.1"`
Could you please help with it?
Regards

**Comment by danghatam** [comment]
me too, i have the same issue with "react-native-app-auth": "^5.1.2" :(
