### ISSUE TITLE
ID Token parsing failed

### ISSUE THREAD

**Issue by shashank0495** [FormidableLabs/react-native-app-auth#392]
When trying to integrate this library with IOS I'm getting the error while calling the authorize method. The error says ID Token parsing failed.
Can someone help me out fixing this issue.

**Comment by pradhul-dev** [comment]
Getting same error here:
react-native info

`System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 38.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
`
here is the error logs:

`projectname[52379:754290] 'errr', { [Error: ID Token parsing failed]
  framesToPop: 1,
  code: 'RNAppAuth Error',
  domain: 'org.openid.appauth.general',
  userInfo: { NSLocalizedDescription: 'ID Token parsing failed' },
  nativeStackIOS: 
   [ '0   projectname                   0x0000000109a799d7 RCTJSErrorFromCodeMessageAndNSError + 135',
     '1   projectname                   0x0000000109a09943 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179',
     '2   projectname                   0x00000001098fcda5 __134-[RNAppAuth authorizeWithConfiguration:redirectUrl:clientId:clientSecret:scopes:useNonce:usePKCE:additionalParameters:resolve:reject:]_block_invoke + 421',
     '3   projectname                   0x0000000109853633 __85+[OIDAuthState authStateByPresentingAuthorizationRequest:externalUserAgent:callback:]_block_invoke_2 + 195',
     '4   projectname                   0x00000001098518d0 __86+[OIDAuthorizationService performTokenRequest:originalAuthorizationResponse:callback:]_block_invoke_7 + 48',
     '5   libdispatch.dylib                   0x000000010aa7fdf8 _dispatch_call_block_and_release + 12',
     '6   libdispatch.dylib                   0x000000010aa80d6c _dispatch_client_callout + 8',
     '7   libdispatch.dylib                   0x000000010aa8ee24 _dispatch_main_queue_callback_4CF + 1500',
     '8   CoreFoundation                      0x00007fff23b0ce49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9',
     '9   CoreFoundation                      0x00007fff23b07aa9 __CFRunLoopRun + 2329',
     '10  CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438',
     '11  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65',
     '12  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621',
     '13  projectname                   0x0000000109849850 main + 112',
     '14  libdyld.dylib                       0x00007fff516ecd29 start + 1' ],
  line: 1745,
  column: 26,
  sourceURL: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false' }
`

**Comment by kadikraman** [comment]
Hi 👋 - the error comes from [here](https://github.com/openid/AppAuth-iOS/blob/cf5b15a6e02ee509c5966c5dacbc45a0bef7c5cf/Source/OIDAuthorizationService.m#L539) and means that the JWT is invalid. Specifically that it fails one of the rules defined [in the spec](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation). If you are using a custom IDP, ensure your JWT is spec compliant.
