### ISSUE TITLE
Redirect not being captured 

### ISSUE THREAD

**Issue by souljacker** [FormidableLabs/react-native-app-auth#397]
After a successful login redirect is done on the opened window instead 

---

## Environment

* **Your Identity Provider**:  My company's webstie
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** no

My config is as 

`const config = {
  serviceConfiguration: {
    authorizationEndpoint: 'https://mycompany.io/oauth/authorize',
    tokenEndpoint: 'https://mycompany.io/oauth/token',
  },
  clientId: '35id
  clientSecret: 'secret',
  redirectUrl: 'http://io.mycompany',
};`

And here's part of my config at my build.gradle

`    defaultConfig {
        applicationId "com.scpush"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
         appAuthRedirectScheme: 'io.mycompany'
        ]
    }`

Am I missing something?

**Comment by DanSmit** [comment]
@souljacker can you please share how you resolved this issue?
