### ISSUE TITLE
Multi tenant URI with Azure Active Directory

### ISSUE THREAD

**Issue by BrentGrammer** [FormidableLabs/react-native-app-auth#403]
We are trying to use this library with Azure Active Directory Single Sign On for a registered Azure application, and cannot get it to work with a multi tenant setup.  We want to set the issuer to `https://login.microsoftonline.com/common/v2.0`, but the uri keeps adding `/.well-known/openid-configuration` causing an invalid URL error.  (this is caused by line 181 in index.js).  

Is there any way to set the issuer to the `.../common/2.0` url so the app will accept external Microsoft accounts to sign on instead of having to add users to Active Directory on Azure?  We do have the registered app on Azure set to accept incoming Microsoft accounts from organizations and personal accounts. We're really struggling with this and understanding how to get this working.  Thanks.

**Comment by kadikraman** [comment]
Hi 👋 - the issuer endpoint is there just for looking up the service configuration. So the app will visit https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration and look up the auth and token endpoints. If for some reason you don't want to use the discovery document, you and omit sending the issuer and define the with and service configuration endpoints directly

So instead of the following:
```js
const config = {
  issuer: 'https://login.microsoftonline.com/common/v2.0',
  [---]
};
```
You can define each of the endpoints manually in the `serviceConfiguration` object:
```js
const config = {
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token'
  }
  [---]
};
```

Hope this helps!

**Comment by mattwoberts** [comment]
Just adding to this - since i was confused myself why it wasn't working... 

It's because the auto-discovery response, contains a issuer URL that looks like this:

> "issuer": "https://login.microsoftonline.com/{tenantid}/v2.0",

With the placeholder for your tenant ID. So that's not going to work, hence the need to specify the endpoints manually.

Cheers.

**Comment by AmaanKulshreshtha** [comment]
Just to clarify,

When writing the manual config,

```js
const config = {
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token'
  }
  [---]
};
``` 
`common` is a placeholder for the `tenant-id` as well, right?

**Comment by mattwoberts** [comment]
At the risk of further complicating it @AmaanKulshreshtha , IIRC, `common` is not a placeholder, it's what you use when you don't want to tie the auth down to a specific tenant (which is what I wanted). 

So my manual config looks like this (i.e. there are no placeholders for tenantId in them)

```
      serviceConfiguration: {
        authorizationEndpoint:
          'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        tokenEndpoint:
          'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      },
```

**Comment by AmaanKulshreshtha** [comment]
But if I want to tie it down to a tenant id, then I'll replace `common` with that tenant id, right ?
