### ISSUE TITLE
Android - Azure AD - Redirect Issues

### ISSUE THREAD

**Issue by CelsoTeixeira** [FormidableLabs/react-native-app-auth#405]
## Issue

Im having issues following the documentation about how I should configure/setup both environments.

Tried to use the urn that is recommend on the configuration example, but Im getting the following error back: 

![erro-scheme (1)](https://user-images.githubusercontent.com/6026577/67529172-c528ff80-f691-11e9-9d13-bf338f5ce924.jpeg)

Tried to use this default URI from the error, but nothing happens when mathcing it on the react-native configuration code, resulting only on a blank screen.
Using the nativeclient URI with the urn on client, I get the "no matching" URI error.

Having both values on Microsoft docs are really confusing on what should I be using, or should I not use any of this values at all?

---

## Environment

* **Your Identity Provider**: `Azure AD`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
Looks like they've updated this recently. It's a change for the better though!

I think you'll have to register your own redirect now, there is no set redirect. According to the docs, it can be anything, e.g. `com.myapp://oauth/redirect` (you'll have to register this somewhere on the Azure console) and then put `com.myapp` to your `build.gradle` to capture the redirect from the app.

```
        manifestPlaceholders = [
          appAuthRedirectScheme: 'com.myapp'
        ]
```

I'll update the docs to remove the old suggestion - thanks for bringing this up!
