### ISSUE TITLE
what is the config for appAuthRedirectScheme value when auth with youtube?

### ISSUE THREAD

**Issue by idoor88** [FormidableLabs/react-native-app-auth#408]
In the document about Android Setup, there is a section about config for appAuthRedirectScheme as following:

To capture the authorization redirect, add the following property to the defaultConfig in android/app/build.gradle:

android {
  defaultConfig {
    manifestPlaceholders = [
      appAuthRedirectScheme: 'io.identityserver.demo'
    ]
  }
}

My question is when I want to auth with my youtube account, what is the config for appAuthRedirectScheme ? it should not be 'io.identityserver.demo', right?

Thanks

**Comment by kadikraman** [comment]
Hi @idoor88 - following the guide from [here](https://developers.google.com/youtube/v3/guides/auth/installed-apps), my config looks like this:

```
const config =  {
  redirectUrl: 'com.myapp:oauth',
  clientId: '<client-id>',
  scopes: ['https://www.googleapis.com/auth/youtube'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenEndpoint: 'https://oauth2.googleapis.com/token',
  },
};
```

My redirect url is `com.myapp:oauth`, so the `appAuthRedirectScheme` will be `com.myapp`
