### ISSUE TITLE
Please copy the code, switch to your application and paste there

### ISSUE THREAD

**Issue by idoor88** [FormidableLabs/react-native-app-auth#409]
I installed and linked the react-native-app-auth library and created the auth function in my react app for android, when I tried to auth, on my android phone, it first showed up my gmails for me to choose, after I selected the right gmail account for my youtube project, It showed this error:
 Sign In
Please copy the code, switch to your application and paste there: <some code> with a copy button.

So what does this mean? how to switch my my application on my phone? where to copy the code?

This is my auth function:
`

     const config = {

            issuer: 'https://accounts.google.com',

            clientId: 'my client Id here',

            redirectUrl: 'urn:ietf:wg:oauth:2.0:oob', // got this from my console account

            scopes: ['https://www.googleapis.com/auth/youtube.readonly']

         };

         try {

              const result = await authorize(config);

              console.log("auth result: ",result);

          } catch (error) {

            console.log("auth error: ", error);

          }

`

## Environment
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 32.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-cn-richtext-editor: 1.0.33
    react-native-git-upgrade: 0.2.7

**Comment by kadikraman** [comment]
Hi 👋 - looks like a problem with the redirect uri. I hope my comment on [this issue](https://github.com/FormidableLabs/react-native-app-auth/issues/408) helps resolve this.
