### ISSUE TITLE
unable to redirect for oauth2 authentication, if implement token end point in server, url scheme not resume activity in ios 10

### ISSUE THREAD

**Issue by sabaakmal023** [FormidableLabs/react-native-app-auth#410]
## Issue

---

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?**

**Comment by kadikraman** [comment]
Hi 👋 - this issue does not have enough detail for me to help you. If the problem persists, please open an issue with detailed steps to reproduce coupled with the library, react native and device versions.
