### ISSUE TITLE
Fitbit not revoke (ios)

### ISSUE THREAD

**Issue by lovetrivedi** [FormidableLabs/react-native-app-auth#423]
## Fitbit not revoke

i am not able to revoke fitbit

---

## IOS

getting 
"{"errors":[{"errorType":"invalid_client","message":"Client id invalid. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."}],"success":false}"

![image](https://user-images.githubusercontent.com/5120795/70531938-fdba6500-1b7b-11ea-899e-1807bf5376a0.png)

here is my code :

![image](https://user-images.githubusercontent.com/5120795/70532089-496d0e80-1b7c-11ea-836c-19fa5389f4db.png)

**Comment by kadikraman** [comment]
Hi @lovetrivedi - looks like Fitbit needs a basic auth header for [revoke](https://dev.fitbit.com/build/reference/web-api/oauth2/#revoking-tokens). This has been recently added, but needs a small tweak to work with Fitbit correctly.

The new revoke config will be:

```js
const result = await revoke(config, {
  tokenToRevoke: authState.accessToken,
  sendClientId: true,
  includeBasicAuth: true
});
```
