### ISSUE TITLE
documentation to setup support for iOS 10 and below

### ISSUE THREAD

**Issue by Ildorado** [FormidableLabs/react-native-app-auth#424]
## Documentation Feedback

It's said in Documentation that to support iOS 10 and below you need to insert the following code : 
```
(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
 }
```
but actually you need to insert "-"(without quotes)  before (BOOL) for it to actually work, like this:
``` 
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
}
```
Probably it's self-evident for most of the people, but for people like me who were introduced to iOS development only due to react-native it can become cause of many frustrations.

**Comment by richardli123** [comment]
Hi, in my initial appdelegate.m file it has:

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

Did you end up replacing the whole thing with the code you posted above or did you have to tweak it a little bit. Any help would be appreciated. thank you.

**Comment by Ildorado** [comment]
As far as I know you should add code I posted atop of your code.I have no experience with ObjC whatsoever so I recommend to try and build code in XCode so it would show mistakes.

**Comment by kadikraman** [comment]
Thanks @Ildorado - great point! I'll update the docs.
