### ISSUE TITLE
Error when init with ejected expo

### ISSUE THREAD

**Issue by MartinMasek** [FormidableLabs/react-native-app-auth#425]
## Issue

Hi, thank you for the library, it makes auth process easier. I've tested it with react native and everything works. However, when I use expo and eject (= I create new app using 'expo init MyProject' command). I'm not able to make it work. I get stuck on the first step which is modifying the AppDelegate which looks different than the one in the example. When I somehow modified the delegate and run the project, I got error RNAppAuth.authorize is null.

Do you think it is possible to post steps how to make it work with bare Expo flow? I think it should be fairly easy for somebody who knows the library and already knows the react-native init flow but I'm just not able to fix it myself.

---

## Environment

* **Your Identity Provider**:  Azure
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?**: Yes

**Comment by kadikraman** [comment]
Hey 👋 you could try to use https://docs.expo.io/versions/latest/sdk/app-auth/

It's essentially a fork of this library, so most of the functionality and the api is the same

**Comment by kadikraman** [comment]
Hi 👋 - looks like there's was bug in the latest expo template which breaks auto discovery when ejecting. It will be [fixed](https://github.com/expo/expo/issues/6689) in future releases, I think. Until then, the following worked for me:

```
expo init MyApp (basic template)
cd MyApp
yarn eject (basic template)
yarn add react-native-app-auth@next
```

Add [these changes](https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7#diff-31ecd6988b850d2c631f493810a85bb4) to `/ios/Podfile` and then install pods with autodiscovery.

```
cd ios
pod install
```

You can verify that the dependencies were added correctly by inspecting the autogenerated `ios/Podfile.lock` and ensuring that it includes the following lines:

```
- react-native-app-auth (5.0.0-rc3):
  - AppAuth (= 1.2.0)
  - React
```

And finally apply the necessary changes to `ios/AppDelegat.h`. Mine ended up looking like this:

```
#import <UIKit/UIKit.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
#import <React/RCTBridgeDelegate.h>
#import <UMCore/UMAppDelegateWrapper.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : UMAppDelegateWrapper <RCTBridgeDelegate, RNAppAuthAuthorizationFlowManager>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;
@property (nonatomic, strong) UIWindow *window;
@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end
```

Hope this helps.
