### ISSUE TITLE
Allow opening private authentication web sessions to avoid iOS consent dialog box

### ISSUE THREAD

**Issue by butimo** [FormidableLabs/react-native-app-auth#428]
Using ASWebAuthenticationSession will automatically present a mandatory dialog box asking the user to give explicit consent for accessing the website’s data. This consent screen shows product and domain name. Our customers are always irritated, what this will mean. New customers also immediately leave the app. Because there is no way to describe that the data is not shared with 3rd parties. iOS 13 may omit the dialog by configuring ASWebAuthenticationSession for a private session using the new prefersEphemeralWebBrowserSession parameter, which needs to be set before start is called.

Would be great to have a chance to configure this parameter as well. Should happen somewhere between line 102 to 118

https://github.com/FormidableLabs/react-native-app-auth/blob/a1c713ec389404981c0c6db1d041b954e902fa87/Example/iOSCarthageExample/ios/Carthage/Checkouts/AppAuth-iOS/Source/iOS/OIDExternalUserAgentIOS.m#L102

**Comment by HolySamosa** [comment]
Any way to work around this at present?  Just integrated 'react-native-app-auth' into our project,  but unfortunately this pop-up box will be a deal-killer for us.

Thanks!

**Comment by jpdriver** [comment]
hey @butimo -- thanks for opening this issue.

as i understand it, i don't think there is any way around the Permissions dialog box -- even through using `prefersEphemeralWebBrowserSession`.

this flag only controls whether or not cookies and browsing data will be shared between the Authentication session and a user's normal browser sessions -- like opening a normal Safari tab vs. a Private Safari tab..

you can -- in theory -- leverage `prefersEphemeralWebBrowserSession` if it is something you want; but currently it would involve patching the underlying AppAuth SDK as `OIDExternalUserAgentIOS` does not directly allow support for it. you could do this using `post_install` hook in your Podfile as mentioned [here](https://stackoverflow.com/questions/16821838/how-to-patch-a-library-imported-with-cocoapods)

but as far as i know, the Permissions dialog box is always presented and controlled by iOS itself any time you are accessing content or passing data between apps; even with that extra flag passed to your `ASWebAuthenticationSession`

sorry about that!

**Comment by dzelemba** [comment]
@jpdriver : are you sure that setting `prefersEphemeralWebBrowserSession: true` doesn't remove the iOS consent box? Was just reading https://developer.okta.com/blog/2022/01/13/mobile-sso which is fairly recent and from a reputable source.

**Comment by jdnichollsc** [comment]
> If this option is set to true, ASWebAuthenticationSession does not show the prompt above, and as a consequence, it does not share cookies with Safari.

@dzelemba did you read the article?

**Comment by dzelemba** [comment]
@jpdriver : I received an email notification of your response, but I don't seem to see it here which is weird.. but let me respond anyways:

I think my last message maybe didn't have enough context, so let me back up and explain my understanding :) apologies if I'm missing something obvious!

Based on https://developer.okta.com/blog/2022/01/13/mobile-sso my understanding is that if you use `ASWebAuthenticationSession` with `prefersEphemeralWebBrowserSession: true` it will no longer show the consent pop-up, which is what the title of this ticket seems to be about. This comes at the cost of not being able to share cookies, but that is OK for some use cases. (e.g. our use case is just doing sign-in for our own application which happens to use a 3rd party identity provider behind the scenes which requires OIDC). So having this library expose that option would be quite useful for us!

**Comment by bentrombley** [comment]
For anyone trying to remove the iOS warning, this worked for me using the [preferEphemeralSession](https://docs.expo.dev/versions/latest/sdk/webbrowser/#authsessionopenoptions):

```js
      const authorizeResult = await authRequest.promptAsync(discovery, {
        useProxy: false, // prevent redirect using expo.dev
        preferEphemeralSession: true, // avoid iOS warning about using "X" to login
      });
```

As stated above, this won't work if you need SSO support and should have no effect on Android.
