### ISSUE TITLE
API_UNAVAILABLE(macCatalyst) while build iOS project.

### ISSUE THREAD

**Issue by nainishmodi** [FormidableLabs/react-native-app-auth#430]
I have updated the react native version and react-native-app-auth lib as well.

**My package.json be like**
![Snip20200106_1](https://user-images.githubusercontent.com/17999172/71795458-40cd0280-306c-11ea-83a6-b3b5065a94f2.png)

**My pod file**
![Snip20200106_3](https://user-images.githubusercontent.com/17999172/71795507-88ec2500-306c-11ea-92a3-fe14f1439013.png)

**My Xcode version is 10.1 (10B61)**

**When I build the project in iOS I got this error.** 

![Snip20200106_4](https://user-images.githubusercontent.com/17999172/71795631-221b3b80-306d-11ea-8e81-511a3e991dd5.png)

![Snip20200106_5](https://user-images.githubusercontent.com/17999172/71795645-3101ee00-306d-11ea-919e-bb0bcaf355fa.png)

**Before upgrading the react native and auth lib it was working fine and also I have updated cocoapods.**

![Snip20200106_9](https://user-images.githubusercontent.com/17999172/71796329-23019c80-3070-11ea-895c-d98786603ba4.png)

Any help would be greatly appreciated.

**Comment by kadikraman** [comment]
Hi 👋 - looks like a version mismatch for sure.

For one, `react-native-app-auth@4.4.0` is not compatible to `AppAuth@1.3`

Can you upgrade to `react-native@0.60+`? In this case you could install `react-native-app-auth@rc3`

**Comment by nainishmodi** [comment]
Yes! I have upgraded the react-native version to **0.61.5** and auth by **5.0.0-rc3** and it is working fine in both the platform. Thanks!

**Comment by kadikraman** [comment]
Awesome! I've actually just released `5.0.0-rc4` btw if you'd like to use the latest. Planning to release `v5` later in the week 🤞
