### ISSUE TITLE
Getting network error for keycloak authentication

### ISSUE THREAD

**Issue by rahulcs1989** [FormidableLabs/react-native-app-auth#431]
## Issue
I am getting network error while using keycloak credentials. 
I did the following steps.
 const config = {
      issuer: 'https://myauthurl.com.my/auth',
      clientId: 'MyClientId',
      redirectUrl: 'my.com.test.app:/callback',
      scopes: ['openid', 'profile']
    };

In AndroidManifest,

 <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="my.com.test.app"/>
</intent-filter>
and 
in Build gradle I added  manifestPlaceholders = [
            appAuthRedirectScheme: 'my.com.test.app'
        ]
---

## Environment

* **Your Identity Provider**: `Keycloak`
* **Platform that you're experiencing the issue on**: Android`
* **Are you using Expo?** No

Any help is appreciated.

**Comment by kadikraman** [comment]
Hi 👋 - it could be a lot of things, but I'd check the issuer.

Does https://myauthurl.com.my/auth/.well-known/openid-configuration show you a discovery document similar to https://demo.identityserver.io/.well-known/openid-configuration? If not, then your issuer is incorrect.

**Comment by rahulcs1989** [comment]
Hi, thank you so much for your quick reply and you are right. The issuer was incorrect. The keycloak server is handled by my client and he gave us the wrong info. Thanks again.
