### ISSUE TITLE
OpenID Connect settings

### ISSUE THREAD

**Issue by ThomasLarge** [FormidableLabs/react-native-app-auth#442]
## Issue

When trying to get the token I need to pass a code from the authorize method but I can't see a way to do this. I'm trying this add a OpenID Connect provider to this package but it's not going too well, I have set up the following:

```js
export const config = {
    issuer: Config.BASE_URL,
    clientId: Config.CLIENT_ID,
    redirectUrl: Config.APP_REDIRECT_URL,
    scopes: [
      'openid',
      'profile',
      'email',
      'phone',
      'profile_extended',
};

AppAuth.authorize(config)

```
I need to also send `response_type: code` when authorizing the user

When asking for the token I need to send the following: 

```js
client_assertion,
client_assertion_type,
redirect_uri,
code,
grant_type
```
In the current docs I can't see anyway to do this, I have tried to use `additionalParameters` but this doesn't change my outcome.

**Comment by kadikraman** [comment]
Hi 👋 - the library will handle all the auth related url parameters, so `redirect_uri` `code` and `grant_type` will be added automatically. The rest should be added to `additionalParameters`.

**Comment by ThomasLarge** [comment]
@kadikraman how does it know the type I need? 

The error that comes back is `Non-200 HTTP response (500) making token request to MY_URL` the only time this is a 500 is when the params are missing?

**Comment by kadikraman** [comment]
Which IDP are you using? Is there any way for me to check this locally?

**Comment by ThomasLarge** [comment]
@kadikraman unfortunately I can't say what one is it is but it follows the rules of OpenId Connect

There is no way to check locally as I don't own the servers

**Comment by tindn** [comment]
@ThomasLarge you might be able to debug this by inspecting the URL for the authorize request. For iOS, you can put a break point on [this line](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthorizationRequest.m#L338) in the `OIDAuthorizationRequest.m` file in Xcode.

**Comment by pke** [comment]
Should we maybe add a logging option so that the request URI is printed to the console log?

**Comment by pke** [comment]
@ThomasLarge did you manage to solve the issue somehow?

**Comment by ThomasLarge** [comment]
@pke The way I got around this was by using `skipCodeExchange` I had to use this as we needed to manually sign

**Comment by liatnetach** [comment]
@ThomasLarge I need to do it also (to split the flow) but when I send the {res.authorizationCode} to my server so they can exchange the code for token - they get unauthorized_client error
did it happen to you as well?

**Comment by ThomasLarge** [comment]
@liatnetach it's hard to look into without seeing your code but I did the following:

```js
const { authorizationCode, state } = await AppAuth.authorize(config);
```

I would confirm `authorizationCode` has a value you are expecting and maybe check your server side code?

**Comment by liatnetach** [comment]
@ThomasLarge thanks for the quick reply !
I took those parameters as well.
did you exchange the code for token from the app itself or from server?

*If im removing the skipCodeExchange from the config file the authorize function finish successfully so I don't get it what is the difference
