### ISSUE TITLE
authorize never resolves on iOS

### ISSUE THREAD

**Issue by FrankFundel** [FormidableLabs/react-native-app-auth#451]
## Issue
`var result = await authorize(config);
console.log(result);`

Does not show any result because authorize never resolves. On Android it works with my config, but I still think this has to be an issue with the redirectUrl or URL Scheme. Typing in the redirectUrl in the browser opens the App.

---

## Environment

* **Your Identity Provider**: `Spotify`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo? No**

**Comment by FrankFundel** [comment]
No Errors. Config is:
`const config = {
    clientId: '***',
    clientSecret: '***',
    redirectUrl: 'soundsquad://callback',
    scopes: ["playlist-read-private"],
    serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.spotify.com/authorize',
        tokenEndpoint: 'https://accounts.spotify.com/api/token'
    }
}`

therefore URL Scheme is:
URL Identifier: com.hadros.soundsquad (same as bundle ID)
URL Scheme: soundsquad

**Comment by kadikraman** [comment]
Hi @FrankFundel - finally got this to work. You need to use one `/` instead of two in the redirect uri.

So:
`appauthexample:/oauth` works
`appauthexample://oauth` does not work

**Comment by FrankFundel** [comment]
Note: You have to create a second Redirect URI on https://developer.spotify.com/dashboard with only one `/` and in takes like 10 minutes to update.

**Comment by npaul2173** [comment]
> Hi @FrankFundel - finally got this to work. You need to use one `/` instead of two in the redirect uri.
> 
> So:
> `appauthexample:/oauth` works
> `appauthexample://oauth` does not work

This did not help at all. 
Please help because i am getting an error in IOS.
![Screenshot 2020-02-21 at 12 52 05 PM](https://user-images.githubusercontent.com/41561899/75131802-95027380-56fa-11ea-89aa-a4170938471b.png)
