### ISSUE TITLE
Implicit flow is supported?

### ISSUE THREAD

**Issue by carloslibardo** [FormidableLabs/react-native-app-auth#452]
## Issue

Hello, i'm trying to implement implicit flow login in my app, but i'm getting **invalid grant type for client** error, reading the AppAuth-iOS and AppAuth-Android lib, it seemed to me that can't use this flow with this lib.

In the DB config the only grant type allowed is implicit then i think that's why i'm getting this error on trying to make authorize call.

This is my config: 
```

const config: AuthConfiguration = {
    issuer: ISSUER,
    clientId: CLIENT_ID,
    redirectUrl: http://localhost/,
    additionalParameters: {},
    scopes: SCOPE,
    useNonce: true
    }
}

```
Can someone help me pls?

---

## Environment

* **Your Identity Provider**: IdentifyServer4
* **Platform that you're experiencing the issue on**: both
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
@carloslibardo as you mentioned the library `AppAuth-iOS/Android` does not support the implicit auth flow.  In general, the implicit flow is discouraged for native apps. It's now even considered legacy for JS web apps - closing this out.
