### ISSUE TITLE
What to do if provider requires redirectUrl to be `https`?

### ISSUE THREAD

**Issue by pie6k** [FormidableLabs/react-native-app-auth#453]
I'm trying to use Wunderlist provider.

It requires my redirect url to be website url (it does not allow app schema to be there)

So what I tried to do was creating my api endpoint `/api/return/oauth/wunderlist` that simply redirects back to the app with the same parameters.

And I configured auth so

```ts
const result = await authorize({
        clientId: WUNDERLIST_CLIENT_ID,
        redirectUrl: `https://myapp.com/api/return/oauth/wunderlist`,
        scopes: [],
        serviceConfiguration: {
          authorizationEndpoint: `https://www.wunderlist.com/oauth/authorize`,
          tokenEndpoint: `https://myapp.com/api/oauth/wunderlist/`,
          // registrationEndpoint
        },
      });
```

My `return` node.js handler is simply

```ts
export const returnToAppHandler: RequestHandler = async (req, res) => {
  const route = req.params[""];
  const queryParams = req.query;

  const serializedQueryParams = serializeQueryParams(queryParams);

  const appTarget = `myapp://${route}?${serializedQueryParams}`;

  res.redirect(302, appTarget);
};
```

So when I start auth flow it seems to work, then it redirects to my return to app api, but then auth window closes and nothing happens (no error, no result)

It seems like auth is still waiting for the in-app url.

**Comment by ryanmendoza** [comment]
I *think* you should be using universal links to accomplish this. Your node app uri isn't the authority that the app initially sent an auth request to, and that may be the problem. You could use your node app to host the Apple app site association file.

iOS: https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content
Android: https://developer.android.com/training/app-links/

**Comment by irishdan** [comment]
Did you ever figure out what the issue was? I have a similar issue with the cronofy API

**Comment by kadikraman** [comment]
You could try it by adding the following to your `AppDelegate.m` under `continueUserActivity`


```
if ([userActivity.activityType isEqualToString:NSUserActivityTypeBrowsingWeb]) {
  if (self.authorizationFlowManagerDelegate) {
    BOOL resumableAuth = [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:userActivity.webpageURL];
    if (resumableAuth) {
      return YES;
    }
  }
}
```

**Comment by xXZang3tsuXx** [comment]
For android, if the redirect URI is HTTPS based schema ```android/app/src/main/AndroidManifest.xml``` has to be modified. 

An example is given in the [openid/AppAuth-Android](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect) library.

```bash
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.example">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="https"
                  android:host="com.example"
                  android:path="/oauthredirect"/>
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

**Comment by pke** [comment]
running into the same problem when the only allowed `redirectUrl` is "https://app.example.com/retur" then the safari will try to navigate to this (non-existing) URL.

```objectivec
- (BOOL) application: (UIApplication *)application
             openURL: (NSURL *)url
             options: (NSDictionary<UIApplicationOpenURLOptionsKey, id> *) options
{
  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
  //return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL) application: (UIApplication *) application
continueUserActivity: (nonnull NSUserActivity *)userActivity
  restorationHandler: (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  if ([userActivity.activityType isEqualToString:NSUserActivityTypeBrowsingWeb]) {
    if (self.authorizationFlowManagerDelegate) {
      BOOL resumableAuth = [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:userActivity.webpageURL];
      if (resumableAuth) {
        return YES;
      }
    }
  }
  return [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

```

However, the webview stays open saying "Safari cannot open the page because the server cannot be found"

**Comment by maxzinovev** [comment]
@pke Thanks! it worked for me

**Comment by Jay-A-McBee** [comment]
This can be supported on Android by updating the manifest as @Pasi-D illustrated. 

On iOS this is [an existing issue](https://github.com/openid/AppAuth-iOS/issues/232) in the backing library `AppAuth-ios`. These providers that require `https` protocol for the redirect url have omitted implementation of a vital part of the OAuth 2 spec for [native app support](https://datatracker.ietf.org/doc/html/rfc8252#appendix-A).

See this [comment](https://github.com/FormidableLabs/react-native-app-auth/issues/200#issuecomment-431285163) and this workaround [to use a fork of the `AppAuth-ios` lib](https://github.com/openid/AppAuth-iOS/issues/232#issuecomment-387216252).

**Comment by JigarBhanushali10** [comment]
adding new activity as @Pasi-D suggested worked for me
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
        
 but normal the deep linking stopped working. can you please help me with this issue?
