### ISSUE TITLE
Error Message Documentation

### ISSUE THREAD

**Issue by Collin3** [FormidableLabs/react-native-app-auth#454]
## Documentation Feedback

This is more of a question than anything. The new [Error Messages](https://github.com/FormidableLabs/react-native-app-auth#error-messages) section is super helpful, but I was curious where some of the messages come from as well. For example on Android, when you close the authorization login WebView, the message is `User cancelled flow`. I couldn't find any references to that in the code anywhere. If someone could point me to where those error messages come from, I'd gladly contribute some documentation to spell that all out. 

Context for wanting the message is because I don't want to show an error alert if I get an error code of `authentication_error` because someone closed the login WebView. 

Thanks!

**Comment by Collin3** [comment]
And just after creating this I stumbled upon the source of those. Looks like they come from the underlying [AppAuth-Android](https://github.com/openid/AppAuth-Android/blob/1a47f749ea5300ec17454ce05b804c9578018b95/library/java/net/openid/appauth/AuthorizationException.java#L165) and [AppAuth-iOS](https://github.com/openid/AppAuth-iOS/blob/5d1d8ede8c7ff221973838a8ca2ca50901d7c39e/Source/iOS/OIDExternalUserAgentIOS.m#L143) SDKs. 

I'm guessing since the messages are sourced from those native SDKs it probably doesn't make sense to also add documentation here.

**Comment by roni-castro** [comment]
Is there a better way to handle this error message than: `if(error !== 'User cancelled flow') { }`
I see that the error code `authentication_failed` is used when you cancel the permission or closes the webview.
Both action below generates `authentication_failed`, which other error generates the code `authentication_failed`?
<img width="204" alt="Captura de Tela 2020-09-30 às 11 12 54" src="https://user-images.githubusercontent.com/24610813/94696994-0c8e2600-030e-11eb-9544-ff3f34e9ce98.png">

<img width="416" alt="Captura de Tela 2020-09-30 às 11 12 35" src="https://user-images.githubusercontent.com/24610813/94696984-09933580-030e-11eb-82fc-da56b40938ff.png">
