### ISSUE TITLE
The authorize promise is not rejected after locking the device while iOS consent dialog box is visible

### ISSUE THREAD

**Issue by AlgirdasVZ** [FormidableLabs/react-native-app-auth#458]
## Issue

Hi!

These are the steps to recreate the issue:

1. Call the react-native-app-auth method "authorize" on any iOS device
2. The iOS consent alert modal is then presented for the user before opening the browser (expected behaviour)
3. Lock your device with the physical lock button while the consent alert modal is visible
4. Unlock your device
5. Observe that the consent alert modal is gone, but the "authorize" promise is neither rejected, nor resolved.

The authorization flow cannot be continued without confirming the consent dialog box, so in case the dialog is dismissed (I'm only able to achieve this by locking the device),  the "authorize" promise should be rejected (like it's rejected when "Cancel" is clicked in the constent dialog box).

**Comment by jpdriver** [comment]
hey @AlgirdasVZ 👋🏻 thanks for opening this issue

it depends on how exactly you're launching the `authorize` flow -- but even after a device sleep / wake the library should always be able to just re-launch the flow again.

this would present a new Alert modal and you should be able to continue as normal. For instance, in the Example app you can just press either of the login buttons again after unlocking the device to launch a new auth flow.

automatically dismissing Alerts on device sleep / wake is behaviour built in to iOS and is part of the app suspension process, so there isn't much we can do here.. for the record we will only reject the Promise in the event of a either a configuration issue or a user cancellation.

however if you really want this behaviour, you may be able to achieve it using React Native's [`AppState`](https://reactnative.dev/docs/appstate.html) and [`Alert`](https://reactnative.dev/docs/alert) APIs to show the same Error message as you would show for `authentication_failed` within a sleep / wake event listener.

hope that helps -- and please feel free to re-open if you are not able to re-launch consecutive auth requests

**Comment by aeirola** [comment]
We have been facing the same issue, and were a bit surprised that the library doesn't choose to handle the case where the screen is locked, but instead leaves the promise "floating". From a developer point of view I think it would indeed be better for the library to listen for application state changes, and reject the promise in the cases where the autorization request cannot be completed anymore.
