### ISSUE TITLE
No podspec found for `RNAppAuth`

### ISSUE THREAD

**Issue by adujoseph** [FormidableLabs/react-native-app-auth#463]
## Issue

on the master branch, when I cd into ios folder and run 'pod install', everything works fine but when I cd into other branches, and run 'pod install', it comes with the following error:

Fetching podspec for `RNAppAuth` from `../node_modules/react-native-app-auth`
[!] No podspec found for `RNAppAuth` in `../node_modules/react-native-app-auth`

---

## Environment
react-native-cli: 2.0.1
ios
 "react": "16.9.0",
 "react-native": "0.61.4",
 "react-native-app-auth": "^4.4.0",

* **Are you using Expo?**
No

**Comment by kadikraman** [comment]
Hi @adujoseph 👋 

`v4.4.0` isn't compatible with `react-native@0.61.4`. Please upgrade to `v5`.
