### ISSUE TITLE
Exception '<AppDelegate: 0x600001ce4120> does not conform to RNAppAuthAuthorizationFlowManager' was thrown while invoking authorize on target RNAppAuth with params.  (.  IOS  )

### ISSUE THREAD

**Issue by npaul2173** [FormidableLabs/react-native-app-auth#469]
## Issue

So i am using react-native-app-auth. version 4.4.0
While calling authorize() method i get a error only for IOS, not for android
![Screenshot 2020-02-21 at 12 52 05 PM](https://user-images.githubusercontent.com/41561899/75129223-f7a14280-56ed-11ea-8a29-8ec278fd12cc.png)

STEPS I TOOK
1) Got config  *** and save it to state
2) Pass as parameter for authorize(  this.state.configauth )

Config Structure looks like this
{

   "issuer”:”Link”,
   "clientId”:”I”d,
   "redirectUrl”:”Link”,
   "additionalParameters":{

      "nonce":"PauKyLe3456bhMgv/OJT7WSx6Q9RiBc/D3zDt4hxsHrkIMMDst0546bsg890dfsgaVVJVOjEniDP7h4e2uOokHUHMIwgk="
   },
   "scopes":[

      "openid",
      "d4a48c9efghfg-429b-9ab5-a4e2e2126079",
      "offline_access"
   ],
   "serviceConfiguration":{

      "authorizationEndpoint":"Link",
      "tokenEndpoint":"Link",
      "revocationEndpoint":"Link
   }
}

---

## Environment

dependencies

    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-app-auth": "^4.4.0",

OS -> MacOS Catalina,   Simulator-> iphone11Pro

**Comment by mjstelly** [comment]
bump! Hi Devs. This issue could really use some love and attention. It has me completely blocked. I've already missed one deadline because of it. Help is appreciated.

**Comment by cciissoooo** [comment]
To get around it, I commented out the following code in `node_modules/react-native-app-auth/ios/RNAppAuth.m` which throws the error.
```  
  if (![[appDelegate class] conformsToProtocol:@protocol(RNAppAuthAuthorizationFlowManager)]) {
        [NSException raise:@"RNAppAuth Missing protocol conformance"
                  format:@"%@ does not conform to RNAppAuthAuthorizationFlowManager", appDelegate];
 }
```
Dependencies:
```
"react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-app-auth": "^5.1.1",
```

**Comment by mjstelly** [comment]
Does it fix the issue, or just kick it down the road to be someone else’s problem?

**Comment by saachitech** [comment]
I was having similar issue, but later I realize that I did not update AppDelegate.h as per [documentation](https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate). Once I update AppDelegate.h that error is gone.

**Comment by mjstelly** [comment]
@saachitech what does that mean? Which AppDelegate? How did you update it? Your comment needs more detail, please.

**Comment by saachitech** [comment]
@mjstelly You can find AppDelegate.h in ios/[whatever_your_project_name] directory. You can open this file in xcode and update it according to the docs link I commented in my last comment. Hope this helps!

**Comment by mjstelly** [comment]
@saachitech That did the trick. I'm in your debt. Thanks!

**Comment by wilkhp29** [comment]
hi with me this code didn't work, my react is 0.62.2 the app goes and closes

**Comment by wilkhp29** [comment]
correct instead of using the documentation import uses this the rest can follow normal

`#import <react-native-app-auth / RNAppAuthAuthorizationFlowManager.h>`

**Comment by jpdriver** [comment]
[this comment](https://github.com/FormidableLabs/react-native-app-auth/issues/469#issuecomment-613333697) explains the correct fix for this.

thanks @saachitech 🤗

**Comment by MattSynaptic** [comment]
> @mjstelly You can find AppDelegate.h in ios/[whatever_your_project_name] directory. You can open this file in xcode and update it according to the docs link I commented in my last comment. Hope this helps!

The documentation wasn't working for me and then I realized I actually had to also add `#import <React/RCTLinkingManager.h>` to `AppDelegate.m` for it to work.

**Comment by nameisjayant** [comment]
If someone is getting this issue now , simply open **AppDelegate.h** file and paste the below code there
```
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"
@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager>

@property (nonatomic, weak) id<RNAppAuthAuthorizationFlowManagerDelegate> authorizationFlowManagerDelegate;

@end
```

**Comment by SeedyROM** [comment]
The documentation does note this being needed but doesn't really make it obvious that it's **REQUIRED** for it to work.

**Comment by arjunAbcd** [comment]
Getting this same error in New React native version 0.77.0. In this version AppDelegate is in Swift, no AppDelegate.h or AppDelegate.mm present

**Comment by pradeep-biits** [comment]
> Getting this same error in New React native version 0.77.0. In this version AppDelegate is in Swift, no AppDelegate.h or AppDelegate.mm present

Hai arjun 

did u get the solution to above error ??
i am also getting same delegate.swift error .

**Comment by MikeLikesCode** [comment]
Bumping, this error is happening in React native version 0.77.0 with their migration to using only a `AppDelegate.swift` file a fix on this would be appreciated

**Comment by MikeLikesCode** [comment]
@carbonrobot

**Comment by MaxGasta** [comment]
React native 0.78.1    how fix  ` AppDelegate.swift`    thanks

**Comment by Dawqss** [comment]
> React native 0.78.1 how fix ` AppDelegate.swift` thanks

Use this as reference, u need to add 
https://github.com/FormidableLabs/react-native-app-auth/blob/main/examples/demo/ios/Example/AppDelegate.swift

RNAppAuthAuthorizationFlowManager and update method 

```func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool```

to file src/ios/<yourprojectname>-Bridging-Header.h

add this line 
```#import <react-native-app-auth/RNAppAuthAuthorizationFlowManager.h>```
