### ISSUE TITLE
Cannot authorize Dropbox

### ISSUE THREAD

**Issue by haithngn** [FormidableLabs/react-native-app-auth#472]
## Issue

config:
```
const config = {
            clientId: '6fd2a_secret_is_love',
            clientSecret: '590j_secret_is_love',
            redirectUrl: com.haithngn.ios://oauth2',
            serviceConfiguration: {
                authorizationEndpoint: 'https://www.dropbox.com/oauth2/authorize',
                tokenEndpoint: `https://www.dropbox.com/oauth2/token`,
            },
            additionalParameters: {
                response_type: "token",
            },
            useNonce: false,
            usePKCE: false,
        };
```

after I clicked on the Allow button, the authorize of Dropbox will be closed but the console said:
```
State mismatch, expecting 9QeIUZw4Ema_s7VeJ3Sj8cbIIE0nrZ3sOwDWA950a8s but got (null) in authorization response <OIDAuthorizationResponse: 0x600003fabed0, authorizationCode: (null), state: "(null)", accessToken: "(null)", accessTokenExpirationDate: (null), tokenType: (null), idToken: "(null)", scope: "(null)", additionalParameters: {
}, request: <OIDAuthorizationRequest: 0x600003735c70, request: https://www.dropbox.com/oauth2/authorize?client_id=6fd2ab83flwdnxf&redirect_uri=org.reactjs.native.example.cloudplayer://oauth2&state=9QeIUZw4Ema_s7VeJ3Sj8cbIIE0nrZ3sOwDWA950a8s&response_type=code&response_type=token>>

```
It's seem duplicate the response_type and the re-direct to ios app was not be called.
Anybody succeed with Dropbox OAuth2.0 please give me some advices.
Thanks,
---

## Environment

* **Dropbox`
* **Platform that you're experiencing the issue on**: `iOS / Android`
* **Are you using Expo?**: No

**Comment by dylancom** [comment]
@haithngn were you able to solve it? Cause I am still getting this error...

**Comment by haithngn** [comment]
@dylancom, sorry for closing the issue without adding any solution.
Actually, I have to implement a native module to integrate with Dropbox Authentication.

**Comment by dylancom** [comment]
@haithngn I've noticed that this is a problem within the original package: https://github.com/openid/AppAuth-iOS/issues/445
As a workaround I'm currently using: react-native-inappbrowser-reborn to authenticate with Dropbox.
