### ISSUE TITLE
Coinbase invalid grant

### ISSUE THREAD

**Issue by maitham** [FormidableLabs/react-native-app-auth#477]
## Issue
I'm trying to implement the coinbase oauth flow using the example provided: 

```
const config =  {clientId: <COINBASE_CLIENT_ID>,
    clientSecret: <COINBASE_CLIENT_SECRET>,
    redirectUrl: '<app_name>://oauth',
    scopes: ['wallet:accounts:read'], 
    serviceConfiguration: {
      authorizationEndpoint: 'https://www.coinbase.com/oauth/authorize',
      tokenEndpoint: `https://api.coinbase.com/oauth/token`,
      revocationEndpoint: 'https://api.coinbase.com/oauth/revoke',
    },

```
I get the following error. 

`[Error: invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.]
`
## Environment

* **Your Identity Provider**: `coinbase`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** 
No

**Comment by maitham** [comment]
I had to include  `usePKCE: false`

**Comment by kadikraman** [comment]
Heads up - not using PKCE will make you vulnerable to a man in the middle attack when linking back to the app. This config option was added in order to support some older IDPs, but you should be aware of the risks. I think you should check your redirect uri, as Coinbase auth should definitely work with PKCE.

**Comment by maitham** [comment]
Oh interesting, the redirect uri is the one included above. Which is correct I believe, is there a way to actually see the requests that get send from app auth?

**Comment by maitham** [comment]
Still struggling with this, i've double checked my redirect uri as well as the url scheme both are correct. I still get invalid_grant. Does anyone have this currently working with coinbase?

**Comment by maitham** [comment]
Ended  up just having a custom oauth endpoint and doing the token exchange on the server. Way more secure and works.

**Comment by blankey1337** [comment]
Seeing this same behavior. Not sure what the correct redirectUrl should be, but usePKCE works. Redirecting to my server is not ideal in my case.
