### ISSUE TITLE
Azure AD B2C Error: *JSON deserialization error*

### ISSUE THREAD

**Issue by dardino** [FormidableLabs/react-native-app-auth#483]
## Issue

OAuth with Azure AD B2C seems not works:
---

## Environment

* **Your Identity Provider**: ` Azure AD B2C`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?** no

## Configuration:

```ts
{
	issuer: `${OAUTH_BASEURL}v2.0/`,
	clientId: OAUTH_CLIENT_ID,
	additionalParameters: {
		p: OAUTH_FLOWID,
	},
	serviceConfiguration: {
		authorizationEndpoint: `${OAUTH_BASEURL}/oauth2/v2.0/authorize`,
		tokenEndpoint: `${OAUTH_BASEURL}/oauth2/v2.0/token`,
		revocationEndpoint: `${OAUTH_BASEURL}/oauth2/v2.0/logout`,
	},
	redirectUrl: OAUTH_REDIRECT,
	scopes: ['openid'],
}
```

the login flow starts correctly but when the return url is called and the control returns to the app, i get this error:

`Error: JSON deserialization error`

no more data are logged.

the return urls contains something like this:
```text
?state=QTGw336ax1z99NHsnpqXPA&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..Qd0V8R495nU9VKOu.msp0JHhkMh0_caFNfAYRa5utlb5CnJ37Jd-u-3PRNWnDXp-t0rg09jrJgr1BjClnnmndCmjNNQyEt7gSAVeq-D9v5d2grcJC13zzZBLRXiM4y_nyQVsJRkYszbKAcm-p3HBr76lbzNVMkizhtAO8CqSWx3SJM9mA_EZprYyV8RehyvK5lKMvU9julJRIfH5hgtNBatwlvCNhLPkfDoBXm5kYgEA55do5nMD1VQfQa5p8vg8NULHNWYfS-0mf6beejhqcp2lBYzN3-w2SwYG1VxEAAtttXBCthCLMYg4ho4w_wvBOtpPpVprFBe8Oqw6Eb2Xlrw57HJV5_3Q-NWlNOmmc2uYoMMaeV0cu-Qgh_ZJkB9BQgzhBXPJooszoJmcoRYO1XMvdgm2L38V8npaG1pHeIb2qomvJ_sn7fcwOddqxQJ1QQrrEclYWhjQWPPAGweuVwhGSeDiYSHxrbYmnWvp2YfTZ7yxze4i8Ps7WTpH9n_E3rHetpXP6xjJjoeW_LfOCNvzjWW8BqfKJ_5sJta2WnDbEFlI9OnjzrkWwWL1yl0RGtsBvtxV5GxnyFpmzyuz29Ui5GK6vUjuCG8RLvn-f3WKrcdBzLKJy9BrvRQ.0Y0x9KGpUcTnnYtzuOogFg
```

**Comment by Jay-A-McBee** [comment]
:wave: Hi @dardino - we recently published a new example of an example Azure AD B2C config, and I noticed that it differs from your config in a couple ways. 

Your config is passing a `p` query string param that identifies the user flow. Is that also the case for the variable `OAUTH_BASEURL` in your serviceConfiguration urls?

Would you mind trying this url format in your `serviceConfiguration` - 
```https://<TENANT_NAME>.b2clogin.com/<TENANT_NAME>.onmicrosoft.com/<USER_FLOW_NAME>/oauth2/v2.0/authorize```. The only difference here is that we aren't appending the `p` query string param.

From your description, it sounds like something is clearly malformed in the token response request. I'd suggest setting breakpoints in Android Studio in the backing native library's code. 

`net.openid.appauth/TokenResponse` is the class. `fromResponseJson` would be the method in question. 

I'd also use flipper (https://fbflipper.com/) to inspect the network requests and ensure that a valid response is being returned from the OID provider.

Let me know if the url structure seems to have any impact 👍

**Comment by Jay-A-McBee** [comment]
@dardino Closing due to lack of engagement - feel free to open a new issue.
