### ISSUE TITLE
Disable Back on oauth login

### ISSUE THREAD

**Issue by qadirhusainee** [FormidableLabs/react-native-app-auth#489]
# Issue
The back button is not getting disabled in the login page opened in a browser.

Current behavior:
When the browser opens up with the issuer of Okta, there is a next and back button showing IP on iOS. After pressing on the back navigation button a loading screen appears.

Required behavior:
Back button should be disabled. Is there any way to hide/disable the back button.

<img width="339" alt="Okta_Login_SS" src="https://user-images.githubusercontent.com/15920551/77414613-5807ca80-6de7-11ea-832c-1af2ec3b6ce9.png">
![Okta_Login_ss1](https://user-images.githubusercontent.com/15920551/77415610-be411d00-6de8-11ea-9b7a-882646a4dc23.png)

---

## Environment
React-Native: 0.59.9
react-native-app-auth: 4.4.0

* **Your Identity Provider**: Okta
* **Platform that you're experiencing the issue on**:  iOS
* **Are you using Expo?** No

**Comment by jpdriver** [comment]
hi @qadirhusainee 

unfortunately this browser view is controlled by the underlying authentication API on iOS. it is not possible to disable the back button.

sorry about that!
