### ISSUE TITLE
Keycloak: app crash

### ISSUE THREAD

**Issue by vincentmarkcelino** [FormidableLabs/react-native-app-auth#490]
## Issue
having issue while invoking handleAuthorize
I have already done the react-native link react-native-app-auth. it adds the AppAuth in the pod and install the dependencies. 

```
const configs = {
    keycloak: {
        issuer: 'https://xxxxxx.com/auth/realms/xxxxx-realm',
        clientId: 'users',
        redirectUrl: 'com.xxxx.xxxxxx',
        scopes: ['openid', 'profile', 'email'],
        clientSecret: 'Some secret key',
    },
};
```
i invoke the function in useEffect
```
    useEffect(() => {
        handleAuthorize('keycloak');
    });
```

 ```
   const handleAuthorize = useCallback(
        async provider => {
            try {
                const config = configs[provider];
                const newAuthState = await authorize(config);
            } catch (error) {
                Alert.alert('Failed to log in', error.message);
            }
        },
        [authState]
    );
```

---

## Environment

* **Your Identity Provider**: keycloak
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** no

**Comment by muxbert** [comment]
I am having it crashing on Android but iOS works fine.
make sure you follow this:
` const config = {
    issuer: 'https://xxxxxx.com/auth/realms/xxxxx-realm',
    clientId: 'com.myapp.keyclockexample',   _//this is same as your bundleIdentfier from xcode_ 
    redirectUrl: 'com.myapp.keyclockexample:/callback',  _//as above but add /callback_
    scopes: ['openid', 'profile'],
    //dangerouslyAllowInsecureHttpRequests:true `//try adding this if not https`
  }`

for me, it crashes on Android when calling authorize function it might be related to the package name as well.

**Comment by Jay-A-McBee** [comment]
Closing due to lack of engagement - @vincentmarkcelino feel free to open a new issue.
