### ISSUE TITLE
null is not an object (evaluating 'RNAppAuth.authorize')

### ISSUE THREAD

**Issue by Texicitys** [FormidableLabs/react-native-app-auth#491]
## Issue

Hello !

I have done exactly what you wrote on the readme for installing `react-native-app-auth`.
I always got this message when I'm calling the `authorize` from `react-native-app-auth` method :

`[TypeError: null is not an object (evaluating 'RNAppAuth.authorize')]`

This is the same issue as [here](https://github.com/FormidableLabs/react-native-app-auth/issues/358) and I find no solution to solve it since 2 days, so I'm posting here because I don't know what more I can try. I hope you can help me.

Thank you very much...

---

## Environment

- "react-native": "^0.62.0", (also with 0.61.5)
- "react-native-app-auth": "^5.0.0-rc4" (idem with ^5.1.1, )
- "react": "16.9.0",
- Emulator Android
- I made init at the begining (I'm not using expo)

**Comment by jdaly13** [comment]
I'm Experiencing the same thing

**Comment by EvanBacon** [comment]
If you're using Expo (specifically the managed workflow) please see https://docs.expo.io/guides/authentication/ all others should ensure their native code is linked properly and natively rebuilt (`npx pod-install && npx react-native run-ios` or `npx react-native run-android`).

**Comment by Jay-A-McBee** [comment]
Closing due to lack of engagement/ no shared repro steps or configuration.
