### ISSUE TITLE
Skipping the authorize request initial popup

### ISSUE THREAD

**Issue by KristineTrona** [FormidableLabs/react-native-app-auth#492]
## Issue

Hello, just wondering if anyone has found a way to skip this pop up on ios?

<img width="378" alt="Screenshot 2020-03-30 at 15 13 21" src="https://user-images.githubusercontent.com/39855778/77916800-f25d8780-7299-11ea-8892-37e56a0d4e6a.png">

## Environment

* **Your Identity Provider**:   IdentityServer 4 
* **Platform that you're experiencing the issue on**:  iOS
* **Are you using Expo?** no

**Comment by thejaa** [comment]
@KristineTrona , did you found any solution?
I am also facing same issue.

**Comment by KristineTrona** [comment]
@thejaa no, sorry, I did not. We decided to keep the pop-up in the app.

**Comment by jpdriver** [comment]
hi @KristineTrona 

unfortunately you cannot skip this popup, as it is a requirement of the way the authentication API works on iOS.

sorry about that!

**Comment by traingethermarc** [comment]
Hi there :) - is there an option to change the text? So you could localize it atleast..... 
Thanks.

**Comment by fahadhaque007** [comment]
@marcibk did you find a way to change the text?

**Comment by fahadhaque007** [comment]
@jpdriver is there a way to update the text on the modal. Thanks
