### ISSUE TITLE
Multiple appAuthRedirectScheme 

### ISSUE THREAD

**Issue by zandercodes** [FormidableLabs/react-native-app-auth#495]
## Issue

How can I use multiple appAuthRedirectSchemes?

Facebook and Google has not the same scheme for callback to android.

---

## Environment

* **Your Identity Provider**: `oauth2`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** no

**Comment by jpdriver** [comment]
hey @zandercodes -- great question

to do this you will need to directly configure your AndroidManifest.xml with multiple intent-filters rather than using `appAuthRedirectSchemes` and manifestPlaceholders

see [this section](https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/README.md#capturing-the-authorization-redirect) in the AppAuth docs for more info

**Comment by edward-g1g2** [comment]
> ## Issue
> How can I use multiple appAuthRedirectSchemes?
> 
> Facebook and Google has not the same scheme for callback to android.
> 
> ## Environment
> * **Your Identity Provider**: `oauth2`
> * **Platform that you're experiencing the issue on**: `Android`
> * **Are you using Expo?** no

How did you solve this?

**Comment by zxctimhk** [comment]
> > ## Issue
> > How can I use multiple appAuthRedirectSchemes?
> > Facebook and Google has not the same scheme for callback to android.
> > ## Environment
> > 
> > * **Your Identity Provider**: `oauth2`
> > * **Platform that you're experiencing the issue on**: `Android`
> > * **Are you using Expo?** no
> 
> How did you solve this?

in your project android\app\src\main\AndroidManifest.xml
add this activity to replace
        `
        
        
        <activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace"
            android:exported="true" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="your_scheme1"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="your_scheme2"/>
            </intent-filter>
        </activity>`
Please remember to change your_scheme1 and your_scheme2

**Comment by IRahulOfficial** [comment]
@zxctimhk I replace net.openid.appauth.RedirectUriReceiverActivity with my package name but still it's not working

**Comment by zxctimhk** [comment]
> [@zxctimhk](https://github.com/zxctimhk) I replace net.openid.appauth.RedirectUriReceiverActivity with my package name but still it's not working

you mean 
`android:name="net.openid.appauth.RedirectUriReceiverActivity"`
 change to other?
if this ,do not change .

you need add  (in your project AndroidManifest.xml)
```
<activity
            android:name="net.openid.appauth.RedirectUriReceiverActivity"
            tools:node="replace"
            android:exported="true" >

```
to replace this lib (react-native-app-auth) "net.openid.appauth.RedirectUriReceiverActivity" activity.

see [this section](https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/README.md#capturing-the-authorization-redirect) in the AppAuth docs for more info
