### ISSUE TITLE
Grant_Type 'password' not supported

### ISSUE THREAD

**Issue by mvaneijk** [FormidableLabs/react-native-app-auth#496]
This library aims to implement the OAuth 2.0 spec which includes the "password" grant type, but it is not supported.

I can see why, because the `openid/AppAuth-Android` library does not support "password" grant. However, it would be nice if that was stated more clearly in the README.md file.

**Comment by kadikraman** [comment]
Thanks for taking the time to point this out. We currently only support the Authorization Code Flow with no immediate plans for supporting anything else, but I'll add a note to the Readme.

Side note - looks like the latest OAuth 2.0 Security Best Current Practice actually [disallows](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-3.4) the password grant entirely.
