### ISSUE TITLE
SFSafariViewController which is already presenting - iOS 10 issue

### ISSUE THREAD

**Issue by doo1** [FormidableLabs/react-native-app-auth#502]
## Issue

Hi,

Thank you for this excellent plugin! We still have a problem with iOS 10. When we invoke authorize, nothing happens. Xcode log the following message: 

_Warning: Attempt to present <SFSafariViewController: 0x7fc880b418a0>  on <UIViewController: 0x7fc880904ac0> which is already presenting <RCTModalHostViewController: 0x7fc87e648180>_

We have implemented the instructions available in the documentation about iOS 10 (CFBundleURLTypes) correctly. Under Android and iOS > 10. It works very well :-)

Thank you for your job and your support!

---

## Environment

* **React-Native**: `0.62.0`
* **react-native-app-auth**: `5.1.1`
* **Platform that you're experiencing the issue on**: `iOS 10`
* **Are you using Expo?** `No`

**Comment by doo1** [comment]
We found the solution -> the call to authorize was made from a modal window. However, iOS 10 does not support this!
Thanks again for your great plugin 😃 !

**Comment by NiranjanXamarin** [comment]
Attempt to present <SFSafariViewController: 0x7fe6e396f600> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fe6e1926e60> (from <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fe6e1926e60>) which is already presenting <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x7fe6e4920ad0>


I am getting this error while integrating OKTA login in forms application which is using prism.
