### ISSUE TITLE
Implement support for "state" parameter

### ISSUE THREAD

**Issue by josomers** [FormidableLabs/react-native-app-auth#504]
For the iOS version there is behind the scenes state a random state generator, as well as validation at the end of the requests to authorise users.

For the Android version "authRequestBuilder.setState("myStateVar")" is not implemented at all in RNAppAuthModule.

What are the reasons not to support this equally and having the ability to pass by a custom "state"?

**Comment by kadikraman** [comment]
Our goal is to have as much feature parity between iOS and Android as possible, so adding this to the android implementation would be a very welcome enhancement!
