### ISSUE TITLE
Google Play Blocker: Unsafe SSL TrustManager & HostnameVerifier Defined

### ISSUE THREAD

**Issue by subinkrishna** [FormidableLabs/react-native-app-auth#505]
## Issue

We did a DataTheorem scan of our app and it identified unsafe implementation of SSL TrustManager & HostnameVerifier

> The following Java or Kotlin classes defined within the App define  [a custom X509TrustManager](https://developer.android.com/reference/javax/net/ssl/X509TrustManager.html)  that does not validate SSL certificates: 
> 
> `com.rnappauth.utils.UnsafeConnectionBuilder$1`

> The following classes within the App define an [insecure HostnameVerifier](https://developer.android.com/reference/javax/net/ssl/HostnameVerifier.html#verify(java.lang.String,%20javax.net.ssl.SSLSession))) that disables SSL hostname validation:
> 
> `com.rnappauth.utils.UnsafeConnectionBuilder$2`

 [Google’s support page](https://support.google.com/faqs/answer/6346016) :
> “Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager.”

 [Google’s support page](https://support.google.com/faqs/answer/7188426) :
> “Beginning March 1, 2017, Google Play will block publishing of any new apps or updates that use an unsafe implementation of HostnameVerifier.”

As per the support page, regardless of whether we use these classes at runtime or not, apps can get blocked

---

## Environment

* **Your Identity Provider**: `internal`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?**: No

**Comment by kadikraman** [comment]
Thanks for bringing this up. The `UnsafeConnectionBuilder` is only used if you enable `dangerouslyAllowInsecureHttpRequests` on Android, and it is intended for local development without a valid SSL cert. It's never meant to be used in prod.

Can you think of a workaround for doing this without `UnsafeConnectionBuilder`?

**Comment by subinkrishna** [comment]
Sure, will do. Thanks for the reply.

**Comment by sriram-viswanathan** [comment]
@subinkrishna I am also facing the same issue. Did you find a work around for this issue, could you please share the details?

**Comment by nob3110** [comment]
If your production app doesn't use UnsafeConnection, I think you just need to change two lines ([# L28](https://github.com/FormidableLabs/react-native-app-auth/blob/580372daf92fab88f645b12b3ba3d9cf0f219fe8/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L28), [# L895](https://github.com/FormidableLabs/react-native-app-auth/blob/580372daf92fab88f645b12b3ba3d9cf0f219fe8/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L895)) in RNAppAuthModule.java.

This way is may a bit crude.
I used [patch-package](https://www.npmjs.com/package/patch-package) to manage the changes in this library with git.

```
//L28
// import com.rnappauth.utils.UnsafeConnectionBuilder; // ← comment out

//L895
if (allowInsecureConnections) {
    proxiedBuilder =DefaultConnectionBuilder.INSTANCE;  / ← like this
} else {
    proxiedBuilder = DefaultConnectionBuilder.INSTANCE;
}
```

**Comment by sriram-viswanathan** [comment]
Thanks for your response @nob3110. I have been using something similar to your suggestion for more than a year now. I had completely forgotten that I had posted in this thread. I should have updated here a long ago (my bad 😞 )
