### ISSUE TITLE
Need to create the file mentioned in redirect uri in client app?

### ISSUE THREAD

**Issue by 3dwesupport** [FormidableLabs/react-native-app-auth#506]
Hi,

I setup the react native environment today and am using this library for oauth authentication with my wordpress installation. All things are working fine until the point when the IDP sends back the authorization code. Although the code & state are generated, it doesn't redirect back to my client app. My question is - do I need to create the "**oauthredirect**" file somewhere in my client app? Please see below for the configuration I am using -

 itinkerdev: {
    issuer: 'https://dev.itinker.in',
    clientId: 'id_from_the_installation'
    redirectUrl: 'com.wp_itinker_dev://**oauthredirect**',
    additionalParameters: {},
    scopes: ['email'],

    serviceConfiguration: {
      authorizationEndpoint: 'https://dev.itinker.in/?oauth=authorize',
      tokenEndpoint: 'https://dev.itinker.in/oauth/token',
      revocationEndpoint: 'https://dev.itinker.in/oauth/destroy'
    }
  }

Thanks for the help.

**Comment by jpdriver** [comment]
hey @3dwesupport 

the `oauthredirect` is not a file you create -- it's just a URL that you app can consume that links back to the AppAuth library.

which platform are you using? have you added a matching entry for the redirect URL scheme to your `Info.plist` (for iOS) or the `appAuthRedirectScheme` in your `build.gradle` (for Android)?

**Comment by hemal-digiflux** [comment]
@3dwesupport Please update. I am getting the same issue and I have same confusion in mind.
Also, `oauthredirect` will be the same for all?

I am using below.
`
const config = {
    issuer: 'https://connect.squareup.com/oauth2/authorize',
    serviceConfiguration:{
        authorizationEndpoint:'https://connect.squareup.com/oauth2/authorize',
        tokenEndpoint:'https://connect.squareup.com/oauth2/token',
        revocationEndpoint:'https://connect.squareup.com/oauth2/revoke',
        registrationEndpoint:'',
    },
    clientId: 'xx-xxxxx-xxxx',
    redirectUrl: 'com.xxx.xxx:/callback',
    scopes : ['CUSTOMERS_WRITE', 'CUSTOMERS_READ']
};`

Info.plist
`<key>CFBundleURLTypes</key>
	<array>
	<dict>
		<key>CFBundleURLName</key>
		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
		<key>CFBundleURLSchemes</key>
		<array>
		<string>com.xxx.xxx</string>
		</array>
	</dict>
	</array>`

I am getting error as **Invalid value for redirect_url**

**Comment by kadikraman** [comment]
For iOS, it doesn't matter what the `redirectUrl` is really, it just has to be the same as what you configured with your Identity Provider.

**Comment by Jay-A-McBee** [comment]
:wave: hey @3dwesupport - closing due to lack of engagement. Sounds like a mis-configuration of the redirect url in your manifest file. Feel free to open a new issue.
