### ISSUE TITLE
[IOS] Issue with azure AD and office 365

### ISSUE THREAD

**Issue by prasanthsd** [FormidableLabs/react-native-app-auth#507]
## Issue

We have an app that read users calendar events. For this we get them to login with their Microsoft account and once they complete login we read the calendar events with the grapth API. This works fine for android in all cases. But with iOS here are the various cases:

1. With a regular Microsoft account and _**redirectUrl**_ configured as _**urn:ietf:wg:oauth:2.0:oob**_ it gives an error as:

```
Error: State mismatch, expecting c2HFATvdkTp_LnkdpelsztWB5aRZv-Y4cUUT_sQaO8o but got (null) in authorization response <OIDAuthorizationResponse: 0x60000250a490, authorizationCode: (null), state: "(null)", accessToken: "(null)", accessTokenExpirationDate: (null), tokenType: (null), idToken: "(null)", scope: "(null)", additionalParameters: {
}, request: <OIDAuthorizationRequest: 0x600002e256c0, request: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?prompt=select_account&nonce=Mlq6u7z6UKydGY2fZtHHItpjHaKnQHxJftyK4sIS5NM&response_type=code&code_challenge_method=S256&scope=openid%20offline_access%20profile%20User.Read%20Calendars.Read%20User.ReadBasic.All&code_challenge=xxxx&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=xxxx&state=c2HFATvdkTp_LnkdpelsztWB5aRZv-Y4cUUT_sQaO8o
``` 

2. With a regular Microsoft account and _**redirectUrl**_ configured as _**custom-scheme://auth**_ it works
3. With a Godaddy issues Office 365 account and _**redirectUrl**_ configured as _**urn:ietf:wg:oauth:2.0:oob**_ it works great
4. With a Godaddy issues Office 365 account and _**redirectUrl**_ configured as _**custom-scheme://auth**_ it does not work and no error responses.

Below is the config:
```
const config = {
  clientId: 'xxxx',
  redirectUrl: Platform.OS === 'ios' ? 'urn:ietf:wg:oauth:2.0:oob' :'custom-scheme://auth',
  scopes: [
    'openid',
    'offline_access',
    'profile',
    'User.Read',
    'Calendars.Read',
    'User.ReadBasic.All'
  ],
  additionalParameters: { prompt: 'select_account' },
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
  }
};
```

Any help would be appreciated which leads to a solution where it works with all types of accounts.

---

## Environment

* **Your Identity Provider**: `Azure` 
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** `No`

**Comment by bachlongkocanh** [comment]
I had the same issue. Have any solution?

**Comment by donovanrichardson** [comment]
I get this when encountering a consent screen. It the app opens a consent screen asking for a Microsoft account email, but then closes the screen immediately after the email is entered, without asking for a password.

**Comment by mattwoberts** [comment]
Hi,

Wondering if you got this working - I'm having similar issues now, although for me what happens is that the `authorize` call from RN doesn't return... so you go through the whole proceess of auth-ing with MS, and then you are sent back to the app but then nothing happens, and the console.log after the `authorize` doesn't execute.

One thing I spotted with your config -it doesn't look like you're setting the right redirectUrl, when you add the ios app to the azure config, it gives you a redirectUrl like this: `msauth.[BUNDLE_ID]://auth` - presumably you should be using that?

**Comment by Appkidd** [comment]
@mattwoberts Hey - I've got the exact same thing with nothing logging after `authorise`. Did you manage to resolve this? We're using the correct redirectUrl.

**Comment by mattwoberts** [comment]
Hi @Appkidd - yes I did get it working - for me it was a missing `/` that caused me all the pain - I was so annoyed about it that I made this pull request for the docs to emphasise it - fingers crossed that might be your issue too.

**Comment by Appkidd** [comment]
@mattwoberts Thanks a lot! That did it.

**Comment by Jay-A-McBee** [comment]
:wave: hey @prasanthsd it looks like your redirect url is also missing a trailing slash `/` - closing this out since there's been no response in a while. Feel free to create a new issue if adding a slack doesn't fix your issue.
