### ISSUE TITLE
How to handle http or https redirect uri response from OAuth server in Android?

### ISSUE THREAD

**Issue by peterlau0010** [FormidableLabs/react-native-app-auth#510]
## how to handle http/https redirect uri response from OAuth serve 

May I know how to handle http/https redirect uri response from OAuth server?

For example:
After auth
OAuth server return : https://com.auth:8090/auth/success/redirect?code=xxxxx&state=yyyy

Setting is below, can redirect back to app, but return **Intent must not be null** exception :

`build.gradle`

    defaultConfig {
        applicationId "com.reactnativeauthclient"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.auth'
        ]
    }

`AndroidManifest.xml`

```
<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
    <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="https"
              android:host="com.auth"
              android:path="/auth/success/redirect"/>
    </intent-filter>
</activity>
```

---

## Environment

* **Your Identity Provider**: `Customise Spring boot OAuth server`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by jpdriver** [comment]
hey @peterlau0010 

if your redirect uri includes a specific port number, you will need to include it as `android:port` within your data specification

more info can be found in the Android docs [here](https://developer.android.com/guide/topics/manifest/data-element)
