### ISSUE TITLE
@import RNAppAuth throws error, module not found.

### ISSUE THREAD

**Issue by bacancy-alokpatel** [FormidableLabs/react-native-app-auth#512]
## Issue

I've installed the library by,
`npm install react-native-app-auth --save`

then Doing 
`pod install`

When I import this in my AppDelegate.swift file, it throws module not found error. Doing import like this,

`@import RNAppAuth`

I tried linking the library using
`react-native link react-native-app-auth`
But no luck.

Also tried adding following line in Podfile,
`pod 'RNAppAuth', path => "../node_modules/react-native-app-auth/ios"`
or 
`pod 'RNAppAuth', path => "../node_modules/react-native-app-auth"`

Both throws Pod spec not found error. 

What's the way to fix this ?

**Comment by rhdeck** [comment]
Yes, instructions are not quite right. `import RNAppAuth` will not work. Remove that line, and  add a line to `swift-Bridging-Header.h` like so: 
```h
#import "RNAppAuthAuthorizationFlowManager.h" // <-- Add this header
```
I submitted a PR (#515) to fix the instructions
