### ISSUE TITLE
Authorize redirect to deep link doesn't work

### ISSUE THREAD

**Issue by daviddelucca** [FormidableLabs/react-native-app-auth#513]
My auth server responds the `authorize` call to a redirect like `myapp://login` and this lib is not opening the screen from `login` route.

Is this supported? I don't want to use a login view from IDP.

The `authorize()` calls my Auth Server and it responds with a redirect, the application open/close instant and go back to initial screen.
![Screen-Recording-2020-05-20-at-20 10 21](https://user-images.githubusercontent.com/5162985/82750692-216b1380-9d88-11ea-8e0f-8d632f2e746b.gif)

---

## Environment

* **Your Identity Provider**: `Ory Hydra`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
Hey! I think this is due to the credentials getting cached on Safari. If you add
```js
additionalParameters: {
  prompt: "login"
}
```
to your config, it will always prompt the user for credentials. Hope this helps!
