### ISSUE TITLE
ask: manifestPlaceholders for multiple login provider

### ISSUE THREAD

**Issue by brambang** [FormidableLabs/react-native-app-auth#520]
i use this for my google login, which is in example redirectUrl is MUST be com.googleusercontent.apps.
And in build.gradle we have to fill with same string value.

But im curious,
How if our apps want to provide many login option??
is it possible??
since manifestPlaceholders is string value.

**Comment by jpdriver** [comment]
hey @brambang -- great question

you can support multiple providers on Android; but to do so you will need to directly configure your AndroidManifest.xml with multiple intent-filters rather than using `manifestPlaceholders`

see [this section](https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/README.md#capturing-the-authorization-redirect) in the AppAuth docs for more info

**Comment by panktiszluck** [comment]
> hey @brambang -- great question
> 
> you can support multiple providers on Android; but to do so you will need to directly configure your AndroidManifest.xml with multiple intent-filters rather than using `manifestPlaceholders`
> 
> see [this section](https://github.com/openid/AppAuth-Android/blob/27b62d5da94023941db545b70036a742a52b7070/README.md#capturing-the-authorization-redirect) in the AppAuth docs for more info

I tried below code in my AndroidManifest.xml file as per the reference document, but still the redirection for google is not working as expected.

`<activity
        android:name="net.openid.appauth.RedirectUriReceiverActivity"
        tools:node="replace">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="myschema"
                  android:host="callback"/>
            <data android:scheme="com.googleusercontent.apps.xxxx678"
                android:host="/oauth2redirect"/>
        </intent-filter>
    </activity>`
