### ISSUE TITLE
Strava - Payload has been different in Android/IOS

### ISSUE THREAD

**Issue by ruanlinos** [FormidableLabs/react-native-app-auth#522]
## Issue

Hi everyone,
i have a very strange problem, basically i using Strava for authenticate in my app, and the response payload is different in Android and ios. I need the scope for request user activities, in ios ok!, but in android hes returns to me an Array empty. 
here comes the example:

**Config Options:**

`const config = {
      clientId: 'MYCLIENTID',
      clientSecret: 'MYCLIENTSECRET',
      redirectUrl:
        'com.MYAPP://oauthcallback',
      serviceConfiguration: {
        authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
        tokenEndpoint:
          'https://www.strava.com/oauth/token?client_id=MYCLIENTID&client_secret=MYCLIENTSECRET',
      },
      scopes: ['profile:read_all,activity:read_all'],
    };`

**IOS Payload**
```
{
   "accessToken":"1ce5c48f2b90cf0522a3a2df19f68098f71edf21",
   "accessTokenExpirationDate":"2020-06-25T18:10:06Z",
   "authorizeAdditionalParameters":{

   },
   "idToken":"",
   "refreshToken":"250f8ce8a419a2deb1b030bc09964fd10685d5ef",
   "scopes":[
      "read,activity:read_all,profile:read_all"
   ],
   "tokenAdditionalParameters":{
      "athlete":{
         "badge_type_id":1,
         "city":"Rio Do Sul",
         "country":"Brazil",
         "created_at":"2020-06-01T14:14:40Z",
         "firstname":"Ruan",
         "follower":null,
         "friend":null,
         "id":601219550,
         "lastname":"Linos Alves",
         "premium":true,
         "profile":"https://graph.facebook.com/2514021931958724/picture?height=256&width=256",
         "profile_medium":"https://graph.facebook.com/2514021931958724/picture?height=256&width=256",
         "resource_state":2,
         "sex":"M",
         "state":"Santa Catarina",
         "summit":true,
         "updated_at":"2020-06-01T20:19:58Z",
         "username":"ruan_linosalves"
      },
      "expires_at":1593108609
   },
   "tokenType":"Bearer"
}
```

**ANDROID Payload**

```
{
   "accessToken":"1ce5c48f2b90cf0522a3a2df19f68098f71edf21",
   "accessTokenExpirationDate":"2020-06-25T18:10:05Z",
   "authorizeAdditionalParameters":{

   },
   "idToken":null,
   "refreshToken":"250f8ce8a419a2deb1b030bc09964fd10685d5ef",
   "scopes":[

   ],
   "tokenAdditionalParameters":{
      "athlete":"{\"id\":60121955,\"username\":\"ruan_linosalves\",\"resource_state\":2,\"firstname\":\"Ruan\",\"lastname\":\"Linos Alves\",\"city\":\"Rio Do Sul\",\"state\":\"Santa Catarina\",\"country\":\"Brazil\",\"sex\":\"M\",\"premium\":true,\"summit\":true,\"created_at\":\"2020-06-01T14:14:40Z\",\"updated_at\":\"2020-06-01T20:19:58Z\",\"badge_type_id\":1,\"profile_medium\":\"https:\\/\\/graph.facebook.com\\/2514021931958724\\/picture?height=256&width=256\",\"profile\":\"https:\\/\\/graph.facebook.com\\/2514021931958724\\/picture?height=256&width=256\",\"friend\":null,\"follower\":null}",
      "expires_at":"15931086060"
   },
   "tokenType":"Bearer"
}
```
---

## Environment

* **Your Identity Provider**: `Strava`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?** `NO - Bare React Native v. 0.62.0`

**Comment by SEdilson** [comment]
Guys, is there any plan to solve this issue on the next release?

**Comment by kadikraman** [comment]
Yes! This should be resolved with https://github.com/FormidableLabs/react-native-app-auth/pull/509 and can be tested on [v6.0.0-rc1](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v6.0.0-rc1)
