### ISSUE TITLE
iOS app not receiving success callback, Government OAuth

### ISSUE THREAD

**Issue by bshyong** [FormidableLabs/react-native-app-auth#523]
## Issue

I am using this library to auth with a US Federal Government OAuth provider. Manually fetching an access token with Curl works, but using the library in the iOS app does not work. The issue seems to be that the app does not receive the authorization code so the request to the token endpoint fails.

Can anybody help figure out what the issue is? I'm not sure if there is something simple I'm missing or there is something deeper.

---

## Environment

* **Your Identity Provider**: OAuth2 compliant provider. US Department of Veteran Affairs
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?** No

**Comment by bshyong** [comment]
Further exploration shows that this issue is due to the authentication window retaining cookies.

In our auth server set up, after the browser window successfully completes an auth and the server redirects with the code, the next request to the token endpoint retains cookies that were picked up when the success callback happened.

**Comment by kadikraman** [comment]
The latest rc includes an option to skip the token exchange step. Perhaps you could try `v6.0.0-rc1` with `skipCodeExchange=true` and do the token exchange request in JavaScript?

**Comment by Jay-A-McBee** [comment]
:wave: hey @bshyong - closing this out due to lack of engagement. Feel free to open a new issue.
