### ISSUE TITLE
client secret is incorrect value in iOS, AuthorizationCodeWithProofKey

### ISSUE THREAD

**Issue by hdayakar** [FormidableLabs/react-native-app-auth#527]
I am using "AuthorizationCodeWithProofKey", provided correct config parameters to authorize(). It is working for android returning token, but same for iOS getting this error after successful credentials page.
Invalid_client: client_id or client_secret is missing or has an incorrect value.

Tried passing in additionalParameters object the client_secret also.

**Comment by Jay-A-McBee** [comment]
:wave: hey @hdayakar - I'm closing this issue due to lack of information and engagement. If this is still an issue, please provide the config you are using and the OAuth provider that you are targeting.
