### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by kadikraman** [FormidableLabs/react-native-app-auth#531]
We should add a contributing guide for new contributors to ease the barrier to entry

## This should include:

- how to set up the project for local development
- overview of any project-wide rules or principles
- example configurations
- (maybe) release guide

**Nice to have**: a short project intro video 👩‍💻

**Comment by deroke** [comment]
Have a look at https://github.com/FormidableLabs/react-native-app-auth/blob/main/.github/CONTRIBUTING.md

**Comment by robwalkerco** [comment]
Closing, as this appears to be resolved now
