### ISSUE TITLE
How to only get the authorization token and not doing the access token request.

### ISSUE THREAD

**Issue by Slapshot9** [FormidableLabs/react-native-app-auth#532]
## Documentation Feedback

On the note about client secrets you cite the AppAuth-Android documentation with "If client secrets must be used by the OAuth2 provider you are integrating with, we strongly recommend performing the code exchange step on your backend, where the client secret can be kept hidden."

But there is no example on how to just fetch the authorization token, so it can be send to the backend, which takes care of the token-request itself by using the client secret.

It seems, that AppAuth-Android offers to create those requests separately, but you only offer the whole flow without ever seeing the authorization token.
I confess I didn't check AppAuth-iOS for this separation yet.

I'm rarely new to react-native, but have far less experience in native app development, so I would love to use your library, but my project-manager insists on doing the token-request on the backend.

**Comment by tolgaarikan** [comment]
Hey, take a look at this PR:
https://github.com/FormidableLabs/react-native-app-auth/pull/466https://github.com/FormidableLabs/react-native-app-auth/pull/466

You can use the fork until it gets merged.

**Comment by Slapshot9** [comment]
Thank you, I will have a try.
