### ISSUE TITLE
Example project fails at npm install

### ISSUE THREAD

**Issue by faizann** [FormidableLabs/react-native-app-auth#533]
## Issue

When `npm install` is run in Example directory, it fails with error
```
npm ERR! code 1
npm ERR! Command failed: git checkout master
npm ERR! error: pathspec 'master' did not match any file(s) known to git.
npm ERR!
```

Tried this with latest master.

---

## Environment
MacOS

* **Your Identity Provider**: Not applicable but was going to use OKTA
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
Sorry about that! We renamed the `master` branch to `main` rcently and forgot to update the example app. This is fixed on the latest main branch.
