### ISSUE TITLE
PresentingViewController sometimes wrong?  Fix included

### ISSUE THREAD

**Issue by garrettm** [FormidableLabs/react-native-app-auth#534]
## Issue

First, I just wanna say thanks for the wonderful library.

I'm using this library with react-native-navigation, calling `authorize` while there's a view controller presented modally over the root view controller.  

Strangely, in this case, at line ~300 of RNAppAuth.m, `appDelegate.window.rootViewController.view` is not nil, but `appDelegate.window.rootViewController.view.window` is nil.  So `OIDExternalUserAgentIOS` gets initialized with a view controller whose view doesn't have a window.  This makes the `ASWebAuthenticationPresentationContextProviding` protocol method return nil, and iOS doesn't like that, so the whole thing fails.

I've tested a fix locally for this, at that same spot, which is pretty simple:
```
    UIViewController *presentingViewController = appDelegate.window.rootViewController.view.window ? appDelegate.window.rootViewController : appDelegate.window.rootViewController.presentedViewController;
    _currentSession = [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                   presentingViewController:presentingViewController
```

Everything is the same, we just check to make sure the thing we're passing has a window, and if not, fall back to passing in the `presentedViewController`.  This fixes the problem in my testing.  Would it be possible to get a dot release quickly with this fix?

---

## Environment

* **Your Identity Provider**: Microsoft
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
Hi @garrettm - thanks for creating this issue. Your reasoning makes sense to me! Would you like to create a PR for this yourself or would you prefer we do it?

**Comment by garrettm** [comment]
@kadikraman I'd prefer you just do it, if you don't mind, since there's a decent amount of overhead for me to fork + setup a PR etc.  But I'm happy to do it, if you want me to.

**Comment by kadikraman** [comment]
No worries, I've created a PR and verified it doesn't cause a regression - could you review?

**Comment by garrettm** [comment]
Looks good to me, thank you
