### ISSUE TITLE
Cannot get control back from web view to react native app in OAuth flow

### ISSUE THREAD

**Issue by rakeshwfg** [FormidableLabs/react-native-app-auth#535]
## Documentation Feedback

I'm trying to implement Google OAuth 2 signin using FormidableLab's react-native-app-auth library in my react native android application as shown below:

```
  googleLoginPressed = async () => {
    const config = {
      serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.google.com/o/oauth2/v2/auth', tokenEndpoint: 'https://accounts.google.com/o/oauth2/v2/auth', 
      },
      clientId: app_params.GOOGLE_CLIENT_ID, redirectUrl: 'https://<my_domain>/oauth/google',
      scopes: ['openid', 'profile', 'email'], additionalParameters: { 'response-type': 'code' },
    };
    try {
      const result = await authorize(config);
    } catch (error) {
      console.log(error);
    }
  }
```
This invokes a web view with Google's signin page and I could successfully authenticate myself. Google then correctly redirects to my oauth callback endpoint and populates the oauth code in the redirect url like it should. At this point, I expect react-native-app-auth to get the control back from the webview to application. Instead, the web view stays open at the redirect url page.

I have added necessary website association configuration under AndroidManifest.xml and the following code under MainActivity.java to check for getting the control back to application from the redirect url:

```
  @Override
  public void onNewIntent(Intent intent) { // this is not getting hit
    super.onNewIntent(intent);
    Uri appLinkData = intent.getData();

    if (appLinkData != null) {
      bar = appLinkData.getPath();
    }
  }
```
What I tried so far

I ensured my app can open Universal links. So website association must be working fine.
Also tried replicating the entire setup on iOS. Same result. The webview shows Google correctly redirecting to oauth endpoint but app fails to get control back.
How do I get control back from oauth web view to my react-native code?

https://stackoverflow.com/questions/63122087/cannot-get-control-back-from-web-view-to-react-native-app-in-oauth-flow

**Comment by kadikraman** [comment]
The redirect uri for native apps dosn't start with `https` (it's not a web link), it should look something like this: `com.googleusercontent.apps.GOOGLE_OAUTH_APP_GUID:/oauth2redirect/google` like in our [config example](https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/google.md).

You'd then also need to add the redirect scheme in your `manifestPlaceholders` in `build.gradle`. For instance, for the example uri above, the placeholder would be:

```
manifestPlaceholders = [
    appAuthRedirectScheme: 'com.googleusercontent.apps.GOOGLE_OAUTH_APP_GUID'
]
```

Hope this helps!

**Comment by rakeshwfg** [comment]
Thank you for pointing in the right direction. I was under the wrong impression that oAuth client ID for web would universally work for both web and native. After fixing that mistake by using a separate oAuth client ID for Android, I am encountering a crash right after successful authentication and redirection. Post redirection, the app appears for a fraction of a second and then crashes right after. Stack trace shows the crash's coming from `AuthorizationService.java:453`. Any idea what might be going on?

```
2020-08-08 06:35:29.050 14496-14694/io.MyApp.MyApp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: io.MyApp.MyApp, PID: 14496
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at net.openid.appauth.Utils.readInputStream(Utils.java:36)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:453)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:395)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by kadikraman** [comment]
I'm not sure why you're getting this error, but searching [AppAuth-Android](https://github.com/openid/AppAuth-Android) (the native library we're bridging) I did find an issue [with the exact same stack trace](https://github.com/openid/AppAuth-Android/issues/402) - maybe you could try to breakpoint it and find the exact JSON it's trying to parse? It looks like it's failing at the token refresh step, so perhaps the token exchange is returning something the library isn't able to parse?

**Comment by rakeshwfg** [comment]
Thanks @kadikraman for your inputs and I will follow those steps. In the meantime, I am upgrading react-native version to latest so that we can use the latest version of react-native-app-auth and then try again.

**Comment by kadikraman** [comment]
Sounds like a plan - good luck on the upgrade! It's a bit of a hassle from 0.59 to 0.60+ (when I did it, ended up `react-native init`'ing a new project and re-adding all the changes manually), but there's lots of awesome stuff in 0.60+ so well worth the hassle!

Closing this for now, but please let me know if you still have the same error post-upgrade!
