### ISSUE TITLE
 Attention Azure B2C : - The operation couldn’t be completed. (org.openid.appauth.general error -3.)

### ISSUE THREAD

**Issue by chamilacnb** [FormidableLabs/react-native-app-auth#537]
## Issue
**Working in androd, Not working in ios**
 "react-native-app-auth": "5.1.1",
Iphone 11 simulator - ios 13.2.2

when trigger authorize(config);

 it loads Azure b2c login in browser but 404
![image](https://user-images.githubusercontent.com/60600065/88998717-4fcd1800-d310-11ea-8838-94c08ed9297f.png)

console log get this:
![image](https://user-images.githubusercontent.com/60600065/88998591-0086e780-d310-11ea-91f3-56313f60bab2.png)

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `Working in Android, Not working in IOS`
* **Are you using Expo?** No

**Comment by sakthivelsubbarayan9** [comment]
Hey, @chamilacnb I faced the same issue. Any solutions?

**Comment by Wicusiu** [comment]
Hey, @chamilacnb How did you manage to solve this issue ? Is it possible without patching the current implementation ?
