### ISSUE TITLE
Add Swift xcode installation in README

### ISSUE THREAD

**Issue by paulbrittain** [FormidableLabs/react-native-app-auth#54]

**Comment by jevakallio** [comment]
@paulbrittain thanks for the suggestion. If you're already setting this up with Swift, would love to see a pull request documenting the steps you took. 

I guess this should only affect the [Define openURL callback](https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate) section, unless there are some additional configuation steps I'm not aware of.

**Comment by paulbrittain** [comment]
I've gotten back to this project after a break, I'm not sure how to proceed, the RNAppAuth.m file imports AppDelegate.h, which is objective-c. A swift project uses an AppDelegate.swift, so the package will have to be modified every time there's a new release. Seems broken to me.

**Comment by paulbrittain** [comment]
@jevakallio Hello again, I have an installation solution for using this library in a Swift project. But it involves using it as a static library. Insofar, I haven't been able to bridge between the Objective-C and Swift code while the Objective-C is not in the Project folder. I'd like to overcome this, but I'm not sure it's possible.

I can make a PR to update the README with how to use the library with Swift as a static library, is that something you're interested in including?

**Comment by kadikraman** [comment]
Hi! It's always worth noting down the progress so far, especially as you've already spent some time on it, and it would be great if others could also benefit from your knowledge :)

I guess the caveat of using it as a static library is that updating to new versions would be a manual process of copying the new file across?
