### ISSUE TITLE
IOS Apple rejected- Guideline 4.0 - Design

### ISSUE THREAD

**Issue by charleycesar** [FormidableLabs/react-native-app-auth#547]
## Issue
I tried to submit a new app for revision in apple today and I received this issue.

did anyone find any solution for this?

Guideline 4.0 - Design

We still noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

Next Steps

To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

Resources

For additional information on the Safari View Controller API, please review the What's New in Safari webpage.

Please see attached screenshot for details.

## Environment

* **Your Identity Provider**: 
My own SSO
* **Platform that you're experiencing the issue on**: 
IOS 11+
* **Are you using Expo?**
NO

**Comment by kadikraman** [comment]
That's strange, I've not seen a rejection like this before. The iOS side of the library is just a bridge of [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) and according to their docs:

> iOS 9+ uses the in-app browser tab pattern (via SFSafariViewController), and falls back to the system browser (mobile Safari) on earlier versions

Which says we _are_ using `SFSafariViewController`. Maybe you could send them a screenshot of the auth page? E.g. here, you can clearly see we're still in-app and you can see the lock and the website url.

<img width="621" alt="Screenshot 2020-08-09 at 17 52 41" src="https://user-images.githubusercontent.com/6534400/89737484-34c57b00-da69-11ea-975d-b3680fd5c74c.png">

**Comment by charleycesar** [comment]
Sure it is strange I read the specifications. Here you are some screens. 

![602C7269-6401-4C61-808C-0060341A7494](https://user-images.githubusercontent.com/5392290/89738772-a691ca80-da51-11ea-92e5-8c129194abc8.png)
![416FD903-B89A-4D64-9BFE-1A1AC28AAE81](https://user-images.githubusercontent.com/5392290/89738777-ad204200-da51-11ea-9006-aedba3aaeb07.png)
![F925714D-FE2A-4061-BCD7-F312E01E8C8C](https://user-images.githubusercontent.com/5392290/89738778-adb8d880-da51-11ea-8c12-757aaa28d1df.png)

**Comment by charleycesar** [comment]
Sorry i think the SFAuthenticationSession is deprecated.
We need to use ASWebAuthenticationSession instead.

Did you know how to update to use this ASWebAuthenticationSession?

**Comment by charleycesar** [comment]
Other question is the bridge use to [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) version 1.2.0 they're in 1.4.0 and resolve a lot of bugs and rejected from apple issues.

A solution is upgrade this bridge?

**Comment by kadikraman** [comment]
Good spot, we should definitely update it. I'll create a PR for it.

**Comment by kadikraman** [comment]
Just published this as [v6.0.0-rc2](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v6.0.0-rc2) 🎉

**Comment by charleycesar** [comment]
Thanks I will try to submission with this release.

**Comment by MFrat** [comment]
@charleycesar, some news? Approved?

**Comment by charleycesar** [comment]
@MFrat  Yes I sent with success and they approved without any issues.
Thanks for all
