### ISSUE TITLE
Getting 404- File or directory not found in IOS 

### ISSUE THREAD

**Issue by sakthivelsubbarayan9** [FormidableLabs/react-native-app-auth#548]
## Issue
I'm trying to integrate Azure AD B2C with my react native App. But i'm getting 404- File or directory not found.But it working fine in Android.
 
"react-native-app-auth": "^5.1.2"

![IMG_20200810_165214](https://user-images.githubusercontent.com/40357539/89777761-f04de400-db29-11ea-88b9-e214179c49a1.png)

---

## Environment

* **Your Identity Provider**: Azure AD B2C
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?**:NO

**Comment by kadikraman** [comment]
Could you check what the actual url is that it's accessing and whether it's different on Android?

**Comment by sakthivelsubbarayan9** [comment]
@kadikraman I used the same code for both Android and IOS
` 
  const config = {
    serviceConfiguration: {
        authorizationEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_login',
        tokenEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_login'
    },
    clientId:<clientId>',
    redirectUrl: 'app://deeplink/movement',
    scopes: ['openid', 'profile', 'email', 'offline_access']
};`

**Comment by kadikraman** [comment]
I think it's the `p=b2c_1_login` - I'm not sure that url parameter is required. Azure b2c should have a discovery document so you don't have to define the auth and token endpoints yourself. Could you update your config to be like this:

```
const config = {
  issuer: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0',
  clientId:<clientId>',
  redirectUrl: 'app://deeplink/movement',
  scopes: ['openid', 'profile', 'email', 'offline_access']
};
```

Or if that url parameter has to be there, you could add it using `additionalParameters` like so:

```
additionalParameters: {
  p: "b2c_1_login"
}
```

**Comment by sakthivelsubbarayan9** [comment]
When I use the issuer I'm getting a network error. So I change the behaviour based on this [link](https://github.com/FormidableLabs/react-native-app-auth/issues/275#issuecomment-477198686) 


![Screenshot_20200810_185903_com qinematicapp](https://user-images.githubusercontent.com/40357539/89788404-bc2fee80-db3c-11ea-99f8-42fd270a3fca.jpg)

**Comment by kadikraman** [comment]
Oh, I see. Does it work on iPhone when you do this? Did you try keeping the `serviceConfiguration` object, but passing the url params in using `additionalParameters`?

**Comment by sakthivelsubbarayan** [comment]
I change the configuration like  `const config = {
    serviceConfiguration: {
        authorizationEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/authorize',
        tokenEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/token'
    },
    clientId:<clientId>', 
    redirectUrl: 'app://deeplink/movement',
    scopes: ['openid', 'profile', 'email', 'offline_access'],
    additionalParameters: {
        p: "b2c_1_login"
    }
};`

But Still I'm getting the error 
<img width="460" alt="Screenshot 2020-08-11 at 11 02 04 AM" src="https://user-images.githubusercontent.com/30147172/89860866-1921b800-dbc2-11ea-9992-592977a58ddb.png">

**Comment by sakthivelsubbarayan9** [comment]
I change the configuration like  `const config = {
    serviceConfiguration: {
        authorizationEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/authorize',
        tokenEndpoint: 'https://<mytenent>.b2clogin.com/<mytenent>.onmicrosoft.com/oauth2/v2.0/token'
    },
    clientId:<clientId>', 
    redirectUrl: 'app://deeplink/movement',
    scopes: ['openid', 'profile', 'email', 'offline_access'],
    additionalParameters: {
        p: "b2c_1_login"
    }
};`

But Still I'm getting the error 
<img width="460" alt="Screenshot 2020-08-11 at 11 02 04 AM" src="https://user-images.githubusercontent.com/30147172/89860866-1921b800-dbc2-11ea-9992-592977a58ddb.png">

**Comment by sakthivelsubbarayan9** [comment]
Yes, @kadikraman. This trick working for me. Thanks
