### ISSUE TITLE
Idea: Provide functionality (or instructions) to safely store authentication tokens

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/react-native-app-auth#55]
Currently the focus of this library is to complete the OAuth token exchange. When it comes to securely storing the received tokens, we leave the user to their own devices (pun intended).

This causes an unfortunate accidental security hazard where a user of this library may inadvertently store their refresh tokens in AsyncStorage etc.

I think we should either 
  1. Provide instructions on how to store the tokens securely using iOS Keychain / as encrypted values in Android SharedPreferences, or
  2. Implement secure storage functionality into the library itself

**Comment by PeterKottas** [comment]
I was working on something along those lines. you can check it out if you want. https://github.com/PeterKottas/react-native-web-redux-auth it's hugely based on redux-oidc and oidc-client libs. You might find this useful https://github.com/PeterKottas/react-native-web-redux-auth/blob/master/src/native/ReactNativePersistentStorage.ts also be aware of this bug for development (it's a pain in the ass at the moment) https://github.com/facebook/react-native/issues/14101

**Comment by jevakallio** [comment]
@PeterKottas in that example you are using AsyncStorage as the backing store?

This is actually what this proposal aims to help avoid in client applications. AsyncStorage storage format is not secure - on iOS is uses plaintext files in application data directory, and SQLite on Android.

This may be fine for some applications, but it won't pass your average security audit, and us as library developers can't make that choice for the user.

If this library were to implement token storage, we'd want to use the iOS Keychain, and a combination of different native storage and encryption methods for different versions of Android, each of which comes with their own complexities and thus, also, the need for us to support the users of this library in getting it right.

**Comment by PeterKottas** [comment]
Ah okay I see. Initially I though there's no way to keep something secret in ios/android. Read an article about it the other day but it seems that applies more for config parameters. Stuff like client secret for example. This definitely seems to be the way to go. 

I was thinking maybe this could help? https://github.com/oblador/react-native-keychain 
That way you don't have to re-implement it yourself which can save valuable time. Of course only as long as you'd be happy with what those guys did. It can become a peer dependency.
