### ISSUE TITLE
On authorize method function can i get response as previously 

### ISSUE THREAD

**Issue by Karthiksheety** [FormidableLabs/react-native-app-auth#554]
## Documentation Feedback
 I have used this for authorize the Strava login. Previous version i have got code and state on authorize method. Based on that i have made login in my app side now i am getting access_token, refresh_Token access_Token_expiry_Date so it will be helpful if i get state and code also.

**Comment by kadikraman** [comment]
Can you explain more: when you say "previous version" vs "now" - could you name the specific versions you are talking about?

**Comment by Karthiksheety** [comment]
Previous mean when i call authorize method passing with my strava client id and client secret. It was opening strava web page we have authorization button on clicking that it was redirected my app. There  i used to get state and code. 
using that state and code i was able to authorize on my application backend.

But now when i click authorize button by default authorization process was done and sending token.

var config = {
    clientId: "XXXXX",
    clientSecret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX7",
    redirectUrl: "auth://www.app.goals.fit/api/v1/profiles/auth/strava/callback",
    serviceConfiguration: {
        authorizationEndpoint: "https://www.strava.com/oauth/mobile/authorize",
        tokenEndpoint: "https://www.strava.com/oauth/token?client_id=XXXXX&client_secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX7",
        revocationEndpoint: "https://www.strava.com/oauth/deauthorize"
    },
    additionalParameters: {
        approval_prompt: "force",
        skipTokenExchange: "true"
    },
    scopes: ["activity:read"]
};

**Comment by kadikraman** [comment]
I think the problem might be that the `skipTokenExchange: true` should be in the config, not in additional parameters.

**Comment by Jay-A-McBee** [comment]
Closing due to unresponsiveness.
