### ISSUE TITLE
Redirecturl

### ISSUE THREAD

**Issue by pikooli** [FormidableLabs/react-native-app-auth#555]
Hello , when i try to log in with this api , i got on the authorisation page of google but after select m account i got redirect to a web browser with google on home page . 
it do no go back to my app . 
i have to do something with the redirect url ? 
but how to format it ? 

thanks you

**Comment by kadikraman** [comment]
Yes, you'll need to configure a redirect url. Are you using Google OAuth? Read more about how to create the redirect url [here](https://developers.google.com/identity/protocols/oauth2/native-app#request-parameter-redirect_uri). You'll then need to pass it into the config and (for android) configure the [redirect scheme](https://github.com/FormidableLabs/react-native-app-auth#android-setup)

**Comment by pikooli** [comment]
Thanks you , will look at it :D

Le sam. 15 août 2020 à 17:14, Kadi Kraman <notifications@github.com> a
écrit :

**Comment by pikooli** [comment]
thanks you , i make it work : D it was hard but now i know how a redirect url look like : D

**Comment by Dhanraj-bidchat** [comment]
Hi@pikooli,  i have added it in configuration as well but for some emails it is not redirecting me back to the app.
It shows loading loading and then shows google page.
please help.
