### ISSUE TITLE
Support for when the Native OS fails to redirect back into the app.

### ISSUE THREAD

**Issue by frantjc** [FormidableLabs/react-native-app-auth#556]
Hello,

My team is currently using this package in a React Native app alongside a Universal Link on the iOS side to integrate with an OAuth2 provider that only supports https:// redirect urls.  This works well most of the time, but occasionally (depending on the version of iOS), the redirect back into the app doesn't work, leaving the user with the browser open to a black page at https://universal-link/oauthredirect (as an example).

Some light research has lead us to believe that this is a problem with some versions of iOS (12.x, specifically).

As a workaround, I thought that we could have the page at https://universal-link/oauthredirect display something along the lines of:

"We failed to redirect you back into the app: Tap here: url-scheme://oauthredirect?code=${auth_code_from_redirect}"

This would, theoretically, get the user back into the app with the auth_code and avoid the failing Universal Link in favor of a Url Scheme. My question is...

Would that work?  If not, would it be possible to implement?

**Update:**

I finally got the environment set up to test if my work-around would work, and it did not.  So, now I'm curious if there is any guidance on if/how I could get it working?

```
this is ideal:
authorize() -> log in -> redirect to https://universal-link/oauthredirect?code=${auth_code} -> OS redirects into the app -> react-native-app-auth continues as usual

this is the desired workaround:
authorize() -> log in -> redirect to https://universal-link/oauthredirect?code=${auth_code} -> OS fails to redirect into the app -> https://universal-link/oauthredirect?code=${auth_code}  does ((something)) that redirects into the app with the auth_code -> react-native-app-auth continues as usual
```

**Comment by RohitRastogi94** [comment]
@frantjc how did you implementated https universal link with redirect. can you please explain the steps

**Comment by RohitRastogi94** [comment]
@frantjc  My team is also trying to add universal link in iOS. but instead of redirecting back to app, it's redirecting to web page. If you can share steps It would be very helpful.
