### ISSUE TITLE
CredStore Error -25300 with ADFS

### ISSUE THREAD

**Issue by ursforrer** [FormidableLabs/react-native-app-auth#558]
## Issue
As am changeing the ADFS installation from a local one, to one behind a netscaler (load balancer) im getting is error when authenticiation is proceded. I can successfully enter the correct login informations and than this error is happening.

CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "sts.domain.ch";
    srvr = "sts.domain.ch";
    sync = syna;
} 

## Environment
The ADFS (Active Directory Federation Services) Installation is running behind a Citrix Netscaler. 
Identity Provider: ADFS
Platform: iOS
No use of expo, running direct on a simulator device.

**Comment by kadikraman** [comment]
Hi there! I've not seen this error before so I'm not sure what to suggest. Did you come across [this StackOverflow thread](https://stackoverflow.com/questions/46099940/credstore-perform-query-error) when looking for a solution? Have you tried some of the suggestions there?

**Comment by ursforrer** [comment]
Hi, thanks for helping. I have tried some the suggestions. Other I have not. 
I have no clue where to set settings regarding the url protection space with react-native-app-auth project. there are no settings or similar things available.

**Comment by ursforrer** [comment]
Yes tried everything. On different devices. Different networks. Always the same issue.

**Comment by Jay-A-McBee** [comment]
Closing due to lack of engagement.
