### ISSUE TITLE
Authorization fails with error message "Errir: Error not specified"

### ISSUE THREAD

**Issue by Jarzka** [FormidableLabs/react-native-app-auth#561]
## Issue

When calling `authorize`, it raises an exception which, when printed to the console, only shows: Error: Error not specified.

Any idea what might cause this? I wonder if this error is even raised from this library, since I could not find "not specified" error message in the code. It feels like the system fails to open the Android web view component or something?

EDIT: It seems that this error can happen if the user does not have Android web view or any web browsers installed. However, the user who is having this issue, has Chrome installed and web view enabled. Also, web view works in other applications.

---

## Environment

* **Your Identity Provider**: `oAuth`
* **Platform that you're experiencing the issue on**: `Android 6`

**Comment by icaru88** [comment]
Hi, anyone is able to resolve this issue?

Afer updating to react-native-app-auth@latest, my app is unable to login on emulator running API 30. Error thrown: Error not specified.

No problem with API 28, API 29

**Comment by icaru88** [comment]
Hi all, just an quick update, after I change my android project targetSDKVersion to 29 as per official RN documentation. I am able to run my app and login in emulator running API 30/ android 11 version.

**Comment by ganeshpatil3** [comment]
Hi All,
I am using the updated version 6.2.0, on targetSDKVersion to 29, it is working fine. But after changing the targetSDKVersion to 30 it is not working. When calling authorize function, it raises an exception which returns an error: Error not specified.
Now, Google said to update the application we must have targetSDKVersion to 30.
Is anyone find the solution?

**Comment by ball-hayden** [comment]
See https://github.com/openid/AppAuth-Android/issues/648, specifically https://github.com/openid/AppAuth-Android/issues/648

We needed to add to our app android manifest:

```xml
<manifest>
...
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
</manifest>
```

**Comment by Jay-A-McBee** [comment]
Same as https://github.com/FormidableLabs/react-native-app-auth/issues/684 - ball-hayden's suggestions seems to be the solution. Closing this out.
