### ISSUE TITLE
Keycloak: register flow

### ISSUE THREAD

**Issue by remch19** [FormidableLabs/react-native-app-auth#563]
How can I open the keycloak registration screen? Thanks

**Comment by jpdriver** [comment]
hey @remch19 -- this library only supports authorising end users.

to register a new user you would probably need to either do that on the Keycloak Admin Console for your server, or you may be able to setup self-registration via Keycloak's REST API but it would need to be handled separately outside this library.

cheers

**Comment by SebastianGrzymala** [comment]
To get directly into registration screen in Keycloak you must use authorize method with extra config: 
```
serviceConfiguration: {
    authorizationEndpoint: authUrl + 'protocol/openid-connect/registrations',
    tokenEndpoint: authUrl + 'protocol/openid-connect/token',
  }
```
