### ISSUE TITLE
Authorize promise does not resolves

### ISSUE THREAD

**Issue by MFrat** [FormidableLabs/react-native-app-auth#566]
The problem is that for a specific in house provider the autorize method does not resolves, and no error occurs. Even with `skipCodeExchange: true`. In Android just works fine. I think is similar to [this issue](https://github.com/FormidableLabs/react-native-app-auth/issues/523), but `skipCodeExchange` has no effect.
The redirection to the app occurs, but the authorize method hangs up.

I just have this log
`Background Task 13 ("Called by XXX, from -[RNAppAuth issuer:redirectUrl:clientId:clientSecret:scopes:additionalParameters:serviceConfiguration:skipCodeExchange:useNonce:usePKCE:resolve:reject:]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

Redirection example:
`com.myapp:/oauth?state=7Nlvhz2-The4OW5L6dQtwA&code=/wEBAAEBACCM80LEUkt44gw4Q1x9kcloQE8@KYq0rTE8CZwIk02nvkahD@Rpkm00RKGF8VQAbTG/4mmbrSW15xmeAtH0lqLW6rAQ05e80f6353Sb9jU9Q9w3hOghTPJNjeCeuQ@GcPovUasglaBWoJXvrd0mZvNZJwGLq@MqJ0E0qDGqDX6y0yo3iJbpP5Bi/3ThUVgkEDdmXAGxpezxoHrvGC6RpWVnqFMii8CUJdoTuzt@Yy4Zs3sCMeuv3AWeYTzQYFjicX4RaZGNJiXmJLaRlhT@DfNOSxNLjz@TYx4iv@OKRfhIBKlOuA8SUiHAgrjEAr6fP9FScwYiHfWxTdKGG1uYtGLfVeWDC@yodOfXdbeSANJbCBSm90oOYNzAHvXtG94@@HVI6MDj@z@x7RE3Fz/MDF2LS7zqg8hZ6okkp52V5MrMDNKwU7yBb8vJMaUvLsCHeIT@HwDBGpLXuExIydpsyZEHkoxuwsi4T6qCrLK6cosjOA~~`

## Environment

**Identity Provider**: Custom Oauth2 Compliant Provider 
**Platform**: iOS (13.7 and 10.3.1)
**React Native**: 0.63
**React Native App Auth**: 6.0.0
**Not using Expo**

**Comment by MFrat** [comment]
The problem was that redirect_uri and custom uri must be the same in iOS. I think this could be more explicit in the docs and in error message.

In my case, redirect_uri was something like https://zzzz.com and custom uri was com.myapp, both needs to be equal.

**Comment by sammarks** [comment]
@MFrat I'm running into this same issue. What do you mean "custom URI" in your message above?

**Comment by MFrat** [comment]
@sammarks custom uri i mean Android/iOS custom scheme, like com.myapp:/auth. For me, i were sending redirect_uri as something like https://aaaaa.com/authz but my iOS redirection is like com.myapp:/auth, and this is not allowed in iOS's Oauth2 Flow, redirect_uri must be a scheme. And if your Oauth2 provider does not support custom schemes, then you will have to configure a https custom scheme.

**Comment by sammarks** [comment]
Ah, gotcha. Makes sense, thanks!
