### ISSUE TITLE
Keyboard not shown, cannot type in credentials

### ISSUE THREAD

**Issue by AndriiTans** [FormidableLabs/react-native-app-auth#568]
Our app is using the latest version of OpenID provider. It works fine on Android but sometimes on iOS 14.0 on big screens (iPad) when typing input, popup moves up but native keyboard is invisible till I change device orientation.

Before changing orientation:
<img width="300" alt="Screenshot 2020-10-12 at 17 54 42" src="https://user-images.githubusercontent.com/48866249/95761170-9a75f380-0cb4-11eb-9494-403933fb5a7e.png">

After orientation changed:
<img width="300" alt="Screenshot 2020-10-12 at 17 55 08" src="https://user-images.githubusercontent.com/48866249/95761201-a792e280-0cb4-11eb-8d0b-3ff21b60be7c.png">
<img width="300" alt="Screenshot 2020-10-12 at 17 55 24" src="https://user-images.githubusercontent.com/48866249/95761214-aa8dd300-0cb4-11eb-83e5-46da6399cff2.png">

**Comment by Jay-A-McBee** [comment]
Closing this out - outside of the scope of this library.
