### ISSUE TITLE
Apple Sign in integration

### ISSUE THREAD

**Issue by Tanuja0064** [FormidableLabs/react-native-app-auth#569]
## Issue

I am trying to integrate Apple sign with this library.

Below are the configurations I added:
serviceConfiguration: {
        authorizationEndpoint: 'https://appleid.apple.com/auth/authorize',
         tokenEndpoint: 'https://appleid.apple.com/auth/token',
     },
    clientId: [apple service ID],
    redirectUrl: [Redirect url integrated at apple service ID],
    scopes: 'openid',,
    clientSecret: [Generated Client secret from private key],

Using these details I am getting below issues:
1. If I mention scopes- email or name, I am getting following error on apple sign in page- 
     response_mode must be form_post
 Under which configuration we can send this value?

2. If I try to use non-https based url like google- the 'invalid web redirect URL' error is shown on apple sign in page.

3. For the time being I am sending only openid scope. Using this I am able to see apple sign in page and I can fill in all the values. after validation I am stuck at browser screen with https redirect URL.
After trying 'https scheme based url' functionality for android, eventually I got in the app again but I am geeting below error:
token_exchange_failed - invalid client.

All the parameter are correct, as I have tried these apis seperately and was able to get the responses correctly.
Can you please confirm if this functionality can be worked out?

**Comment by Jay-A-McBee** [comment]
> after validation I am stuck at browser screen with https redirect URL

On iOS you'll need to follow the Apple documentation to register a "universal link" that your app can claim. A universal link is a standard `https:<domain>/<path>/` formatted url that will open in your app instead of in a browser. There are some more details around it covered [here](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content?preferredLanguage=occ)

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
