### ISSUE TITLE
library not found for -lAppAuth

### ISSUE THREAD

**Issue by npaul2173** [FormidableLabs/react-native-app-auth#572]
ISSUE when Running React-native project.

ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Experiencing this issue on IOS
This project is done using bare react native

![Screenshot 2020-10-21 112917](https://user-images.githubusercontent.com/41561899/96679385-2d87eb00-1391-11eb-8111-629d7a89e4f4.png)
![Screenshot 2020-10-21 112917](https://user-images.githubusercontent.com/41561899/96679425-41335180-1391-11eb-8ed3-c36df7691a04.png)

Package.Json dependencies

"dependencies": {
    "@react-native-community/checkbox": "^0.5.3",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/datetimepicker": "^3.0.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.7",
    "@react-native-firebase/app": "^8.4.6",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "aws-sdk": "^2.771.0",
    "base64-arraybuffer": "^0.2.0",
    "i": "^0.3.6",
    "npm": "^6.14.8",
    "patch-package": "^6.2.2",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-contacts": "^5.2.7",
    "react-native-device-info": "^6.2.0",
    "react-native-eventemitter": "0.0.1",
    "react-native-fbsdk": "^2.0.0",
    "react-native-fcm": "^16.2.4",
    "react-native-geocoding": "^0.4.0",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-google-places-autocomplete": "^2.0.3",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-crop-picker": "^0.34.1",
    "react-native-image-marker": "^0.6.1",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.27.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-paper": "^4.1.0",
    "react-native-permissions": "^2.2.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-popup-menu": "^0.15.9",
    "react-native-reanimated": "^1.13.0",
    "react-native-s3-upload": "0.0.12",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1",
    "react-native-simple-toast": "^1.1.3",
    "react-native-skeleton-content-nonexpo": "^1.0.11",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "^7.0.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22"
  },

**Comment by lander854** [comment]
same problem
