### ISSUE TITLE
Getting error 'Client must send a client_secret when redeeming a confidential grant.' for azure if client secret is not sending

### ISSUE THREAD

**Issue by gchowdhari** [FormidableLabs/react-native-app-auth#576]
## Issue

client_secret not needed for Mobile app client's for azure provider. Still I am getting following error when try to authorize without client_secret,
"Client must send a client_secret when redeeming a confidential grant."

---

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?**: `No`

**Comment by Jay-A-McBee** [comment]
Closing due to lack of information. @gchowdhari we have a working example for both Azure AD and Azure AD B2C. Please reference the [config examples](https://github.com/FormidableLabs/react-native-app-auth/tree/main/docs/config-examples) and open a new issue if this is still a problem.
