### ISSUE TITLE
revoke the token send to logut but when i try to authenticate i have bug ,but if close th app then is authenticate without entering information

### ISSUE THREAD

**Issue by attachi20** [FormidableLabs/react-native-app-auth#578]
## Issue

---
 revoke = async () => {
    try {
      await revoke(config, {
        tokenToRevoke: this.state.accessToken,
        includeBasicAuth: true,
        sendClientId: true
      });
      this.animateState({
        accessToken: '',
        accessTokenExpirationDate: '',
        refreshToken: '',
        beers: []
      });
    } catch (error) {
      console.log(error.message)
      Alert.alert('Failed to revoke token', error.message);
    }
## Environment

* **Your Identity Provider**: `e.g. Keycloak
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?** no react native

**Comment by Jay-A-McBee** [comment]
:wave: hey @attachi20 - Thanks to @gispada's https://github.com/FormidableLabs/react-native-app-auth/pull/693 recent edition, you should be able to actually end a user's session through the Idp. Try upgrading to `6.4.2`.
