### ISSUE TITLE
Navigation after authorize completion hangs because browser is still in closing animation on iOS 11

### ISSUE THREAD

**Issue by jesperkristensen** [FormidableLabs/react-native-app-auth#579]
## Issue

When the `authorize` promise resolved or rejected, I navigate somewhere else, but the navigation hangs/fails on iOS. After some digging, I found out that the `authorize` promise resolves/reject before the browser hiding animation is complete. When I start my navigation, it tries to start another animation, and either iOS or react-native-navigation does not seem to handle these two concurrent animations.

Either the `authorize` promise should only resolve/reject after the hide browser animation is complete, or there should be some other way to wait for the animation.

Code sample showing the problem:

```
import {authorize} from 'react-native-app-auth';
import {Navigation} from 'react-native-navigation';

try {
  const result = await authorize(authConfig);
  await Navigation.showModal(...);
} catch (ex) {
  await Navigation.showModal(...);
}
```

 I have attempted to insert a call to `InteractionManager.runAfterInteractions` right after `authorize`, but that runs immediately, and does not wait for the hide browser animation.

The only workaround I have found is to wait for a fixed amount of time, and assume that the animation is finished by then.

I don't see the problem on Android.

---

## Environment

* iOS 13.7 Simulator
* react-native@0.63.3
* react-native-app-auth@6.0.0
* react-native-navigation@6.12.2

**Comment by rashidul0405** [comment]
have u got any solution?

**Comment by hollanderbart** [comment]
Also experiencing this error. It seems to already returning the promise, before the animation has finished.

**Comment by Jay-A-McBee** [comment]
Closing this out because this is not an issue with the library. These concurrent animations that are colliding occur after the library has resolved/rejected the auth requests.
