### ISSUE TITLE
Doesn't seem to work with IBM App ID or can't set response_mode

### ISSUE THREAD

**Issue by thomas-shares** [FormidableLabs/react-native-app-auth#580]
## Issue
Hi,
I am running the example and I would like to use it combination with IBM App ID [1]. When I try to login with the correct credentials I get the following error:

```
Error: missing credentials in request
```
When I do a log in on a web page using the IBM provided JS toolkit for App ID I can see one difference in the authorization call and that is that in the working case there is a `response_mode` included in the call.
When I try to set `response_mode` on Android I get the following error:

```
Parameter response_mode is directly supported via the authorization request builder, use the builder method instead
```
Any ideas on what I need to do in order to get this working with IBM App ID? Many thanks in advance.

[1] https://cloud.ibm.com/docs/appid?topic=appid-getting-started
---

## Environment

* IBM App ID
* Android
* Are you using Expo? No I am using the example as provided in this Repo.

**Comment by avisiboni** [comment]
Hi @thomas-shares,
Any progress with that?

**Comment by thomas-shares** [comment]
Hi @avisiboni  
I'm 'fraid not. In the end I have given up on this and now we are using AWS Cognito and that works really well for us. I can close this issue if needed.

**Comment by Jay-A-McBee** [comment]
Closing due to lack of engagement and OP using alternate provider. If you found this issue and are still experiencing issues with IBM App ID, please create a new issue.

**Comment by paulschreiber** [comment]
See related: https://github.com/FormidableLabs/react-native-app-auth/issues/484
