### ISSUE TITLE
after login just loading and redirect to google page

### ISSUE THREAD

**Issue by hotaryuzaki** [FormidableLabs/react-native-app-auth#581]
## Issue

Before this, my google login work.
But i dont know why right now it dont work.
I already put appAuthRedirectScheme in build gradle, as i said that before this happen my google login work.

is there anyone facing this issue?

---

## Environment

* **Your Identity Provider**:
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** Yes, but eject to managed workflow. Expo 37

**Comment by develerik** [comment]
Our team is facing the same issue. We also use it on iOS and there it's working just fine

**Comment by hotaryuzaki** [comment]
> Our team is facing the same issue. We also use it on iOS and there it's working just fine

Do you mean you have same issue but not in IOS? just android?
Is it work before?

**Comment by develerik** [comment]
Yes, in our app the problem only occurs on android. and it also worked before

**Comment by hotaryuzaki** [comment]
> Yes, in our app the problem only occurs on android. and it also worked before

Hmm.. is it might be any change from google for android?

What version do you used?
Are you using expo?

I'm using 5.1.2
And expo 37.0 managed workflow.

**Comment by develerik** [comment]
We use 5.1.1 without Expo, but we also tried using the latest 6.0.1

**Comment by hotaryuzaki** [comment]
suddenly the error become this.
https://github.com/FormidableLabs/react-native-app-auth/issues/583

are you experienced this too?

**Comment by hotaryuzaki** [comment]
ok i found it only occur in android studio emulator.
when i installed to real device the problem was not exist.

is it possible policy change in google?? which is they disallowed the function in emulator?

**Comment by hotaryuzaki** [comment]
UPDATE:
i tried in emulator for API 28, 29, and 30.
API 29 and 30 it's works, but API 28 just loading and redirect to google.
it means android 9 PIE.

i tried in some real device, i have android 8.1.0 OREO samsung J7 and Redmi 5 plus.
Redmi 5 plus is works, but samsung J7 had same problem.
maybe i would try in emulator for API 27

**Comment by fafo** [comment]
I've tried on a device with android 10 and it's happening.

**Comment by hotaryuzaki** [comment]
> I've tried on a device with android 10 and it's happening.

im not found any solution.
so i migrated to react-native-google-signin, it was harder to setup but it works

**Comment by panktiszluck** [comment]
I am facing same issue in real device as well as emulator
below is the code I used for authorising google. Please let me know if anyone finds the solution.

```
const OAUTH_REDIRECT_URI = 'myPackage:/oauth2callback';  <----- tried this as well as  'myPackage:/oauth2redirect'
const config = {
   issuer: 'https://accounts.google.com/',
   clientId: `${OAUTH_CLIENT_ID}.apps.googleusercontent.com`,
   redirectUrl: OAUTH_REDIRECT_URI,
   scopes: [
        'openid',
        'profile'
    ]
};
try {
   // Log in to get an authentication token
   const authState = await authorize(config);
} catch (e: any) {
   console.log(e);
}
```

**Comment by 1Pjagtap** [comment]
`appAuthRedirectScheme` in app's build.gradle is the issue here, it should not be `com.example.com` else it should be `com.googleusercontent.apps.CLIENT_ID`

**Comment by panktiszluck** [comment]
> `appAuthRedirectScheme` in app's build.gradle is the issue here, it should not be `com.example.com` else it should be `com.googleusercontent.apps.CLIENT_ID`

It is not possible to set `com.googleusercontent.apps.CLIENT_ID` as I am using multiple `appAuthRedirectScheme`

**Comment by 1Pjagtap** [comment]
@panktiszluck Use `<intent-filters>` instead of `appAuthRedirectScheme` something like this.

```
 <activity android:name="net.openid.appauth.RedirectUriReceiverActivity" tools:node="replace" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.googleusercontent.apps.CLIENT_ID" />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.example.com" />
      </intent-filter>
    </activity>`
```

**Comment by panktiszluck** [comment]
> @panktiszluck Use `intent-filters` instead of `appAuthRedirectScheme` something like this.
> 
> ```
>  <activity android:name="net.openid.appauth.RedirectUriReceiverActivity" tools:node="replace" android:exported="true">
>       <intent-filter>
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="com.googleusercontent.apps.CLIENT_ID" />
>       </intent-filter>
>       <intent-filter>
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="com.example.com" />
>       </intent-filter>
>     </activity>`
> ```

I tried this, but it was not re-directing to my app.

**Comment by panktiszluck** [comment]
> `appAuthRedirectScheme` in app's build.gradle is the issue here, it should not be `com.example.com` else it should be `com.googleusercontent.apps.CLIENT_ID`

I tried `com.example.com` as well as `com.googleusercontent.apps.CLIENT_ID`, `com.googleusercontent.apps.CLIENT_ID` is not redirecting to app at all. so I has to use `com.example.com`.

**Comment by rush86999** [comment]
anybody have a step by step solution to this problem? I m trying to use google calendar api and it keeps redirecting to google.com instead of closing the tab back to the app

**Comment by H4mxa** [comment]
@rush86999 facing same issue have you figured it out?

**Comment by ishan-flek-ai** [comment]
Everyone is having the google redirect issue, 
### Android

```
    namespace "com.ember"
    defaultConfig {
        applicationId "com.ember"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.googleusercontent.apps.[id]',
        ]
    }
```

appAuthRedirectScheme has to be google URL to be secure that is the issue everyone is facing. that is because they are using invalid appAuthRedirectScheme, it is not com.[packageName] but what google has given

**Comment by ashish3805** [comment]
Hey @faizplus  I am still facing the issue on android 14, emulator with Google OAuth.
