### ISSUE TITLE
google login error rnappauth.authorize got 13 arguments expected 14

### ISSUE THREAD

**Issue by hotaryuzaki** [FormidableLabs/react-native-app-auth#583]
## Issue

Before this error, i got this [error](https://github.com/FormidableLabs/react-native-app-auth/issues/581)
But suddenly while i'm trying to figure out, the error become this.

`rnappauth.authorize got 13 arguments expected 14`

it is red alert and i dont know what happened, because even i rollback the error still same.

**UPDATE:**
**oh this happened after i update to 6.0.1 ver (before is 5.1.2)**

---

## Environment

* **Your Identity Provider**: 
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** yes, expo 37.0 bare workflow

**Comment by hapablap21** [comment]
Same issue here, only in release builds.

**Comment by hotaryuzaki** [comment]
> Same issue here, only in release builds.

Are you just update the version?

**Comment by hotaryuzaki** [comment]
my problem is gone, i dont know which fixed that.
npm cache verify/clear or re-installed, or delete node_modules and npm install again.

but my origin problem still exist in 581
