### ISSUE TITLE
In app browser doesn't close on redirect in iOS

### ISSUE THREAD

**Issue by ghost** [FormidableLabs/react-native-app-auth#584]
## Issue

I am using the `authorize` flow with OIDC SMART IDP. As long the user completes the flow in IDP screen, the application works fine. But I have links to forget password and signup in custom IDP page.
It works fine in Android, but in iOS, clicking on those links open the correct page using Universal Link in the App but the overlay browser does not close.

In short, the brower stays there and nothing happens. But in the background ios app has already opened the correct page.

---

## Environment

* **OIDC : SMART IDP**
* **iOS**
* **Not using Expo**

**Comment by badams2527** [comment]
@MohammedAtif did you ever find a way around this? Just ran into the exact same issue when trying to incorporate a universal link into my OAuth flow.

**Comment by Jay-A-McBee** [comment]
:wave: hey everyone 

Closing this out as it's outside the scope of this library, but it sounds similar to https://github.com/FormidableLabs/react-native-app-auth/issues/579 - @badams2527 feel free to open a new issue if you're still dealing with universal link issues.
