### ISSUE TITLE
How to avoid the consent dialog?

### ISSUE THREAD

**Issue by ranjanadangolcsu** [FormidableLabs/react-native-app-auth#585]
## Issue

I want to avoid the consent dialog which appears before the authorize is being called.
---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by samOpenforce** [comment]
I would also appreciate any guidance on suppressing this dialog (or possibly pre-granting the permission on install?).

### Environment
- Your Identity Provider: Keycloak
- Platform that you're experiencing the issue on: iOS
- Are you using Expo? No

**Comment by Gabotron-ES** [comment]
Same here

**Comment by savv** [comment]
There is really no way around that consent dialog - it's just how iOS is designed.

**Comment by Palid** [comment]
https://github.com/openid/AppAuth-iOS/issues/402 - there is a way to avoid the consent dialog in iOS 13+
There are some solutions suggested in the comments (see gists) that may need implementing on the native iOS side here.

**Comment by savv** [comment]
@Palid thanks for the link! It's interesting to see others consider the same trade offs. You are right, I should have said:

If you want to use the standard auth flow that Apple recommends, (also ensuring that your users are also logged into Safari), then there is no way around the consent dialog.

**Comment by jpdriver** [comment]
As mentioned this is not possible for now. If the upstream AppAuth iOS SDK merges support for ephemeral sessions, we will update this library to add the same support.

**Comment by paritosh-yadav** [comment]
Hi @jpdriver ,
As in the below [PR-645](https://github.com/openid/AppAuth-iOS/pull/645) `AppAuth iOS SDK` provided support for ephemeral sessions.
When can we expect same in this library?

**Comment by paritosh-yadav** [comment]
> Hi @jpdriver , As in the [PR-645](https://github.com/openid/AppAuth-iOS/pull/645) `AppAuth iOS SDK` provided support for ephemeral sessions. When can we expect same in this library?

Hi @jpdriver , any update on this?

**Comment by davidmalis** [comment]
Any ETA on providing support for ephemeral sessions?

**Comment by IKTANIM** [comment]
Any update on this @jpdriver

**Comment by paritosh-yadav** [comment]
Hi @jpdriver ,

Any update on this?

**Comment by enlightenedpie** [comment]
This whole library seems dead. Not much action on new releases, including a fix to add ephemeral sessions in iOS. Someone might need to fork the repo and continue development there.

**Comment by badsyntax** [comment]
Support for `prefersEphemeralSession` has been added with #787 and released with [v7.0.0-rc2](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v7.0.0-rc2)
