### ISSUE TITLE
IPad only - authorize model closes with no response on tap outside 

### ISSUE THREAD

**Issue by louisobasohan** [FormidableLabs/react-native-app-auth#586]
## Issue

On an IPAD, Hook up a button to the authorize function. 
Click the button, the model/webview opens.
Click outside the model/webview,
The model/webview closes, but there is no response from the authorize function

**Expected Behaviour**: There should be a response/exception similar to when the model/webview is closed using the x/close button

---

## Environment

* **Provider: IdentityServer 4 / PKCE`
react-native-app-auth: 6.0.1
react-native": 0.63.2
* **Platform: IOS
* **Are you using Expo?** No

**Comment by SMKH-PRO** [comment]
I am facing same issue on iOS, using microsoft login, works fine on Android but authorize does not resolve on iOS

**Comment by HolySamosa** [comment]
We're running into the same issue.  As @louisobasohan suggested, I would like to see the same behavior as pressing the "Cancel" button and/or having an option to disable closing of the window when pressing outside.

**Comment by hkdilan** [comment]
Please look at this issue. Still, iPad has this issue.

**Comment by MaanuVazquez** [comment]
Having the same issue for iPad as well

**Comment by thijs-qv** [comment]
This is a bug in iPadOS, and is fixed in 14.5.

**Comment by Jay-A-McBee** [comment]
Closing - outside the scope of this library.
