### ISSUE TITLE
The ability to specify browser in authorize method

### ISSUE THREAD

**Issue by crechet** [FormidableLabs/react-native-app-auth#588]
Hello!

Maybe I missed something in the documentation and select wrong issue pattern for my question.

In our application, we faced with the problem of transition to the site of another service, access to which is also configured in SSO.

For some reason, when initially logging into the mobile app, chrome is used instead of the default browser. But to follow the link, android uses the default browser. As a consequence, session and cookies are not shared between the chrome browser and the default browser. And the user goes to the site unauthorized.

As far as I understand, if for some reason the default browser cannot be used for authorization in authorize method, then chrome will be used.

Is there a way to find out which browser was used to initially log into the application?
Is there a way to configure the use of a specific browser for authorization so that I can use it to follow links to other resources through SSO?

Thanks!

**Comment by tdekoning** [comment]
I was encountering the same issue, and have created a pull request to add these options: #655
