### ISSUE TITLE
Typings issue 

### ISSUE THREAD

**Issue by PeterKottas** [FormidableLabs/react-native-app-auth#59]
Hi guys, just pulled down the latest version and I see a problem with typings on latest typescript version.

It's this line. https://github.com/FormidableLabs/react-native-app-auth/blob/master/index.d.ts#L20

Basically you can't extend type, it either has to be interface or class. Types are combined via '&' operator. 

Easiest fix would be to change AuthConfiguration to type and do = BaseAuthConfiguration & {
...
}

**Comment by PeterKottas** [comment]
PR : #60

**Comment by kadikraman** [comment]
PR merged
