### ISSUE TITLE
Application Crashes on Login on Device

### ISSUE THREAD

**Issue by jlordi70** [FormidableLabs/react-native-app-auth#598]
## Issue

We are able to login with 2 factor authentication on the emulator.  This works every time.  On our devices (Symbol T-75), We can get to the login screen, the 2 factor screen (Submit the and approve the message).  Once all of this happens the application crashes and restarts.  It does not log an issue to Sentry IO and not logging that is adding after the the authorize call.  
  
When it crashes the only message I see in the logs that appears to be an issue is the following:

 W ActivityManager: Duplicate finish request for ActivityRecord{28cd6aed u0 com.x.x/net.openid.appauth.RedirectUriReceiverActivity t425 f}

Has anybody seen this issue or can point me in a direction?

Any help would be greatly appreciated.

## Environment

react-native-app-auth Version 5.1.2 and 5.1.3
Internal Ping Identity
This is for Android devices only (No IOS devices are used)
* **Are you using Expo?** NO

**Comment by peterkarman1** [comment]
upgrade to latest app-auth package. resolved there

**Comment by Jay-A-McBee** [comment]
@jlordi70 this was a long time ago, but can you confirm if this is still an issue or not?
