### ISSUE TITLE
browser_not_found (Android only) - no suitable browser installed - In React Native

### ISSUE THREAD

**Issue by prorohit** [FormidableLabs/react-native-app-auth#601]
## Issue

On **Android** device targeting **API level 30** , I am getting the following issue, when making the authorize request for MS AD login.

**browser_not_found**

---

## Environment

React Native 0.61.5

**Solution:**
**What is the solution for this problem ?**

**Comment by sandan10** [comment]
Hi. I had the same experience. 
When this library checks for browsers, it can't find any. I guess this is because of [this change](https://developer.android.com/about/versions/11/privacy/package-visibility).

I added the following code to my manifest (above the application-tag) and now it works:
```xml
<queries>
    <intent>
        <action android:name=
            "android.support.customtabs.action.CustomTabsService" />
    </intent>
</queries>

```

**Comment by masiddee** [comment]
Thanks for sharing your solution @sandan10!

@prorohit I'm unable to replicate when logging into my test Microsoft AD application using either of the following builds:

- Android 11 using Pixel 3 (API 30)
- Android 10 using Pixel 4 (API 29)

I'm also running React Native 0.63.2. I was able to authenticate successfully and get the accessToken and refreshToken. Can you confirm if you are still experiencing this issue? If so, could you share some additional details around what build you are on and if implementing @sandan10's recommendation has helped you?

**Comment by Jay-A-McBee** [comment]
Closing due to lack of response from OP. Sounds similar to https://github.com/FormidableLabs/react-native-app-auth/issues/684.

**Comment by atitpatel** [comment]
This is still happening for me:
React Native version:  0.67.4
react-native-app-auth: 6.4.3

I am getting 'browser_not_found' error even after having browsers up-to-date(Chrome and Opera).

@Jay-A-McBee

**Comment by stbhb** [comment]
I can also reproduce the 'browser_not_found' error when having Opera installed on the device. No error for other single installations or combined installations of Chrome, Firefox, Brave or Vivaldi.

I also checked and changed the standard browser settings on Android, but still getting the error.

React Native version: 0.66.4
react-native-app-auth: 6.4.3

**Comment by AnassHmida** [comment]
@stbhb  did you figure out a solution for this ?

**Comment by stbhb** [comment]
I did not see it before, but https://github.com/FormidableLabs/react-native-app-auth/pull/731 fixes it
