### ISSUE TITLE
authorise() call works but return ID Token Expired error

### ISSUE THREAD

**Issue by SainagChunduru** [FormidableLabs/react-native-app-auth#602]
## Issue

When we call authorise(), it opens browser and after entering valid credentials we are facing this error. Can anyone pls help in fixing it.
---

## Environment

- We are experiencing this in **iOS** for **Azure Ad**.

**Comment by tatva-hiral** [comment]
Facing the same error, not able to find out a possible solution, the same configuration was working in "react-native": "v0.61.5" and "react-native-app-auth": "5.1.3" but we need to upgrade the whole project with the latest version, Anyone please help on this?

Thank you in advance.

**Comment by ahmed-abdelkader-00** [comment]
Did you figure out what the problem was, i am getting the same error

**Comment by Jay-A-McBee** [comment]
I was able to set up an Azure AD tenant and login using the following config. Also using `react-native v0.63.2` and `react-native-app-auth v6.4.2`.

{
  issuer:
      'https://login.microsoftonline.com/<TENANT-ID>/v2.0/',
    clientId: <CLIENT ID>,
    redirectUrl: 'example.myapp.com://oauth/',
    scopes: [ 'openid', 'offline_access']
}
Closing this out - unable to replicate. @SainagChunduru feel free to open a new issue if you think we can help.
