### ISSUE TITLE
authorize promise never resolves/rejects

### ISSUE THREAD

**Issue by Vamate** [FormidableLabs/react-native-app-auth#603]
## Issue

I have a simple app where I want to use `Spotify` as a way to register/log in. I followed the setup steps and implemented the authorization logic like this: 
```
const openSpotify = async () => {
    const spotifyAuthConfig = {
      clientId: SPOTIFY_APP_CLIENT_ID,
      redirectUrl: 'org.example.app://callback',
      scopes: ['user-read-email'],
      serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.spotify.com/authorize',
        tokenEndpoint: 'https://accounts.spotify.com/api/token',
      },
    };
    try {
      const result = await authorize(spotifyAuthConfig); // this promise hangs forever
      console.log(JSON.stringify(result)); // this never runs
      return result;
    } catch (error) {
      console.error(JSON.stringify(error)); // this never runs
    }
  };

  return (
    <View style={styles.container}>
      <Button title={t('LOGIN_BUTTON')} onPress={openSpotify} />
    </View>
  );
```

When I click on my login button, the message "ExampleApp Wants to Use spotify.com to Sign In" pops, and then I can sign in with my spotify account, press allow and the window dissapears but nothing happens. The `authorize()` promise stays pending even though the process went through. Any ideas what can I be doing wrong? 

---

## Environment

* **Your Identity Provider**: `Spotify OAuth`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** `No`

**Comment by Conrix** [comment]
Same problem for me on android: I use the following configuration:

react-native: 0.63.4
react-native-app-auth: 6.0.2

```
// This function is called to trigger the login
const login = async function () {
  const config = {
    serviceConfiguration: {
      authorizationEndpoint:
        'http://keycloak.localdev/auth/realms/myrealm/protocol/openid-connect/auth',
      tokenEndpoint:
        'http://keycloak.localdev/auth/realms/myrealm/protocol/openid-connect/token","introspection_endpoint',
      revocationEndpoint: '',
      registrationEndpoint:
        'http://keycloak.localdev/auth/realms/myrealm/clients-registrations/openid-connect',
    },
    clientId: 'myclient',
    redirectUrl: 'oauth://keycloak.localdev.me.com',
    scopes: ['openid', 'profile'],
    dangerouslyAllowInsecureHttpRequests: true,
  };

  try {
    const result = await authorize(config);
    console.log('Result is: ', result);
  } catch (error) {
    console.log('There is an error.', error);
  }
};
```
./android/app/build.gradle
```
    ...
    defaultConfig {
        manifestPlaceholders = [
                appAuthRedirectScheme: 'com.me.localdev.keycloak'
        ]
    }
   ...
```

./android/app/src/main/AndroidManifest.xml
```
        ...
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />

          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />

          <data android:scheme="com.me.localdev.keycloak" />
        </intent-filter>
        ...
```
After login to my identity provider the browser stays open for ever.

**Comment by Vamate** [comment]
The browser window closes for me and I’m back to my app and the promise still won’t resolve...

**Comment by joewired** [comment]
I ran into the same issue when starting a new project.

Turns out I was missing Step 3 of the installation:
https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate

**Comment by mashish584** [comment]
Thanks @badsyntax . You save my day.

**Comment by Jay-A-McBee** [comment]
Closing due to lack of response from OP.

**Comment by mnjsnj** [comment]
In my case ab360://Login/(Not working)  ab360://login/ (Working) only difference of case sensitive i don't know why it working like this

**Comment by LeeMoonki** [comment]
> In my case ab360://Login/(Not working) ab360://login/ (Working) only difference of case sensitive i don't know why it working like this

You save my time 🙏
