### ISSUE TITLE
Failed to Login. Network Error.

### ISSUE THREAD

**Issue by phanidharmot** [FormidableLabs/react-native-app-auth#605]
## Issue

The login flow works fine until I get authenticated and then I am seeing network error like in https://github.com/FormidableLabs/react-native-app-auth/issues/275
I am using this library for a quite a bit of time. Lately I am seeing this issue like since a month on Android. iOS works fine with no issue. I tried various versions of android studio and simulators and react-native version and the solution from the issue 275. Nothing helped. 

## Environment

* **Your Identity Provider**: Internal OAuth2.0 provider
* **Platform that you're experiencing the issue on**:  Android 
* **Are you using Expo?** No.

react-native-cli: 2.0.1
react-native: 0.63.1

"react-native-app-auth": "^6.0.1",

const configs = {
  identityserver: {
    issuer:'https://domain.com',
    clientId: <id>,
    clientSecret: <secret>,
    redirectUrl: <redirecturi>,
    scopes: ['openid', 'mobileapp'],
    serviceConfiguration: {
      authorizationEndpoint: 'https://domain/oauth2/authorize',
      tokenEndpoint: 'https://domain/oauth2/token',
    }
  },
};

**Comment by phanidharmot** [comment]
`<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">10.0.2.2</domain>
    </domain-config>
</network-security-config>` Allowing cleartexttraffic in main/res/xml/network_security_config.xml for debug mode fixed the issue

**Comment by tomjoj** [comment]
use in config
dangerouslyAllowInsecureHttpRequests: true,

**Comment by TirumaleswaraReddy** [comment]
I'm facing the same issue, I have tried all the above solutions but still have the same issue 'Error: Network error'

**Comment by hamjethm** [comment]
> use in config dangerouslyAllowInsecureHttpRequests: true,

Where should i add this ?
