### ISSUE TITLE
Return http code error when error occurs in authorize

### ISSUE THREAD

**Issue by MFrat** [FormidableLabs/react-native-app-auth#608]
Currently it is not possible to access http error code when error occurs in authorize method.

**Comment by Jay-A-McBee** [comment]
:wave: hey @MFrat  - sorry for not getting back to you sooner, but I don't think we'll be able to return the http error codes when an exception occurs. All error handling/mapping first passes through the native libraries authorization exception classes - (ex. [AuthorizeException](https://github.com/openid/AppAuth-Android/blob/ceb253b8118e481f3fe6f648772a8d16179a11fe/library/java/net/openid/appauth/AuthorizationException.java#L223)  class in AppAuth-Android).

Unfortunately the http response code is not returned to the calling code on the error object.
