### ISSUE TITLE
Peer dependency on React Native and README mismatch

### ISSUE THREAD

**Issue by acostalima** [FormidableLabs/react-native-app-auth#610]
## Issue

There is a peer dependency on React Native >=0.63.0 but the README states the latest version 6.2.0 is supported on React Native >=0.60.0. Which one is it? 😄

**Comment by masiddee** [comment]
Thanks @acostalima! 😅  We've updated the README to reflect this!

**Comment by acostalima** [comment]
@masiddee v6.2.0 seems to be working just fine on React Native 0.62.0, at least the `authorize` method does. I'm now wondering... where does the dependency on React Native 0.63.x comes from exactly?
