### ISSUE TITLE
Deeplinking scheme conflict on Android

### ISSUE THREAD

**Issue by badsyntax** [FormidableLabs/react-native-app-auth#611]
## Issue

Related to https://github.com/FormidableLabs/react-native-app-auth/issues/494

I've added a detailed comment about the issue here: https://github.com/FormidableLabs/react-native-app-auth/issues/494#issuecomment-797394994

While this might not be seen as a "bug", I feel the documentation and Example should be updated to show how to integrate this library on Android with existing deeplinking integration already in place.

It would be great if:

- The README was updated to mention how to handle auth redirect scheme, and existing deeplinking scheme on android 
- The Example was updated to show how to support auth redirect sheme and existing deeplinking scheme on android (preferably using https://reactnavigation.org/)
---

## Environment

* **Your Identity Provider**: Azure B2C
* **Platform that you're experiencing the issue on**: Android
* **Are you using Expo?** No

**Comment by pke** [comment]
I am also currently having the problem that the app will show a choice for the user after successful login.
Any hint in the readme how to combine deep linking and OAuth2 flow would be appreciated.

**Comment by masiddee** [comment]
@badsyntax thanks for the additional details! We've update the READMEs to reflect this change when implementing into a project that uses React Navigation deep linking.

**Comment by badsyntax** [comment]
awesome thanks @masiddee !

**Comment by JulianKingman** [comment]
I wasn't particularly happy with choosing a different scheme, so I found two different solutions:
1. If you have a defined list of hosts (ie `scheme://host`), you can filter them using `pathPattern`. Unfortunately there's no exclusion filter, so you can only filter specific paths.
2. You can create a custom deep link handler, I'm in the process of writing one myself. Most of the instructions are here: https://tech.justeattakeaway.com/2015/06/29/deep-linking-in-android-the-easy-way/, you also need to add app auth package to dependencies build.gradle (`implementation 'net.openid:appauth:0.8.1'`, as of this comment), and import and call `net.openid.appauth.RedirectUriReceiverActivity` from the IntentHelper.java file.

Hopefully that's enough for anyone to figure out.
