### ISSUE TITLE
Clarification on redirectUrl

### ISSUE THREAD

**Issue by badsyntax** [FormidableLabs/react-native-app-auth#615]
## Issue

Hi. This is more of a clarification question than an issue. I'm having some difficulty understanding the purpose of the redirectUrl. It seems in all cases it doesn't matter what the redirectUrl is, as long as it matches the auth provider settings and app sheme.  On successful auth, the app UI doesn't actually redirect to this url, and instead redirects back to the original screen from where the auth started. Is the AppAuth library handling the redirect url behind the scenes and then redirecting back to the original screen? If so can you confirm we can't actually build a "auth callback" screen in the app?
Many thanks.

---

## Environment

* **Your Identity Provider**: `Azure B2C`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

**Comment by badsyntax** [comment]
Hi @masiddee Sorry for tagging you but i'd love to get some clarification on this. It doesn't seem like the auth flow actually redirects back to deeplink as specified by the redirectUrl. Is this the expected behaviour?

**Comment by olosegres** [comment]
Man, redirectUrl is a part of oauth2 and this lib use it to handle response from auth server and resolve promise of `authorize` function. So you should handle this resolve and redirect user whatever you want in your app.

p.s. I was just passing by, sorting out another problem

**Comment by Jay-A-McBee** [comment]
The `redirectUrl` is what triggers the redirect from the browser (where the user logged in) back to your app (which has registered the redirect url's scheme as something the app should handle and not the browser.)

The UI displayed by your app when the user leaves to authenticate will be the same when the user returns until the state value that signifies the user is now authenticated is updated. On the initial return to your app, this state value hasn't updated yet so the user still sees the login page.

I'm not sure how avoidable this is, but it's outside of the scope of what this library does. Off the top of my head an alternative would be routing to the interstitial view on login button click. The interstitial view would handle the auth request, success, failure etc. Upon returning this would be the view the user sees and not the login page.

**Comment by badsyntax** [comment]
@Jay-A-McBee thanks for the suggestions. There's a couple different approaches I can take, now that I understand that redirectUrl is not used as a deeplink. (Imo docs could be improved to explain this.)

**Comment by Jay-A-McBee** [comment]
@badsyntax you can set up deep-linking to act on these incoming links - https://reactnative.dev/docs/linking.
