### ISSUE TITLE
iOS setup instructions conflict with reactnavigation

### ISSUE THREAD

**Issue by badsyntax** [FormidableLabs/react-native-app-auth#616]
## Issue

Hello. It would be great if the README provided some additional info to explain how to combine the auth redirect logic with existing deeplinking libraries.

The instructions for react-native-app-auth:

```diff
+ - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
+  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
+ }
```

The [instructions](https://reactnavigation.org/docs/deep-linking/#ios) for reactnavigation:

```diff

+ - (BOOL)application:(UIApplication *)application
+    openURL:(NSURL *)url
+    options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
+ {
+  return [RCTLinkingManager application:application openURL:url options:options];
+ }
```

It would be great if the README provided some guidance on how to combine the two. Something on the lines of:

```obj-c
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  if (SOME_CONDITION){
    return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
  } else{
    return [RCTLinkingManager application:application openURL:url options:options];
  }
}
```

I just don't what what `SOME_CONDITION` should be, to let the `authorizationFlowManagerDelegate` handle the redirect url. It would be awesome to provide an example in the README. 
 
---

## Environment

* **Your Identity Provider**: `Azure B2C`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

**Comment by masiddee** [comment]
Thanks for pointing this out @badsyntax! I've updated this README based on the suggestion by the original author in this [issue comment](https://github.com/FormidableLabs/react-native-app-auth/issues/342#issuecomment-530684621)
