### ISSUE TITLE
Support .well-known/oauth-authorization-server OAuth2 metadata discovery

### ISSUE THREAD

**Issue by ThiefMaster** [FormidableLabs/react-native-app-auth#617]
The format is pretty much the same as for the `.well-known/openid-configuration` OIDC metadata: https://tools.ietf.org/id/draft-ietf-oauth-discovery-08.html

**Comment by ThiefMaster** [comment]
OK looks like this might be better suited in the appauth-{android,ios} repos since it doesn't work with oauth-only metadata (no jwks or id token stuff in it) atm

**Comment by Jay-A-McBee** [comment]
👍 yeah @ThiefMaster - the discovery endpoint url comes from the native AppAuth libs. Closing this out as it's outside the scope.
