### ISSUE TITLE
org.openid.appauth.general error -3 on navigating to a page

### ISSUE THREAD

**Issue by antonabyzov** [FormidableLabs/react-native-app-auth#618]
## Issue

<code>
const config = {
      issuer: `${API}/my-security-api`,
      clientId: 'native.code',
      redirectUrl: 'my.domain:/callback',
      scopes: ['openid', 'profile']
    };
</code>

Library version `6.2.0`

It doesn't work with config. Identity Server 4 has client `native.code` configured correctly ("ClientName": "Native Client (Code with PKCE)").
It tries to open a page and navigates to Safari on mobile and it looks like tries to open correct domain in the url, but based on server logs it doesn't hit Login endpoint and finally displays Localhost in safari.
![image](https://user-images.githubusercontent.com/44438816/112640195-28ecc480-8e52-11eb-9fff-5e01aa662988.png)
![image](https://user-images.githubusercontent.com/44438816/112640372-56d20900-8e52-11eb-8931-8d5a3a2932c0.png)
![image](https://user-images.githubusercontent.com/44438816/112640658-96005a00-8e52-11eb-92eb-baebd61bb63b.png)

---

## Environment

* **Custom Identity Server 4**
* **iOS emulator (tried on 12, 5s) with iOS 14.4 and 12.1**
* **Not using Expo**

**Comment by leena-sharma** [comment]
@antonabyzov I am also facing same issue, 

How are you able to resolve it ?

**Comment by maoapp** [comment]
any solution for this ?

**Comment by Jay-A-McBee** [comment]
I found this [issue](https://github.com/IdentityServer/IdentityServer4/issues/1142) in the IdentityServer4 repo and I think this could be the cause behind what you are seeing. I'm closing this out for now. If adding a `response_mode` parameter does not have any effect, please open a new issue.
