### ISSUE TITLE
Authorization on iPhone 12 completes but returns empty page

### ISSUE THREAD

**Issue by emad0525** [FormidableLabs/react-native-app-auth#619]
## Issue

I copied the code given in the "Example" project but changed the provider specs to "dexcom". The authorization opens the login page for Dexcom, accepts the login credentials and returns empty page. In the developer console I noticed that the authState is empty. 

If I run the same process for the Identityserver provider as given in the Example project, the promise resolves successfully and returns with access token. 

I could share the code if needed. Any help would be greatly appreciated. 

Emad

---

## Environment

* **Your Identity Provider**: `e.g. Dexcom`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
:wave: hey @emad0525 - if this is still an issue please include your current configuration with private/secret info redacted (client id, etc.).

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
