### ISSUE TITLE
Support Custom User-Agents on iOS

### ISSUE THREAD

**Issue by martin-shaw** [FormidableLabs/react-native-app-auth#622]
AppAuth-iOS supports custom user agents https://github.com/openid/AppAuth-iOS#custom-user-agents-ios-and-macos https://github.com/openid/AppAuth-iOS/issues/200

I'm planning to fork and add this feature to support the out of the box custom browsers in AppAuth-iOS plus other custom browsers. My requirement is to support https://www.vmware.com/uk/products/workspace-one/enterprise-mobile-browser.html

I have found this feature has been requested here https://github.com/FormidableLabs/react-native-app-auth/issues/471

My question is, if I go ahead and add this feature to my fork is it likely to be accepted as a feature back into the main project?

**Comment by ULTiALAt** [comment]
I'd be interested in this feature being added

**Comment by TonyFTannous** [comment]
I'd be interested in this feature being added, any news
