### ISSUE TITLE
Stuck after completing Login process with Azure

### ISSUE THREAD

**Issue by aditya38112** [FormidableLabs/react-native-app-auth#623]
I have a react-native app in which for Android alone I have made the required changes to use react-native-app-auth, and I have tried v1.0 and 2.0 both endpoints for the login process, what is happening for me is that it is coming to the stage where it asking 
"Are you trying to sign in to MobileAppClient", then It is getting stuck there, and clicking "Cancel" and "Continue" both have no result, after sometime clicking them results in "the user can not be signed in". So am I doing it wrong in the case of appAuthRedirectScheme in the Gradle file?

Have anyone faced this issue, please help

Your Identity Provider: Azure
A platform that you're experiencing the issue on Android
Are you using Expo? : NO
[
![msalissue](https://user-images.githubusercontent.com/20928906/114318531-0681c900-9b2b-11eb-8237-8322faea7742.jpg)
](url)

**Comment by redwind** [comment]
The same to me. After click continue, login page close without any message or error log. The first, i though it cause by redirect scheme is not working, but i tested app scheme by open it from browser and it work. 

Your Identity Provider: Azure
A platform that you're experiencing the issue on iOS
Are you using Expo? : NO

**Comment by redwind** [comment]
@aditya38112 found the solution
`**Important** When you add your app in the azure portal and are given a `redirectUrl` to use, make sure you add a trailing slash when you add it to your config - e.g. `msauth.BUNDLEID://auth/` - failure to add that causes it to fail in IOS.`

**Comment by aditya38112** [comment]
Hi, I have tried it but it is not working for Android, and my case is different than yours as in I get the MobileAppclient window after completing 2MFA where I remain stuck. But thanks for replying.

**Comment by francesco-clementi-92** [comment]
I have the same problem. Did you manage to fix it?

**Comment by aditya38112** [comment]
Nope finally I used react-native-msal

**Comment by brijpatel6080** [comment]
Getting the error after installing the react-native-msal plugin when build bundle can you explain how to install properly ? @aditya38112

**Comment by Jay-A-McBee** [comment]
Closing this out due to lack of configuration info and topic drift.

**Comment by akravchukabto** [comment]
Hi, for me the issue was called by wrong 
**appAuthRedirectScheme** entry in **build.gradle**
removing the wrong entry fixed the issue.
