### ISSUE TITLE
Issue with redirect URIs in Azure auth when using non HTTP URI

### ISSUE THREAD

**Issue by aditya38112** [FormidableLabs/react-native-app-auth#624]
So, I am facing an issue that using non HTTP URIs lead me to this page where no button works, but when I use a HTTP URL then it opens that link in the browser and no redirect happens, I found one issue related to that,(https://stackoverflow.com/questions/63577935/desktop-app-microsoft-authentication-error), so can someone please suggest me what to do here?

![msalissue](https://user-images.githubusercontent.com/20928906/114693631-6ea4fa80-9d37-11eb-9cbc-2f546958940c.jpg)

* Your Identity Provider: Azure
* Platform that you're experiencing the issue on: Android
* Are you using Expo? : No

**Comment by badsyntax** [comment]
Can you provide the redirect url you're using? Also have you registered the redirect url in the app registration?

**Comment by paulorod07** [comment]
@aditya38112 Did You find any solution?
I am getting the same error

**Comment by aditya38112** [comment]
The issue was that I needed to use web view in some way as other methods like the browser are not trusted by AAD, so I finally used react-native-msal in which we can provide custom parameters to show webview and it resolved my issue.

**Comment by liatnetach** [comment]
@aditya38112 , can you please explain a little bit more what you did so https redirect url will actually redirect the user?

currently when Im using non http scheme it redirect me and everything is working.
but I need https redirect_uri and it doesn't redirect me after , just stack in the web session the autorize() opened.

I defined my native redirectActivity similar to that:

`<data android:scheme="https"
              android:host="users.dot.com"
              android:path="/auth/sso"/>`
  (and this is the **redirect_uri** in the config- https://users.dot.com/auth/sso)

**Comment by Jay-A-McBee** [comment]
I was able to set up and Azure AD tenant and login using the following config.
```
{
  issuer:
      'https://login.microsoftonline.com/<TENANT-ID>/v2.0/',
    clientId: <CLIENT ID>,
    redirectUrl: 'example.myapp.com://oauth/',
    scopes: [ 'openid', 'offline_access']
}
```

Closing this out - unable to replicate. @aditya38112 feel free to open a new issue if you think we can help.
