### ISSUE TITLE
[Question] There is some way to get internal error on auth endpoint?

### ISSUE THREAD

**Issue by Gitarcitano** [FormidableLabs/react-native-app-auth#627]
## Question

Is some way to get an error when the auth page is loaded with an internal error like below?

![image](https://user-images.githubusercontent.com/44866256/115735076-92cc9100-a360-11eb-9779-15e92fc89311.png)

I want to catch this error to report to Sentry, but I don't found any way to do that

---

## Environment

* **Your Identity Provider**: `internal OAuth`
* **Platform that you're experiencing the issue on**: ` both`
* **Are you using Expo?**: No

**Comment by Jay-A-McBee** [comment]
500 is an internal server error - Since you are using an internal idp, why not report this error server side or have this page that is loading in a browser tab report it? Closing this out - This error is occurring within the idp's code and not the code of this library or the backing libraries.
