### ISSUE TITLE
Missing AppAuth-Library on Android 11

### ISSUE THREAD

**Issue by martinhellwig** [FormidableLabs/react-native-app-auth#632]
## Issue

We experienced some problems by using this library on some Android phones. When we want to start the "authorize"-method, we only get an error with the info "Error: Error not specified". No Authorization-Flow is started at all. Normally a new Overlay with a Chrome-Tab inside will be opened.

After some research we found out, that the issue is only present on Android 11 devices. Android 10 and below are working as expected. We upgraded to the newest version of this library as well as using the newest Android sdks:
- CompileSDK: 30
- TargetSDK: 30
- buildToolsVersion: 29.0.3

Also the entry "<activity android:name="net.openid.appauth.AuthorizationManagementActivity" />" in the AndroidManifest is red, because the needed AppAuth-Android library is not added as a dependency at all.
The only way to fix this issue for now is to add the android-dependency manually in the build-gradle as follows:
`implementation 'net.openid:appauth:0.8.1'`

Maybe there is some issue with using your newest SDK together with the Android-SDK 30 running on Android 11 phones?

---

## Environment

* Identity Provider: Keycloak
* Platform: Android 11 (Android SDK 30)
* We are using Expo

**Comment by rishabhrathod** [comment]
Hi @martinhellwig, 
How did you arrive to this `net.openid:appauth:0.8.1` ? 
I am using older version of the library and which works well for Android 10 and older but not with 11
Can you please let me know where can I look for this information.

I am pretty new to this, so please pardon if it sounds naive.
Thanks in advance :)

**Comment by rishabhrathod** [comment]
Hi @martinhellwig ,
I am getting following error when I try to update the build-gradle of this package, 
from implementation `'net.openid:appauth:0.7.1'` to `implementation 'net.openid:appauth:0.8.1'`
Did you face the following error, if yes can you please help? 

`AAPT: error: unexpected element <queries> found in <manifest>.`

Thanks in advance :)

**Comment by kadikraman** [comment]
This should be fixed with https://github.com/FormidableLabs/react-native-app-auth/pull/630

**Comment by thijs-qv** [comment]
> `AAPT: error: unexpected element <queries> found in <manifest>.`
Perhaps you need to update your Gradle plugin, see https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html
