### ISSUE TITLE
useNonce not passed to Android

### ISSUE THREAD

**Issue by yll090** [FormidableLabs/react-native-app-auth#638]
## Issue

I'm working on a RN app that needs to connect to an inhouse built (it is still WIP) auth server. The backend team does follow strictly the OIDC protocols, so I have no problem connecting to it, however, as it is still being worked on, issues with it occur. For example, it's missing a nonce when returning the payload, so validating the token fails. While that's good for me to send as feedback, I believe there is a setting to disable the nonce check altogether -- `useNonce`. However, if you check the implementation over [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/index.js#L200), only iOS is being sent that config flag, not Android. Is there a specific reason for that that I'm unaware? This sounds like a bug to me, but if there is something else I'm missing -- please let me know.

---

## Environment

* **Your Identity Provider**: `Custom inhouse`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?**: No

**Comment by mmitjans** [comment]
Currently is not supported for Android. The new android auth library now exposes a method ```setNonce```. In iOS the nonce is generated via a random number generator `SecRandomCopyBytes`.

For android there's a class named `SecureRandom` which can be used to generate the nonce and set it into the AuthorizationRequest.Builder.

**Comment by yll090** [comment]
@mmitjans What do you mean it's not supported? The nonce is missing when I get it returned _from_ the backend, it's not missing when I send it _to_ them, I can clearly see it's generated on the client. I am asking if we can straight up skip it in case of developing the auth server and it missing features. iOS respects the missing nonce while Android doesn't, it should be at least in the docs. As to why that is -- there is a flag `useNonce` that is _not_ delegated to the method over [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L161) so it can be skipped as it's supported over [here](https://github.com/openid/AppAuth-Android/blob/ceb253b8118e481f3fe6f648772a8d16179a11fe/library/java/net/openid/appauth/AppAuthConfiguration.java#L52).

In any case, I'll `patch-package` it so it works in my case, but am not sure why the 2 platforms need to have different behaviors.

**Comment by SleipRecx** [comment]
> @mmitjans What do you mean it's not supported? The nonce is missing when I get it returned _from_ the backend, it's not missing when I send it _to_ them, I can clearly see it's generated on the client. I am asking if we can straight up skip it in case of developing the auth server and it missing features. iOS respects the missing nonce while Android doesn't, it should be at least in the docs. As to why that is -- there is a flag `useNonce` that is _not_ delegated to the method over [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L161) so it can be skipped as it's supported over [here](https://github.com/openid/AppAuth-Android/blob/ceb253b8118e481f3fe6f648772a8d16179a11fe/library/java/net/openid/appauth/AppAuthConfiguration.java#L52).
> 
> In any case, I'll `patch-package` it so it works in my case, but am not sure why the 2 platforms need to have different behaviors.

We experienced the same thing, `useNonce=false` is not respected on Android, submitted a PR that should fix this issue.
