### ISSUE TITLE
unknown field "nonce"

### ISSUE THREAD

**Issue by Cannonball2134** [FormidableLabs/react-native-app-auth#645]
Hi All,

I am trying to connect to dropbox but I get an unknown field "nonce" error from dropbox when using the example code:

`
const config = {

clientId: 'your-client-id-generated-by-dropbox',
  clientSecret: 'your-client-secret-generated-by-dropbox',
  redirectUrl: 'https://native-redirect-endpoint/oauth/dropbox',
  scopes: [],
  serviceConfiguration: {
    authorizationEndpoint: 'https://www.dropbox.com/oauth2/authorize',
    tokenEndpoint: `https://www.dropbox.com/oauth2/token`,
  },
  useNonce: false,
  usePKCE: false,
};

// Log in to get an authentication token
const authState = await authorize(config);
const dropboxUID = authState.tokenAdditionalParameters.account_id;
`

 useNonce is false, so i assume there shouldn't be a nonce field anyway. 

I haven't been able to test on another device, but this issue appears on a OnePlus 5T mobile phone running Android 10, and i am not using expo. 

This is possibly related to issue #638

**Comment by Jay-A-McBee** [comment]
closing - fixed by https://github.com/FormidableLabs/react-native-app-auth/pull/640.
