### ISSUE TITLE
'AppAuth.h' file not found

### ISSUE THREAD

**Issue by victorious85** [FormidableLabs/react-native-app-auth#647]
## Issue

I am using  version 6.3.0
But faced with issue 'AppAuth.h' file not found.

I download your Example and I got the same error.
---

## Environment

    "react-native": "0.63.4",
    Xcode 12.4
   Platform that you're experiencing the issue on**: `iOS`

![Screenshot 2021-06-08 at 17 32 12](https://user-images.githubusercontent.com/25690337/121204299-78526680-c87f-11eb-92e1-18bfeff44743.png)

**Comment by Lapaenergy** [comment]
I have faced the same issue, whats going on ?

**Comment by ivan-khr85** [comment]
@victorious85 
Do you have any solution for this issue?

**Comment by jpdriver** [comment]
hey @victorious85 -- thanks for opening this issue.

i haven't been able to recreate this; so please can you provide the list of what steps you took before seeing this?

i tried:-

1. `git clone`
2. `cd /Example`
3. `yarn`
4. `cd ios`
5. `pod install`
6. `open Example.xcworkspace`

`⌘` + `B` (build)

<img width="1130" alt="Screen Shot 2021-07-08 at 1 45 20 PM" src="https://user-images.githubusercontent.com/2393035/124988561-fe82d980-dff2-11eb-917c-733534c04960.png">

that built successfully without issue and if i browse to that same file I don't see any warnings..

**Comment by victorious85** [comment]
I have resolved my problem. The problem was with cash packages in CocoaPods.

Sreps: 
1) yarn cache clean
2) delete pods, Podfile.lock, workspace
3) rm -rf ~/Library/Caches/CocoaPods
4) rm -rf ~/Library/Developer/Xcode/DerivedData
5) Xcode > product > clean build folder
6) yarn install
7) pod update from ios directory
8) launch build from Xcode

**Comment by jpdriver** [comment]
glad to hear you got it working. if you need any more help, please don't hesitate to reach out
