### ISSUE TITLE
Open links in auth page in same browser view not in app

### ISSUE THREAD

**Issue by pke** [FormidableLabs/react-native-app-auth#648]
It seems with universal linking enabled all links in the auth page that point to the associated app domain are tried to be opened in the app while they should be opened in the same view or an external browser?

I know there is no way to prevent the OS from opening the app when the universal links are configured to be "catch all". But shouldn't the RN-App-Auth view sheet be able to intercept links and load them within the current open view?

**Comment by Jay-A-McBee** [comment]
Universal links can be configured to be more granular - see the [applinks config here](https://developer.apple.com/documentation/bundleresources/applinks).  Closing this out - beyond the scope of this library.
