### ISSUE TITLE
Feature request: Decoding id_token

### ISSUE THREAD

**Issue by PeterKottas** [FormidableLabs/react-native-app-auth#65]
Hi gents, I was working with auth again a little bit and found a possible improvement. It would be of reasonable value to add id_token decoding imho. It appears to be an easy task with a lot of potential value. There's apparently 2 libs to choose from https://jwt.io/#libraries-io. Oidc-client which is kind of web equivalent of what you have here is doing it. It's handy to be able to get user id, email, username and so on hassle free. What do you think?

**Comment by PeterKottas** [comment]
Typescript interface for storing decoded token as a reference 
```
export interface OidcProfile{
  sid: string;
  //User id
  sub: string;
  auth_time: number;
  idp: string;
  amr: string[];
  preferred_username: string;
  name: string;
}
```
This is what I have atm. There is for sure more stuff that might fall out of there depending on the provider.

**Comment by PeterKottas** [comment]
Yeah checking the docs, there's plenty of stuff there :D https://auth0.com/docs/tokens/id-token

**Comment by jevakallio** [comment]
Hi! Thanks for the suggestion! We'll review and see if this is something we want to incorporate.

Just a note for future reference, the creator and primary maintainer of this library is not a "gent" 😉

**Comment by PeterKottas** [comment]
Oh my apologies, I only talked with the male part of the team so far so I jumped to conclusion. Hope you won't think less of me. Anyways, hope it works out with the feature, I think it could be rly good to have it in there 👍

**Comment by jevakallio** [comment]
No worries @PeterKottas! We'll look at this when we have a chance, right now the team is busy with other projects.

**Comment by kadikraman** [comment]
Hi @PeterKottas thanks for the suggestion! Decoding the token with [jwt-decode](https://github.com/auth0/jwt-decode) is as easy as
```js
import jwt_decode from 'jwt_decode';

const token = 'eyJ0eXAiO...'; // jwt token

const decodedToken = jwt_decode(token);
console.log(decodedToken);

// {
//   foo: "bar",
//   exp: 1393286893,
//   iat: 1393268893
// }
```

So I'm not sure how much benefit there is in importing `jwt_decode` from the library vs directly as there is nothing tricky in the middle.

We are currently not handling token storage/auto-refresh/requests, however if we do decide to do that in the future, then this feature would be useful, as it would help make react-native-app-auth a one-stop-shop for all your native auth needs.

So leaving this open for now, but no plans to implement it yet unless of course there's much more interest 😊

RE: gents - I don't know, I recon I could pull off a top hat/monacle combo if it came to it 🎩 😄

<img src="https://user-images.githubusercontent.com/6534400/37661398-9bcce9f0-2c4c-11e8-9761-f0a27d20b211.png" width="200" />

**Comment by PeterKottas** [comment]
Hey, yeah you're totally right. Biggest reason for putting it in is the one-stop-shop thing. Same logic is actually followed by https://github.com/IdentityModel/oidc-client-js (they have it build into it) but I agree this should mainly be considered if you go forward with #55 
Lol about the hat/monacle combo. Doesn't get more hipster than that I guess :D

**Comment by coopbri** [comment]
I know this thread is old, but I agree completely with @PeterKottas. It's really nice using OIDC client libraries that have JWT decoding built into the library, as well as a built-in hooks, such as in https://github.com/react-keycloak/react-keycloak.

Of course, it's easy enough to implement these things yourself, but I also vibe with the "one-stop shop" mentality (with escape hatches/customizability)!
