### ISSUE TITLE
iOS OAuth callback on-error behaviour differs from Android

### ISSUE THREAD

**Issue by pond** [FormidableLabs/react-native-app-auth#653]
## Issue

I'm entering this issue because I already have a PR to fix it (in draft at the time of writing while I check on tests - see #654), and the PR template requires an issue number.

When handling OAuth callback URI errors with `error` and (optionally) `error_description` parameters, on Android we see a raised exception from React Native App Auth where `error.code` contains the value that was in the `error` query string parameter and `error.message` contains the value that was in the `error_description` query string parameter. This makes sense; we get to access the server's error information and choose how or if to present relevant related information to the user.

On iOS, the integration with AppAuth-iOS differs from the Android layer by composing `error` and `error_description` into a single string that's put into `error.message`, e.g. `server_error: Foo`. This is inconsistent and can be obstructive, especially if one "owns" both the app and the server-side implementation, with the server side presenting information that we, as end-to-end system creators and maintainers, _do_ intend to show to the user.

It's easy to fix since AppAuth-iOS includes a complete dictionary of query parameters in the `NSError` object's `userInfo`, allowing us to extract the relevant information.

## Environment

* **Your Identity Provider**: All
* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?**: I don't know what that is, so probably - no!

**Comment by whithajess** [comment]
@kadikraman Any change of a release for this fix? Thanks.
