### ISSUE TITLE
`authorize` and `refresh` should return response context

### ISSUE THREAD

**Issue by alexander-joinlane** [FormidableLabs/react-native-app-auth#657]
## Context

I don't know if I'm just absolutely missing something about this, but the nature of the token acquisition methods primarily focus on the typically more important response objects (`accessToken`, `accessTokenExpirationDate`, `idToken`, `refreshToken`, etc...).

My use-case involves authorization a user via AzureAD (PKCE) which works fantastically and yields those fields as expected.

Continuing on that line of reasoning the AzureAD domain has additional apps who would essentially authenticate the same way (same credentials, same MFA, same `iss` and `sid`, PKCE not strictly required as that would likely occur via a `WebView`).

When my mobile app (iOS/Android) is opened to such an application, I would like to be able to provide it with session context (the cookies/headers that would likely have been provided during the 'Redemption of challenge for token' portion of PKCE).

If anyone is aware of a means that I can safely and securely provide context to these additional applications, I would also be very grateful.

## Possible Complication

- It's possible the such a context cookie is set in the response on the Microsoft portion of the response (during redirects) and would be unavailable to `react-native-app-auth`

**Comment by Jay-A-McBee** [comment]
:wave: hey @alexander-joinlane - I'm not sure that anything needs to be done to enable this. The native backing libraries (AppAuth-ios/Android) both implement a user agent that should enable persistent cookies to be shared.

AppAuth-ios docs
>AppAuth ships with several implementations of an external user-agent out of the box, including defaults for iOS and macOS suitable for most cases. **The default user-agents typically share persistent cookies with the system default browser, to improve the chance that the user doesn't need to sign-in all over again.**

AppAuth-Android uses a ["custom tabs" implementation ](https://developer.chrome.com/docs/android/custom-tabs/). One of the main benefits of using custom tabs:
>Shared cookie jar and permissions model so users don't have to sign-in to sites they are already connected to, or re-grant permissions they have already granted.

On both platforms the cookies from the "custom tab" should be shared with the default browser. 

Let me know if that lines up with what you think or if I'm missing something.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
