### ISSUE TITLE
Error while refreshing token with refresh method : "Credentials in post body and basic Authorization header do not match" 

### ISSUE THREAD

**Issue by mohalepooja** [FormidableLabs/react-native-app-auth#658]
Hi Team,

We have created desktop type app on GCP console. Our configuration contains issuer. clientId, redirectUrl, scopes and clientSecret. We are able to autherize user by using authorize method but while refreshing token using refresh method we get  error message "Credentials in post body and basic Authorization header do not match". 
We have checked all values which we are passing are correct this is only happening with third party google login our microsoft login is working fine. 

Library version: 5.1.2

Could you please look into issue urgently?

**Comment by Jay-A-McBee** [comment]
:wave: hey @mohalepooja - This issue has been around for a while. If you haven't already, could you try updating to the latest version of the library `6.4.2`?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
