### ISSUE TITLE
Support for login without using SSO IOS

### ISSUE THREAD

**Issue by sattaman** [FormidableLabs/react-native-app-auth#66]
I'm not sure whether this is supported by appauth-ios or not , but I'd like to sign in without using SSO and so remove the popup box that appears, and also share my id server cookie with my safari views., which we are currently breaking out into for certain bits of functionality which will not work (https://github.com/openid/AppAuth-iOS/issues/120).

They suggest on to edit the code directly here

https://github.com/openid/AppAuth-iOS/issues/182

I'm not an objective c developer though so any advice on how I'd  be able to get this working with your library would be appreciated.

**Comment by jevakallio** [comment]
@sattaman thanks for submitting this issue. 

I believe you could achieve this by implementing a custom `OIDAuthorizationUICoordinator` (as in https://github.com/openid/AppAuth-iOS/issues/200) and passing that to as the UICoordinator parameter to `authStateByPresentingAuthorizationRequest` in RNAppAuth: https://github.com/FormidableLabs/react-native-app-auth/blob/master/ios/RNAppAuth.m#L151

If I understand the API correctly, you should be able to do this without forking AppAuth-iOS.

We can take this feature into consideration, but it's not likely to be a high priority or get implemented quickly. If you do end up implementing this, I would love to see your work or a PR with the same.








https://github.com/openid/AppAuth-iOS/issues/200

**Comment by sattaman** [comment]
ok thanks for your reply , ill have a play

**Comment by sattaman** [comment]
To follow up , I actually just edited the app-auth-ios library in the end , commenting out the lines metioned openid/AppAuth-iOS#182.

**Comment by j-petty** [comment]
Is this something that is supported as part of the library now?
