### ISSUE TITLE
Error when trying to compile on iOS

### ISSUE THREAD

**Issue by AlysCole** [FormidableLabs/react-native-app-auth#660]
## Issue

I followed the steps as written in the documentation using Cocoapods. When I try to build the app, this error comes up:

```
duplicate symbol '_taskId' in:
    /Users/macbookair/Library/Developer/Xcode/DerivedData/*****-afgsdxvymoklbzewpcpgrfdslmhi/Build/Products/Debug-iphonesimulator/A0Auth0/libA0Auth0.a(A0Auth0.o)
    /Users/macbookair/Library/Developer/Xcode/DerivedData/*****-afgsdxvymoklbzewpcpgrfdslmhi/Build/Products/Debug-iphonesimulator/react-native-app-auth/libreact-native-app-auth.a(RNAppAuth.o)
ld: 1 duplicate symbol for architecture x86_64
```

It looks like there's a conflicting symbol between Auth0 and react-native-app-auth. Has anyone come across this issue?

---

## Environment

* **Platform that you're experiencing the issue on**: iOS
* **Are you using Expo?** No

**Comment by oferRounds** [comment]
Hey @AlysCole, have you found solution to this issue? Seeing it also
