### ISSUE TITLE
SAML 2.0 Authentication with Azure Active Directory?

### ISSUE THREAD

**Issue by Atin007** [FormidableLabs/react-native-app-auth#661]
## Issue

Can I use this package for building an app for an enterprise client using SAML 2.0 authentication with Azure Active Directory? If yes, how to do it?

---

## Environment

* **Your Identity Provider**: `Azure Active Directory`
* **Platform that you're experiencing the issue on**: `iOS (React Native)`
* **Are you using Expo?** No

**Comment by vitorverasm** [comment]
I'm searching for this too!

**Comment by Atin007** [comment]
Not yet.

**Comment by jpdriver** [comment]
hey @Atin007 

yes -- this library fully supports Azure AD. You can find a usage guide [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/azure-active-directory.md)

if you have a specific question or issue please feel free to reopen this
