### ISSUE TITLE
Facebook deprecating login support on Android WebViews?

### ISSUE THREAD

**Issue by ganeshpatil3** [FormidableLabs/react-native-app-auth#667]
We are using “react-native-app-auth” plugin for OAuth, after Facebook deprecating login support on Android WebViews from  5 Oct 2021 will having any impact on our production?

After Facebook deprecating login support on Android WebViews our application will work as it is or we require to do any implementation changes ?

Any help or suggestion will be valuable for us.

**Comment by ganeshpatil3** [comment]
Reminder,
    As we have less than one month facebook stop login from webviews, as we are using the "react-native-app-auth" for facebook login. But we are not sure the "react-native-app-auth" library is internally using webview or custom tabs for facebook login. 

Please update after Facebook stops login support on Android WebViews our application will work as it is or we require to do any implementation changes ?

**Comment by ganeshpatil3** [comment]
Hi,
   Anyone can confirm that after facebook stops login from webview, will that impact on our facebook login  using "react-native-app-auth" library. We are waiting for confirmation from "react-native-app-auth" library but didn't get any comments that it will impact or will not impact on current production app.

**Comment by Jay-A-McBee** [comment]
Closing this out - The backing library `AppAuth-Android` uses custom tabs when available so this should not be an issue.
