### ISSUE TITLE
[Error: invalid_request: client_secret: This field is required. client_id: This field is required.]

### ISSUE THREAD

**Issue by dev-apps-code** [FormidableLabs/react-native-app-auth#668]
Im using HTTPS as for my redirect url, thats why im using universal linking, everything works on android im receiving the results and responses well, but on IOS after allowing auth safari closes and the app logs this [Error: invalid_request: client_secret: This field is required.
client_id: This field is required.]

**Comment by Jay-A-McBee** [comment]
Is the config object identical to what you are using for Android?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
