### ISSUE TITLE
FitBit: Non-200 HTTP response (401) making token request to 'https://api.fitbit.com/oauth2

### ISSUE THREAD

**Issue by AshCoolman** [FormidableLabs/react-native-app-auth#670]
## Issue

`authorize` raises this exception in JavaScript:
```
Non-200 HTTP response (401) making token request to 'https://api.fitbit.com/oauth2
```
which includes:

```
  "{\"errors\":[{\"errorType\":\"invalid_client\",\"message\":\"Invalid authorization header format. The header was not recognized to be a valid header for any of known implementations or a client_id was not specified in case of a public client Received header = null. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process.\"}],\"success\":false}"
```

---

## Background

Our web authflow for Fitbit takes the auth `code` (appended to `redirect_url` by FitBit) and sends that to a backend endpoint we wrote, which gets the token.

We do this because we do not want the `client_secret` in the client code.

## The problem

My understanding is that this library assumes the responsibility of requesting the token (which it fails to do due to the lack of client_secret).

**Question**: Is there a way to stop this library from doing this - or is it simply the way this library works?

## Environment

* FitBit
* iOS
* Not using Expo

**Comment by Jay-A-McBee** [comment]
:wave: hey @AshCoolman - you can pass `skipCodeExchange: true` on the object you're passing to the authorize function. This will allow you to receive the code and exchange it for a token server side.  Let me know if this works for you.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
