### ISSUE TITLE
Support for Auth0 Social Login

### ISSUE THREAD

**Issue by therunbuddy** [FormidableLabs/react-native-app-auth#673]
Would it be possible to add support for Auth0 social login so that you can login via google/facebook without having to open the Auth0 universal login page?

**Comment by Jay-A-McBee** [comment]
:wave: hey @therunbuddy - this is outside of the scope of this library. This library doesn't support any one specific provider. It is a wrapper around the native libraries AppAuth-iOS and AppAuth-Android. These libraries also don't support any specific providers. These libraries provide convenience methods to interact with authentication providers (servers) that implement the Open ID connect/oAuth 2.0 specification.
