### ISSUE TITLE
[Android] No redirect back to the app

### ISSUE THREAD

**Issue by anisimov74** [FormidableLabs/react-native-app-auth#674]
## Issue

There is no redirect back to the app, If `MainActivity` in the Manifest.xml contains `android:taskAffinity=""`.
This settings should prevent possible phishing via task hijacking.

---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `Android`
* **Pure React Native project**

**Comment by Jay-A-McBee** [comment]
This sounds like it's outside the scope of this library. If the consuming app sets `taskAffinity` or `launchMode` differently, it would be the consuming app's responsibility to  implement alternate handling of incoming intents.

**Comment by hpelitebook745G2** [comment]
@anisimov74 I also have this issue and verified that adding `taskAffinity=""` causes the redirection not to work. It was advised by our Penetration Tester to have our app add this attribute to prevent task hijacking.

Any workarounds?

**Comment by anisimov74** [comment]
@hpelitebook745G2 I had to remove `taskAffinity=""` and live with `android:launchMode="singleInstance"` only.
