### ISSUE TITLE
java.lang.NullPointerException error

### ISSUE THREAD

**Issue by mharrisweb** [FormidableLabs/react-native-app-auth#676]
## Issue

WHen using the latest version 6.4.0 I get the error below can anyone help?

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.openid.appauth.IdToken.validate(IdToken.java:141)
	at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:698)
	at net.openid.appauth.AuthorizationService$TokenRequestTask.onPostExecute(AuthorizationService.java:564)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

```

---

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`

* **Platform that you're experiencing the issue on**: `iOS / Android / both`

Android

* **Are you using Expo?**

No

**Comment by ANIBIT14** [comment]
I am also getting the same error 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

Stack trace is

com.rnappauth.RNAppAuthModule.onActivityResult RNAppAuthModule.java:419
com.facebook.react.bridge.ReactContext.onActivityResult ReactContext.java:305
com.facebook.react.ReactInstanceManager.onActivityResult ReactInstanceManager.java:762
com.facebook.react.ReactDelegate.onActivityResult ReactDelegate.java:90
com.facebook.react.ReactActivityDelegate.onActivityResult ReactActivityDelegate.java:112
com.facebook.react.ReactActivity.onActivityResult ReactActivity.java:68
android.app.Activity.dispatchActivityResult Activity.java:8550
android.app.ActivityThread.deliverResults ActivityThread.java:5534
android.app.ActivityThread.handleSendResult ActivityThread.java:5582
android.app.servertransaction.ActivityResultItem.execute ActivityResultItem.java:51
android.app.servertransaction.TransactionExecutor.executeCallbacks TransactionExecutor.java:135
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:95
android.app.ActivityThread$H.handleMessage ActivityThread.java:2317
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:246
android.app.ActivityThread.main ActivityThread.java:8595
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:602
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1130

Can anyone tell what might be causing it

**Comment by justinairbase** [comment]
@ANIBIT14 Your issue is related to #672

**Comment by Jay-A-McBee** [comment]
:wave: hey @mharrisweb - If you can give us more information (identity provider, config, etc.),  we can try to help with this issue. 

@ANIBIT14 - your issue is unrelated. Your error occurs in the `onActivityResult` handler. The OP's error is being thrown by the backing native library `AppAuth-Android`.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by thomasrose** [comment]
I ran into the same issue, albeit using FusionAuth. The `issuer` in the FusionAuth tenant was configured without a protocol (e.g. `example.com` instead of `https://example.com`). Adding `https://` resolved the problem.
