### ISSUE TITLE
authentication_failed Error messages

### ISSUE THREAD

**Issue by sanjib-tatva** [FormidableLabs/react-native-app-auth#677]
Getting authentication_failed Error messages in Values  on the code field only in iOS, in android working fine.

**Comment by Jay-A-McBee** [comment]
:wave: hey @sanjib-tatva - we need more information to try and work with you on this. 

- What identity provider are you using? 
- What is your configuration object?, etc. 

 I'm closing this issue - If it's still a problem, please open a new issue and include the relevant information.
