### ISSUE TITLE
On login success, the scopes in the response are empty. 

### ISSUE THREAD

**Issue by Goutham-Elangovan** [FormidableLabs/react-native-app-auth#678]
## Issue
I'm trying to use login using Azure active directory. The login succeeds but the response after success returns "scopes:[]"

I'm assuming that this is the reason why im not able to succeed my API call. It currently returns [401 error.](geeksforgeeks.org/how-to-fix-a-401-unauthorized-error/#:~:text=The%20401%20Unauthorized%20Error%20is,request%20could%20not%20be%20authenticated.) (accessToken is appended in the header section as Bearer token while making the call).

Any leads would be really helpful

---

## Environment

* **Your Identity Provider**: Azure
* **Platform that you're experiencing the issue on**: `both emulators, havent tried on a device yet`
* **Are you using Expo?** - NOPE!!!

**Comment by anujraghuvanshi** [comment]
Hi @Goutham-Elangovan - Did you get solution of your issue ?  I am also having same issue.

**Comment by Goutham-Elangovan** [comment]
@anujraghuvanshi I used https://www.npmjs.com/package/react-native-msal and it worked in my case.
