### ISSUE TITLE
invalid request

### ISSUE THREAD

**Issue by yudiz-harshad** [FormidableLabs/react-native-app-auth#680]
## Issue

https://sso.sbx.edenred.io/connect/authorize?response_type=code_id=989acfb423ba4f9f944f1819da89abe7=openid%20edg-xp-mealdelivery-api%20offline_access_uri=http://nowhere.edenred.com/callback=abc123=456azerty_values=tenant:tr-ben_locales=tr

When i try to open this url in web it redirect me to auth page but in react native app its not working and giving error of invalid_request. Below is the code that i am using in react native.

                        clientId: '989acfb423ba4f9f944f1819da89abe7',
                        clientSecret: '07ca6ded7b9b4801a405c65acd7538b5',
                        redirectUrl: 'com.tamam:/oauthredirect',
                        serviceConfiguration: {
                            authorizationEndpoint: 'https://sso.sbx.edenred.io/connect/authorize',
                            tokenEndpoint: 'https://sso.sbx.edenred.io/connect/token',
                        },
                        additionalParameters: { prompt: 'login', },
                        scopes: ['openid', 'profile', 'email', 'offline_access'],

---
Can anyone one  help me out with this like how i can make it work for react native i tried to pass additionalParameters but still
i was getting same error..
## Environment

* **Your Identity Provider**: `Edenred`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by haresh12** [comment]
> Your re-direct URL should be something like this "com.example://react-native-auth/". You are missing slashes!

Actually in library code example you can see that it has single / redirect url and when I was using that it was working fine so not sure what’s issue with this

**Comment by Jay-A-McBee** [comment]
:wave: hey @yudiz-harshad - I'm not familiar with this provider, but I notice that the url which works in the browser has quite a few additional query string parameters. You should try adding these same values to the `additionalParameters` object. I'm not sure if this is the issue, but the request url that would be created in RN would not match what you have linked as a working url.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
