### ISSUE TITLE
Undefined is not an object (evaluating 'RNAppAuth.authorize')

### ISSUE THREAD

**Issue by ll1314xh** [FormidableLabs/react-native-app-auth#681]
## Issue

I just made a simple configuration:
1). npm i react-native-app-auth
2). pod install
3). use await authorize(config);
But there still tips RNAppAuth.authorize is undefined, i found in the node_modules/react-native-app-auth/index.js, the 
 NativeModules is still null, i don't know what should i to configuration
---
![2381634827500_ pic_hd](https://user-images.githubusercontent.com/75356138/138301938-a2603fb3-d1e1-449c-818f-3e82bd9f107c.jpg)

## Environment
react-native: 0.63.3,
ios:13.0
react-native-app-auth: 6.4.0

**Comment by DavidReinberger** [comment]
Hey @ll1314xh I can see you've closed the issue by yourself, have you found a solution to the problem? Do you think you could share it here? We are currently facing the same issue and struggling to find a working solution. Thanks
