### ISSUE TITLE
New access token coming from refresh token not updated by new info in access token !!

### ISSUE THREAD

**Issue by HalimaHanafy** [FormidableLabs/react-native-app-auth#682]
## Issue

New access token coming from refresh token not updated by new info in access token !!
i ordered new refresh token , i got it but contains old data , 
to get updated data in my access token i had to log out and log in again to get new updated access token !!

any suggestions about this problem please?? 
---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** no

**Comment by Jay-A-McBee** [comment]
:wave: hey @HalimaHanafy - I'm not sure I understand the issue. What "updated data" are you expecting? What is the "old data" that the refresh token contains?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
