### ISSUE TITLE
Error while updating prop fontWeight, java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by JulianKingman** [FormidableLabs/react-native-app-auth#685]
## Issue

```Error while updating prop fontWeight, java.lang.Double cannot be cast to java.lang.String```

I get this error when logging in if:
 - The phone is a Google Pixel
 - Brave is set as default browser

For another user with a pixel and brave, it cancels the flow instead of crashing (it says user cancelled flow as soon as they enter the text input to change the email/password).

I've checked everywhere in the app, and every single node module, and can find no instances of fontWeight being set to a number (Double). It may be a deep dependency in app auth (which is why I'm posting this here), or something to do with Android and custom fonts (might explain why it's only pixels), or...?

---

## Environment

Android, google pixel only
No expo

**Comment by Jay-A-McBee** [comment]
hmm... I don't think this library can be of much help with this issue. UI and setting `fontWeight` values is not something that this library would affect. The second outcome mentioned sounds like the brave browser is crashing. 

Is your app using a custom font?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by Upsite-cor** [comment]
NUUUU! I am having the same issue W
