### ISSUE TITLE
Unable to receive access token 

### ISSUE THREAD

**Issue by Rachana-red** [FormidableLabs/react-native-app-auth#686]
Using below configuration:

 issuer: 'https://demo.identityserver.io/',  
 clientId: 'MobileApp',
 usePkc:true
 redirectUrl: 'com.appName://callback',
 scopes: ['openid','offline_access','profile','api1']
 
It is redirecting to application after login but getting the following response with null tokens.
Using Identity Server 4

Server config:
var client = new Client
{
  ClientId = "MobileApp",
  ClientName = "Mobile App (Code with PKCE)",
  RequireClientSecret = false,
  RedirectUris = { "com.appName://callback" },
  AllowedGrantTypes = GrantTypes.Code,
  RequirePkce = true,
  AllowedScopes = { "openid", "profile" },
  AllowOfflineAccess = true
};

{\"codeVerifier\":\"kJ1PNL2s0gEMOxvcq6q6bfYYO2wdR2vHXDFs_Dp71XIkuanekKhMiwfpsyk4DL64vEhgWrGIm5Yd97k94cOKKA\",\"tokenType\":null,\"accessToken\":null,\"idToken\":null,\"additionalParameters\":{\"session_state\":\"vyKYJyKnVBJxI3kZgwo4U4LCcSmqjFO74LUOx2a3GwI.64D58A6E85045BF043BEE80745CB1333\"},\"scopes\":[\"openid\",\"offline_access\",\"profile\",\"api1\"],\"authorizationCode\":\"C4F111E9DF93C66E4F94F8ECD2A488AD1652903947F7DB775EC5391AAF62C360\"}"

Thank you
Awaiting for your response
Quick response appreciated
-DRR

**Comment by Rachana-red** [comment]
Unable to receive access token - 
Please help me with the above concern.

**Comment by Jay-A-McBee** [comment]
:wave: hey @Rachana-red - hmm... I'm not sure what the issue is. In our example app we use 'https://demo.identityserver.io/' as our issuer value and we have no problem hitting the discovery endpoint and going through the full flow with identity server.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by SanjaySargam** [comment]
Hey @Rachana-red , Is your issue resolved?

I am also facing with the same issue
