### ISSUE TITLE
Unknown field "redirect_uri" using refresh on DropBox

### ISSUE THREAD

**Issue by scottaric** [FormidableLabs/react-native-app-auth#687]
## Issue

When calling `refresh` using the same config as when the original access token was acquired, the call fails with error text 'unknown field "redirect_uri"'.  The config does in fact specify the `redirectUrl`.

---

## Environment

* **Your Identity Provider**: `DropBox`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** `No`

**Comment by Jay-A-McBee** [comment]
:wave: hey @scottaric - Unfortunately, it doesn't seem like you will be able to use the refresh method. The redirect_uri cannot be omitted from the token request. See https://github.com/openid/AppAuth-iOS/blob/master/Source/AppAuthCore/OIDTokenRequest.m#L135. 

I was able to replicate the bug and I found a workaround. The request to refresh the access token can be handled directly by your app using fetch or any other networking library.

I was able to refresh the token using the following url structure and request config. 
```
// this needs to be encoded (encodeURI)

const uri = `https://api.dropboxapi.com/oauth2/token?grant_type=refresh_token&refresh_token=<REFRESH_TOKEN>&client_id=<CLIENT_ID>&scope=<YOUR SCOPES>`

await fetch(encodeURI(uri), {
  method: 'POST',
  contentType: 'application/x-www-form-urlencoded',
});
```

https://user-images.githubusercontent.com/13589602/153502503-be20cb9e-8b5b-4c1e-bf4a-5e5b321f7b37.mp4

As you can see in the video the response won't be formatted in the same way so this is something else your app would need to handle.

Let me know if that works for your use case 🚀 .

**Comment by scottaric** [comment]
Hey @Jay-A-McBee, thanks this is extremely helpful.  I can definitely make your suggestion work for my use case.  Wasn't sure if I was missing something originally.  Thanks for the detailed info - much appreciated!
