### ISSUE TITLE
iOS crashed when request login Google

### ISSUE THREAD

**Issue by vinhtranhti** [FormidableLabs/react-native-app-auth#688]
## Issue
const config = {
      issuer: 'https://accounts.google.com',
      clientId: Config.IOS_CLIENT_ID,
      redirectUrl: Config.IOS_REDIRECT_URL,
      scopes: ['openid', 'profile', 'email'],
    }
authorize(config)
      .then((result) => {
        console.log('result', result)
      })
      .catch((e) => {
        console.log('handleLoginGg e', e)
      })

Crash log:

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9905c __exceptionPreprocess
1  libobjc.A.dylib                0x15f54 objc_exception_throw
2  CoreFoundation                 0x17601c +[NSObject(NSObject) _copyDescription]
3  CoreFoundation                 0x2e484 ___forwarding___
4  CoreFoundation                 0x2d5c0 _CF_forwarding_prep_0
5  CFNetwork                      0x69c4 CFURLRequestSetHTTPRequestBody
6  CFNetwork                      0x3133c _CFNetworkErrorCopyLocalizedDescriptionWithHostname
7  CFNetwork                      0x58ad4 _CFHTTPCookieStorageGetDefault
8  CFNetwork                      0x44270 _CFNetworkCopyATSContext
9  CFNetwork                      0x29194 CFURLRequestSetRequestPriority
10 App                          0xa680 +[OIDAuthorizationService discoverServiceConfigurationForDiscoveryURL:completion:] + 333 (OIDAuthorizationService.m:333)
11 App                          0xa5b0 +[OIDAuthorizationService discoverServiceConfigurationForIssuer:completion:] + 324 (OIDAuthorizationService.m:324)
12 App                          0x279ab8 -[RNAppAuth issuer:redirectUrl:clientId:clientSecret:scopes:additionalParameters:serviceConfiguration:skipCodeExchange:additionalHeaders:useNonce:usePKCE:resolve:reject:] + 118 (RNAppAuth.m:118)
13 CoreFoundation                 0x22304 __invoking___
14 CoreFoundation                 0x3fad4 -[NSInvocation invoke]
15 CoreFoundation                 0x76934 -[NSInvocation invokeWithTarget:]

---

## Environment
"react-native": "^0.62.2",
"react-native-app-auth": "^6.4.0",

* **Your Identity Provider**: `Google`
* **Platform that you're experiencing the issue on**: `iOS `
* **Are you using Expo?**: `No`

**Comment by Jay-A-McBee** [comment]
:wave: hey @vinhtranhti - is this still an issue?  I was able to create a new app and login through google using their discovery endpoint on iOS.

**Comment by Jay-A-McBee** [comment]
Closing this out due to lack of response from OP.
