### ISSUE TITLE
Hiding the url address bar

### ISSUE THREAD

**Issue by edwardkes** [FormidableLabs/react-native-app-auth#689]
I use Azure B2C for the authentication on my app.
Whenever I call for the authentication on both platforms Android/iOS - it opens the in-app browser.
I wanted to know if it's possible to hide the address bar from that browser?

**Comment by Jay-A-McBee** [comment]
This currently isn't possible see Android-AppAuth discussion
https://github.com/openid/AppAuth-Android/issues/277#issuecomment-335029724 and 
https://github.com/openid/AppAuth-Android/issues/277#issuecomment-335029724.

. Closing - Same as https://github.com/FormidableLabs/react-native-app-auth/issues/699
