### ISSUE TITLE
Error not specified.     at Object.promiseMethodWrapper [as authorize] (NativeModules.js:103)  at authorize (index.js:213)

### ISSUE THREAD

**Issue by prasidhda** [FormidableLabs/react-native-app-auth#690]
## Issue
All of sudden login with google in Android throws the following error. 
Error not specified.
    at Object.promiseMethodWrapper [as authorize] (NativeModules.js:103)
    at authorize (index.js:213)

---

## Environment

* **React native**: `0.63.4`
* **react-native-app-auth**: `6.1.0`
* **Are you using Expo?**: `No`

**Comment by Jay-A-McBee** [comment]
:wave: hey @prasidhda - is this still an issue? If so, we'll need more information to try to help. Could you provide your config object with the private information redacted?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
