### ISSUE TITLE
Getting User cancelled flow in android while working with azure ad b2c

### ISSUE THREAD

**Issue by skanwarjeet** [FormidableLabs/react-native-app-auth#691]
## Issue

I'm using react-native-app-auth to get access token from azure ad b2c but I'm facing issues in android and in IOS
in android it's showing error that 
`Unable to complete authorization as there
is no interactive call in progress. This
can be due to closing the app while the
authorization was in process.`
I also added screenshot of that
![Screenshot_1638860995](https://user-images.githubusercontent.com/95462621/144985386-f9ef4c12-8117-4d0a-adb7-ae9e58db7346.png)

and in IOS it's redirecting but not returning anything.

```
const config = {
  issuer:
    'https://ksg1806.b2clogin.com/tenantId/v2.0/',
  clientId: 'clientId',
  redirectUrl:
    Platform.OS == 'ios'
      ? 'msauth.com.gfk.consumervoice://auth'
      : 'msauth://com.gfkconsumer/Cb7s2L1nogp57%2BKdddohtF8%2Funk%3D',
  additionalParameters: {},
  scopes: ['openid'],
  serviceConfiguration: {
    authorizationEndpoint:
      'https://ksg1806.b2clogin.com/ksg1806.onmicrosoft.com/b2c_1_signup_signin/oauth2/v2.0/authorize',
    tokenEndpoint:
      'https://gfkms.b2clogin.com/GFKMS.onmicrosoft.com/b2c_1_signup_signin/oauth2/v2.0/token',
    revocationEndpoint:
      'https://gfkms.b2clogin.com/GFKMS.onmicrosoft.com/b2c_1_signup_signin/oauth2/v2.0/logout',
  },
};

  const getAccessToken = async () => {
    try {
      const authState = await authorize(config);
      console.log(authState);
    } catch (error: any) {
      Alert.alert('Failed to log in', error.message);
    }
  };
```
that's the code I used to get access token from azure ad b2c. Please help 
---

## Environment
```
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-app-auth": "^6.4.0",
```

**Comment by Jay-A-McBee** [comment]
:wave: hey @skanwarjeet - try adding a final trailing slash to your `serviceConfiguration` urls. There have been [issues](https://github.com/FormidableLabs/react-native-app-auth/pull/609) with this in the past.

Are there any error message that you see on iOS?

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by skanwarjeet** [comment]
> 👋 hey @skanwarjeet - try adding a final trailing slash to your `serviceConfiguration` urls. There have been [issues](https://github.com/FormidableLabs/react-native-app-auth/pull/609) with this in the past.
> 
> Are there any error messages that you see on iOS?

thanks for replying but I already solve it and slash is the problem

**Comment by Venkatesh63740** [comment]
<data android:scheme="com.omnex.suppliermanagement" android:host="callback" />
 
 
 is. this correct?
