### ISSUE TITLE
Example React Native With Emulator Not working

### ISSUE THREAD

**Issue by karthikrsubs** [FormidableLabs/react-native-app-auth#695]
We are trying to use Project given in github examples of React-Native-App-Auth with Keycloak, Keycloak is install in same machine where we are building the example too.
i.e localhost keycloak,
We are unable to bring the Keycloak UI Page itself 
Can some one help in reviewing our settings.

**Comment by Jay-A-McBee** [comment]
:wave: hey @karthikrsubs  - if you can show us your service configuration with the client ids/secrets redacted, we can try to help.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
