### ISSUE TITLE
AAD code exchange error invalid_client

### ISSUE THREAD

**Issue by liatnetach** [FormidableLabs/react-native-app-auth#698]
## Issue

Hey, I have issues while trying to login with Azure.
my flow is split (using skipCodeExchange=true) cause My server do the other part of the flow (token endpoint).
I think I may have a problem with state mismatch - cause as part of this library you generate random state for me, how can I override it?

Generally I'm getting Invalid_client error at the code exchange phase.

I have to mention that the web flow with same user work perfectly so it is something with my definition.
also, the server send nonce- is it necessary to add it in my side? if so how can I add it?

Thanks.

---

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
:wave: hey @liatnetach - you can pass `useNonce: true` on the config object to generate and add this value to the request query string.

The library doesn't currently allow the consumer to override the `state` value for the request on iOS. This is generated using the [`OIDAuthorizationRequest` class's `generateState` method in iOS](https://github.com/FormidableLabs/react-native-app-auth/blob/main/ios/RNAppAuth.m#L285).

We do support this for [Android](https://github.com/FormidableLabs/react-native-app-auth/blob/main/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L580), though. You can pass a `state` value on the `additionalParameters` object.

Note that [the default implementation for the state parameter is encouraged ](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationRequest.java#L454) by both backing native libraries.

Let me know if that fixes anything for you :rocket:

**Comment by liatnetach** [comment]
@Jay-A-McBee Thanks for your reply !
The default nonce value is true, no? how can it make a difference?

but anyway I came to a conclusion that the problem is only with Azure, seems that they expect different behavior when using mobile devices.
with other providers my config did work.
there is similar case where the client (mobile) using this library to do the Authorization and then the server do the Code Exchange? with Azure Provider
I guess this is the source of my issue.. :/

**Comment by Jay-A-McBee** [comment]
Ah yeah you can pass `skipCodeExchange: true` and this will bypass the token exchange and return the code to the client. You can then make a request to your server with the code and it can exchange the it for an access token.  
 
 Let me know if that works out 👍

**Comment by Jay-A-McBee** [comment]
@liatnetach if `skipCodeExchange` is working for you, it sounds like there is an issue in the server side code. Feel free to create a new issue if you find that's not the case 👍 .
