### ISSUE TITLE
No redirect back to the App Spotify [Android, IOS]

### ISSUE THREAD

**Issue by RukshanWithanage** [FormidableLabs/react-native-app-auth#700]
**When login success there is no redirect back to the app.**

I have set up below configurations 

```
const config ={
      clientId: '<clientid>',
      clientSecret: '<secretid>',
      redirectUrl: 'https://spotifyauthtestapp:/oauth',
      scopes: [
        'playlist-read-private',
        'playlist-modify-public',
        'playlist-modify-private',
        'user-library-read',
        'user-library-modify',
        'user-top-read',
      ],
      serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.spotify.com/authorize',
        tokenEndpoint: 'https://accounts.spotify.com/api/token',
      },
    };
```
**on build.gradle**

```
defaultConfig {
        applicationId "com.spotifyauth"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
            appAuthRedirectScheme: "spotifyauthtestapp"
        ]
    }
```
And also I have updated **redirect URI**,  **Android Package Name**, **SHA1 Fingerprint** on the Spotify dashboard. Everything is working except redirecting back to the App.  :(

**Comment by jerryMaxpaine** [comment]
Same issue  :(

**Comment by Jay-A-McBee** [comment]
@obereignermichael  - the OP's issue is related to spotify which doesn't require `https` protocol for redirect urls. There's more leg work required to use an https redirect in iOS. You would need to setup a "universal link" and a two-way app/domain association. You may have already done this, but if not here's a link to the [Apple docs](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content?preferredLanguage=occ).

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by RohitRastogi94** [comment]
I have done every setup required for iOS universal link. on taping on link from notes or contact's url it is working fine but from redirect after authentication it loads webpage. I am using https link for redirection @Jay-A-McBee

**Comment by RohitRastogi94** [comment]
@Jay-A-McBee Do you have any update?

**Comment by GunnarAK** [comment]
@RohitRastogi94 did you find any solution to the issue with redirect URLs that start with `https://` like Instagram?

I also have Apple Universal Links & Android App Links set up, but the redirect url just loads the page in the in-app browser on both Android and iOS.
