### ISSUE TITLE
Returned scopes array is empty

### ISSUE THREAD

**Issue by lsmith-scorchsoft** [FormidableLabs/react-native-app-auth#710]
## Issue

Hi. So the scopes in the `authorize` return are coming through empty, when they are in the response body. 
When logging the auth state from the app:
```
{
    "accessToken": "...",
    "accessTokenExpirationDate": "...",
    "authorizeAdditionalParameters": {
        "client-request-id": "..."
    },
    "idToken": "...",
    "refreshToken": "...",
    "scopes": [],
    "tokenAdditionalParameters": {
        "refresh_token_expires_in": 28588,
        "resource": "urn:microsoft:userinfo"
    },
    "tokenType": "bearer"
}
```

Response body:
```
{
    "access_token": "...",
    "token_type": "bearer",
    "expires_in": 3600,
    "resource": "urn:microsoft:userinfo",
    "refresh_token": "...",
    "refresh_token_expires_in": 28588,
    "scope": "profile openid",
    "id_token": "..."
}
```
Testing this with the demo.identityserver.io credentials the scopes are logged out as expected. I've looked around and seen this issue a couple of times but couldn't find anything that resolves this. Any help would be greatly appreciated!

---

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** `No`

**Comment by Jay-A-McBee** [comment]
:wave: hey @lsmith-scorchsoft  - 

When targeting Azure AD the objects passed to the [format method ](https://github.com/FormidableLabs/react-native-app-auth/blob/main/ios/RNAppAuth.m#L538)(response and authResponse) for ios don't contain the same info as they do when targeting the identity server demo.


We expect the scope to come from the `authResponse` obj
<img width="921" alt="format_fn" src="https://user-images.githubusercontent.com/13589602/154752985-fce84b0c-6cda-4d74-b0e6-dbca1a596e4e.png">

This value is nil on the `authResponse` object when using Azure AD.
<img width="1226" alt="auth_resp" src="https://user-images.githubusercontent.com/13589602/154753046-331b147f-7b7e-47be-abad-a5f25ca382da.png">

But it is defined on the `response` object.
<img width="1211" alt="resp_obj" src="https://user-images.githubusercontent.com/13589602/154753169-49f609e7-7875-47d1-a756-f4746c253563.png">


If I tweak the method to check both objects, I'm able to return the scopes.
```obj-c
    NSArray *scopes = authResponse.scope ? [authResponse.scope componentsSeparatedByString:@" "] : response.scope ? [response.scope componentsSeparatedByString:@" "] : [NSArray new];
```
<img width="330" alt="working_scopes" src="https://user-images.githubusercontent.com/13589602/154753487-02073b5f-16cc-43f2-92a5-b9b449ec907a.png">


So we can obviously, make this happen. But, I'm curious about your use case. Is it vital that these scope strings are returned to your app? I noticed this [comment](https://github.com/openid/AppAuth-iOS/blob/master/Source/AppAuthCore/OIDAuthState.m#L366) in the AppAuth-ios source. It references the oauth 2.0 spec which states that `scope` is optional in the response if the returned scopes are no different from the requested scopes. The granted scopes are implicit in the returned `access_token` so in this instance the lack of returned scopes signifies the scopes were granted.

Let me know if my line of thinking is off here - look forward to hearing from you :rocket:

**Comment by lsmith-scorchsoft** [comment]
Hi @Jay-A-McBee 👋 

Thanks so much for this fantastic response! You really helped my understanding of this.

No need to make any changes, we're happy to accept the scope return as indicated by the spec and will use the request scopes when we need them. 👍

**Comment by anujraghuvanshi** [comment]
Hi @lsmith-scorchsoft @Jay-A-McBee   - I am having the same issue. The scopes array is returned empty. I have tried on both Android & iOS and passsed `['openid', 'profile', 'User.Read']` scopes  to `authorize` method and it's not working. 

I was earlier doing with `react-native-azure-auth` and the scopes were returned but using this package, I am not able to get.
