### ISSUE TITLE
Apple Signin Feature

### ISSUE THREAD

**Issue by Parathantl** [FormidableLabs/react-native-app-auth#711]
Hey Guys,
This library is so much easy to integrate and can see the fully-functioning workflow quickly.
Do you guys have any idea to implement the Sign in with Apple feature?

**Comment by Jay-A-McBee** [comment]
:wave: hey @Parathantl  - I'm not sure that this library is a suitable choice for implementing the Sign In with Apple feature. You should look into a lib that's focused on the `apple sign in` auth flow exclusively - [react-native-apple-authentication](https://github.com/invertase/react-native-apple-authentication).

**Comment by Jay-A-McBee** [comment]
No response - closing this out

**Comment by Parathantl** [comment]
@Jay-A-McBee thanks for your info. I will try the library you mentioned. Thanks again
