### ISSUE TITLE
React Native SAML provider

### ISSUE THREAD

**Issue by glorio-loopstudio** [FormidableLabs/react-native-app-auth#713]
I don't really know how to configurate an SAML provider in mobile app. I am using a url that redirect me to the auth page, that in web is working fine. But I don't know how to use it in React Native and get the token from this.

Any help? Thanks!

**Comment by Jay-A-McBee** [comment]
:wave: hey @glorio-loopstudio - This library will only support providers that implement the OAuth 2.0 and OIDC spec.  Unfortunately the native libraries we use do not support SAML 2.0.  See this [issue](https://github.com/openid/AppAuth-iOS/issues/351#issuecomment-469556213) in AppAuth-ios.

**Comment by glorio-loopstudio** [comment]
Do you know Any way?
