### ISSUE TITLE
Error 403: disallowed_useragent

### ISSUE THREAD

**Issue by weyron2014** [FormidableLabs/react-native-app-auth#716]
## Issue

Hi guys, I am using Identity Server for authentication. I am able to log in through Google or Facebook social sign-in on IOS, BUT 
Android gives me error Error 403: disallowed_useragent for Google and a similar error for Facebook.

Here is the screenshot: 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/46655778/157359623-1d604259-8649-41fc-8660-1ee0523c4a15.png">

I specified the redirect link in **manifestPlaceholders** for Android in app/build.gradle

I am using Emulator from Android Studio and it opens a Webview. 

I found that google blocked login from Webview and that I need to specify user-agent (https://stackoverflow.com/a/43973356). Could you guide me on what actions should be taken to resolve this issue?

Thanks a lot!
---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
:wave: hey @weyron2014 - I think this is an issue with your emulator and the fact that it's launching the authentication session in `WebView Browser Tester` and not an installed browser application (ex. Chrome). If the play store is installed on the emulator, download chrome and set this as the default browser. 

If the play store isn't installed, go to the AVD manager in Android Studio and create a new virtual device. 
<img width="500" alt="create" src="https://user-images.githubusercontent.com/13589602/157562507-73917c79-4b3c-4ea6-b072-8baa4ad095b9.png">


When selecting the device, choose one that includes the play store.
<img width="500" alt="play" src="https://user-images.githubusercontent.com/13589602/157562532-66192474-e62e-4ce0-b913-9dda269c46c8.png">

Give that a try :rocket:

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.

**Comment by dylanlewis89** [comment]
For anyone else happening upon this page, this solution solved a problem I had been facing that was really tough to debug because I originally thought it was a bad configuration in the library I was using to initiate authentication. Thank you @Jay-A-McBee for providing the insight that the simulator device has to have a real default browser installed for the auth libraries to open it, and providing instructions on how to access simulator devices with the necessary tools. Not being an Android user, it was easy to miss.

**Comment by bajwapopo220** [comment]
I wanted to take Android AND-403 exam but this plan flawed as my exam date was getting closer and still I had no preparation for my exam. Then one of my friends told me about **PassCertHub** study guide for a quick and reliable exam preparation. This advice worked wonders and I passed Android AND-403 without a bit trouble. **PassCertHub** guide really proved its worth!  https://www.passcerthub.com/android/and-403-dumps.html
