### ISSUE TITLE
Authorize popup

### ISSUE THREAD

**Issue by houssemanypli** [FormidableLabs/react-native-app-auth#717]
Hello, I am using authorize and i want to delete the popup shown for connection in ios
Is there any method to do this or at least to change the message shown? 
<img width="212" alt="Screen Shot 2022-03-09 at 3 44 05 PM" src="https://user-images.githubusercontent.com/97892581/157464912-f89e2525-b926-4a7a-a1cf-f90ad081ca77.png">

**Comment by Jay-A-McBee** [comment]
:wave: hey @houssemanypli - unfortunately there's no way to suppress this alert or edit its content. [This question](https://github.com/FormidableLabs/react-native-app-auth/issues/428) has come up before and there's an [old thread](https://github.com/openid/AppAuth-iOS/issues/120#issuecomment-329865111) in AppAuth-ios that mentions this. This is a mandatory dialog triggered by the use of `SFAuthenticationSession` (iOS 11) and `AFWebAuthenticationSession` (iOS 13). 

If the change is cosmetic (displaying a different app name, etc.), there are a [couple suggestions](https://github.com/openid/AppAuth-iOS/issues/343) in this issue.

**Comment by IKTANIM** [comment]
Logout happens even if press the cancel button.
