### ISSUE TITLE
I got RNAppAuth.authorize got 13 aurguments, expected 16

### ISSUE THREAD

**Issue by nguyen-tam** [FormidableLabs/react-native-app-auth#719]
## Issue

I got RNAppAuth.authorize got 13 aurguments, expected 16
---
Here is the code 👍 
```
const config = {
    clientId: AuthConfig.appId,
    issuer: 'https://login.microsoftonline.com/common',
    redirectUrl: Platform.OS === 'ios' ? 'urn:ietf:wg:oauth:2.0:oob' : 'graph-tutorial://react-native-auth',
    scopes: AuthConfig.appScopes,
    additionalParameters: { prompt: 'select_account' },
    serviceConfiguration: {
      authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    },
};  
var result = await authorize(config);
```

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
👋 hey there @nguyen-tam - hmm... what version of this library are you using? `6.4.3`? If not, try upgrading to this most recent version.

I tried logging into Azure using our Example app. I also mirrored your config object. I was able to log in without any issues.
```
{
  issuer: 'https://login.microsoftonline.com/common/v2.0/',
  clientId: <CLIENT_ID>,
  redirectUrl: 'example.myapp.com://oauth',
  additionalParameters: { prompt: 'select_account' },
  scopes: ['openid', 'offline_access'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
 }
}
```
![azure_login](https://user-images.githubusercontent.com/13589602/160207563-026eac7e-ef41-48c9-869b-e1d02bba8992.gif)

Let me know if you still see the issue after upgrading 🚀

**Comment by nguyen-tam** [comment]
@Jay-A-McBee Thanks for your reply. It turns out I got this error because I upgraded from 5.1.3 to 6.4.3. Here is how I fixed it.

1. npm uninstall react-native-app-auth
2. gradlew clean
3. npm install --save react-native-app-auth ( install the newest version here)

**Comment by Jay-A-McBee** [comment]
👍 glad you got it sorted out
