### ISSUE TITLE
Use of undeclared identifier 'RCTLinkingManager' 

### ISSUE THREAD

**Issue by fukemy** [FormidableLabs/react-native-app-auth#722]
## Issue
Hi, i follow all the step but i got this error, im sure the AppAuth was installed in XCode project
![Screen Shot 2022-04-06 at 12 12 26](https://user-images.githubusercontent.com/8202437/161900400-22d78a14-f7b8-4e15-917e-a9684e74464c.png)

Please help my problem

Here is full code:
***AppDelegate.h***
```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
//APPAUTH
#import <AppAuth/AppAuth.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, RNAppAuthAuthorizationFlowManager>

@property (nonatomic, strong) UIWindow *window;
@property(nonatomic, weak) id<RNAppAuthAuthorizationFlowManagerDelegate> authorizationFlowManagerDelegate;

@end


```

---

## Environment

* **Your Identity Provider**:  solved bug first
* **Platform that you're experiencing the issue on**: `IOS`
* **Are you using Expo?** No

**Comment by fredmanxu** [comment]
Add the following code to `AppDelegate.m`
```
#import <React/RCTLinkingManager.h>
```
It worked for me.

**Comment by fukemy** [comment]
tks it work

**Comment by Jay-A-McBee** [comment]
👍 Thanks @fredmanxu for chiming in!!

**Comment by ngocptmio** [comment]
If add `#import <React/RCTLinkingManager.h>` to the `AppDelegate.m` or `AppDelegate.m` file is not working.
You can try add `#import <React/RCTLinkingManager.h>` to the `AppDelegate.h`.
And that is working with me.
