### ISSUE TITLE
Library not found for -lAppAuth

### ISSUE THREAD

**Issue by HarshavardhanRai** [FormidableLabs/react-native-app-auth#728]
## Issue

When I try to run the app it gives the below error.

ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation), Please help me in solving the issue.
---

react native version: "0.67.4"
React native app auth: "^6.4.3"

## Environment

* **Your Identity Provider**: `e.g. Azure`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

**Comment by mehthabux** [comment]
try changing deployment target to 11.0

**Comment by alexzobi** [comment]
Any movement on this? I've tried manually linking the library as well and nothing seems to work. Side note for M1 users, running the command above might not work either. If it doesn't, try running `arch -x86_64 npx react-native run-ios`. I have an M1 and didn't have to do this, but a teammate with an M1 did.

**Comment by alexzobi** [comment]
@Jay-A-McBee what info would help you with this? here is the output from `npx react-native info`
```bash
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.18 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: ^0.69.4 => 0.69.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    ```

**Comment by K0ustavC** [comment]
I am facing the same issue 

react-native info :

```
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 71.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.7 - ~/code/mobile-shipper-app/node_modules/.bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AlexSobiloffSonos** [comment]
@K0ustavC no we're still dealing with this. The workaround we have is that after every project clean, we run the app from command line: `npx react-native run-ios` and that builds successfully. All subsequent builds will work from xcode, unless of course you clean your build again. It's pretty annoying but what can you do? Something must be happening under the hood with the command line tools that building directly in xcode is not doing.

**Comment by maxikgreat** [comment]
bros, open xcworkspace not xcodeproj extension
