### ISSUE TITLE
Config parameter `customHeaders` is not taken into account

### ISSUE THREAD

**Issue by jfschaff** [FormidableLabs/react-native-app-auth#734]
## Issue

It looks like the config parameter `customHeaders` is disregarded.

```
const config = {
  ...
  customHeaders: {
    authorize: {
      "X-MyCustomHeader": "value",
    },
  },
};

authorize(config)
```

The outgoing authorization request does not have a custom header `X-MyCustomHeader` on Android.

---

## Environment

* **Your Identity Provider**: not relevant 
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by Geraldojrcg** [comment]
I have the same problem in IOS version. Any suggestion? 
```
const config = {
  ...
  additionalHeaders: {
     "X-MyCustomHeader": "value",
  },
};
```
