### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new _reactNativeAppAuth2.default')

### ISSUE THREAD

**Issue by mraible** [FormidableLabs/react-native-app-auth#75]
I'm trying to update my [Build a React Native App and Authenticate with OAuth 2.0](https://scotch.io/tutorials/build-a-react-native-app-and-authenticate-with-oauth-20) article to use react-native-app-auth@2.2.0 and having issues. When I run `npm run ios`, I get the following error:

![image](https://user-images.githubusercontent.com/17892/37476514-ff8a8c42-283a-11e8-904e-2d375b1cfa5e.png)

**Comment by ryan-roemer** [comment]
As discussed in detail in https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v2.0.0 we don't have a `default` export anymore.

In https://unpkg.com/react-native-app-auth@1.0.1/index.js we have:

```js
export default class AppAuth {}
```

In https://unpkg.com/react-native-app-auth@2.3.0/index.js we have:

```js
export const authorize = () => {}
export const refresh = () => {}
export const revoke = async () => {}
```

and the readme is updated as well to reflect the API changes: https://github.com/FormidableLabs/react-native-app-auth#supported-methods

Hopefully all those guides will help your article!

**Comment by mraible** [comment]
Wow! Thanks for the super-fast response @ryan-roemer! Your tips pointed me in the right direction and I've fixed the problem.

**Comment by Shoukat488** [comment]
not working for me please help.
<-------------------------------Fire.js----------------------------->


import React  from 'react';
import * as firebase from 'firebase';
import { FirebaseConfig } from '../config/firebaseConfig';
import { connect } from 'react-redux';

const mapStateToProps = (state) => ({
        comb_id: state.Combid.combid
    })

class Fire extends React.Component {


    constructor(props) {
        super(props);
    }

    send = (messsages) => {
        messsages.forEach(item => {

            const messsage = {
                text: item.text,
                timestamp: firebase.database.ServerValue.TIMESTAMP,
                user: item.user
            }
            this.db().push(messsage)
        });
    }

    parse = messsage => {
        const { user, text, timestamp } = messsage.val();
        const { key: _id } = messsage;
        const createdAt = new Date(timestamp);

        return {
            _id,
            createdAt,
            text,
            user
        }
    }
    get = callback => {
        this.db().on('child_added', snapshot => callback(this.parse(snapshot)))
    }
    db() {
        return firebase.database().ref(`reference..`);
    }
    off() {
        // this.db().off();
    }
    // get uid() {
    //     return (firebase.auth().currentUser || {}).uid
    // }

}

export default connect(mapStateToProps)(Fire);

<---------------------------------chat.js constructor --------------------------------->

class Chat extends React.Component {

  state = {
    messages: [],
    comb_id: '',
  }

  constructor() {
    super();

    const obj = new Fire();  // this.obj = new Fire() is also not working.
    this.setComb_id();
  }
 }

**Comment by noahfranco** [comment]
What about in regards to class component's not functional components? Would the `default export` be updated?

**Comment by EdimarfS** [comment]
for those who still looking for this solution, 
this link : 
https://aboutreact.com/swipe-gestures-not-working-in-android/ helped  a lot...
