### ISSUE TITLE
The App Auth Pod is Locked to 1.4.0 and is Conflicting with other pods that require higher versions

### ISSUE THREAD

**Issue by tanakaderoy** [FormidableLabs/react-native-app-auth#755]
## Issue

Getting this error when trying to install @react-native-google-signin/google-signin v8.0.0
```
[!] CocoaPods could not find compatible versions for pod "AppAuth":
  In snapshot (Podfile.lock):
    AppAuth (= 1.4.0, ~> 1.4)

  In Podfile:
    RNGoogleSignin (from `../node_modules/@react-native-google-signin/google-signin`) was resolved to 8.0.0, which depends on
      GoogleSignIn (~> 6.2.2) was resolved to 6.2.2, which depends on
        AppAuth (~> 1.5)

    react-native-app-auth (from `../node_modules/react-native-app-auth`) was resolved to 6.4.3, which depends on
      AppAuth (= 1.4.0)


You have either:
 * changed the constraints of dependency `AppAuth` inside your development pod `RNGoogleSignin`.
   You should run `pod update AppAuth` to apply changes you've made.
   ```
a fix could be in the podspec change `s.dependency 'AppAuth', '1.4.0'` to `s.dependency 'AppAuth', '~> 1.4'` so that projects arent locked to 1.4.0 only and can go any version of 1.x higher
---

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?**

**Comment by karatekid430** [comment]
Having similar issue here

**Comment by AbdurakhmonZiyodov** [comment]
yarn add react-native-app-auth@next try this

**Comment by hrdyjan1** [comment]
The solution from [AbdurakhmonZiyo](https://github.com/AbdurakhmonZiyodov) will be working.
There is another option - using [patch-package](https://github.com/ds300/patch-package)
In this case, change the line with **AppAuth** dependency ([link](https://github.com/FormidableLabs/react-native-app-auth/commit/32a9937bbcef2f6aa4b9026d4682b9e91a3fe0b3))  and type: `yarn patch-package react-native-app-auth`
