### ISSUE TITLE
What are the advantages of this library? Also, documentation needs to be made clearer.

### ISSUE THREAD

**Issue by BryceBlankinship** [FormidableLabs/react-native-app-auth#761]
## Documentation Feedback

I'd like to preface this by saying that if anyone can provide me with concrete evidence that this library is better than implementing OAuth2 on my own, that I'll make the proposed changes to the documentation to make it clearer and more readable. However, after going through the docs, I'm not convinced as to what this library is helping me to do. What's the difference between this and just making the http calls to an identity provider myself? I still have to handle the tokens myself, so it's not like it actually helps in getting a new access token once the current one expires... even though the library _knows_ when the expiration date is. I still have to make that check myself. So, is this mostly just a wrapper for the actual http requests to an identity provider? Only real value im seeing is in the android prefetch documentation. 

The docs just need some work in small areas, like removing numerated lists when its actually supposed to be an "do this OR that", not "follow these steps". And also better explanation of what the library is accomplishing in each step. Also, the examples need some work. Just providing an example with little context has left me going everywhere **but** the docs... not ideal! I could work specifically on the Google example as that is what I'm using in my app.

Again, this post is not intended to purely slander the library and its contributors, like I said, I'll become a contributor and help try to clean up these docs to make them more readable and approachable, if someone can give me a solid set of reasons to use this library instead of handling the auth process myself.

**Comment by justin-tay** [comment]
Essentially as stated in the [Why you may want to use this library](https://github.com/FormidableLabs/react-native-app-auth#why-you-may-want-to-use-this-library) section, the main purpose of this library is to leverage native implementations that implements  [RFC 8252 - OAuth 2.0 for Native Apps](https://tools.ietf.org/html/rfc8252) as this is the current best practice for securely implementing OAuth 2.0 for Native Apps on Android and iOS. This leverages [AppAuth Android](https://github.com/openid/AppAuth-Android) and [AppAuth iOS](https://github.com/openid/AppAuth-iOS). 

It is generally not good practice, nor a good use of time and development effort, to roll your own security implementation, for instance by just making http calls to an identity provider, as you would need to be fairly familiar with the specification to implement it securely.

**Comment by BryceBlankinship** [comment]
Ok so after skimming through the RFC, most of the value this library aims to provide is in providing auth through the user's browser/external user agent? And then of course the other details the RFC mentions. I don't know why, but the documentation just didn't click with me the first time. Maybe I could propose changes as I use this library. Auth is a tricky topic that I have 0 interest in, but need to work with it. Maybe one day I'll have some interest in it lol. Thanks for replying.
