### ISSUE TITLE
Authorization with Discord return empty scrope and idToken 

### ISSUE THREAD

**Issue by YuliPolishchuk** [FormidableLabs/react-native-app-auth#762]
Config file - 
```
const config = {
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET',
  redirectUrl: 'BUNDLE_IDENTIFIER://oauthredirect',
  scopes: ['email', 'identify'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://discord.com/api/oauth2/authorize?client_id=[YOUR_CLIENT_ID]&redirect_uri=[BUNDLE_IDENTIFIER://oauthredirect]&response_type=code&scope=email%20identify',
    tokenEndpoint: 'https://discordapp.com/api/oauth2/token',
    revocationEndpoint: 'https://discordapp.com/api/oauth2/token/revoke'
  }
}

```
Returned status 200 and redirected back, but a response like that, scope and idToken is empty

`{"accessToken": "eqRXY6qT13IsddURYBHXbjvoOdv2JY", "accessTokenExpirationDate": "2022-08-29T11:14:16Z", "authorizeAdditionalParameters": {}, "idToken": "", "refreshToken": "7sYoKlWsfdt5LTjpuxiCa5ht8ZMvbg", "scopes": [], "tokenAdditionalParameters": {}, "tokenType": "Bearer"}`

**Comment by AnisDerbel** [comment]
@YuliPolishchuk  since your closed the issue, can you share your solution how did you override the response_type to include `id_token` ?

**Comment by YuliPolishchuk** [comment]
> @YuliPolishchuk since your closed the issue, can you share your solution how did you override the response_type to include `id_token` ?

I'm going with just an access token, without token id and it works well for me

**Comment by AnisDerbel** [comment]
@YuliPolishchuk  but how did you use the logout function since it requires to pass the `idToken` based on the doc
