### ISSUE TITLE
Upgrade to AppAuth 1.5.0

### ISSUE THREAD

**Issue by rush86999** [FormidableLabs/react-native-app-auth#764]
I am using another react native sign in plugin and their dependency is AppAuth 1.5 while react-native-app-auth is 1.4.0. There is a pod dependency conflict that can be easily resolved by upgrading to latest AppAuth version

**Comment by FZYdesign** [comment]
the same issues

**Comment by robwalkerco** [comment]
This was upgraded to 1.6 by #787
