### ISSUE TITLE
"The certificate for this server is invalid"-error

### ISSUE THREAD

**Issue by semvankoutrik** [FormidableLabs/react-native-app-auth#768]
When executing the function "authorize" I get the following error-message: "The certificate for this server is invalid". I am running a Duende Identityserver project locally. I installed the certificates using "dotnet https dev-certs --trust"-command and tried both http & https with the config-option dangerouslyAllowInsecureHttpRequests set to true. I also tried localhost and 127.0.0.1 as url, but still no luck.
I am running the app on a iPhone 13 simulator on M1 Macbook.

**Comment by HarshavardhanRai** [comment]
Can anyone help in solving this issue?

I am also facing the below issue.

**Connection error fetching discovery document, The certificate for this server is invalid. You might be connecting to the server that is pretending to be**

**Comment by ntuan7059** [comment]
I am also facing the below issue.

does anyone have solution? Many thanks
