### ISSUE TITLE
Upgrade to AppAuth 1.6.0

### ISSUE THREAD

**Issue by boostvolt** [FormidableLabs/react-native-app-auth#771]
I would like to use the `prefersEphemeralSession` parameter which was introduced with AppAuth-iOS [1.6.0](https://github.com/openid/AppAuth-iOS/releases/tag/1.6.0). This would require updating the AppAuth-iOS pod to 1.6.0 and adding appropriate support.

**Comment by alexhernandez** [comment]
Is there any existing area where this arg can be added?

**Comment by hannibaldinski** [comment]
+1 😊

**Comment by badsyntax** [comment]
For us we have no need for SSO support and we want a non shared session, so `prefersEphemeralSession` is exactly what we're looking for. It'd be great to have this feature.

**Comment by badsyntax** [comment]
Note I've added a PR for this here: https://github.com/FormidableLabs/react-native-app-auth/pull/787

**Comment by alexhernandez** [comment]
MR looks good. @kadikraman could you review?
