### ISSUE TITLE
Why is `compileSdkVersion` at 23 in build.gradle?

### ISSUE THREAD

**Issue by vladikoff** [FormidableLabs/react-native-app-auth#78]
Hey, I noticed that the `compileSdkVersion` is at `23` there:

https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/build.gradle#L14-L18

But the project readme asks to use version 25 in new projects per the README.md. Does this need to be updated?

**Comment by kadikraman** [comment]
Good spot, I think you're right.

**Comment by kadikraman** [comment]
This will be updated to `27` in the newest release
