### ISSUE TITLE
Is it possible to use HTTPS format for redirect URI?

### ISSUE THREAD

**Issue by vendeza** [FormidableLabs/react-native-app-auth#785]
In my project need to use `redirectUrl` in the HTTPS format  e.g. "https://my.app.auth". 
Because issuer server supports only the https format  for redirect links.
 
I tried to add the link in build.gradle:

```
manifestPlaceholders = [
           appAuthRedirectScheme: 'https://my.app.auth'
       ]
```

and test it using `authorize()`. But it opens mobile browser with 502 Bad Gateaway.

Then I tried to add https in Manifest like described  [here](https://github.com/openid/AppAuth-android#capturing-the-authorization-redirect) . Tested it using `authorize()`. Then the app opened with  `[Error: Data intent is null]`.

I'm wondering if it's possible to use HTTPS format for a redirect URI ?

**Comment by vendeza** [comment]
Yes. It's possible for iOS and Android.

If redirectURI is `https://example.com`, for Android need to do:

1. Need to add the new activity in AndroidManifest.xml

```
 <activity
                android:name="net.openid.appauth.RedirectUriReceiverActivity"
                android:exported="true">
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                      android:host="example.com"
                      android:path="/auth"/>
            </intent-filter>
        </activity>
```

2. Add the configuration as described for example [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/uber.md) :
```
const config = {
  clientId: 'your-client-id-generated-by-uber',
  clientSecret: 'your-client-secret-generated-by-uber',
  redirectUrl: 'https://example.com', //note: path is required
  scopes: ['profile', 'delivery'], // whatever scopes you configured in Uber OAuth portal
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.uber.com/oauth/v2/authorize',
    tokenEndpoint: 'https://login.uber.com/oauth/v2/token',
    revocationEndpoint: 'https://login.uber.com/oauth/v2/revoke'
  }
};
```

3. Add a placeholder in `build.gradle` file:
```
manifestPlaceholders = [
           appAuthRedirectScheme: 'https://my.app.auth'
       ]
```

**Comment by prabakarviji** [comment]
@vendeza So you are suggesting to another activity in manifest that handle HTTPS scheme? But how this is possible in react -native adding another activity?

**Comment by GunnarAK** [comment]
@vendeza could you please explain how this would be done for iOS? 
I have Associated Domains setup and I've added the code snippets shown in the README setup.
