### ISSUE TITLE
How to handle logout from Azure AD?

### ISSUE THREAD

**Issue by AlbinCederblad** [FormidableLabs/react-native-app-auth#789]
## Issue

I have a logout button,

when i click it i call this function with the `idToken` i saved after logging in:

```
/**
 * Logout using react-native-app-auth
 * @returns 
 */
export const logoutFromAD = async (idToken: string) => {
  try {
    const logoutResult = await logout(config, {
      idToken: idToken,
      postLogoutRedirectUrl: 'myapp://home',
    });
    console.log("Logged out", JSON.stringify(logoutResult, null, 2));
  } catch (error) {
    console.log(error);
  }
}
```

Now I am not sure what I'm supposed to do with the `postLogoutRedirectUrl`.

I tried using deep linking with `reactnavigation` as seen above,
with my `AndroidManifest `looking like this after running `npx uri-scheme add myapp --android`
```
<intent-filter>
  <action android:name="android.intent.action.VIEW"/>
  <category android:name="android.intent.category.DEFAULT"/>
  <category android:name="android.intent.category.BROWSABLE"/>
  <data android:scheme="myapp"/>
</intent-filter>
```

Am I doing something completely wrong with deep linking / redirect? Is there anywhere I can find an example code of someone using the logout function?

Any help appreciated

---

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?**: `No`

**Comment by AlbinCederblad** [comment]
I've found a work around for now by calling first `logout`, then I expect the user to click X when left on the
"successfully logged out" screen, thus cancelling the user flow resulting in error `[Error: User cancelled flow]`, I catch that error and then call `authorize` again.

**Comment by rijspathan** [comment]
@AlbinCederblad  Where did you found idToken? i have integrated saml protocol to azur ad using react-native-app-auth lib by RND, my reply url in saml config is my backends url there we did not receive any token.
