### ISSUE TITLE
[Error: Response state param did not match request state]

### ISSUE THREAD

**Issue by haristl** [FormidableLabs/react-native-app-auth#795]
Hi i am using the custom auth configuration here is the example url for the auth 

https://YOUR_DOMAIN/login/oauth/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=myapp://from-app-auth://auth&code_challenge=fedcba654321&code_challenge_method=S256&state=abcde

My request params- 

const config = {
  clientId: 'jjfnnfjnv-rvnjrnvjr-vrmkrvmr-vmrjttnn-eerjn',
  redirectUrl: 'myapp://from-app-auth://auth',
  dangerouslyAllowInsecureHttpRequests: true,
  responseType: 'code',
  code_challenge: 'fedcba654321',
  code_challenge_method: 'S256',
  state: 'abcde',
  scopes: [],
  serviceConfiguration: {
    authorizationEndpoint: 'https://YOUR_CLIENT_ID/login/oauth/authorize',
    tokenEndpoint: 'https://YOUR_CLIENT_ID/login/oauth/token',
  },
  additionalParameters: {
    approval_prompt: 'force',
  }
};

Getting this below error anyone can guide why this is happening to me.

[Error: Response state param did not match request state]

**Comment by johanwesteinde** [comment]
Hi, were you ever able to resolve this issue? I'm seeing the same thing occur for me.

**Comment by ankitvat** [comment]
Any updates on this ?

**Comment by RavinaBuran** [comment]
Facing this issue on the latest version. Any way to resolve this issue?
