### ISSUE TITLE
RN 0.71 support

### ISSUE THREAD

**Issue by billnbell** [FormidableLabs/react-native-app-auth#801]
How do we setup on React Native 0.71?

@interface AppDelegate : RCTAppDelegate

Old code:
@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, RNAppAuthAuthorizationFlowManager, UNUserNotificationCenterDelegate>

How do we add RNAppAuthAuthorizationFlowManager?

**Comment by justin-tay** [comment]
In React Native 0.71 in `AppDelegate.h` it's now
`@interface AppDelegate : RCTAppDelegate`
to add `RNAppAuthAuthorizationFlowManager`
it's now
`@interface AppDelegate : RCTAppDelegate <RNAppAuthAuthorizationFlowManager>`

In your case it should look like 
`@interface AppDelegate : RCTAppDelegate <RNAppAuthAuthorizationFlowManager, UNUserNotificationCenterDelegate>`

**Comment by dylanFdvhuset** [comment]
Can we update the doc to work with 0.72 ?

**Comment by robwalkerco** [comment]
Fixed by #900
