### ISSUE TITLE
Refresh token when using Github Provider is null

### ISSUE THREAD

**Issue by iChristosK** [FormidableLabs/react-native-app-auth#816]
## Issue

Refresh token when using Github Provider is null. What changes should I make in my configuration in order to get the refresh token? My access token expires after a while and I get 401 unauthorized. 

I am using this configuration: 
```
const authGithubConfig = {
    issuer: 'https://github.com',
    redirectUrl: 'com.commitsapp://oauthredirect',
    clientId: 'xxx',
    clientSecret: 'xxx',
    scopes: ['identity', 'user', 'repo', 'offline_access'],
    usePKCE: true,
    additionalParameters: {
        access_type: 'offline',
    },
    additionalHeaders: { 'Accept': 'application/json' },
    serviceConfiguration: {
        authorizationEndpoint: 'https://github.com/login/oauth/authorize',
        tokenEndpoint: 'https://github.com/login/oauth/access_token',
        revocationEndpoint: 'https://github.com/settings/connections/applications/xxx',
    },
};
```

And inside the login screen I have: 
```

import { authorize, refresh } from 'react-native-app-auth';


const result = await authorize(authGithubConfig);

const tokenResponse = {
  accessToken: result.accessToken,
  refreshToken: result.refreshToken, // here the refresh token which is null
  tokenType: result.tokenType,
  scope: result.scope,
  expiresIn: result.expiresIn,
};

// ...

```

---

## Environment

* **Your Identity Provider**: `Github`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** : No

**Comment by iChristosK** [comment]
In case anyone is having similar issue, I was able to find the solution for the refresh token doing the following:
I integrated authentication with firebase:

import auth from '@react-native-firebase/auth';
import { authorize } from 'react-native-app-auth';

    const result = await authorize(authGithubConfig);
    const credential = auth.GithubAuthProvider.credential(result.accessToken);
    const userCredential = await auth().signInWithCredential(credential);
// ... when you make a request make sure that the response is 401 so the access token is expired then to get the new Token the below line.
   const newToken = await userCredential.user.getIdToken(true)

Hope it helps.

**Comment by iChristosK** [comment]
Should I close this? No one is answering, and probably the package does not offer refresh token, right?

**Comment by justin-tay** [comment]
If you just use `curl` does Github return the refresh token?

Also from reading the docs it looks like Github doesn't support public clients with PKCE and you are embedding the client secret in your app. See https://github.com/FormidableLabs/react-native-app-auth#note-about-client-secrets.

**Comment by iChristosK** [comment]
```
curl -X POST \
  -H "Accept: application/json" \
  -d "client_id={client_id}" \
  -d "client_secret={client_secret}" \
  -d "code=AUTHORIZATION_CODE" \
  https://github.com/login/oauth/access_token
```
I tried using the above but I get AUTHORIZATION_CODE is expired. Not sure what I am doing wrong. 
I have remove client secret and PKCE from the config and it still does not fetch refresh token.

**Comment by justin-tay** [comment]
Are you building a [Github App](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/identifying-and-authorizing-users-for-github-apps) or an [OAuth App](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps)?

It looks like OAuth Apps don't return refresh tokens and Github Apps only return refresh tokens if this [feature](https://developer.github.com/changes/2020-04-30-expiring-user-to-server-access-tokens-for-github-apps/) is enabled.

Authorization codes are single use only. Did you also get it using `curl`? If your app already sent it to the server it can't be reused.

**Comment by iChristosK** [comment]
I am building a Github Client App. 
The Expiring user-to-server access tokens feature is not appearing to Opt-in. 

No I didn’t get it using curl. How would I do it using curl?

**Comment by justin-tay** [comment]
Sorry what I meant was are you getting the code manually? Or is the code already used?

**Comment by justin-tay** [comment]
When creating the Github App there is a checkbox to opt out of the feature. After that when you edit the Github App there is an Optional features tab on the left.

**Comment by iChristosK** [comment]
Thank you Justin. I edit the Github App and opted in. Issue resolved and closed.

<img width="1046" alt="Screenshot 2023-03-11 at 15 29 51" src="https://user-images.githubusercontent.com/16455384/224490284-da72839b-1db7-49fe-a6e0-6f7634bb0ab0.png">
