### ISSUE TITLE
redirectURL doesn't work

### ISSUE THREAD

**Issue by HelenCris** [FormidableLabs/react-native-app-auth#818]
## Issue

MY CODE: 

const config = {
                    clientId: 'MYCLIENTID',
                    redirectUrl: 'myapp:/authredirect',
                    scopes: [''],
                    serviceConfiguration: {
                        authorizationEndpoint: 'MYAUTHLINK',
                        tokenEndpoint: 'MYTOKENLINK'
                    }            
                }
                const result = await authorize(config);

## Environment

* **Your Identity Provider**:  Red Hat
* **Platform that you're experiencing the issue on**: Android (I didnt test on IOS)
* **Are you using Expo?** No

**Comment by sakshambhatt** [comment]
Are you using React Navigation's deeplinking?
If yes, then please check the NOTE, in [Android setup](https://github.com/FormidableLabs/react-native-app-auth#android-setup).

When integrating with [React Navigation deep linking](https://reactnavigation.org/docs/deep-linking/#set-up-with-bare-react-native-projects), be sure to make this scheme (and the scheme in the config's redirectUrl) unique from the scheme defined in the deep linking intent-filter. E.g. if the scheme in your intent-filter is set to com.myapp, then update the above scheme/redirectUrl to be com.myapp.auth https://github.com/FormidableLabs/react-native-app-auth/issues/494#issuecomment-797394994.

However, in my case, it is not working despite changing the scheme for authorization.
React Navigation deeplink scheme: com.mobileclient
React Native app auth's appAuthRedirectScheme: 'com.mobileclient.auth'

In my case, it is redirecting back to my app, but there is an error in authorize which does not make sense.

```JSX
async function loginWithGithub(config: Config) {
  try {
    const result = await authorize(config);
    console.log({result});
    return result;
  } catch (err) {
    console.log({err});
  }
}

function Login() {
  const handleSignIn = useCallback(async () => {
    const config = {
      clientId: GITHUB_OAUTH_CLIENT_ID,
      clientSecret: GITHB_OAUTH_CLIENT_SECRET,
      redirectUrl: 'com.mobileclient.auth://oauthredirect',
      scopes: ['read:user'],
      serviceConfiguration: {
        authorizationEndpoint: 'https://github.com/login/oauth/authorize',
        tokenEndpoint: 'https://github.com/login/oauth/access_token',
        revocationEndpoint: `https://github.com/settings/connections/applications/${GITHUB_OAUTH_CLIENT_ID}`,
      },
    };
    const result = await loginWithGithub(config);
    console.log({result});
  }, []);

  return (
    <View style={styles.loginContainer}>
      <Text style={styles.heading}>Login Screen</Text>
      <Pressable style={styles.btnContainer} onPress={handleSignIn}>
        <Text style={styles.btnText}>Sign in with GitHub</Text>
      </Pressable>
    </View>
  );
}
```
