### ISSUE TITLE
ios run failed

### ISSUE THREAD

**Issue by togenius1** [FormidableLabs/react-native-app-auth#819]
## Issue

---

This is AppDelegate.h for reace-native 0.71.3
---------
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>

@interface AppDelegate : RCTAppDelegate

@end

-------

So that, I cannot config as in the document.
and ios run failed like this:

The following build commands failed:
	CompileC /Users/nunggu/Library/Developer/Xcode/DerivedData/Finner-egqjpsjbgnygpzfhaectvsqbodcg/Build/Intermediates.noindex/Finner.build/Debug-iphonesimulator/Finner.build/Objects-normal/arm64/AppDelegate.o /Volumes/M2/Mobile-Project/Finner/ios/Finner/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Finner' from project 'Finner')
(1 failure)

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Are you using Expo?**

**Comment by robwalkerco** [comment]
Resolved by #900
