### ISSUE TITLE
await authorize() call never returns on Android after I finalize or cancel the login

### ISSUE THREAD

**Issue by colinyoung** [FormidableLabs/react-native-app-auth#82]
I am developing a Create React Native App/Expo app (versions: RN 0.52.0, Expo 25) and I have seemingly correctly set up my AndroidManifest.xml with the correct net.openid.appauth activity; I think I know this because after I login inside the authorization webview, I'm redirected, the Android app starts back up, and I can see the redirect code/url in my logcat.

However, nothing happens after that - the promise just never returns and the token isn't requested. The promise from RNAppAuth doesn't return even if I cancel the authorization request, by the way. This isn't isolated to my custom identity provider - it's the same thing for Google, too. I believe I'm using the latest version of the Android-AppAuth and react-native-app-auth libraries, but it's very hard to determine precisely which version of Android-AppAuth I'm using since it's an existing ExpoKit dependency as well.

**Comment by colinyoung** [comment]
I learned more info about this. I think the reason this conflict occurs is because Android-AppAuth is already included within ExpoKit. I've chosen another path for now but will return to give more info based on what I find.

**Comment by kadikraman** [comment]
I've not tried the library with ExpoKit, but I have heard that they also use AppAuth, which would explain the conflict. Not sure how feasible it would be to make these two play nicely with each other.

**Comment by colinyoung** [comment]
Agreed and I think it would be better to create an issue on the Expo side. Closing this now.

**Comment by aaddaamm** [comment]
I'm on `ReactNative 55.3` and using `react-native-app-auth 2.3.0` We are not using ExpoKit and have seen this issue where on Android, The authorize request will never return. We will have to close the web page manually and try logging in again.

**Comment by kadikraman** [comment]
@aaddaamm 
1) does it only happen on Android or iOS as well?
2) which API version Android are you testing with?

**Comment by kadikraman** [comment]
Hi @N1ghtly just trying to repo this. I've created a new project with expo and tried to eject immediately. I get these options. Did you choose 1 or 2?

<img width="649" alt="screenshot 2018-12-11 at 12 43 55" src="https://user-images.githubusercontent.com/6534400/49801581-7ce74400-fd42-11e8-9494-f8e752ea6c7c.png">

**Comment by N1ghtly** [comment]
Hi @kadikraman, we chose Expokit, but I have figured it out by now. Expo overrides the native Activity and fails to propagate onActivityResult to non-Expo libraries. It should be fixed in SDK 32.

**Comment by mdcuk34** [comment]
@N1ghtly We are experiencing this issue on an ExpoKit project (32 SDK). Do you have any pointers?
