### ISSUE TITLE
iosPrefersEphemeralSession is not working 

### ISSUE THREAD

**Issue by sritharIOS** [FormidableLabs/react-native-app-auth#823]
## Issue

Hi All,

To suppress the permission alert and session in browser,  I have used the iosPrefersEphemeralSession: true config in authorize call. But this is not working and also while doing signout its asking the signin permissiion alert.

I need to do disable this one, please help.

 below code for accesstoken- authorize 

```
const config = {
  issuer: issuerUrl(),
  clientId: clientId(),
  redirectUrl: 'app://token/',
  scopes: ['openid', 'offline_access', clientId()],
  iosPrefersEphemeralSession: true,
};
 const result = await authorize(config);

```
Below code for Signout:

```
 const logoutConfig = {
      issuer: issuerUrl(),
      iosPrefersEphemeralSession: true,
    };
  const result = await logout(logoutConfig, {
      idToken: token,
      postLogoutRedirectUrl: 'app://token/',
    });
    
```
---
<img width="320" alt="Screen Shot 2023-03-08 at 5 46 26 PM" src="https://user-images.githubusercontent.com/16605998/223886124-0a28bfc0-45cc-4d22-b1a5-4d1b5337b435.png">

## Environment

* **Your Identity Provider**: `Azure B2C`
* **Platform that you're experiencing the issue on**: `iOS `
* **Are you using Expo?** No
React native version: 0.68.3
"react-native-app-auth": "^6.4.3",
iOS version: 15 and 16

**Comment by kkaplinski** [comment]
@sritharIOS you need to install the new version of the library [v.7.0.0-rc2](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v7.0.0-rc2). Documentation is changed for that version.

**Comment by sritharIOS** [comment]
@kkaplinski Is any chance to hide the address bar in app auth modal screen?

<img width="488" alt="Screen Shot 2023-03-10 at 9 56 22 AM" src="https://user-images.githubusercontent.com/16605998/224376655-f73d3a82-45a5-4896-b231-d1adab40235b.png">

**Comment by paritosh-yadav** [comment]
Hi @kadikraman 
Why this support not added to latest Tag v6.4.3 ?

**Comment by sumitgarg9604** [comment]
Hi @kkaplinski  @paritosh-yadav @sritharIOS 

I am able to get it working on authorize() but the popup still comes on logout().

I am using 

` const config = {
    issuer: 'https://login.microsoftonline.com/<tenantId>/v2.0',
  };

  try {
    let result;

    result = await logout(config, {
      idToken: accessToken,
      
      postLogoutRedirectUrl: '<post logout url>',
      iosPrefersEphemeralSession: true,
    });
  } catch (error) {
    console.log('error logging out', error);

  }
