### ISSUE TITLE
React native 0.71.4

### ISSUE THREAD

**Issue by MikeBytenko** [FormidableLabs/react-native-app-auth#824]
## Documentation Feedback

Can you provide setup documentation for the latest RN?

**Comment by messivite** [comment]
we are waiting provide setup documentation for RN 0.71.4

**Comment by JavoxirNazarov** [comment]
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager> 

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end

**Comment by JavoxirNazarov** [comment]
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager> 

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end

**Comment by JavoxirNazarov** [comment]
`#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager> 

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end
`

**Comment by JavoxirNazarov** [comment]
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager>

**Comment by JavoxirNazarov** [comment]
`@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager>`
