### ISSUE TITLE
The token is not being exchanged when using "iosCustomBrowser".

### ISSUE THREAD

**Issue by BradleyVangelder** [FormidableLabs/react-native-app-auth#829]
## Issue

The token is not being exchanged when using **iosCustomBrowser**.

**config:**

`const config: AuthConfiguration = {
  issuer: issuer(),
  clientId: clientId(),
  redirectUrl: redirectUrl(),
  iosCustomBrowser: 'safari',
  androidAllowCustomBrowsers: ['chrome','firefox','samsung'],
  additionalParameters: { prompt: 'login' },
  serviceConfiguration: {
    authorizationEndpoint: authorizeEndpoint(),
    tokenEndpoint: tokenEndpoint(),
  },
  iosPrefersEphemeralSession: true,
  scopes: []
};`

---

## Environment

* **Your Identity Provider**: `Forgerock `
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?**: `NO`

**Comment by snode4** [comment]
I am seeing this issue too. When using a custom browser, the response has an empty strong for the access token and all the additional specifiers for the access token.

Has anyone found a workaround?

**Comment by snode4** [comment]
I think I found the issue. 
In `RNAppAuth.m` on line 409, we seem to provide the same method we would use if we were attempting to skip the code exchange.

These are the steps I took to fix the issue.

1. Took the `callback` instantiation on line 413 and moved it to the first line in the parent `else` block. 
2. On line 409, replaced `_currentSession = [OIDAuthorizationService presentAuthorizationRequest:request
                                                                    externalUserAgent:externalUserAgent
                                                                             callback:callback];`
with`_currentSession = [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                                                    externalUserAgent:externalUserAgent
                                                                             callback:callback];`
3. Rebuilt and ran.

Nice and easy steps, but after changing the logic in this `else` block, everything seemed to work as expected.

**Comment by maheshwarimrinal** [comment]
@dev-ov2 Can you help with the exact code code

**Comment by owenadley** [comment]
Having this issue as well.

**Comment by remacr** [comment]
@maheshwarimrinal @owenadley check the [PR](https://github.com/FormidableLabs/react-native-app-auth/pull/939), thanks @dev-ov2 for that finding.
