### ISSUE TITLE
Token Storage advice in Readme

### ISSUE THREAD

**Issue by getaaron** [FormidableLabs/react-native-app-auth#83]
A common question when implementing OAuth is how to store the secrets when the application is not running. Currently the readme is silent on this. I'd like to suggest a section that answers:

- Does react-native-app-auth provide a secure token storage mechanism or is that left as an exercise for the developer?
- If not, what tool / storage approach is recommended? [react-native-keychain](https://github.com/oblador/react-native-keychain)?

**Comment by kadikraman** [comment]
Thanks for the suggestion. This idea has actually come up before: https://github.com/FormidableLabs/react-native-app-auth/issues/55 - presently we do not provide neither a storage mechanism nor instructions, but it does seem like it would be a valuable addition and will certainly be added to the backlog.

react-native-keychain is arguably a bit too opinionated for token storage. For sensitive storage, I'd use [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info) although as a caveat, a jailbroken device can access your iOS Keychain/ Android shared preference and key store in plain text. So for really valuable apps, e.g. banking, you'd have to protect your sensitive info with a further layer of security in the form of touch/face ID.

**Comment by getaaron** [comment]
Would you be open to a PR briefly discussing those two options?

**Comment by kadikraman** [comment]
Yes, definitely, it would be most useful!
