### ISSUE TITLE
[Android] Data intent is null -> using universal links/applinks.

### ISSUE THREAD

**Issue by RaviKiranMakala** [FormidableLabs/react-native-app-auth#835]
## Issue

I am using `Android AppLinks` for redirection and unable to get the response for `authorize()` method. I am facing the below error.
`[Error: Data intent is null]`
`{"nativeStackAndroid":[],"userInfo":null,"message":"Data intent is null","code":"authentication_error"}` 

It is working with `app scheme` but not with the `app links`

below are my configurations

AndroidManifest.xml

`<intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https"
          android:host="mydomain.com"
        />
      </intent-filter>`

build.gradle

`android {
  defaultConfig {
  manifestPlaceholders = [
            appAuthRedirectScheme: 'appScheme',
        ]
  }
}`

Okta configuration
{
        issuer: "https://dev-xxxxxx.okta.com/oauth2/default",
        clientId: '{clienId}',
        clientSecret: '{clienSecret}',
        // redirectUrl: "https://mydomain.com",                       -> `{Getting Data intent null}`
        redirectUrl: 'appScheme://app/Dashboard',                 -> `Working fine as expected`
        scopes: ['openid', 'profile', 'email', 'offline_access'],
}

---

## Environment

* **Your Identity Provider**: `Okta`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** `No`

**Comment by lucassms9** [comment]
same problem ... any solution ?
