### ISSUE TITLE
Setup with an Expo Development Build Project

### ISSUE THREAD

**Issue by markmccoid** [FormidableLabs/react-native-app-auth#842]
## Issue

I would like to use this module in an Expo application using the dev-client.  I have used other "non" expo modules, but none that modified things in the xCode project.

I'm getting hung up on the changes to the AppDelegate.h file

Expo has its own entry: `@interface AppDelegate : EXAppDelegateWrapper`

I saw another user mention adding the following instead:
```
@interface AppDelegate : RCTAppDelegate<RNAppAuthAuthorizationFlowManager>

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;
```

This worked in the sense that I could develop and use the library, but I started getting errors that may have been caused by removing the EXAppDelegateWrapper.

I have no idea what the AppDelegate.h file does, so I'm hoping to get some guidance. 

This library works great.  I originally tried Expo's auth library, but it doesn't return a refresh token for Dropbox.

Here is the error being generated:
```
 Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate
application:openURL:options:]: unrecognized selector sent to instance 0x600002b8c300'
*** First throw call stack:
(
0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
2   CoreFoundation                      0x000000018041d47c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   UIKitCore                           0x0000000115dc7d74 -[UIResponder doesNotRecognizeSelector:] + 232
4   CoreFoundation                      0x0000000180412490 ___forwarding___ + 740
5   CoreFoundation                      0x0000000180414b4c _CF_forwarding_prep_0 + 92
6   BookTracker                         0x0000000102b66988 -[AppDelegate application:openURL:options:] + 128
7   UIKitCore                           0x0000000115da5b38 __58-[UIApplication _applicationOpenURLAction:payload:ori<…>
```
---

## Environment

* **Your Identity Provider**: `dropbox`
* **Platform that you're experiencing the issue on**: `iOS `
* **Are you using Expo?** Yes

**Comment by markmccoid** [comment]
I have found a solution.  See the full file below:

```
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import <Expo/Expo.h>
#import "RNAppAuthAuthorizationFlowManager.h"

// added the <RNAppAuthAuthorizationFlowManager>
@interface AppDelegate : EXAppDelegateWrapper <RNAppAuthAuthorizationFlowManager>

@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;

@end
```

**Comment by ArtRabbit** [comment]
This looks really interesting thanks for sharing. Any chance you could share the full setup to get it to work with expo / expo-dev client?

**Comment by faizplus** [comment]
closing as the solution is provided [here](https://github.com/FormidableLabs/react-native-app-auth/issues/842#issuecomment-1512368775)
