### ISSUE TITLE
Small error in installation guide for Android

### ISSUE THREAD

**Issue by Landcross** [FormidableLabs/react-native-app-auth#85]
I believe there is a small error in the (manual) installation guide. Under _Getting Started_ -> _Manual Installation_ -> _Android_ it says to add an import and an RNAppAuthPackage() to **MainActivity.java**.

However, I believe that should be **MainApplication.java**. The example project has added those lines in the MainApplication.java and the getPackages() method is also only available in the MainApplication.java and not in the MainActivity.java.

**Comment by kadikraman** [comment]
Wow, that's a great spot! We actually used a library [react-native-create-library](https://github.com/frostney/react-native-create-library) to generate the boilerplate and it seems like the same error [is there as well](https://github.com/frostney/react-native-create-library/blob/db4549aa24728eae23dfed5509d7698566a3a508/templates/general.js#L23). Thanks for pointing it out though, I'll get it fixed here and submit a PR for them as well 👍

In the future, feel free to submit a PR yourself. No contribution is too small 😊
