### ISSUE TITLE
Account stays cached

### ISSUE THREAD

**Issue by slavko-lukic** [FormidableLabs/react-native-app-auth#856]
## Issue

I cannot get authorize() method to open account selection page after I select google account first time.
It looks like to me that something stays cached in that safari view that app opens.
Is there any configuring that needs to be done on aws side?

This is my config:

```javascript
const baseAuthConfig: BaseAuthConfiguration = {
  clientId: AUTH_CLIENT_ID,
  serviceConfiguration: {
    authorizationEndpoint: `${AUTH_DOMAIN_NAME}/oauth2/authorize`,
    tokenEndpoint: `${AUTH_DOMAIN_NAME}/oauth2/token`,
    revocationEndpoint: `${AUTH_DOMAIN_NAME}/oauth2/revoke`,
  },
};

const googleConfig: AuthConfiguration = {
  ...baseAuthConfig,
  scopes: ["profile", "email", "openid"],
  redirectUrl: OAUTH_LOGIN_REDIRECT,
  additionalParameters: {
    identity_provider: "Google",
    prompt: "select_account",
  },
};
```

"react-native": "0.71.7",
"react-native-app-auth": "^6.4.3",

---

## Environment

* **Your Identity Provider**: `AWS Cognito`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?**: No

**Comment by sumitgarg9604** [comment]
I also faced the same issue. The account selection only came when the there are multiple microsoft accounts were cached in safari web browser. If only one account, then the account selection screen is skipped and the app auto logs in. 

Use this in configuration to get the mandatory account selection screen
`    additionalParameters: { prompt: 'select_account' },
`
