### ISSUE TITLE
Difference AppDelegate.m

### ISSUE THREAD

**Issue by joh-klein** [FormidableLabs/react-native-app-auth#86]
Tbh I am very new to react native and thus I get insecure very quickly if any lines in a readme are not the way I expect them to be. In this case, you have these lines:

```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
```

But the default from RN looks like this:

```
- (BOOL)application:(UIApplication *)application 
            didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{
```

Since I have only a very limited idea, what any of this does, I don't know, if you expect me to replace the default line with yours or only parts of it, or if yours is just older.

Thanks in advance!

**Comment by kadikraman** [comment]
Hmm. The version in the readme was what is created with `react-native init` at the time. Which version of React Native are you using?

**Comment by joh-klein** [comment]
react-native-cli: 2.0.1
react-native: 0.55.2

**Comment by joh-klein** [comment]
Looking at [your AppDelegate.m example](https://github.com/FormidableLabs/react-native-app-auth/blob/master/Example/ios/AppAuthExample/AppDelegate.m) it is clear, that I totally misunderstood the instructions.

Would be really nice, if you added a link to the example from the code blocks.

**Comment by getaaron** [comment]
For any future readers, `application:didFinishLaunchingWithOptions:` is called by iOS when your application starts, and `application:openURL:options:` is called when a URL is requested that your app is registered to handle.

**Comment by joh-klein** [comment]
Thanks for the explanation!
