### ISSUE TITLE
0.72 React Native Guide

### ISSUE THREAD

**Issue by ishan-flek-ai** [FormidableLabs/react-native-app-auth#867]
### Adding google auth

- https://github.com/FormidableLabs/react-native-app-auth

- Create project on console `https://console.cloud.google.com/` can do this without setting up GCP
- Create oauth consent screen
- No need to add anything apart from the name and email
- Go to credentials and then create credentials, select OAuth client ID,
- Application type is Android -> works on both android and ios package name is com.[name]
- Create a keystore folder in both ios and android folder and generate keystore
- https://medium.com/@hasangi/making-a-signed-apk-for-your-react-native-application-98e8529678db
- Follow instruction to generate SHA1 fingerprint
- It will generate `[key].apps.googleusercontent.com`

https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/google.md

```
const config = {
issuer: 'https://accounts.google.com',
clientId:
'[key].apps.googleusercontent.com',
redirectUrl:
'com.googleusercontent.apps.[key]:/oauth2redirect/google',
scopes: ['openid', 'profile'],
};

const result = await authorize(config);
```

https://github.com/FormidableLabs/react-native-app-auth
https://github.com/FormidableLabs/react-native-app-auth/issues/801

AppDelegate.h

```
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
+ #import <React/RCTLinkingManager.h>
+ #import "RNAppAuthAuthorizationFlowManager.h"

+ @interface AppDelegate : RCTAppDelegate <RNAppAuthAuthorizationFlowManager>
+ @property(nonatomic, weak) id<RNAppAuthAuthorizationFlowManagerDelegate> authorizationFlowManagerDelegate;

@end
```

https://github.com/FormidableLabs/react-native-app-auth/issues/453
What to do if provider requires redirectUrl to be https?

AppDelegate.mm

```
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"ember";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL) application: (UIApplication *)application
             openURL: (NSURL *)url
             options: (NSDictionary<UIApplicationOpenURLOptionsKey, id> *) options
{
  // return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL) application: (UIApplication *) application
continueUserActivity: (nonnull NSUserActivity *)userActivity
  restorationHandler: (nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  if ([userActivity.activityType isEqualToString:NSUserActivityTypeBrowsingWeb]) {
    if (self.authorizationFlowManagerDelegate) {
      BOOL resumableAuth = [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:userActivity.webpageURL];
      if (resumableAuth) {
        return YES;
      }
    }
  }
  return [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

**Comment by ishan-flek-ai** [comment]
Everyone is having the google redirect issue, 
### Android

```
    namespace "com.ember"
    defaultConfig {
        applicationId "com.ember"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.googleusercontent.apps.[id]',
        ]
    }
```

appAuthRedirectScheme has to be google URL to be secure that is the issue everyone is facing. that is because they are using invalid appAuthRedirectScheme, it is not com.[packageName] but what google has given

**Comment by rcidt** [comment]
@ishan-flek-ai should the `appAuthRedirectScheme` literally be "com.googleusercontent.apps.[id]", or should `[id]` be some arbitrary string?

**Comment by asapMaki** [comment]
For me the case is that I upgraded my RN version to 0.72.4, previously everything worked like a charm, right now, only iOS works. Android is stuck at infinite loading for google login, for email login it is just stuck or it says Bad request.
`appAuthRedirectScheme: 'com.app.scheme'` in app/build.gradle
Also we are using `msauth.com.` as a oAuth provider not google
Any thoughts ideas how to debug at least ? Thanks in advance

**Comment by ishan-flek-ai** [comment]
@rcidt that is your oauth client id that you created on google cloud console
