### ISSUE TITLE
Cannot read property 'authorize' of undefined

### ISSUE THREAD

**Issue by joh-klein** [FormidableLabs/react-native-app-auth#87]
I get `TypeError: Cannot read property 'authorize' of undefined` with this setup

```
import { authorize as auth } from 'react-native-app-auth';

const config = {
  clientId: 'app-id',
  clientSecret: 'super-secret',
  redirectUrl: 'com.app://redirect',
  scopes: ['activity', 'sleep'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://domain/authorize',
    tokenEndpoint: 'https://domain.tld/token',
    revocationEndpoint: 'https://domain.tld/revoke'
  }
};

auth(config).then(result => {
  console.log(result);
}).catch(e => {
  console.error(e);
});
```

**Comment by joh-klein** [comment]
I use `"react-native-app-auth": "2.4.0"`.

**Comment by ryan-roemer** [comment]
Weird. https://unpkg.com/react-native-app-auth@2.4.0/index.js has `export const authorize` right in there. Can you create a minimal repository with install + build steps so we can clone it and hit the error you're hitting?

Thanks!

**Comment by adba** [comment]
@joh-klein I just had the same error message. 

It turns out the step: `react-native link react-native-app-auth` for some reason didn't add the libRNAppAuth.lib to "Linked frameworks and Libraries".

I did the "manual install" to solve it for me: https://github.com/FormidableLabs/react-native-app-auth#manual-installation

@ryan-roemer The error comes from the line that says:

`return RNAppAuth.authorize(...nativeMethodArguments);`

RNAppAuth is undefined if it wasn't linked correctly.

**Comment by joh-klein** [comment]
OK. I am beginning to understand, where to look. When I build the iOS part it says
`fatal error: 'AppAuth.h' file not found`

And my AppDelegate.m looks like that (so maybe it is related to #86?!):

```
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import "RCCManager.h"
#import <React/RCTRootView.h>
#import "AppAuth.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

#ifdef DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];

  if ([_currentAuthorizationFlow resumeAuthorizationFlowWithURL:url]) {
    _currentAuthorizationFlow = nil;
    return YES;
  }

  return NO;
}

@end
```

Also, I have the feeling, that the Android Manual Install is not precise enough for dummies (like me). It says:

> Open up android/app/src/main/java/[...]/MainActivity.java
Add import com.reactlibrary.RNAppAuthPackage; to the imports at the top of the file
Add new RNAppAuthPackage() to the list returned by the getPackages() method

But there is no "getPackages()" method in the MainActivity.java file …

**Comment by joh-klein** [comment]
I also thought, it had something to do with #80, but changing that only changed the error message to
`fatal error: 'AppAuth/AppAuth.h' file not found`
How would I know, that I installed AppAuth correctly? I did `carthage bootstrap` and followed the steps of the AppAuth project …

**Comment by joh-klein** [comment]
Looking at [your AppDelegate.m example](https://github.com/FormidableLabs/react-native-app-auth/blob/master/Example/ios/AppAuthExample/AppDelegate.m) it is clear, that I totally misunderstood the instructions.

Maybe you could link to the examples at each code block (for people like me, who skipped ahead and didn't know there were any examples …)?!

And it also looks like, carthage is as of right now too advanced for me. I evidently couldn't get it to add the AppAuth package properly. I removed the whole stuff and did it with Pods. Works!

**Comment by kadikraman** [comment]
Glad you figured it out! I assumed you were using carthage due to an existing project constraint and were struggling because out example uses Pods, so didn't think to recommend it 😄

**Comment by kadikraman** [comment]
@tuannkop that error means the native library can't be found. Have a look at the [manual installation instructions](https://github.com/FormidableLabs/react-native-app-auth#android) for Android and ensure your application has the same changes.

**Comment by tuannkop** [comment]
@kadikraman thank you for reponse , i tried with both react-native link react-native-app-auth and manual install but its still not working . however, i tried add library with new init react native project , it working well =)) i'm so confused , i thought because 'com.android.support:appcompat-v7:25.3.1'
, i have use react-native-navigation .

**Comment by kadikraman** [comment]
@ydvsailendar yes you need to eject from expo in order for any native dependencies to work

**Comment by frostless** [comment]
I have been struggling for this for the past few days...
I use pod and react-native link react-native-app-auth, and I also check with the example so make sure everything is the OK. But I still get this error.

**Comment by arjunpathy** [comment]
Im getting the following error whenever im using react-native-app-auth 
![Screenshot 2019-07-10 at 11 12 17 PM](https://user-images.githubusercontent.com/21103179/60991704-add73800-a368-11e9-8da5-c1989c448f55.png)


here is my package.json

![Screenshot 2019-07-10 at 11 12 58 PM](https://user-images.githubusercontent.com/21103179/60991741-bdef1780-a368-11e9-84c1-1a4baaed9f77.png)


I have also tried linking RN with RNAppAuth.. but it didn't work.

**Comment by kadikraman** [comment]
Hi @arjunpathy 👋 - this error is always to do with misconfiguration. Make sure you've followed the setup instructions, `react-native link`ed, and rebuilt your app with `react-native run-ios` or `react-native run-android`.

**Comment by tarun29061990** [comment]
Any update on this? I am still facing the issue on IOS simulator. I have tried everything mentioned in this thread still no success

**Comment by kadikraman** [comment]
Hi @tarun29061990 👋 Could you try running the iOS [example app](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example/iOSPodsExample) and see if it works for you? If it does, you can compare your configuration to that of the example app and see what's different.

**Comment by fsg101** [comment]
I encountered the same error as mentioned here when I try to load an app for a Windows app. (return RNAppAuth.authorize(...nativeMethodArguments); "TypeError: Cannot read properties of undefined"). I tried the linking process but it is intended only for Android and iPhone; as seen below. Does somebody know if there is an easy fix for a Windows app ?

I use react-native-app-auth@6.4.1.


npx react-native link react-native-app-auth
      npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
      warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
      Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
      info Linking "react-native-app-auth" iOS dependency
      info iOS module "react-native-app-auth" has been successfully linked
      info Linking "react-native-app-auth" Android dependency
      info Android module "react-native-app-auth" has been successfully linked
