### ISSUE TITLE
Network Profiling

### ISSUE THREAD

**Issue by joh-klein** [FormidableLabs/react-native-app-auth#88]
I just tried the "Network Profiler" built into Android Studio, but it didn't detect any traffic. Possible reason was:

> Currently, the Network Profiler supports only the HttpURLConnection and OkHttp libraries for network connections.

How do others detect/monitor the outgoing network traffic?

**Comment by kadikraman** [comment]
Hi 👋  The easiest way to track network traffic would be to use a proxy app.

[Charles Proxy](https://www.charlesproxy.com/) is what I usually use (they have a free trial). There's also plenty of free ones you could use, e.g [mitmproxy](https://mitmproxy.org/).
