### ISSUE TITLE
access token is null

### ISSUE THREAD

**Issue by SanjaySargam** [FormidableLabs/react-native-app-auth#884]
## Issue

```
const config = {
  clientId: '<CLIENT_ID>',
  clientSecret:'<CLIENT_SECRET>',
  redirectUrl: 'com.opencollective.dev:/callback',
  scopes: ['account'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://opencollective.com/oauth/authorize',
    tokenEndpoint: 'https://opencollective.com/oauth/token',
  } as ServiceConfiguration, // Type assertion to ServiceConfiguration
  usePKCE:true,
  skipCodeExchange:true,
};
```
---
Here is my config details 

The access token always returns null after successfully authorized.
`authresult {"accessToken": null, "additionalParameters": {}, "authorizationCode": "a4dvfvfbf738c3666cff6237334ae654ea227014bvfgcbebd68e6ad5089841e032734fe2f9", "codeVerifier": "kT89emhumA0MrzbOUTgdg7LLJPtIosCkSH7Rk913YSqdOyfdfgfdRziVfVZO5MXQGQ367X5xssWNhVncExogCzaQsPEbcAg", "idToken": null, "scopes": [], "tokenType": null}`

https://docs.opencollective.com/help/developers/oauth

## Environment

* **Your Identity Provider**: `Open Collective`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** No

**Comment by thehood02** [comment]
Hi, did you find the solution for this issue? Thanks.

**Comment by SanjaySargam** [comment]
> Hi, did you find the solution for this issue? Thanks.
> 

Yes

**Comment by thehood02** [comment]
Cool, can you tell me how? What did you do?
