### ISSUE TITLE
Digital asset links error after upgrade to 7.0.0

### ISSUE THREAD

**Issue by Daniel-Parkinson** [FormidableLabs/react-native-app-auth#907]
## Issue

After upgrading to 7.0.0, we are now getting an error message when opening the browser on authorize requests.

`Digital asset links verification failed on https:` followed by the authorize endpoint URL.

We believe this may be an issue introduced in #747, as we can't see a way to override this new behavior in the exposed configuration.

`customTabsIntent.intent.putExtra(TrustedWebUtils.EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY, true);`

This seems to be setting this value for all requests on a new enough SDK version, and is always passing it through to the `AuthorizationService`.

Using a third party OIDC provider, we can't provide an assetlinks.json file.

---

## Environment

* **Your Identity Provider**: `Azure AD B2C`
* **Platform that you're experiencing the issue on**: `Android`
* **Your `react-native` Version**: `10.70.3`
* **Your `react-native-app-auth` Version**: `7.0.0`
* **Are you using Expo?** `No`

**Comment by robwalkerco** [comment]
This should be resolved in [v7.1.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v7.1.0)
