### ISSUE TITLE
When can the changes in v7.0.0-rc2 be included in a main release build?

### ISSUE THREAD

**Issue by josephk96** [FormidableLabs/react-native-app-auth#920]
Hi everyone, my company is using this library to use FusionAuth as our iDP. I saw quite a few opened issues related to the alerts that are shown every time we call a method provided by this package; and for logouts especially it might be confusing for users to be prompted with the alert saying that we need their permission to "Sign In". I saw that in `v7.0.0-rc2`, there are changes that allow us to pass in `iosPrefersEphemeralSession: true`, as a config value, and I'm wondering when we can get these changes included in a main release so we can start using it in our app? Thanks!

https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v7.0.0-rc2

**Comment by josephk96** [comment]
![CleanShot 2023-11-08 at 14 50 41@2x](https://github.com/FormidableLabs/react-native-app-auth/assets/44601888/38cc445e-c123-4573-9119-1025b65cdc16)

The popup looks like this, by the way.

**Comment by hamxabaig** [comment]
Wondering the same thing as @josephk96

**Comment by mustkeme** [comment]
+1
