### ISSUE TITLE
Apple Privacy Manifest for AppAuth-iOS

### ISSUE THREAD

**Issue by rhoadsjustin** [FormidableLabs/react-native-app-auth#954]
Apple's Privacy manifest requirement is required by May 1st. 

https://developer.apple.com/news/?id=3d8a9yyh

AppAuth is mentioned in the SDKs that require a privacy manifest and signature: 
https://developer.apple.com/support/third-party-SDK-requirements/

It looks like the AppAuth-iOS pod released the version that has the privacy manifest recently:
https://github.com/openid/AppAuth-iOS/releases/tag/1.7.3

I was able to patch the latest version of RN App Auth to have the podspec point to this version and my app builds fine. wondered if we can make that version update or if were waiting for another AppAuth-iOS release? 

thanks!

**Comment by vasylnahuliak** [comment]
`bundle exec pod update AppAuth` will update to 1.7.3 version
