### ISSUE TITLE
Problems setting redirectUri using Expo

### ISSUE THREAD

**Issue by cr1337-sudo** [FormidableLabs/react-native-app-auth#957]
## Issue
-- SPOTIFY LOGIN --
Hi there. I'm using react native with Expo and I'm facing a problem when I have to redirect after he clicks the 'Agree' button.
I'm not quite sure about what url should I use, according to a few StackOverflow questions I should use the redirect uri *'exp://192.168.1.2:8081/--/spotify-auth-callback'*

This is my `spotifyConfig`that I'm using to initiate the login:
```
this.spotifyAuthConfig = {
			clientId: 'CLIENT-iD',
			clientSecret: 'CLENT-SECRETI,
			redirectUrl: 'exp://192.168.1.2:8081/--/spotify-auth-callback',
			scopes: [
				'playlist-read-private',
				'playlist-modify-public',
				'playlist-modify-private',
				'user-library-read',
				'user-library-modify',
				'user-top-read',
			],
			serviceConfiguration: {
				authorizationEndpoint: 'https://accounts.spotify.com/authorize',
				tokenEndpoint: 'https://accounts.spotify.com/api/token',
			},
		};
```
---
I'm using the same redirectUri in my Spotify Project Configuration. 

## Environment

* **Your Identity Provider**: `Not sure`
* **Platform that you're experiencing the issue on**: `both`
* **Your `react-native` Version**: `0.73.6`
* **Your `react-native-app-auth` Version**: 7.1.3
* **Are you using Expo?**: Yes

**Comment by zibs** [comment]
I think you'll want to take a look at https://docs.expo.dev/versions/latest/sdk/auth-session/#usage-in-standalone-apps for how to set a redirect URI scheme using Expo.
