### ISSUE TITLE
Getting the authorization_code

### ISSUE THREAD

**Issue by authuser** [FormidableLabs/react-native-app-auth#96]
Hello,

Is there documentation somewhere which describes how to perform *only* the authorize request (do not perform the token request)? It would be very useful to be able to get the authorization_code.

The main use case for this is if your OAuth provider requires a non-shareable client secret, which according to the readme means that the authorization_code -> access_token exchange should be done on the server side. In order to do this with this library, we would need to be able to get the authorization_code somehow. My understanding is that this is not currently possible?

From my reading of the source, it seems reasonably straightforward to do this for android: 

1. Remove the token request calls from onActivityResult
2. Adapt tokenResponseToMap for the authorization_code to return to RN

However I am not sure how to do this for iOS. There doesn't seem like a nice way to separate the token request from the authorize request as far as I can tell. That said I am not very familiar with Objective-C, so if anyone can point me in the right direction, I would greatly appreciate it.

If none of this is at all possible, how is it recommended to do *only* the authorize request for an openId connect integration on RN? If at all possible I would like to use AppAuth, but doing the authentication/authorization flow is possible to do manually. The main challenge here is how to implement Custom Tabs (Android) and `SFAuthenticationSession/SFSafariViewController` on iOS. I think there is a react-native package for Custom Tabs, but I've yet to see anything (other than this excellent library) to implement `SFAuthenticationSession/SFSafariViewController`.

If anyone could point me in the right direction, I would greatly appreciate it.

**Comment by authuser** [comment]
It appears that this has already been attempted in the GemHQ fork: https://github.com/GemHQ/react-native-app-auth/

I can't comment on how stable it is yet, but it seems to demonstrate how it could be done at least. Thanks @thedoctor and whoever else contributed!

**Comment by thedoctor** [comment]
@authuser We did have basically the same requirements and, as you noted, found modifications had to be made. So I hacked in the changes from this commit: https://github.com/GemHQ/react-native-app-auth/commit/1e242edd97f00c9933173ea097f9655b09755894
I wasn't sure if the goal of this project was just to support the normal [OIDC](https://openid.net/connect/) flow for serverless authentication or if the maintainers would be interested in modifying it to have more broad OAuth facilities. 
I won't be able to find the time to make a proper PR myself for awhile, but I think if people want it, then the module's public API deserves a bit of refactoring.

**Comment by addmaths07** [comment]
We really need this. The workaround I came up with was to integrate my own server call in place of tokenEndpoint. This way I could retrieve the authorization code, & didn't require to have clientSecret in the client app.

**Comment by kadikraman** [comment]
It certainly seems to be a common enough use-case to warrant support. @thedoctor have you been using your fork in production? Any issues?

**Comment by thedoctor** [comment]
@kadikraman I agree that that would be _better_ than what we have, but I think the API should really be refactored to match OAuth and OIDC flows more closely.
e.g. I would argue that what is currently called `authorize` should really be a convenience method called something like `authenticateUser` which should, internally, call both `requestAuthorization` (which would never do token exchange) and `redeemAuthorizationCode` (which would _only_ do token exchange)

**Comment by kadikraman** [comment]
@thedoctor yes, agreed. For reference, the initial (and indeed ideal) use case for the library was authenticating with an OpenID registered auth provider (to use autodiscovery) that supports PKCE (to exchange those tokens all safe-like) in which you call `authorize` with only 3 config variables and the library does the rest.

Support for non-openID auth providers was added later and indeed being able to pass in client secrets (completely stupid and adding no security whatsoever for a mobile apps) was also added later to allow authentication with older or more rigid services.

So separating the methods to allow you to call authorize and token exchange separately is yet another non-ideal use-case, but certainly common enough to warrant adding.

I think we used `authorize` initially to match the `AppAuth` naming conventions, but I don't mind adding an alias for `authenticateUser`.

**Comment by thedoctor** [comment]
Seems like a reasonable start. I definitely don't want to see this project fracture into multiple ones. I'll open up the PR from our fork.

**Comment by kadikraman** [comment]
@DonMartin76 We _do_ support PKCE and do it as default when the authorization server supports it.

**Comment by DonMartin76** [comment]
Awesome! Sorry for my nitpicking!

**Comment by kadikraman** [comment]
@DonMartin76 no worries at all 😄 - the PKCE support was the original reason why this library was built. Everything else has been added due to popular demand.

**Comment by bhaskardabhi-oviyum** [comment]
@thedoctor tried to use that library but didn't work. Not sure if some diff setup has to be done.

![Screenshot 2019-07-10 at 5 01 26 PM](https://user-images.githubusercontent.com/20903929/60965885-99794800-a334-11e9-95be-73c97a2cf132.png)

**Comment by bhaskardabhi-oviyum** [comment]
@thedoctor sorry found out the mistake. Not sure if its mistake. If I passed `skipTokenExchange: true` then it doesn't work.  If I send `skipTokenExchange: "true"` (true as string) then only it works. Anyway thanks.

**Comment by sregg** [comment]
Is this still available?
I couldn't find `skipTokenExchange` anywhere in the code...

**Comment by kadikraman** [comment]
Currently, the `authorize` call does 3 things
1. fetch the service configuration from the issuer
2. `/authorize` call (use authenticates)
3. `/token` call (exchange auth code for JWT)

There is an open issue for [separating these calls](https://github.com/FormidableLabs/react-native-app-auth/issues/234) to allow more control, but it is non-trivial.

Closing this issue because the conversation has deviated from the original issue.
