### ISSUE TITLE
Login redirect to app is broken after browser cache is cleared

### ISSUE THREAD

**Issue by mihaf70** [FormidableLabs/react-native-app-auth#960]
## Issue

After cleaning browser (chrome) cache and opening login instance regularly within app, in app browser is not opened inside app but as a separate browser. You can see it on the following screenshots. Because of that, when I'm redirected to the app after login process, the only I can see is a grey screen. After app relaunch I'm logged in so it's only an UI defect, login logic is working. 

Browser cache cleared (incorrect behaviour):
![Screenshot_20240417-123747](https://github.com/FormidableLabs/react-native-app-auth/assets/72543203/357713ef-aa4b-4bd2-ad91-e39db9447b8a)

Correct behaviour:
![Screenshot_20240417-123757](https://github.com/FormidableLabs/react-native-app-auth/assets/72543203/13999227-3bb7-47f7-b601-cb4bb2490ddf)

Issue was reproduced on Google Pixel 7 Pro (Android 15 Beta) both on debug and release app mode.

Here's the screen recording:
https://github.com/FormidableLabs/react-native-app-auth/assets/72543203/da8412ae-b1f6-455f-aba6-5a03d9bd88dd

---

## Environment
* **Platform that you're experiencing the issue on**: `Android`
* **Your `react-native` Version**: `e.g. 0.71.7`
* **Your `react-native-app-auth` Version**: `e.g. 7.1.3`
* **Are you using Expo?** No

**Comment by faizplus** [comment]
This seems to be coding error and is unrelated to this open source library and falls under general development help. Try to debug the response after login and check how you are managing your internal state. Closing this issue but feel free to reopen if you find issue with this package.
