### ISSUE TITLE
Is it possible to close WebView programmatically in Android? 

### ISSUE THREAD

**Issue by Brittognanaraj** [FormidableLabs/react-native-app-auth#961]
## Issue

---

## Environment

* **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
* **Platform that you're experiencing the issue on**: `iOS / Android / both`
* **Your `react-native` Version**: `e.g. 0.72.1`
* **Your `react-native-app-auth` Version**: `e.g. 7.0.0`
* **Are you using Expo?**

**Comment by faizplus** [comment]
This seems to be coding/config error and is unrelated to this open source library and falls under general development help.
