### ISSUE TITLE
Example is confusing

### ISSUE THREAD

**Issue by mjaggard** [FormidableLabs/react-native-app-auth#963]
## Documentation Feedback
The [Google example](https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/google.md) is confusing because it includes a `redirectUrl` that takes the user to the Google home page rather than back to your app. The actual URL needs to be

1. Configured in AndroidManifest.xml as an intent filter (see code block below).
2. Have a scheme that is identical to the package name / app ID of the app (because Google don't let you specify the redirect URI when creating Android credentials)
3. `manifestPlaceholders["appAuthRedirectScheme"] = "com.myapp"`
4. Defined in an Android credential in Google's credentials page with "Enable custom URI scheme" ticked.
5. The credential may need to have been created several hours before.

```
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="com.myapp" android:host="oauth2redirect"/>
            </intent-filter>
```

**Comment by faizplus** [comment]
@mjaggard you don't need to change anything in AndroidManifest.xml, first follow instructions from main doc page [Android setup](https://github.com/FormidableLabs/react-native-app-auth?tab=readme-ov-file#android-setup), then follow specific auth providers docs.

**Comment by mjaggard** [comment]
Agreed, step 1 may not be needed but steps 2, 3 and 5 definitely are and I can't find them documented anywhere.

**Comment by mjaggard** [comment]
@faizplus
