### ISSUE TITLE
AppDelegate Inheritance

### ISSUE THREAD

**Issue by gwashburne** [FormidableLabs/react-native-app-auth#983]
## Issue

Following the [docs,](https://commerce.nearform.com/open-source/react-native-app-auth/docs/) I expect to update my AppDelegate to as follows:
`@interface AppDelegate : RCTAppDelegate <RNAppAuthAuthorizationFlowManager>`
However, because I am using some Expo modules in this app (I am NOT using a managed workflow, just some modules), the AppDelegate inherits from EXAppDelegateWrapper. Since you can't inherit from  more than one class, I can't inherit from RCTAppDelegate. 
However, it appears to work if I don't inherit from RCTAppDelegate at all. Below is what my AppDelegate is now, and everything seems to be working:
`@interface AppDelegate : EXAppDelegateWrapper <RNAppAuthAuthorizationFlowManager>`

My question is: is this ok? Or will this approach cause issues? If this is incorrect, what would the correct approach be?

---

## Environment

* **Platform that you're experiencing the issue on**: `iOS`
* **Your `react-native` Version**: `0.74.1`
* **Your `react-native-app-auth` Version**: `7.20`
* **Are you using Expo?**
No, just some modules

**Comment by lovegaoshi** [comment]
EXAppDelegateWrapper extends RCTAppDelegate. this is perfectly fine.

**Comment by gwashburne** [comment]
Awesome, thank you!
